/*
 * Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition.
 * 
 *
 * OperativeAcctProductnewMRB.java
 * 
 * Created on Wed Jul 21 10:50:46 IST 2004
 */

package com.see.truetransact.ui.product.operativeacct;

import java.util.ListResourceBundle;

public class OperativeAcctProductnewMRB extends ListResourceBundle {
    public OperativeAcctProductnewMRB(){
    }

    public Object[][] getContents() {
        return contents;
    }

    static final String[][] contents = {
        {"cboCreditIntRoundOff", "CreditIntRoundOff should be a proper value!!!"},
        {"txtAcClosingChrg", "AcClosingChrg should not be empty!!!"},
        {"txtMinBalAmt", "MinBalAmt should not be empty!!!"},
        {"txtMaxAmtWDSlip", "MaxAmtWDSlip should not be empty!!!"},
        {"txtMinBal1FlexiDep", "MinBal1FlexiDep should not be empty!!!"},
        {"txtStatChrg", "StatChrg should not be empty!!!"},
        {"txtMinBalIVRS", "MinBalIVRS should not be empty!!!"},
        {"rdoDebitCompReq_Yes", "DebitCompReq should be selected!!!"},
        {"txtPenalIntChrgStart", "PenalIntChrgStart should not be empty!!!"},
        {"cboCreditProductRoundOff", "CreditProductRoundOff should be a proper value!!!"},
        {"txtTaxGL", "TaxGL should not be empty!!!"},
        {"txtAcctHd", "AcctHd should not be empty!!!"},
        {"cboStartProdCalc", "StartProdCalc should be a proper value!!!"},
        {"txtFreeChkPD", "FreeChkPD should not be empty!!!"},
        {"rdoFolioToChargeOn_Credit", "FolioToChargeOn should be selected!!!"},
        {"txtApplDebitIntRate", "ApplDebitIntRate should not be empty!!!"},
        {"rdoTaxIntApplNRO_Yes", "TaxIntApplNRO should be selected!!!"},
        {"txtMaxCrIntRate", "MaxCrIntRate should not be empty!!!"},
        {"cboEndDayProdCalcSBCrInt", "EndDayProdCalcSBCrInt should be a proper value!!!"},
        {"rdoCrIntGiven_Yes", "CrIntGiven should be selected!!!"},
        {"rdoATMIssued_Yes", "ATMIssued should be selected!!!"},
        {"rdoChkAllowed_Yes", "ChkAllowed should be selected!!!"},
        {"cboInOpAcChrgPd", "InOpAcChrgPd should be a proper value!!!"},
        {"rdoStopPaymentChrg_Yes", "StopPaymentChrg should be selected!!!"},
        {"txtPenalIntDebitBalAcct", "PenalIntDebitBalAcct should not be empty!!!"},
        {"txtInOpChrg", "InOpChrg should not be empty!!!"},
        {"rdoIntUnClearBal_Yes", "IntUnClearBal should be selected!!!"},
        {"txtOutwardChkRetChrg", "OutwardChkRetChrg should not be empty!!!"},
        {"txtMinBalDebitCards", "MinBalDebitCards should not be empty!!!"},
        {"cboFolioChrgApplFreq", "FolioChrgApplFreq should be a proper value!!!"},
        {"rdoNonMainMinBalChrg_Yes", "NonMainMinBalChrg should be selected!!!"},
        {"cboCalcCriteria", "CalcCriteria should be a proper value!!!"},
        {"cboStatChargesChr", "StatChargesChr should be a proper value!!!"},
        {"rdoNomineeReq_Yes", "NomineeReq should be selected!!!"},
        {"cboBehaves", "Behaves should be a proper value!!!"},
        {"rdoIntroReq_Yes", "IntroReq should be selected!!!"},
        {"txtNoEntryPerFolio", "NoEntryPerFolio should not be empty!!!"},
        {"txtExcessFreeWDChrgPT", "ExcessFreeWDChrgPT should not be empty!!!"},
        {"cboMinTreatInOp", "MinTreatInOp should be a proper value!!!"},
        {"txtNoFreeChkLeaves", "NoFreeChkLeaves should not be empty!!!"},
        {"rdoStatCharges_Yes", "StatCharges should be selected!!!"},
        {"cboMinTreatasDormant", "MinTreatasDormant should be a proper value!!!"},
        {"cboDebitCompIntCalcFreq", "DebitCompIntCalcFreq should be a proper value!!!"},
        {"cboStDayProdCalcSBCrInt", "StDayProdCalcSBCrInt should be a proper value!!!"},
        {"txtMinTreatasInOp", "MinTreatasInOp should not be empty!!!"},
        {"tdtLastIntApplDateCr", "LastIntApplDateCr should not be empty!!!"},
        {"txtChkBkIssueChrgPL", "ChkBkIssueChrgPL should not be empty!!!"},
        {"rdoFolioChargeAppl_Yes", "FolioChargeAppl should be selected!!!"},
        {"txtChrgMiscServChrg", "ChrgMiscServChrg should not be empty!!!"},
        {"rdoCreditCdIssued_Yes", "CreditCdIssued should be selected!!!"},
        {"cboStatFreq", "StatFreq should be a proper value!!!"},
        {"txtStMonIntCalc", "StMonIntCalc should not be empty!!!"},
        {"txtAcctCrInt", "AcctCrInt should not be empty!!!"},
        {"txtStopPayChrg", "StopPayChrg should not be empty!!!"},
        {"txtEndProdCalc", "EndProdCalc should not be empty!!!"},
        {"txtMinCrIntRate", "MinCrIntRate should not be empty!!!"},
        {"tdtLastIntApplDate", "LastIntApplDate should not be empty!!!"},
        {"cboCrIntCalcFreq", "CrIntCalcFreq should be a proper value!!!"},
        {"txtAcctOpenChrg", "AcctOpenChrg should not be empty!!!"},
        {"rdoTempODAllow_Yes", "TempODAllow should be selected!!!"},
        {"tdtFreeWDStFrom", "FreeWDStFrom should not be empty!!!"},
        {"txtExcessFreeWDChrg", "ExcessFreeWDChrg should not be empty!!!"},
        {"cboIntCalcEndMon", "IntCalcEndMon should be a proper value!!!"},
        {"rdoIVRSProvided_Yes", "IVRSProvided should be selected!!!"},
        {"cboFreeChkLeaveStFrom", "FreeChkLeaveStFrom should be a proper value!!!"},
        {"txtApplCrIntRate", "ApplCrIntRate should not be empty!!!"},
        {"txtMinDebitIntAmt", "MinDebitIntAmt should not be empty!!!"},
        {"txtMinBal2FlexiDep", "MinBal2FlexiDep should not be empty!!!"},
        {"cboIncompFolioROffFreq", "IncompFolioROffFreq should be a proper value!!!"},
        {"cboMinTreatNewClosure", "MinTreatNewClosure should be a proper value!!!"},
        {"txtFolioChrg", "FolioChrg should not be empty!!!"},
        {"cboFreeWDStFrom", "FreeWDStFrom should be a proper value!!!"},
        {"rdoFlexiHappen_SB", "FlexiHappen should be selected!!!"},
        {"cboFreeWDPd", "FreeWDPd should be a proper value!!!"},
        {"rdoCreditComp_Yes", "CreditComp should be selected!!!"},
        {"rdoIssueToken_Yes", "IssueToken should be selected!!!"},
        {"txtNoNominees", "NoNominees should not be empty!!!"},
        {"txtStatChargesChr", "StatChargesChr should not be empty!!!"},
        {"cboCreditCompIntCalcFreq", "CreditCompIntCalcFreq should be a proper value!!!"},
        {"txtChrgPreClosure", "ChrgPreClosure should not be empty!!!"},
        {"rdoCollectInt_Yes", "CollectInt should be selected!!!"},
        {"txtMinATMBal", "MinATMBal should not be empty!!!"},
        {"txtStDayProdCalcSBCrInt", "StDayProdCalcSBCrInt should not be empty!!!"},
        {"txtAcctDebitInt", "AcctDebitInt should not be empty!!!"},
        {"txtAcctClosingChrg", "AcctClosingChrg should not be empty!!!"},
        {"txtDesc", "Desc should not be empty!!!"},
        {"cboProdCurrency", "ProdCurrency should be a proper value!!!"},
        {"txtFreeWDChrg", "FreeWDChrg should not be empty!!!"},
        {"txtMiscServChrg", "MiscServChrg should not be empty!!!"},
        {"rdoLimitDefAllow_Yes", "LimitDefAllow should be selected!!!"},
        {"txtMainTreatNewAcctClosure", "MainTreatNewAcctClosure should not be empty!!!"},
        {"txtAcctOpenCharges", "AcctOpenCharges should not be empty!!!"},
        {"rdoChkIssuedChrgCh_Yes", "ChkIssuedChrgCh should be selected!!!"},
        {"txtPrematureClosureChrg", "PrematureClosureChrg should not be empty!!!"},
        {"txtInwardChkRetChrg", "InwardChkRetChrg should not be empty!!!"},
        {"txtInOperative", "InOperative should not be empty!!!"},
        {"rdoMobBankClient_Yes", "MobBankClient should be selected!!!"},
        {"cboToCollectFolioChrg", "ToCollectFolioChrg should be a proper value!!!"},
        {"cboMinBalAmt", "MinBalAmt should be a proper value!!!"},
        {"cboDebitIntApplFreq", "DebitIntApplFreq should be a proper value!!!"},
        {"rdoStaffAcct_Yes", "StaffAcct should be selected!!!"},
        {"cboStMonIntCalc", "StMonIntCalc should be a proper value!!!"},
        {"txtEndInterCalc", "EndInterCalc should not be empty!!!"},
        {"cboStartInterCalc", "StartInterCalc should be a proper value!!!"},
        {"rdoABBAllowed_Yes", "ABBAllowed should be selected!!!"},
        {"cboDebitIntCalcFreq", "DebitIntCalcFreq should be a proper value!!!"},
        {"cboEndProdCalc", "EndProdCalc should be a proper value!!!"},
        {"txtlInOpAcChrg", "lInOpAcChrg should not be empty!!!"},
        {"tdtLastIntCalcDate", "LastIntCalcDate should not be empty!!!"},
        {"tdtFreeChkLeaveStFrom", "FreeChkLeaveStFrom should not be empty!!!"},
        {"rdoAllowWD_Yes", "AllowWD should be selected!!!"},
        {"txtMinBalCreditCd", "MinBalCreditCd should not be empty!!!"},
        {"txtProductID", "ProductID should not be empty!!!"},
        {"txtMaxDebitIntRate", "MaxDebitIntRate should not be empty!!!"},
        {"txtNoFreeWD", "NoFreeWD should not be empty!!!"},
        {"tdtLastIntCalcDateCR", "LastIntCalcDateCR should not be empty!!!"},
        {"rdoToChargeOnApplFreq_Manual", "ToChargeOnApplFreq should be selected!!!"},
        {"rdoAcc_Reg", "Type Of Account Should be selected should be selected!!!"},
        {"rdoAcc_Nro", "Type Of Account Should be selected should be selected!!!"},
        {"rdoAcc_Nre", "Type Of Account Should be selected should be selected!!!"},
        {"rdoDebitIntChrg_Yes2", "DebitIntChrg should be selected!!!"},
        {"txtStopPaymentChrg", "StopPaymentChrg should not be empty!!!"},
        {"rdoAcctOpenAppr_Yes", "AcctOpenAppr should be selected!!!"},
        {"txtStartProdCalc", "StartProdCalc should not be empty!!!"},
        {"cboProdFreq", "ProdFreq should be a proper value!!!"},
        {"txtNonMainMinBalChrg", "NonMainMinBalChrg should not be empty!!!"},
        {"txtMinCrIntAmt", "MinCrIntAmt should not be empty!!!"},
        {"txtMaxCrIntAmt", "MaxCrIntAmt should not be empty!!!"},
        {"txtIntCalcEndMon", "IntCalcEndMon should not be empty!!!"},
        {"txtMinBalABB", "MinBalABB should not be empty!!!"},
        {"cboDebitProductRoundOff", "DebitProductRoundOff should be a proper value!!!"},
        {"txtStartInterCalc", "StartInterCalc should not be empty!!!"},
        {"cboCrIntApplFreq", "CrIntApplFreq should be a proper value!!!"},
        {"rdoDebitCdIssued_Yes", "DebitCdIssued should be selected!!!"},
        {"cboProdFreqCr", "ProdFreqCr should be a proper value!!!"},
        {"cboFlexiTD", "FlexiTD should be a proper value!!!"},
        {"txtRatePerFolio", "RatePerFolio should not be empty!!!"},
        {"txtMinBalwchk", "MinBalwchk should not be empty!!!"},
        {"txtMinTreatasDormant", "MinTreatasDormant should not be empty!!!"},
        {"txtChkRetChrgIn", "ChkRetChrgIn should not be empty!!!"},
        {"cboFreeChkPd", "FreeChkPd should be a proper value!!!"},
        {"cboDebitIntRoundOff", "DebitIntRoundOff should be a proper value!!!"},
        {"txtMinDebitIntRate", "MinDebitIntRate should not be empty!!!"},
        {"txtEndDayProdCalcSBCrInt", "EndDayProdCalcSBCrInt should not be empty!!!"},
        {"rdoLinkFlexiAcct_Yes", "LinkFlexiAcct should be selected!!!"},
        {"txtClearingIntAcctHd", "ClearingIntAcctHd should not be empty!!!"},
        {"txtChkRetChrOutward", "ChkRetChrOutward should not be empty!!!"},
        {"txtMinTreatasNew", "MinTreatasNew should not be empty!!!"},
        {"txtRateTaxNRO", "RateTaxNRO should not be empty!!!"},
        {"cboEndInterCalc", "EndInterCalc should be a proper value!!!"},
        {"rdoIntClearing_Yes", "IntClearing should be selected!!!"},
        {"cboMinTreatasNew", "MinTreatasNew should be a proper value!!!"},
        {"txtMinMobBank", "MinMobBank should not be empty!!!"},
        {"txtChkBkIssueChrg", "ChkBkIssueChrg should not be empty!!!"},
        {"txtMaxDebitIntAmt", "MaxDebitIntAmt should not be empty!!!"},
        {"txtMinBalChkbk", "MinBalChkbk should not be empty!!!"},
        {"txtFreeWDPd", "FreeWDPd should not be empty!!!"} ,
        {"txtNumPatternFollowedPSuffix","txtNumPatternFollowedPSuffix Should Not Be Empty"},
        {"txtNumPatternFollowedPrefix","txtNumPatternFollowedPrefix Should Not Be Empty"}

   };

}
