/*
 * Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition.
 * 
 *
 * OperativeAcctProductnewRB.java
 * 
 * Created on Tue Jul 20 16:10:53 IST 2004
 */

package com.see.truetransact.ui.product.operativeacct;

import java.util.ListResourceBundle;

public class OperativeAcctProductnewRB extends ListResourceBundle {
    public OperativeAcctProductnewRB(){
    }

    public Object[][] getContents() {
        return contents;
    }

    static final String[][] contents = {
        {"lblMinBalAmt", "Amount"},
        {"lblDebitIntApplicable", "Applicable Interest Rate"},
        {"rdoTaxIntApplNRO_No", "No"},
        {"lblMaxDebitIntRate", "Maximum Interest Rate"},
        {"lblMinTreatasInOp", "as Inoperative"},
        {"lblStDayProdCalcSBCrInt", "Start Day of Product Calculation"},
        {"lblCrIntUnclear", "Credit Interest on Unclear Balance Applicable"},
        {"lblAllowWith", "Allow Withdrawal Slip?"},
        {"lblMinCrIntAmt", "Minimum Interest Amount"},
        {"rdoTempODAllow_No", "No"},
        {"btnFolioChrg", ""},
        {"lblMinBalIVRS", "Min. Balance for IVRS"},
        {"rdoToChargeOnApplFreq_Both", "Both"},
        {"lblNonMainMinBalChrg", "Charges Non-Maintenance Minimum Balance P & L Account Head"},
        {"rdoIVRSProvided_No", "No"},
        {"rdoStatCharges_No", "No"},
        {"lblChkBkIssueChrgPL", "Chequebook Issue Charges (per Leaf)"},
        {"rdoTaxIntApplNRO_Yes", "Yes"},
        {"btnAcctDebitInt", ""},
        {"rdoIssueToken_No", "No"},
        {"rdoToChargeOnApplFreq_System", "System"},
        {"lblCreditComp", "Credit Compound?"},
        {"rdoATMIssued_Yes", "Yes"},
        {"btnReject", ""},
        {"lblMinTreatNewAcctClosure", "New Account for Closure"},
        {"rdoChkAllowed_Yes", "Yes"},
        {"lblNonMainMinBalCharges", "Non-Maintenance Min Bal Charges"},
        {"rdoLimitDefAllow_No", "No"},
        {"lblRatePerFolio", "Rate per Folio"},
        {"lblFreeChkLeavePd", "Free Cheque Leaves Period"},
        {"lblEndProdCalc", "End Day of Product Calculation"},
        {"lblFlexiTD", "Flexi Term Deposit"},
        {"lblRateNRO", "Rate of Tax (NRO) %"},
        {"rdoNonMainMinBalChrg_Yes", "Yes"},
        {"rdoABBAllowed_No", "No"},
        {"panSpecialDetails", " Special Details "},
        {"lblCreditIntRoundOff", "Credit Interest Round Off"},
        {"lblEndInterCalc", "End Day of Interest Calculation"},
        {"lblCrIntApplFreq", "Credit Interest Application Frequency"},
        {"lblDebitIntCalcFreq", "Calculation Frequency"},
        {"btnException", ""},
        {"lblAcctClosingChrg", "Account Closing Charges - GL Head"},
        {"lblMaxCrIntRate", "Maximum Interest Rate"},
        {"rdoFlexiHappen_TD", "New TD Account"},
        {"btnAcctHd", ""},
        {"lblPenalIntDebitBalAcct", "Penal Interest for Debit Balance Accounts"},
        {"lblInOperative", "In-Operative Account Head"},
        {"lblStartInterCalc", "Start Day of Interest Calculation"},
        {"rdoFolioChargeAppl_Yes", "Yes"},
        {"btnTaxGL", ""},
        {"btnSave", ""},
        {"btnStopPaymentChrg", ""},
        {"rdoFolioChargeAppl_No", "No"},
        {"lblFolioToChargeOn", "To Charge On"},
        {"lblStatChargesChrg", "Statement Charge"},
        {"rdoTempODAllow_Yes", "Yes"},
        {"btnMiscServChrg", ""},
        {"lblFolioChargeLastAppliedDt","Folio Charges Last Applied Dt"},
        {"lblFolioChargeNextAppDt", "Folio Charges Next Due Dt"},
        {"lblStatCharges", "Statement Charges"},
        {"lblCrIntApplicable", "Applicable Interest Rate"},
        {"lblAcClosingChrg", "Account Closing Charges"},
        {"lblCalcCriteria", "Calculation Criteria"},
        {"lblExcessFreeWDChrgPT", "Excess Free Withdrawals Charge (per Transaction)"},
        {"lblIncompFolioROffFreq", "Incomplete Folio Rounding Off Freq"},
        {"lblStartProdCalc", "Start Day of Product Calculation"},
        {"lblChkIssuedChrg", "Chequebook Issued Charges"},
        {"rdoNonMainMinBalChrg_No", "No"},
        {"lblExcessFreeWDChrg", "P & L Account Head for Charges in Excess of Free Withdrawals"},
        {"lblDebitProductRoundOff", "Debit Product Round Off"},
        {"lblStopPaymentChrg", "Stop Payment Charges - GL Head"},
        {"lblStatChrg", "Statement Charges - GL Head"},
        {"lblStopPayChrg", "Stop Payment Charge"},
        {"rdoStaffAcct_No", "No"},
        {"lblPenalIntChrgStart", "Penal Interest Charge Start Day (Nth Day)"},
        {"btnFreeWDChrg", ""},
        {"lblPer5", "%"},
        {"lblCrIntGiven", "Credit Interest to be Given"},
        {"rdoCreditComp_No", "No"},
        {"lblLimit", "Limit Definition Allowed"},
        {"lblSpace4", " "},
        {"lblDebitCompoundReq", "Debit Compound Required?"},
        {"lblSpace2", "     "},
        {"btnAcctCrInt", ""},
        {"lblSpace3", "     "},
        {"lblSpace1", " Status :"},
        {"rdoDebitIntChrg_No2", "No"},
        {"lblATMIssued", "ATM Card Issued?"},
        {"lblAcctOpenApprReq", "A/c Opening Approval Required"},
        {"lblLinkFlexiAcct", " Whether linked to Flexi Account"},
        {"lblMinBalChqbk", "Minimum Balance with Chequebook"},
        {"btnAcctClosingChrg", ""},
        {"rdoLimitDefAllow_Yes", "Yes"},
        {"lblCreditCdIssued", "Credit Card Issued?"},
        {"rdoChkIssuedChrgCh_Yes", "Yes"},
        {"rdoLinkFlexiAcct_No", "No"},
        {"lblPer4", "%"},
        {"lblProductID", "Product ID"},
        {"lblTaxGL", "Tax GL Account Head"},
        {"rdoABBAllowed_Yes", "Yes"},
        {"lblTempOD", "Temporary O/D Allowed"},
        {"lblChkRetChrOutward", "Cheque Return Charges (Outward)"},
        {"lblChrgPreClosure", "Charges for Premature Closure (for New A/c)"},
        {"rdoStopPaymentChrg_No", "No"},
        {"rdoAllowWD_Yes", "Yes"},
        {"lblStopPaymentCharges", "Stop Payment Charges"},
        {"lblABBAllowed", "Is Any Branch Banking Allowed?"},
        {"rdoMobBankClient_No", "No"},
        {"rdoToChargeOnApplFreq_Manual", "Manual"},
        {"lblFreeWDPd", "Free Withdrawals Period"},
        {"rdoAcctOpenAppr_Yes", "Yes"},
        {"lblMinBal1FlexiDep", "Min. Balance1 for Flexi Deposit"},
        {"lblChrgMiscServChrg", "Misc. Service Charges"},
        {"panMiscDetails", " Miscellaneous Details "},
        {"lblStatus", "                      "},
        {"lblDebitCompIntCalcFreq", "Debit Compound Interest Calculation Frequency"},
        {"lblMinCrIntRate", "Minimum Interest Rate"},
        {"lblClearingIntAcctHd", "Against Clearing Interest Account Head"},
        {"panMinPerd", " Minimum Period to Treat Account "},
        {"lblFlexiHappen", " Whether Flexi will Happen in"},
        {"lblSpace5", "     "},
        {"rdoFolioToChargeOn_Both", "Both"},
        {"rdoDebitCdIssued_Yes", "Yes"},
        {"btnDelete", ""},
        {"lblPer1", "%"},
        {"rdoChkAllowed_No", "No"},
        {"lblInwardChkRetChrg", "Cheque Return Charges (Inward) - GL Head"},
        {"lblMinMobBank", "Min. Balance for Mobile Banking"},
        {"lblDebitIntApplFreq", "Application Frequency"},
        {"rdoATMIssued_No", "No"},
        {"rdoDebitCdIssued_No", "No"},
        {"lblLastIntCalcDateCR", "Last Interest Calculation Date - Credit"},
        {"lblIntroReq", "Introducer Required?"},
        {"rdoLinkFlexiAcct_Yes", "Yes"},
        {"rdoIntClearing_Yes", "Yes"},
        {"lblOutwardChkRetChrg", "Cheque Return Charges (Outward) - GL Head"},
        {"lblStMonIntCalc", "Start Day of Interest Calculation"},
        {"lblAcctHd", "Account Head"},
        {"lblFolioChargeAppl", "Folio Charges Applicable"},
        {"btnClose", ""},
        {"lblNoNominee", "Number of Nominees"},
        {"lblStatFreq", "Statement Frequency"},
        {"btnOutwardChkRetChrg", ""},
        {"lblNoFreeChkLeaves", "No. of Free Cheque Leaves"},
        {"lblFreeChkLeaveStart", "Free Cheque Leaves Starting From"},
        {"btnAuthorize", ""},
        {"lblProdCurrency", "Product Currency"},
        {"lblIntCalcEndMon", "End Day of Interest Calculation"},
        {"lblMsg", ""},
        {"rdoDebitCompReq_Yes", "Yes"},
        {"lblChequeAllowed", "Are Chequebooks Allowed?"},
        {"lblFreeWDChrg", "Free Withdrawal Charges - P & L Account Head"},
        {"lblDebitIntRoundOff", "Debit Interest Round Off"},
        {"lblATMGL", "ATM Account P & L Account Head"},
        {"lblFolioChrg", "Folio Charges Account P & L Account Head"},
        {"lblDebitInt", "Debit Interest against Clearing Applicable"},
        {"rdoNomineeReq_No", "No"},
        {"rdoFolioToChargeOn_Credit", "Credit"},
        {"lblNomineereq", "Nominee Required?"},
        {"lblMinBalwochk", "Minimum Balance without Chequebook"},
        {"rdoCrIntGiven_Yes", "Yes"},
        {"lblPer2", "%"},
        {"lblAcctOpenCharges", "Account Opening Charges"},
        {"rdoStopPaymentChrg_Yes", "Yes"},
        {"lblMinDebitIntAmt", "Minimum Interest Amount"},
        {"btnInwardChkRetChrg", ""},
        {"lblDebitCardIssued", "Debit Card Issued?"},
        {"rdoIntUnClearBal_Yes", "Yes"},
        {"lblMinBalDebitCards", "Minimum Balance for Debit Card"},
        {"rdoAllowWD_No", "No"},
        {"btnPrint", ""},
        {"lblProductFreq", "Product Frequency"},
        {"rdoNomineeReq_Yes", "Yes"},
        {"lblPer3", "%"},
        {"lblMinBalABB", "Minimum Balance for ABB"},
        {"btnInOpChrg", ""},
        {"rdoIntroReq_Yes", "Yes"},
        {"lblMaxDebitIntAmt", "Maximum Interest Amount"},
        {"lblInOpAcChrgPd", "In-Operative A/c Charges Period"},
        {"rdoStatCharges_Yes", "Yes"},
        {"lblAcctCrInt", "P & L Head of Account for Credit Interest"},
        {"lblCollectInt", "Collect Interest after Balance gets to Credit"},
        {"lblNROTax", "Tax on Interest Applicable (NRO)"},
        {"lblToChargeOnApplFreq", "To Charge On"},
        {"rdoCreditCdIssued_Yes", "Yes"},
        {"lblInOpAcChrg", "In-Operative A/c Charges"},
        {"rdoIntClearing_No", "No"},
        {"lblToCollectFolioChrg", "To Collect Folio Charges"},
        {"lblCreditProductRoundOff", "Credit Product Round Off"},
        {"lblLastIntCalcDateDebit", "Last Interest Calculation Date - Debit"},
        {"rdoIVRSProvided_Yes", "Yes"},
        {"lblMobBankClient", "Mobile Banking Client?"},
        {"btnNew", ""},
        {"rdoIntroReq_No", "No"},
        {"rdoIntUnClearBal_No", "No"},
        {"rdoDebitCompReq_No", "No"},
        {"rdoFlexiHappen_SB", "SB"},
        {"rdoCreditComp_Yes", "Yes"},
        {"rdoIssueToken_Yes", "Yes"},
        {"lblMinBalCreditCd", "Minimum Balance for Credit Card"},
        {"rdoAcctOpenAppr_No", "No"},
        {"lblPrematureClosureChrg", "Charges for Premature Closure (for new A/c) - GL Head"},
        {"lblStaff", "Staff Account Only"},
        {"rdoCreditCdIssued_No", "No"},
        {"lblPer7", "%"},
        {"rdoCollectInt_Yes", "Yes"},
        {"lblEndDayProdCalcSBCrInt", "End Day of Product Calculation"},
        {"lblFreeWDStart", "Free Withdrawals Starting From"},
        {"rdoCrIntGiven_No", "No"},
        {"lblNoFreeWD", "No Of Free Withdrawals"},
        {"lblIssue", "Issue Token"},
        {"lblPer6", "%"},
        {"lblCrIntCalcFreq", "Credit Interest Calculation Frequency"},
        {"lblChkRetChrgIn", "Cheque Return Charges (Inward)"},
        {"rdoCollectInt_No", "No"},
        {"lblAcctOpenChrg", "Account Opening Charges - GL Head"},
        {"btnClearingIntAcctHd", ""},
        {"rdoChkIssuedChrgCh_No", "No"},
        {"btnChkBkIssueChrg", ""},
        {"lblChkBkIssueChrg", "Cheque Book Issue Charges - Account Head"},
        {"lblNoEntryPerFolio", "No. of Entries per Folio"},
        {"btnEdit", ""},
        {"lblFolioChrgApplFreq", "Folio Charges Applicability Frequency"},
        {"lblDesc", "Product Description"},
        {"rdoMobBankClient_Yes", "Yes"},
        {"lblMaxCrIntAmt", "Maximum Interest Amount"},
        {"lblMiscServChrg", "Misc. Service Charges - GL Head"},
        {"rdoStaffAcct_Yes", "Yes"},
        {"btnNonMainMinBalChrg", ""},
        {"btnExcessFreeWDChrg", ""},
        {"lblMinATMBal", "Minimum Balance for ATM"},
        {"lblAcctDebitInt", "P& L Head for Account for Debit Interest"},
        {"rdoDebitIntChrg_Yes2", "Yes"},
        {"lblMaxAmtWDSlip", "Max. Amt. Allowed for Withdrawal Slip"},
        {"lblLastIntApplDate", "Last Interest Application Date - Debit"},
        {"lblMinDrIntRate", "Minimum Interest Rate"},
        {"lblInOpChrg", "In-Operative Account Charges P & L Account Head"},
        {"btnAcctOpenChrg", ""},
        {"lblMinTreatasNew", "as New"},
        {"lblCreditCompIntCalcFreq", "Credit Compound Interest Calculation Frequency"},
        {"lblDebitIntChrg", "Debit Interest to be Charged"},
        {"rdoFolioToChargeOn_Debit", "Debit"},
        {"lblMinTreatasDormant", "as Dormant"},
        {"lblLastIntApplDateCr", "Last Interest Application Date - Credit"},
        {"lblMinBal2FlexiDep", "Min. Balance2 for Flexi Deposit"},
        {"lblProdFreqCr", "Product Frequency"},
        {"btnPrematureClosureChrg", ""},
        {"btnCancel", ""},
        {"btnStatChrg", ""},
        {"lblIVRSProvided", "Is IVRS provided?"},
        {"btnInOperative", ""},
        {"lblBehaves", "Operates Like"} ,
        {"rdoAcc_Reg", "REG"},
        {"rdoAcc_Nro", "NRO"},
        {"rdoAcc_Nre", "NRE"},
        {"lblTypeOfAcc", "Type Of Account"},
        {"lblIMinBalForInts","Min Bal for Interest Calculation"},
        
        
        {"strOK", "OK"} ,
        {"MAXDAYSWARNING", "Days Entered are more than the No of days in the Selected Month."} ,
        {"PRODIDWARNING", "This Product Id and/or Description Already Exists."} ,
        {"CHEQUELEAVESWARNING", "Free Cheque Leaves Should Not Be More Than The No. Of Free Withdrawls."},
        {"MAXRATEWARNING", "Minimum Interest Rate Should Be Less Than Maximum Interest Rate."},
        {"INTERESTRANGEWARNING", "Applicable Interest Should Be Between Maximum And Minimum Interest Rates.."},
        {"MAXAMOUNTWARNING", "Minimum Interest Amount Should Be Less Than Maximum Interest Amount."},
        {"PREFIXWARNING" ,"Enter the Numbering pattern To Be Followed!! "},
        {"SUFFIXWARNING" ,"Enter the Numbering pattern To Be Followed!! "},
        {"lblFixedFolio", "Fixed Folio Charge"},
        {"lblMinimumNoOfEntry", "Minimum No Of Entry For Charge"}
            

   };

}
