/*
 * Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition.
 * 
 *
 * CDateField.java
 *
 * Created on July 31, 2003, 8:00 PM
 */

package com.see.truetransact.uicomponent;

import java.util.Vector;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.ActionListener;

/**
 *
 * @author  karthik
 */
public class CDateField extends javax.swing.JPanel {
    private String helpMessage;
    private javax.swing.JLabel lblDisplay;
    private boolean isBranchDate ;
    
    /** Creates new form BeanForm */
    public CDateField() {
        initComponents();
        jTextField1.setDisabledTextColor(new java.awt.Color(51,51,51));
        helpFocus();
    }
    
    /** Creates new form BeanForm */
    public CDateField(boolean isBranchDate) {
        this.isBranchDate = isBranchDate;
        initComponents();
        jTextField1.setDisabledTextColor(new java.awt.Color(51,51,51));
        helpFocus();
    }
    
    private void helpFocus() {
        addFocusListener(new HelpFocusAdapter());
        jTextField1.setFocusable(false);
        //jTextField1.addFocusListener(new HelpFocusAdapter());
        jButton1.addFocusListener(new HelpFocusAdapter());
        
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                if (evt.getKeyChar() == '\n') {
                    nextFocus();
                }
            }
        });
//        jTextField1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                if (jTextField1.getText().length()>0) {
//                    nextFocus();
//                }
//            }
//        });
    }

    private class HelpFocusAdapter extends java.awt.event.FocusAdapter {
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (lblDisplay != null) lblDisplay.setText(helpMessage);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (lblDisplay != null) lblDisplay.setText("");
        }
    }
    
    public void setHelpMessage(javax.swing.JLabel lblDisplay, String helpMessage) {
        this.helpMessage = helpMessage;
        this.lblDisplay = lblDisplay;
    }
    public String getHelpMessage() {
        return this.helpMessage;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        setPreferredSize(new java.awt.Dimension(101, 21));
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setEditable(false);
        jTextField1.setMinimumSize(new java.awt.Dimension(80, 21));
        jTextField1.setPreferredSize(new java.awt.Dimension(80, 21));
        add(jTextField1, new java.awt.GridBagConstraints());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/see/truetransact/uicomponent/images/Calendar.gif")));
        jButton1.setMaximumSize(new java.awt.Dimension(21, 21));
        jButton1.setMinimumSize(new java.awt.Dimension(21, 21));
        jButton1.setPreferredSize(new java.awt.Dimension(21, 21));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        add(jButton1, new java.awt.GridBagConstraints());

    }//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Add your handling code here:
        com.see.truetransact.uicomponent.CCalendar calendar = new com.see.truetransact.uicomponent.CCalendar(jTextField1, isBranchDate);
        nextFocus();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /** Getter for property dateValue.
     * @return Value of property dateValue.
     *
     */
    public String getDateValue() {
        return jTextField1.getText();
    }
    
    /** Setter for property dateValue.
     * @return Value of property dateValue.
     *
     */
    public void setDateValue(String dateValue) {
        jTextField1.setText(dateValue);
    }
    
    public void setEnabled(boolean enable) {
        jTextField1.setEnabled(enable);
        jButton1.setEnabled(enable);
        if (enable == false)
            jTextField1.setBackground(new java.awt.Color(220,220,220));
        else
            jTextField1.setBackground((new javax.swing.JTextField()).getBackground());
    }
    public boolean isEnabled() {
        return jTextField1.isEnabled();
    }
    
    public void addFocusListener(java.awt.event.FocusAdapter focus) {
        jButton1.addFocusListener(focus);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
