/*
 * Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition.  
 * 
 *
 * CScrollPaneTable.java
 *
 * Created on July 31, 2003, 12:38 PM
 */

package com.see.truetransact.uicomponent;

/**
 *
 * @author  annamalai_t1
 */
public class CScrollPaneTable extends com.see.truetransact.uicomponent.CScrollPane {
    
    /** Creates new form CScrollPaneTable */
    public CScrollPaneTable() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        cTable = new com.see.truetransact.uicomponent.CTable();

        cTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        setViewportView(cTable);

    }//GEN-END:initComponents
        
    public CTable getTable(){
        return cTable;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.see.truetransact.uicomponent.CTable cTable;
    // End of variables declaration//GEN-END:variables
    
}
