/*
 * Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition.  
 * 
 * StandingInstructionRB.java
 */
package com.see.truetransact.ui.supporting.standinginstruction;
import java.util.ListResourceBundle;
public class StandingInstructionRB extends ListResourceBundle {
    public StandingInstructionRB(){
    }
    
    public Object[][] getContents() {
        return contents;
    }
    
    static final String[][] contents = {
        {"btnHelpAccNoCSI", ""},
        {"lblRettCommChargesSI", "Remittance Charges"},
        {"lblAccNoDSI", "Acct Number"},
        {"btnHelpAccNoDSI", ""},
        {"btnClose", ""},
        {"lblNameValueDSI", "Value"},
        {"lblNameDSI", " Name"},
        {"lblMsg", ""},
        {"btnSaveCSI", "Save"},
        {"lblEndDtSI", "End Date"},
        {"lblSpace2", "     "},
        {"lblSpace3", "     "},
        {"btnSaveDSI", "Save"},
        {"lblMultiplieSI", "Multiples of "},
        {"lblRettCommSI", "Remittance Commission"},
        {"lblCommChargesSI", "SI Charges"},
        {"lblFrequencySI", "Freq"},
        {"btnEdit", ""},
        {"btnDeleteCSI", "Delete"},
        {"lblCommSI", "SI Commission"},
        {"rdoCommSI_Yes", "Yes"},
        {"lblAccHeadCSI", "Acct Head"},
        {"btnNewCSI", "New"},
        {"panMainSI", ""},
        {"lblSINo", "Standing Instruction No"},
        {"btnPrint", ""},
        {"lblNameValueCSI", "Value"},
        {"lblParticularsCSI", "Particulars"},
        {"lblAmountDSI", "Amount"},
        {"lblAmountCSI", "Amount"},
        {"panDebitSI", "Debit Account Details"},
        {"lblStartDtSI", "Start Date"},
        {"rdoCommSI_No", "No"},
        {"rdoRettCommSI_No", "No"},
        {"lblMinBalSI", "Min Balance"},
        {"btnSave", ""},
        {"lblParticularsDSI", "Particulars"},
        {"lblStatus", "                      "},
        {"lblAccHeadDSI", "Acct Head"},
        {"lblNameCSI", " Name"},
        {"lblBeneficiarySI", "Beneficiary"},
        {"btnDelete", ""},
        {"lblMoTSI", "Mode Of Transmission"},
        {"lblAccHeadValueDSI", "Value"},
        {"btnNewDSI", "New"},
        {"lblSpace", " Status :"},
        {"lblProdIDCSI", "Product ID"},
        {"rdoRettCommSI_Yes", "Yes"},
        {"lblAccNoCSI", "Acct Number"},
        {"lblAccNoCSIMDS", "Chittal No"},
        {"lblGraceDaysSI", "Gracedays"},
        {"btnNew", ""},
        {"lblProdIDDSI", "Product ID"},
        {"panCreditSI", "Credit Account Details"},
        {"btnDeleteDSI", "Delete"},
        {"btnCancel", ""},
        {"btnAuthorize", ""},
        {"btnReject", ""},
        {"btnException", ""},
        {"lblSIType", "Standing Instruction Type"},
        {"lblAccHeadValueCSI", "Value"},
        {"lblDebitTotal" , "Total"},
        {"lblCreditTotal" , "Total"},
        {"lblDbTotalValue", ""},
        {"lblCrTotValue", ""},
        {"lblWeekDay", "WeekDay"},
        {"lblSIHoliday", "SI Holiday Execution"},
        {"panHolidayExecution","SIHolidayExecution"},
        {"lblAutomaticPosting","Automatic Posting"},
        {"panAutoPosting", "AutomaticPosting"},
        {"lblForwardCount","SI ForwardCount"},
        {"lblAcceptanceCharges","Postage Charges"},
        {"lblExecutionCharges","SI Charges Service Tax"},
        {"lblFailureST","Failure Charges Service Tax"},
        {"lblServiceTax","Remittance Service Tax"},
        {"lblFailureCharges","Failure Charges"},
        {"lblExecConfig","Execution Configuration"},
        {"lblWeek", "Week"},
        {"lblSpecificDate","SpecificDt"},
        {"errormsg", "Invalid Standing Instruction Amount to be Credited is not equal to Amount to be Debited"},
        {"tblmsg", "Debit Details Not filled up"},
        {"craccNoMsg" , "AccountNumber Choosen already exists in DebitAccountDetails"},
        {"dbaccNoMsg" , "AccountNumber Choosen already exists in CreditAccountDetails"},
        {"acHdMsg", "Accoutn Head Choosen Already exists in DebitAccountDetails"},
        {"cDialogOK", "OK"},
        {"tblColounHeading1", "Product Type"},
        {"tblColounHeading2", "Product ID"},
        {"tblColounHeading3", "Account Head"},
        {"tblColounHeading4", "Account No"},
        {"tblColounHeading5", "Amount"},
        {"panSchedule", "StandingInstruction Schedule"},
        {"panCharges", "StandingInstruction Charges"},
        {"panSI", ""},
        {"panSIID", ""},
        {"panStandingInstruction","Standing Instruction"},
        {"lblProductTypeCSI", "Product Type"},
        {"lblProductTypeDSI", "Product Type"},
        {"lblExecutionDay", "Execution Day"},
        {"amountMsg", "Amount Entered should be greater than Zero"},
        {"chkSuspendUser", ""},
        {"chkCloseSI", ""},
        {"lblSuspendUser", "Suspend User"},
        {"lblCloseSI", "Close SI"},
        
        
    };
    
}
