/*
 * Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition.  
 * 
 * AdvancesProductRB.java
 */
package com.see.truetransact.ui.product.advances;
import java.util.ListResourceBundle;
public class AdvancesProductRB extends ListResourceBundle {
    public AdvancesProductRB(){
    }

    public Object[][] getContents() {
        return contents;
    }

    static final String[][] contents = {
        {"rdoCreditCompdInterestPayable_Yes", "Yes"},
        {"lblLastCDIP", "Last Interest Calculated Date - Credit"},
        {"lblCreditCardSI", "Credit Card "},
        {"lblCreditInterestAmt","Minimum Credit Interest Amount"},
        {"rdoDIAUEAccount_Yes", "Yes"},
        {"rdoTokanAccount_No", "No"},
        {"lblRateCROC", "Rate"},
        {"lblCalcCriteriaIP", "Calculation Criteria"},
        {"rdoBranchBankingSI_No", "No"},
        {"lblPSProcessingCharges", "%"},
        {"lblChequeLeaves", "Number of Free Cheque Leaves"},
        {"lblRateFCharges", "Rate per Folio"},
        {"btnDeleteCRIC", "Delete"},
        {"lblNewAccountPLRIR", " For New Account"},
        {"rdoSAOAccount_No", "No"},
        {"lblDIRoundOffIR", "Debit Interest Round Off"},
        {"rdoDebitCompoundIR_No", "No"},
        {"lblBranchBankingSI", "Any  Branch Banking "},
        {"lblChargeOnDocFCharges", "To Charge On"},
        {"lblCreditInterestRateIIP", "Applicble Credit Interest Rate"},
        {"lblLastAccNo", "Last Account Number"},
        {"lblCLPeriod", "Free Cheque Leaves Period"},
        {"rdoChargedDIIR_Yes", "Yes"},
        {"lblIsStopPaymentCharges", "Stop Payment"},
        {"btnSPCAHHelp", ""},
        {"rdoBranchBankingSI_Yes", "Yes"},
        {"btnEIAHHelp", ""},
        {"lblAIStaffIP", "Addtional Interest for Staff"},
        {"lblCPROIP", "Credit Product Round Off"},
        {"rdoTokanAccount_Yes", "Yes"},
        {"rdoCreditIntInterestPayable_No", "No"},
        {"lblLastADIP", "Last Interest Application Date- Credit"},
        {"lblPenalOthersIR", "Penal Applicable"},
        {"lblIsProcessingCharges", "Processing"},
        {"lblDICompoundFIR", "Debit Interest Compound Frequency"},
        {"lblCreditCompdIP", "Credit Compound"},
        {"lblEIAH", "Expiry Interest - P & L Head"},
        {"panCRChargesInward", "Cheque Return Inward Charges"},
        {"panSplItemDetails", "Special Items Details"},
        {"lblAppliedFromPLRIR", "Applicable From"},
        {"btnSave", ""},
        {"btnMSCAHHelp", ""},
        {"lblMaxAmount4WS", "Maximum Amount  for withdrawal Slip"},
        {"rdoIsCommitmentCharges_Yes", "Yes"},
        {"lblCreditInterestIP", "Credit Interest to be Paid"},
        {"rdoIsApplicablePLRIR_No", "No"},
        {"lblMicsServiceCharges", "Misc Service"},
        {"rdoMobileBankingClientSI_Yes", "Yes"},
        {"lblFCAH", "Folio Charges Account - P & L Head"},
        {"rdoLimitEIOthersIR_Yes", "Yes"},
        {"lblPenalIROthersIR", "Penal Interest Rate"},
        {"rdoSAOAccount_Yes", "Yes"},
        {"lblCreditInterestCompdFIP", "Credit Interest Compounr Frequency"},
        {"rdoLDAccount_Yes", "Yes"},
        {"lblDIAH", "Account For Debit Interest  - P & L Head"},
        {"lblDebitCardSI", "Debit Card "},
        {"lblExOLHAH", "Excess Over Limit Head - P & L Head"},
        {"rdoATMCardSI_No", "No"},
        {"rdoIsApplicablePLRIR_Yes", "Yes"},
        {"lblIsCommitmentCharges", "Commitment"},
        {"lblSpace2", "     "},
        {"lblSpace3", "     "},
        {"panFolioCharges", "Folio Charges"},
        {"rdoMobileBankingClientSI_No", "No"},
        {"lblMaxDIRateIR", "Maximum Debit Interest Rate"},
        {"panDebitInterestIR", "Debit Interest Details"},
        {"lblIRFrequencyFCharges", "Incomplete Rounding off Frequency"},
        {"lblStatementCharges", "Value"},
        {"rdoExistingAccountPLRIR_Yes", "Yes"},
        {"rdoCIUEAccount_Yes", "Yes"},
        {"rdoIsChequebookCharges_Yes", "Yes"},
        {"lblPercentageRatePLRIR", "%"},
        {"lblMaxDIAmtIR", "Maximum Debit Interest Amount"},
        {"lblIsStatementCharges", "Statement"},
        {"lblIsApplicablePLRIR", "Is PLR Applicable"},
        {"lblToken", "Issue Token"},
        {"rdoIsStatementCharges_Yes", "Yes"},
        {"lblAmountCRIC", "Amount"},
        {"rdoWSAccount_No", "No"},
        {"lblChargeOnTransactionFCharges", "To Charge On"},
        {"rdoExistingAccountPLRIR_No", "No"},
        {"lblDICalculationFIR", "Debit Interest Calculation Frequency"},
        {"rdoPenalOthersIR_No", "No"},
        {"panOtherCharges", "Other Charges"},
        {"lblUAICOthersIR", "Unclear Advance Interest Charges"},
        {"lblODOverAboveLimimt", " O/D Allowed Over and Above Limit"},
        {"lblAddIntRateIP", "%"},
        {"rdoCreditCardSI_No", "No"},
        {"btnDelete", ""},
        {"lblProdFrequencyIP", "Product Frequency"},
        {"rdoWSAccount_Yes", "Yes"},
        {"lblAmountCROC", "Amount"},
        {"lblSPCAH", "Stop Payment Charges - P & L Head "},
        {"lblIsApplicableFCharges", "Folio Chagres Applicable"},
        {"lblPIAH", "Panel Interest - P & L Head"},
        {"lblPercentageMaxDIRateIR", "%"},
        {"lblMSCAH", "Misc Service Charges - P & L Head"},
        {"lblChargedDIIR", "Is Debit Interest Applicable"},
        {"lblCrediInterestAFIP", "Credit Interest Application Frequency"},
        {"lblDCRequiredIR", "Debit Compound Required"},
        {"lblCRCInwardAH", "Cheque Return Charges (Inward) - P & L Head"},
        {"rdoUAICOthersIR_Yes", "Yes"},
        {"btnClose", ""},
        {"rdoIsStopPaymentCharges_No", "No"},
        {"rdoEOLOthersIR_Yes", "Yes"},
        {"lblLastAppliedFCharges", "Last Charges Applied On"},
        {"rdoACAAccount_Yes", "Yes"},
        {"lblMobileBankingClientSI", "Mobile Banking Client"},
        {"lblStateFrequency", "Statement Frequency"},
        {"lblCAFrequencyFCharges", "Charges Applicable Frequency"},
        {"panOthersIR", "Other Details "},
        {"rdoIsProcessingCharges_Yes", "Yes"},
        {"btnDeleteCROC", "Delete"},
        {"lblWithdrawalSlip", "Allow Withdrawal Slip"},
        {"lblPercentagePenalIROthersIR", "%"},
        {"lblCICAH", "Chequebook Issue Charges - Account Head"},
        {"lblDueDateFCharges", "Next Due Date"},
        {"btnDeleteSI", "Delete"},
        {"btnPIAHHelp", ""},
        {"btnSaveCRIC", "Save"},
        {"rdoDebitCardSI_No", "No"},
        {"btnSaveSI", "Save"},
        {"rdoDebitCompoundIR_Yes", "Yes"},
        {"rdoCreditCompdInterestPayable_No", "No"},
        {"btnPrint", ""},
        {"lblInterestADDebitIR", "Last Interest Application Date - Debit"},
        {"lblACCAH", "Account Closing Charge - P & L Head"},
        {"lblPercentageCreditInterestRateIP", "%"},
        {"rdoCreditIntInterestPayable_Yes", "Yes"},
        {"btnACCAHHelp", ""},
        {"rdoIsApplicableFCharges_Yes", "Yes"},
        {"rdoNewAccountPLRIR_Yes", "Yes"},
        {"lblAssetsSI", "Assets Category"},
        {"lblExistingAccountPLRIR", "For Existing Accounts "},
        {"rdoIsStatementCharges_No", "No"},
        {"panMiscItemSI", "Miscellanous Item Details"},
        {"btnCRCoutwardAHHelp", ""},
        {"btnNewCRIC", "New"},
        {"lblInterestCDDebitIR", "Last Interest Calculated Date- Debit"},
        {"lblPercentageMinDIRateIR", "%"},
        {"lblAIRStaffIP", "Interest Rate"},
        {"btnCICAHHelp", ""},
        {"rdoLimitEIOthersIR_No", "No"},
        {"lblIsChequebookCharges", "Chequebook"},
        {"btnCIAHHelp", ""},
        {"btnNew", ""},
        {"lblProdId", "Product Id"},
        {"lblLimitDefination", "Is Limit Definition Allowed"},
        {"lblDPRoundOffIR", "Debit Product Round Off"},
        {"rdoEOLOthersIR_No", "No"},
        {"btnExOLHAHelp", ""},
        {"rdoIsChequebookCharges_No", "No"},
        {"rdoIsStopPaymentCharges_Yes", "Yes"},
        {"rdoDebitCardSI_Yes", "Yes"},
        {"btnNewSI", "New"},
        {"lblProductFOthersIR", "Product Frequency"},
        {"rdoIsApplicableFCharges_No", "No"},
        {"btnAccountHeadAccountHelp", ""},
        {"lblAccountSFPLRIR", "For Account Sactioned From"},
        {"lblBehaveLike", "Operates Like"},
        {"lblMD4EOL", "Percentage of Manager Discounts for EOL"},
        {"rdoODALAccount_Yes", "Yes"},
        {"rdoUAICOthersIR_No", "No"},
        {"lblFolioEntriesFCharges", "No of Entries per Folio"},
        {"lblProcessingCharges", "Applicable Charges "},
        {"btnFCAHHelp", ""},
        {"panPLRIR", "PLR Details"},
        {"btnSCAHHelp", ""},
        {"lblRateSI", "Rate"},
        {"lblStaffAccOpened", "Is Staff Account Opened"},
        {"rdoAdditionalIntInterestPayable_Yes", "Yes"},
        {"btnEdit", ""},
        {"rdoCreditCardSI_Yes", "Yes"},
        {"lblCreditInterestCFIP", "Credit Interest Calculation Frequency"},
        {"lblAgCIAH", "Against Clearing Interest Account Head "},
        {"lblCRCOutwardAH", "Cheque Return Charges (Outward) - P & L Head"},
        {"btnAgCIAHHelp", ""},
        {"btnSaveCROC", "Save"},
        {"lblCollectChargeFCharges", "To Collect Charges"},
        {"rdoChargedDIIR_No", "No"},
        {"lblPSCommitmentCharges", "%"},
        {"rdoAdditionalIntInterestPayable_No", "No"},
        {"lblDebitInterestOnDAUE", "Debit Interest Against Unclear Effect"},
        {"lblLimitEIOthersIR", "Limit Expiry Interest"},
        {"lblAccountCLosingCharges", "Account Closing"},
        {"lblNumberPattern", "Numbering Patterns to be Followed"},
        {"lblAccountHead", "Account Head"},
        {"rdoCIUEAccount_No", "No"},
        {"rdoACAAccount_No", "No"},
        {"btnNewCROC", "New"},
        {"lblRateCRIC", "Rate"},
        {"rdoPenalOthersIR_Yes", "Yes"},
        {"lblACA", "Are Chequebooks Allowed"},
        {"lblCIROIP", "Credit Interest Round Off"},
        {"lblMinDIRateIR", "Minimum Debit Interest Rate"},
        {"rdoNewAccountPLRIR_No", "No"},
        {"rdoDIAUEAccount_No", "No"},
        {"rdoODALAccount_No", "No"},
        {"lblProdDesc", "Product Description"},
        {"lblDIApplicationFIR", "Debit Interest Appliction Frequency"},
        {"lblCreditInterestOnUE", "Credit Interest on Unclear Effect"},
        {"btnCRCInwardAHHelp", ""},
        {"lblRatePLRIR", "Rate"},
        {"rdoIsProcessingCharges_No", "No"},
        {"lblSCAH", "Statament Charges - P & L Head"},
        {"lblATMCardSI", "ATM Card "},
        {"rdoATMCardSI_Yes", "Yes"},
        {"lblCLStart", "Free Cheque Leaves Starting From"},
        {"btnDIAHHelp", ""},
        {"lblEOLOthersIR", "EOL Applicable"},
        {"panCRChargesOutward", "Cheque Return Outward Charges"},
        {"rdoLDAccount_No", "No"},
        {"lblCIAH", "Account for Credit Interest - P & L Head"},
        {"btnCancel", ""},
        {"lblMinDIAmtIR", "Minimum Debit Interest Amount"},
        {"lblPercentageMDAccount", "%"},
        {"rdoIsCommitmentCharges_No", "No"},
        
        {"EDIT_WARNING", "No Data Exists for the Selected Product ID, Pls Enter as New!!!"},
        
        {"MaxInteRuleWarning", "Maximum Debit Interest Rate Should Be Greater than Minimum Debit Interest Rate."},
        {"MaxAmtRuleWarning", "Maximum Debit Interest Amount Should Be Greater than Minimum Debit Interest Amount."},
        {"prodIdWarning", "This Product Id Already Exist, please Enter the New one."}
   };

}
