/*
 * Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition.  
 * 
 * AdvancesProductMRB.java
 */
package com.see.truetransact.ui.product.advances;
import java.util.ListResourceBundle;
public class AdvancesProductMRB extends ListResourceBundle {
    public AdvancesProductMRB(){
    }

    public Object[][] getContents() {
        return contents;
    }

    static final String[][] contents = {
        {"txtExOLHAH", "ExOLHAH should not be empty!!!"},
        {"cboProdCurrency", "ProdCurrency should be a proper value!!!"},
        {"rdoCreditCompdInterestPayable_Yes", "CreditCompdInterestPayable should be selected!!!"},
        {"rdoUAICOthersIR_Yes", "UAICOthersIR should be selected!!!"},
        {"rdoDIAUEAccount_Yes", "DIAUEAccount should be selected!!!"},
        {"cboCollectChargeFCharges", "CollectChargeFCharges should be a proper value!!!"},
        {"cboChargeOnDocFCharges", "ChargeOnDocFCharges should be a proper value!!!"},
        {"cboDIRoundOffIR", "DIRoundOffIR should be a proper value!!!"},
        {"rdoEOLOthersIR_Yes", "EOLOthersIR should be selected!!!"},
        {"txtMaxAmountOnWS", "MaxAmountOnWS should not be empty!!!"},
        {"txtProductIdAccount", "ProductIdAccount should not be empty!!!"},
        {"rdoACAAccount_Yes", "ACAAccount should be selected!!!"},
        {"txtRatePLRIR", "RatePLRIR should not be empty!!!"},
        {"txtMaxDIAmtIR", "MaxDIAmtIR should not be empty!!!"},
        {"txtCRCoutwardAH", "CRCoutwardAH should not be empty!!!"},
        {"tdtLastADIP", "LastADIPDate should not be empty!!!"},
        {"tdtCLStartAccount", "CLStartAccountDate should not be empty!!!"},
        {"rdoIsProcessingCharges_Yes", "IsProcessingCharges should be selected!!!"},
        {"txtAddIntRateIP", "AddIntRateIP should not be empty!!!"},
        {"txtLastAccNoAccount", "LastAccNoAccount should not be empty!!!"},
        {"txtFolioEntriesFCharges", "FolioEntriesFCharges should not be empty!!!"},
        {"txtCICAH", "CICAH should not be empty!!!"},
        {"cboCLPeriod", "CLPeriod should be a proper value!!!"},
        {"cboProcessingCharges", "ProcessingCharges should be a proper value!!!"},
        {"rdoChargedDIIR_Yes", "ChargedDIIR should be selected!!!"},
        {"rdoDebitCompoundIR_Yes", "DebitCompoundIR should be selected!!!"},
        {"tdtLastAppliedFCharges", "LastAppliedFChargesDate should not be empty!!!"},
        {"rdoBranchBankingSI_Yes", "BranchBankingSI should be selected!!!"},
        {"txtMiscServiceCharges", "MiscServiceCharges should not be empty!!!"},
        {"txtDIAH", "DIAH should not be empty!!!"},
        {"txtMinDIRateIR", "MinDIRateIR should not be empty!!!"},
        {"rdoTokanAccount_Yes", "TokanAccount should be selected!!!"},
        {"rdoCreditIntInterestPayable_Yes", "CreditIntInterestPayable should be selected!!!"},
        {"cboCIROIP", "CIROIP should be a proper value!!!"},
        {"cboDICalculationFIR", "DICalculationFIR should be a proper value!!!"},
        {"rdoIsApplicableFCharges_Yes", "IsApplicableFCharges should be selected!!!"},
        {"rdoNewAccountPLRIR_Yes", "NewAccountPLRIR should be selected!!!"},
        {"cboCreditInterestAFIP", "CreditInterestAFIP should be a proper value!!!"},
        {"txtPIAH", "PIAH should not be empty!!!"},
        {"txtStopPaymentCharges", "StopPaymentCharges should not be empty!!!"},
        {"tdtInterestCDDebitIR", "InterestCDDebitIRDate should not be empty!!!"},
        {"rdoIsCommitmentCharges_Yes", "IsCommitmentCharges should be selected!!!"},
        {"txtStatementCharges", "StatementCharges should not be empty!!!"},
        {"txtProductDescAccount", "ProductDescAccount should not be empty!!!"},
        {"rdoMobileBankingClientSI_Yes", "MobileBankingClientSI should be selected!!!"},
        {"txtAgCIAH", "AgCIAH should not be empty!!!"},
        {"rdoLimitEIOthersIR_Yes", "LimitEIOthersIR should be selected!!!"},
        {"rdoSAOAccount_Yes", "SAOAccount should be selected!!!"},
        {"txtChequebookCharges", "ChequebookCharges should not be empty!!!"},
        {"txtCIAH", "CIAH should not be empty!!!"},
        {"rdoLDAccount_Yes", "LDAccount should be selected!!!"},
        {"txtSCAH", "SCAH should not be empty!!!"},
        {"txtNumberpatternAccount", "NumberpatternAccount should not be empty!!!"},
        {"txtMSCAH", "MSCAH should not be empty!!!"},
        {"txtRateFCharges", "RateFCharges should not be empty!!!"},
        {"rdoIsStopPaymentCharges_Yes", "IsStopPaymentCharges should be selected!!!"},
        {"txtSPCAH", "SPCAH should not be empty!!!"},
        {"rdoDebitCardSI_Yes", "DebitCardSI should be selected!!!"},
        {"cboCommitmentCharges", "CommitmentCharges should be a proper value!!!"},
        {"txtManagerDistAccount", "ManagerDistAccount should not be empty!!!"},
        {"rdoIsApplicablePLRIR_Yes", "IsApplicablePLRIR should be selected!!!"},
        {"rdoODALAccount_Yes", "ODALAccount should be selected!!!"},
        {"txtAccountClosingCharges", "AccountClosingCharges should not be empty!!!"},
        {"txtMaxDIRateIR", "MaxDIRateIR should not be empty!!!"},
        {"txtCLPeriodAccount", "CLPeriodAccount should not be empty!!!"},
        {"cboProdFrequencyIP", "ProdFrequencyIP should be a proper value!!!"},
        {"cboDPRoundOffIR", "DPRoundOffIR should be a proper value!!!"},
        {"txtPenalIROthersIR", "PenalIROthersIR should not be empty!!!"},
        {"txtCreditInterestRateIP", "CreditInterestRateIP should not be empty!!!"},
        {"rdoAdditionalIntInterestPayable_Yes", "AdditionalIntInterestPayable should be selected!!!"},
        {"rdoCIUEAccount_Yes", "CIUEAccount should be selected!!!"},
        {"rdoCreditCardSI_Yes", "CreditCardSI should be selected!!!"},
        {"rdoIsChequebookCharges_Yes", "IsChequebookCharges should be selected!!!"},
        {"tdtAppliedFromPLRIR", "AppliedFromPLRIRDate should not be empty!!!"},
        {"tdtLastCDIP", "LastCDIPDate should not be empty!!!"},
        {"txtACCAH", "ACCAH should not be empty!!!"},
        {"cboDIApplicationFIR", "DIApplicationFIR should be a proper value!!!"},
        {"cboCreditInterestCompdFIP", "CreditInterestCompdFIP should be a proper value!!!"},
        {"cboStmtFrequency", "StmtFrequency should be a proper value!!!"},
        {"tdtDueDateFCharges", "DueDateFChargesDate should not be empty!!!"},
        {"tdtInterestADDebitIR", "InterestADDebitIRDate should not be empty!!!"},
        {"rdoIsStatementCharges_Yes", "IsStatementCharges should be selected!!!"},
        {"cboDICompoundFIR", "DICompoundFIR should be a proper value!!!"},
        {"cboCreditInterestCFIP", "CreditInterestCFIP should be a proper value!!!"},
        {"cboCalcCtriteriaIP", "CalcCtriteriaIP should be a proper value!!!"},
        {"txtFreeCLAccount", "FreeCLAccount should not be empty!!!"},
        {"rdoPenalOthersIR_Yes", "PenalOthersIR should be selected!!!"},
        {"rdoExistingAccountPLRIR_No", "ExistingAccountPLRIR should be selected!!!"},
        {"cboProductFOthersIR", "ProductFOthersIR should be a proper value!!!"},
        {"cboCPROIP", "CPROIP should be a proper value!!!"},
        {"cboIRFrequencyFCharges", "IRFrequencyFCharges should be a proper value!!!"},
        {"cboChargeOnTransactionFCharges", "ChargeOnTransactionFCharges should be a proper value!!!"},
        {"tdtAccountSFPLRIR", "AccountSFPLRIRDate should not be empty!!!"},
        {"txtProcessingCharges", "ProcessingCharges should not be empty!!!"},
        {"txtEIAH", "EIAH should not be empty!!!"},
        {"txtFCAH", "FCAH should not be empty!!!"},
        {"cboBehavesLike", "BehavesLike should be a proper value!!!"},
        {"rdoWSAccount_Yes", "WSAccount should be selected!!!"},
        {"rdoATMCardSI_Yes", "ATMCardSI should be selected!!!"},
        {"txtCRCInwardAH", "CRCInwardAH should not be empty!!!"},
        {"cboCAFrequencyFCharges", "CAFrequencyFCharges should be a proper value!!!"},
        {"txtMinDIAmtIR", "MinDIAmtIR should not be empty!!!"},
        {"txtCommitmentCharges", "CommitmentCharges should not be empty!!!"},
        {"txtAccountHeadAccount", "AccountHeadAccount should not be empty!!!"}, 
        {"rdoExistingAccountPLRIR_Yes","PLR should be selected!!!"},
        {"cboAmountCRIC","Amount should be a proper value!!!"},
        {"cboAmountCROC","Amount should be a proper value!!!"},
        {"cboAssetsSI","Assets should be a proper value!!!"},
        {"txtRateCRIC","RateCRIC should not be empty!!!"},
        {"txtRateCROC","RateCROC should not be empty!!!"},
        {"txtRateSI","Rate SI should not be empty!!!"}

   };

}
