/*
 * Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition. 
 * 
 * frmLoanApplication.java
 *
 * Created on September 12, 2011, 10:33 AM
 */

package com.see.truetransact.ui.termloan.loanapplicationregister;
import com.see.truetransact.clientutil.ClientUtil;
/**
 *
 * @author  user
 */
public class frmLoanApplication extends com.see.truetransact.uicomponent.CFrame implements java.util.Observer  {
    
    private LoanApplicationOB observable;
    /** Creates new form panBorrowings */
    public frmLoanApplication() {
        initComponents();
        initIntCompnents();
  //       setMaxLengths();
        observable = new LoanApplicationOB();
       // observable.addObserver(this);
    }
    private void setMaxLengths() {
       // txtUserID.setAllowAll(true);
       // txtPwd.setAllowAll(true);
        this.setBounds(0,0, 1350, 700);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        cButton1 = new com.see.truetransact.uicomponent.CButton();
        cDesktopPane1 = new com.see.truetransact.uicomponent.CDesktopPane();
        cButton3 = new com.see.truetransact.uicomponent.CButton();
        cButton4 = new com.see.truetransact.uicomponent.CButton();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        cButton1.setText("New Borrwing");
        cButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        getContentPane().add(cButton1);
        cButton1.setBounds(10, 10, 130, 26);

        getContentPane().add(cDesktopPane1);
        cDesktopPane1.setBounds(0, 0, 0, 0);

        cButton3.setText("Borrowing Disbursal");
        cButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        getContentPane().add(cButton3);
        cButton3.setBounds(10, 50, 130, 26);

        cButton4.setText("Borrowing funds");
        cButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        getContentPane().add(cButton4);
        cButton4.setBounds(10, 90, 130, 26);

    }//GEN-END:initComponents
    public void initIntCompnents()
    {
      ifrNewBorrowings=new LoanApplicationUI();
      //ifrNewBorrowings.setVisible(true);
      getContentPane().add(ifrNewBorrowings);
      ifrNewBorrowings.setBounds(160,10,1000,600);
      
    //  ifrBorrowingfunds=new ifrBorrowingfunds();
    //   getContentPane().add(ifrBorrowingfunds);
    //  ifrBorrowingfunds.setBounds(160,10,1150,650);
      
 
    }
    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
         //ClientUtil.displayAlert(evt.);
       // ClientUtil.displayAlert(evt.getActionCommand());
   //  initIntCompnents();
        if(evt.getActionCommand()=="New Borrwing")
        {
           // ifrNewBorrowings=new ifrNewBorrowing();
          //  ClientUtil.displayAlert("INNN");
            ifrNewBorrowings=new LoanApplicationUI();
      //ifrNewBorrowings.setVisible(true);
      getContentPane().add(ifrNewBorrowings);
      ifrNewBorrowings.setBounds(160,10,1000,600);
      
          ifrNewBorrowings.setVisible(true);
        //   ifrBorrowingfunds.setVisible(false);
     //      ifrRepaymentInterest.setVisible(false);
       //  ifrRepaymentInterest.dispose();
//          ifrRepIntCls.dispose();
//          ifrDisbursal.dispose();
        }
        
       
    }//GEN-LAST:event_btnNewActionPerformed
private void exitForm(java.awt.event.WindowEvent evt) {
        System.exit(0);
    }
   public static void main(String args[]) throws Exception {
        new frmLoanApplication().show();
    }
    public void update(java.util.Observable observable, Object obj) {
    }    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.see.truetransact.uicomponent.CButton cButton1;
    private com.see.truetransact.uicomponent.CButton cButton3;
    private com.see.truetransact.uicomponent.CButton cButton4;
    private com.see.truetransact.uicomponent.CDesktopPane cDesktopPane1;
    // End of variables declaration//GEN-END:variables
    public LoanApplicationUI ifrNewBorrowings;
    // public  ifrBorrowingfunds ifrBorrowingfunds;
  
}
