/*
 * Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition.  
 **
 *
 * EditWaiveTableUI.java
 *
 * Created on March 3, 2004, 1:46 PM
 */
package com.see.truetransact.ui.common.viewall;

import javax.swing.table.*;
import javax.swing.*;
import javax.swing.event.*;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import com.see.truetransact.commonutil.CommonUtil;
import com.see.truetransact.uicomponent.CInternalFrame;
import com.see.truetransact.clientutil.ClientUtil;




import com.see.truetransact.uicomponent.CTable;
import java.util.*;


public class EditWaiveTableUI extends com.see.truetransact.uicomponent.CDialog {

    private TableModelListener tableModelListener;
    HashMap dataMap = null;
    CInternalFrame parent = null;
    javax.swing.JList lstSearch;
    java.util.ArrayList arrLst = new java.util.ArrayList();
    Date currDt = null;
    private String subsidyId = "";
    boolean isFilled = false;
    boolean transAmtEdit = false;
    private String sourceScreen = "";
    private ArrayList recoveryList = new ArrayList();

    /**
     * Creates new form EditWaiveTableUI
     */
    public EditWaiveTableUI() {
        setupInit();
        setupScreen();
    }

    /**
     * Creates new form EditWaiveTableUI
     */
    public EditWaiveTableUI(CInternalFrame parent, HashMap paramMap) {
        this.parent = parent;
        setupInit();
        setupScreen();
    }

    /**
     * Creates new form EditWaiveTableUI
     */
    public EditWaiveTableUI(String sourceScreen, HashMap dataMap) {

        this.sourceScreen = sourceScreen;
        this.dataMap = dataMap;
        setupInit();
        setupScreen();
    }

    private void setupInit() {
        currDt = ClientUtil.getCurrentDate();
        initComponents();
        internationalize();
        setObservable();
        initSubsidyTableData();
    }

    private void setupScreen() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
    }

    private void setObservable() {
        try {
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void fillData(Object obj) {
        HashMap dataMap = (HashMap) obj;
    }

    private void editDeleteTableData(HashMap map) {
        transAmtEdit = false;
        transAmtEdit = true;
        initSubsidyTableData();
    }

    public void show() {

//        if (isShow) {
        Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        pack();

        /*
         * Center frame on the screen
         */
        Dimension frameSize = getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        setLocation((screenSize.width - frameSize.width) / 2,
                (screenSize.height - frameSize.height) / 2);
        setModal(true);
        super.show();
        // }


//          super.show();
    }

    /**
     * Bring up and populate the temporary project detail screen.
     */
    private void whenTableRowSelected() {
        int rowIndexSelected = tblData.getSelectedRow();
        setColour();
    }

    private boolean isSelectedRowTicked(com.see.truetransact.uicomponent.CTable table) {
        boolean selected = false;
        for (int i = 0, j = table.getRowCount(); i < j; i++) {
            selected = ((Boolean) table.getValueAt(i, 0)).booleanValue();
            if (!selected) {
                //            table.setForeground(Colu
                break;
            }
        }
        return selected;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panTable = new com.see.truetransact.uicomponent.CPanel();
        panMembershipTable = new com.see.truetransact.uicomponent.CPanel();
        srpMemberShipCTable = new com.see.truetransact.uicomponent.CScrollPane();
        tblData = new com.see.truetransact.uicomponent.CTable();
        panTotal = new com.see.truetransact.uicomponent.CPanel();
        btnSave = new com.see.truetransact.uicomponent.CButton();
        btnClose = new com.see.truetransact.uicomponent.CButton();

        setTitle("Edit Table UI");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panTable.setMinimumSize(new java.awt.Dimension(400, 250));
        panTable.setPreferredSize(new java.awt.Dimension(400, 250));
        panTable.setLayout(new java.awt.GridBagLayout());

        panMembershipTable.setMinimumSize(new java.awt.Dimension(300, 250));
        panMembershipTable.setPreferredSize(new java.awt.Dimension(300, 250));
        panMembershipTable.setLayout(new java.awt.GridBagLayout());

        srpMemberShipCTable.setMinimumSize(new java.awt.Dimension(450, 200));

        tblData.setBackground(new java.awt.Color(212, 208, 200));
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Due", "Recieved", "Recievable"
            }
        ));
        tblData.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblData.setDragEnabled(true);
        tblData.setInheritsPopupMenu(true);
        tblData.setMaximumSize(new java.awt.Dimension(1000, 1000));
        tblData.setMinimumSize(new java.awt.Dimension(450, 200));
        tblData.setPreferredScrollableViewportSize(new java.awt.Dimension(100, 500));
        tblData.setPreferredSize(new java.awt.Dimension(450, 250));
        tblData.setRequestFocusEnabled(false);
        srpMemberShipCTable.setViewportView(tblData);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panMembershipTable.add(srpMemberShipCTable, gridBagConstraints);

        panTotal.setMaximumSize(new java.awt.Dimension(450, 100));
        panTotal.setMinimumSize(new java.awt.Dimension(450, 25));
        panTotal.setPreferredSize(new java.awt.Dimension(200, 25));
        panTotal.setLayout(new java.awt.GridBagLayout());

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        panTotal.add(btnSave, new java.awt.GridBagConstraints());

        btnClose.setText("CANCEL");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        panTotal.add(btnClose, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 42, 0, 42);
        panMembershipTable.add(panTotal, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        panTable.add(panMembershipTable, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(panTable, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void initSubsidyTableData() {
        tblData.setModel(new javax.swing.table.DefaultTableModel(
                setTableData(),
                new String[]{
                    "Name", "Amount", "WaiveAmount"
                }) {

            Class[] types = new Class[]{
                java.lang.String.class,
                java.lang.String.class,
                java.lang.String.class,};
            boolean[] canEdit = new boolean[]{
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                if (columnIndex == 2) {
                    return true;
                }

                return canEdit[columnIndex];
            }
        });


        tblData.setCellSelectionEnabled(true);
        tblData.addPropertyChangeListener(new java.beans.PropertyChangeListener() {

            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblDataPropertyChange(evt);

            }
        });
        setTableModelListener();

    }

    private void tblDataPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblRecoveryListTallyPropertyChange
    }//GEN-LAST:event_tblRecoveryListTallyPropertyChange

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed

        tblData = new CTable();
        ClientUtil.clearAll(this);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseActionPerformed

    private void setTableModelListenerUpdate() {
        tableModelListener = new TableModelListener() {

            public void tableChanged(TableModelEvent e) {
                if (e.getType() == TableModelEvent.UPDATE) {
                    System.out.println("Cell " + e.getFirstRow() + ", "
                            + e.getColumn() + " changed. The new value: "
                            + tblData.getModel().getValueAt(e.getFirstRow(),
                            e.getColumn()));
                    int row = e.getFirstRow();
                    int column = e.getColumn();
                    if (column == 2) {
                        TableModel model = tblData.getModel();
//                        tblData.setValueAt(model.getValueAt(tblData.getSelectedRow(),5),tblData.getSelectedRow(),5);
//                        calcEachChittal();
//                        calcTotal();
                    }
                }
            }
        };
        tblData.getModel().addTableModelListener(tableModelListener);
    }

    private Object[][] setTableData() {
        DefaultTableModel tblModel = (DefaultTableModel) tblData.getModel();
        HashMap whereMap = new HashMap();
        //added by rishaad for listing waive amount
        whereMap = this.dataMap;
        Object totalList[][] = new Object[whereMap.keySet().size()][3];
        int i = 0;
        for (Iterator it = whereMap.entrySet().iterator(); it.hasNext();) {
            Map.Entry entry = (Map.Entry) it.next();
            totalList[i][0] = entry.getKey();
            totalList[i][1] = entry.getValue();
            totalList[i][2] = "0";
            i++;
        }
        return totalList;
    }

    private void setTableModelListener() {
        tableModelListener = new TableModelListener() {

            public void tableChanged(TableModelEvent e) {
                if (e.getType() == TableModelEvent.UPDATE) {
                    int row = e.getFirstRow();
                    int column = e.getColumn();
                    if (column == 2) {
                        if (CommonUtil.convertObjToDouble(tblData.getModel().getValueAt(e.getFirstRow(), e.getColumn())).doubleValue() > 0) {
                            double demand_Amount = CommonUtil.convertObjToDouble(tblData.getValueAt(tblData.getSelectedRow(), 1).toString()).doubleValue();
                            double recovered_Amount = CommonUtil.convertObjToDouble(tblData.getValueAt(tblData.getSelectedRow(), 2).toString()).doubleValue();
                            if (demand_Amount < recovered_Amount && recovered_Amount > 0) {
                                ClientUtil.showMessageWindow("Transaction Amount should not Cross Interest Amount !!!");
                                tblData.setValueAt(tblData.getValueAt(tblData.getSelectedRow(), 1), tblData.getSelectedRow(), 2);
                            } else {
                                String scheme_Name = CommonUtil.convertObjToStr(tblData.getValueAt(tblData.getSelectedRow(), 2));
                            }
                        }
//                        TableModel model = tblData.getModel();
                        //                        calcTallyListTotal();
                    }
                }
            }
        };
        tblData.getModel().addTableModelListener(tableModelListener);
    }

    public ArrayList getTableData() {
        ArrayList singleList = new ArrayList();
        ArrayList totList = new ArrayList();
        int count = tblData.getModel().getRowCount();
        int columnCount = tblData.getModel().getColumnCount();
        for (int i = 0; i < count; i++) {
            singleList = new ArrayList();
            for (int j = 0; j < columnCount; j++) {
                singleList.add(tblData.getValueAt(i, j));
            }
            totList.add(singleList);
        }
        return totList;
    }

    private void setColour() {
        /*
         * Set a cellrenderer to this table in order format the date
         */
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer() {

            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                boolean selected = ((Boolean) table.getValueAt(row, 0)).booleanValue();
                if (!selected) {
                    setForeground(Color.RED);
                } else {
                    setForeground(Color.BLACK);
                }
                // Set oquae
                this.setOpaque(true);
                return this;
            }
        };
        tblData.setDefaultRenderer(Object.class, renderer);
    }

    private void internationalize() {
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }

    public void update(Observable o, Object arg) {
    }

    public void updateOBFields() {
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.see.truetransact.uicomponent.CButton btnClose;
    private com.see.truetransact.uicomponent.CButton btnSave;
    private com.see.truetransact.uicomponent.CPanel panMembershipTable;
    private com.see.truetransact.uicomponent.CPanel panTable;
    private com.see.truetransact.uicomponent.CPanel panTotal;
    private com.see.truetransact.uicomponent.CScrollPane srpMemberShipCTable;
    private com.see.truetransact.uicomponent.CTable tblData;
    // End of variables declaration//GEN-END:variables
}
