/*
 * Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition. 
 * 
 * TableDataUI.java
 *
 * Created on January 20, 2004, 10:45 AM
 */

package com.see.truetransact.ui.common.viewall;

import java.util.HashMap;
import com.see.truetransact.clientutil.ClientUtil;
//import com.see.truetransact.clientutil.TableColorRenderer;
import com.see.truetransact.commonutil.CommonConstants;
import com.see.truetransact.commonutil.CommonUtil;
import com.see.truetransact.clientproxy.ProxyParameters;
/**
 *
 * @author  bala
 */
public class TableDataUI extends com.see.truetransact.uicomponent.CInternalFrame {
    
    /** Creates new form TableDataUI */
    public TableDataUI(String mapName) {
        initComponents();
        initSetup(mapName, null);
    }

    /** Creates new form TableDataUI */
    public TableDataUI(String mapName, HashMap whereConditionMap) {
        initComponents();
        initSetup(mapName, whereConditionMap);
    }
    
    private void initSetup(String mapName, HashMap whereConditionMap) {
        HashMap whereMap = new HashMap();
        whereMap.put(CommonConstants.MAP_NAME, mapName);
        
        if (whereConditionMap != null) {
           
            whereMap.put(CommonConstants.MAP_WHERE, whereConditionMap);
        }else if(whereConditionMap ==null || whereConditionMap.isEmpty()){
            whereConditionMap =new HashMap();
            whereConditionMap.put(CommonConstants.BRANCH_ID,ProxyParameters.BRANCH_ID);
            whereConditionMap.put(CommonConstants.USER_ID,ProxyParameters.USER_ID);
            whereMap.put(CommonConstants.MAP_WHERE, whereConditionMap);
        }
            
        if(!mapName.equals("getAllUsersList") && !mapName.equals("getAllTempUsersList"))
        btnLogOut.setVisible(false);
        ClientUtil.setTableModel(whereMap, tblDenomination);
        
        /*HashMap map = new HashMap();
        map.put (new Integer("1"), java.awt.Color.yellow);
        TableColorRenderer renderer = new TableColorRenderer(map);
        tblDenomination.setDefaultRenderer(Object.class, renderer);*/
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        panDenomination = new com.see.truetransact.uicomponent.CPanel();
        scrDenomination = new com.see.truetransact.uicomponent.CScrollPane();
        tblDenomination = new com.see.truetransact.uicomponent.CTable();
        panButton = new com.see.truetransact.uicomponent.CPanel();
        btnLogOut = new com.see.truetransact.uicomponent.CButton();
        btnOk1 = new com.see.truetransact.uicomponent.CButton();

        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(660, 655));
        panDenomination.setLayout(new java.awt.GridBagLayout());

        tblDenomination.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrDenomination.setViewportView(tblDenomination);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panDenomination.add(scrDenomination, gridBagConstraints);

        getContentPane().add(panDenomination, java.awt.BorderLayout.CENTER);

        panButton.setLayout(new java.awt.GridBagLayout());

        btnLogOut.setText("LogOut");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        panButton.add(btnLogOut, gridBagConstraints);

        btnOk1.setText("Close");
        btnOk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOk1ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        panButton.add(btnOk1, gridBagConstraints);

        getContentPane().add(panButton, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void btnOk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOk1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnOk1ActionPerformed
 private void deletescreenLock(String userid){
            HashMap map=new HashMap();
            map.put("USER_ID",userid);
            map.put("TRANS_DT", ClientUtil.getCurrentDate());
            map.put("INITIATED_BRANCH",ProxyParameters.BRANCH_ID);
            ClientUtil.execute("DELETE_SCREEN_LOCK", map);
        }
 
    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // Add your handling code here:
       HashMap where = new HashMap();
       int i = tblDenomination.getSelectedRow();
       if(i<0){
           ClientUtil.displayAlert("Choose Any Row To Set The Status LogOut");
       }else{
            String bcode = CommonUtil.convertObjToStr(tblDenomination.getValueAt(i, 0));
            String userid = CommonUtil.convertObjToStr(tblDenomination.getValueAt(i, 1));
          
            // Below changes made by Jeffin John on 30-05-2014 for Mantis ID - 9191
            
            where.put("BRANCH_CODE", bcode);
            where.put("USER_ID", userid);
            where.put("LAST_LOGOUT_DT", new java.util.Date());
            where.put("LOGIN_STATUS", "LOGOUT");
            ClientUtil.execute("updateSuspendUser", where);
            tblDenomination.setValueAt("LOGOUT", i, 4);
            ClientUtil.execute("updateUserLoginHistory", where);
            deletescreenLock(userid);
        }
    }//GEN-LAST:event_btnLogOutActionPerformed
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        this.dispose();
    }//GEN-LAST:event_exitForm
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.see.truetransact.uicomponent.CButton btnLogOut;
    private com.see.truetransact.uicomponent.CButton btnOk1;
    private com.see.truetransact.uicomponent.CPanel panButton;
    private com.see.truetransact.uicomponent.CPanel panDenomination;
    private com.see.truetransact.uicomponent.CScrollPane scrDenomination;
    private com.see.truetransact.uicomponent.CTable tblDenomination;
    // End of variables declaration//GEN-END:variables
    
}
