/*
 * Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition.
 * 
 *
 * RemittanceProductRB.java
 *
 * Created on Fri Jun 04 12:09:38 GMT+05:30 2004
 */

package com.see.truetransact.ui.product.remittance;

import java.util.ListResourceBundle;

public class RemittanceProductRB extends ListResourceBundle {
    public RemittanceProductRB(){
    }
    
    public Object[][] getContents() {
        return contents; 
    }
    
    static final String[][] contents = {
        {"lblProdIDRemitProdBranch", ""},
        {"lblProdIDRemitProdChrg", "Product ID"},
        {"lblSpace4", "     "},
        {"lblProdDescRemitProdCharge", ""},
        {"lblProdIDRemitProdCharge", ""},
        {"lblDisplayBankCode", ""},
        {"lblDisplayBranchCode", ""},
        {"lblChargesBankCode", "Bank Code"},
        {"lblChargesBranchCode", "Branch Code"},
        {"lblProdIDRemitProdBrch", "Product ID"},
        {"panRemitProdCharges", "Product Charges"},
        {"lblProdDescRemitProdBrch", "Product Name"},
        {"lblProdDescRemitProdChrg", "Product Name"},
        {"lblProdDescRemitProdBranch", ""},
        {"btnOCHeadGRHelp", ""},
        {"rdoEFTProductGR_No", "No"},
        {"btnClose", ""},
        {"btnBrchRemittNumberDelete", "Delete"},
        {"lblProductIdGR", "Product Id"},
        {"btnAuthorize", ""},
        {"lblProdCurrency", "Product Currency"},
        {"lblMsg", ""},
        {"panBranchRemittance", "Branch and Remittance Number"},
        {"lblDCHeadGR", "Duplicate Charges Head"},
        {"lblSpace2", "     "},
        {"rdoPrintServicesGR_No", "No"},
        {"lblCashLimitGR", "Cash Limit"},
        {"lblLapsedPeriodGR", "Lapsed Period"},
        {"lblSpace3", "     "},
        {"lblPayableHeadGR", "Payable Head"},
        {"btnBrchRemittNumberNew", "New"},
        {"lblSeriesGR", "Branch-wise Series to be maintained?"},
        {"lblIsLapsedGR", "Lapsed Applicable"},
        {"rdoPrintServicesGR_Yes", "Yes"},
        {"btnLapsedHeadGRHelp", ""},
        {"lblLapsedHeadGR", "Lapsed Head"},
        {"btnRCHeadGRHelp", ""},
        {"btnReject", ""},
        {"btnEdit", ""},
        {"rdoSeriesGR_Yes", "Yes"},
        {"rdoIsLapsedGR_Yes", "Yes"},
        {"btnDCHeadGRHelp", ""},
        {"btnPrint", ""},
        {"btnPostageHeadGRHelp", ""},
        {"lblPrintServicesGR", "Print Services?"},
        {"lblRemarksGR", "Remarks"},
        {"lblIssueHeadGR", "Issue Head"},
        {"lblExchangeHeadGR", "Exchange / Commission Head"},
        {"lblNumberPattern", "Number Pattern"},
        {"rdoIsLapsedGR_No", "No"},
        {"btnBranchName", ""},
        {"rdoSeriesGR_No", "No"},
        {"btnException", ""},
        {"btnIssueHeadGRHelp", ""},
        {"lblProductDescGR", "Product Description"},
        {"rdoEFTProductGR_Yes", "Yes"},
        {"btnSave", ""},
        {"lblTCHeadGR", "Telegram Charges Head"},
        {"lblStatus", "                      "},
        {"lblPayableBranchGR", "Payable at"},
        {"lblPostageHeadGR", "Postage Head"},
        {"lblRCHeadGR", "Revalidation Charges Head"},
        {"lblSpace5", "     "},
        {"btnDelete", ""},
        {"btnTCHeadGRHelp", ""},
        {"btnCCHeadGRHelp", ""},
        {"btnRTGSSuspenseHeadHelp", ""},
        {"lblSpace", " Status :"},
        {"btnBrchRemittNumberSave", "Save"},
        {"lblOCHeadGR", "Service Tax Head"},
        {"btnNew", ""},
        {"btnExchangeHeadGRHelp", ""},
        {"lblCCHeadGR", "Cancellation Charges Head"},
        {"btnCancel", ""},
        {"btnPayableHeadGRHelp", ""},
        {"lblEFTProductGR", "EFT Product"},
        {"lblBranchNameBR", "Branch Name"},
        {"lblBranchCodeBR", "Branch Code"},
        {"lblRttTypeBR", "Transmission Mode"},
        {"lblRttLimitBR", "Remittance Limit"},
        {"lblIVNoRR", "Last Inward Variable No."},
        {"lblOVNoRR", "Last Outward Variable No"},
        {"lblMinAmtRR", "Minimum Amount"},
        {"lblMaxAmtRR", "Maximum Amount"},
        {"lblBankCode", "Bank Code"},
        {"lblBehavesLike", "Behaves Like"},
        {"btnBankCode", ""},
        {"bankName", "Bank Code"},
        {"branchCode", "Branch Code"},        
        {"branchName", "Branch Name"},
        {"inwardVarNum", "Inward Var. No."},
        {"outwardVarNum", "Outward Var. No."},
        {"minAmt", "Min. Amt."},
        {"maxAmt", "Max. Amt."},
        {"lblChargeType", "Charge Type"},
        {"lblCategory", "Customer Category"},
        {"lblAmtRangeFrom", "Amt Range from"},
        {"lblAmtRangeTo", "Amt Range to"},
        {"lblCharges", "Charges"},
        {"btnRemitProdChargesNew", "New"},
        {"btnRemitProdChargesSave", "Save"},
        {"btnRemitProdChargesDelete", "Delete"},
        {"lapsedPeriod", "Lapsed Period be non zero value!!!"},
        {"cDialogOk", "Ok"},
        {"cDialogYes", "Yes"},
        {"cDialogNo", "No"}, 
        {"cDialogCancel", "Cancel"},         
        {"amountMinMaxWarning", "Minimum Amount & Maximum Amount range is not valid."},
        {"amountMinWarning", "Pls. enter the Minimum Amount before inserting."},
        {"amountMaxWarning", "Pls. to enter the Maximum Amount before inserting."},
        {"maintainSeriesWarning", "Choose the proper option to maintain the Series"},
        {"maintainSeriesOptionNoWarning", "Atleast one value to be entered in the Remittance Product Branch details"},
        {"existanceWarning", "This Charge Type, Customer Category & Amount Range Already exist."},
        {"deleteWarning", "The Product you are trying to delete, is already have issue data"},
        {"uniqueProductIDWarning", "Product ID is already present"},
        {"uniqueProductDESCWarning", "Product Description is already present"},
        {"uniqueProductIDandDESCWarning", "Both Product ID and Product Description are already present"},
        {"deleteOptionWarning","Are you sure you want to Delete?"},
        {"amountRangeWarning", "Amount range is not valid"},
        {"TOCommandError", ""},
        {"lblPercentage", "Percentage"},
        {"lblServiceTax", "Service Tax %"},
        {"lblForEvery", "For Every"},
        {"Warning", "Please Select a Row in the Above Table !!!"},
        
        {"chargeCheck","Charge related details should not be empty"},
        {"forEveryCheck","For Every related details should be filled completely"},
        {"remitNoDuplicate","This Bank and Branch already exist"},        
    };
    
}
