/*
 * Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition.
 * 
 *
 * LodgementBillsRB.java
 *
 * Created on Mon Feb 07 11:57:03 IST 2005
 */

package com.see.truetransact.ui.bills.lodgement;

import java.util.ListResourceBundle;

public class LodgementBillsRB extends ListResourceBundle {
    public LodgementBillsRB(){
    }
    
    public Object[][] getContents() {
        return contents;
    }
    
    static final String[][] contents = {
        {"panLableValues", ""},
        {"lblBankName", "Other Bank Name"},
        {"btnClose", ""},
        {"lblOperatesLike", "Operates Like"},
        {"btnInstNew", "New"},
        {"lblDraweeHundi", "Drawee Hundi"},
        {"btnAuthorize", ""},
        {"panRRLRARPPDetails", "RR/LR/AR/PP Details"},
        {"lblMsg", ""},
        {"lblHundiRemarks", "Remarks"},
        {"lblOtherCountry", "Country"},
        {"lblBillTenor", "Tenor of the Bill"},
        {"lblDraweePinCode", "Pin Code"},
        {"rdoDraweeHundi_Yes", "Yes"},
        {"lblDraweeBankCode", "Bank Code"},
        {"lblOtherPinCode", "Pin Code"},
        {"panOtherBankDetails", "Other Bank Details"},
        {"rdoBillAcceptance_Yes", "Yes"},
        {"lblAcceptanceDate", "Date of Acceptance"},
        {"btnInstSave", "Save"},
        {"lblDraweeState", "State"},
        {"btnReject", ""},
        {"lblOtherBranchNameValue", ""},
        {"lblOtherAddress", "Address"},
        {"lblOtherCity", "City"},
        {"lblDraweeBranchName", "Drawee Branch Name"},
        {"rdoDraweeHundi_No", "No"},
        {"btnPrint", ""},
        {"lblProductType", "Product Type"},
        {"lblDraweeName", "Branch Name"},
        {"lblInstrumentAmount", "Instrument Amount"},
        {"lblInstrumentDate", "Instrument Date"},
        {"lblRemitInst", "Remit Instrument Date"},
        {"lblBranchCode", "Branch Code"},
        {"lblPayable", "Where Payable"},
        {"btnException", ""},
        {"panChequeDetails", "Cheque "},
        {"lblReceivedFrom", "Received From"},
        {"lblBillsType", "Bills Type"},
        {"lblActivities", "Activity"},
        {"lblOtherName", "Name"},
        {"lblProductId", "Product Id"},
        {"btnSave", ""},
        {"lblHundiNo", "Hundi No."},
        {"btnBranchCode", ""},
        {"lblTransportCompany", "Transport Company"},
        {"lblOtherBranchName", "Branch Name"},
        {"lblRRLRNumber", "RR/LR Number"},
        {"lblInstrumentNo", "Instrument No"},
        {"lblDraweeBankName", "Drawee Bank Name"},
        {"lblCustomerName", "Name"},
        {"lblAdditionalInstruction", "Additional Instruction"},
        {"panOtherDetails", "Other Details"},
        {"btnNew", ""},
        {"btnView", ""},
        {"lblRRLRDate", "RR/LR Date"},
        {"lblBranchCodeValue", ""},
        {"btnInstDelete", "Delete"},
        {"lblInstrumentType", "Instrument Type"},
        {"lblInvoiceNumber", "Invoice Number"},
        {"lblInvoiceDate", "Invoice Date"},
        {"lblGoodsAssigned", "Goods Assigned"},
        {"lblBillAcceptance", "Acceptance Bill"},
        {"panBranchDetails", "Branch Details"},
        {"lblSpace3", "     "},
        {"lblSpace1", " Status :"},
        {"lblInvoiceAmount", "Invoice Amount"},
        {"lblOtherBranchCode", "Branch Code"},
        {"panDraweeDetails", ""},
        {"rdoBillAcceptance_No", "No"},
        {"btnEdit", ""},
        {"lblReference", "Reference"},
        {"lblDueDate", "Due Date of Bill"},
        {"panInvoiceDetails", "Invoice Details"},
        {"lblStdInstruction", "Charge Type"},
        {"lblAccountNo", "Account No."},
        {"btnOtherBranchCode", ""},
        {"btnAccountNo", ""},
        {"lblBankNameValue", ""},
        {"lblDrawBnk", ""},
        {"lblDrawBran", ""},
        {"lblCustomerNameValue", ""},
        {"lblPayeeName", "Payee Name"},
        {"lblDraweeCountry", "Country"},
        {"lblStatus", "                      "},
        {"lbSpace2", "     "},
        {"lblDraweeAddress", "Address"},
        {"lblGoodsValue", "Goods Value"},
        {"lblRemarks", "Remarks"},
        {"lblDraweeNo", "Drawee No"},
        {"lblDraweeBankNamee", "Bank Name"},
        {"lblAccountHead", "A/c Head"},
        {"lblSpace5", "     "},
        {"btnDelete", ""},
        {"cDialogYes", "Yes"},
        {"cDialogNo", "No"},
        {"cDialogCancel", "Cancel"},
        {"lblHundiAmount", "Hundi Amount"},
        {"lblDraweeCity", "City"},
        {"lblSendingTo", "Sent To"},
        {"lblMICR", "MICR"},
        {"lblOperatesLikeValue", ""},
        {"lblBankCode", "Other Bank Code"},
        {"panBillofExchange", "Bill of Exchange (Hundi)"},
        {"btnCancel", ""},
        {"btnBankCode", ""},
        {"lblState", "State"},
        {"lblBranchName", "Branch Name"},
        {"lblHundiDate", "Hundi Date"},
        {"lblDraweeBranchCode", "Branch Code"} ,
        {"tblHeading1", "S. No. "},
        {"tblHeading2", "Instructions"},
        {"tblHeading3", "Amount"},
        {"tblHeading4", "Service Tax"},
        {"tblHeadingInst1", "S. No. "},
        {"tblHeadingInst2", "Instructions"},
        {"tblHeadingInst3", "Particulars"},
        {"tblHeadingAct1", "Product ID"},
        {"tblHeadingAct2", "Account No"},
        {"tblHeadingAct3", "Name"},
        {"existanceWarning", "This Record Already Exists. Do you want to modify it ?"},
        {"lblLodgementId", "Lodgement Id"},
        {"lblCurStatus1", "Current Status"},
        {"txtCreatDt", ""},
        {"lblCreatDt", "Created Date"},
        {"lblCurStatus", ""},
        {"cDialogOK", "OK"},
        {"tenorMsg", "Enter a Valid Tenor Period"},
        {"lblTotalAmt", "Total Charges"},
        {"lblAmount", "Amount"},
        {"lblRemitProdID", "Advice Id"},
        {"lblRemitCity", "City"},
        {"lblRemitDraweeBank", "Drawee Bank"},
        {"lblRemitBranchCode", "Branch Code"},
        {"lblRemitFavour", "Other Bank Charges"},
        {"lblRemitAmt", "Inst Amt"},
        {"lblInstNo", "Inst No"},
        {"lblCustCategory", "Customer Category"},
        {"lblTranstype", "Transtype"},
        {"lblRateForDelay", "Rate For Delayed Realization"},
        {"lblInstruction", "Instruction"},
        {"lblParticulars", "Particulars"},
        {"lblProductID", "Product ID"},
        {"lblAccountNum", "Account No"},
        {"lblRateForDelay1", "Margin"},
        {"lblIntDays", "Int. to be collected on Cheque Discounting"},
        {"lblDiscountRateOfBD", "Discount Rate For Bills"},
        {"lblOverdueInterestForBD", "Overdue Interest Rate For Bills"},
        {"lblOverdueRateCBP", "Overdue Rate For CBP"},
        {"lblAtParLimit", "At Par Limit"},
        {"lblCleanBillsPurchased", "Clean Bills Purchased"},
        {"lblTransitPeriod", "Transit Period"},
        {"lblDefaultPostage", "Default Postage Rate"},
        {"lblIntICC", "Int to be collected during Lodgement of ICC"},
        
    };
    
}
