/*
 * Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition.
 **
 *
 * AccountsMRB.java
 * 
 * Created on Fri Mar 26 11:47:27 IST 2004
 */

package com.see.truetransact.ui.operativeaccount;

import java.util.ListResourceBundle;

public class AccountsMRB extends ListResourceBundle {
    public AccountsMRB(){
    }

    public Object[][] getContents() {
        return contents;
    }

    static final String[][] contents = {
        {"cboGuardianAddrState", "GuardianAddrState should be a proper value!!!"},
        {"txtBranchITP2", "BranchITP2 should not be empty!!!"},
        {"cboCustAddrCity", "CustAddrCity should be a proper value!!!"},
        {"dtdActOpenDateAI", "null"},
        {"chkNonMainMinBalChrgAD", "NonMainMinBalChrgAD should be selected!!!"},
        {"dtdMinorDOBNO", "null"},
        {"cboIdentityTypeITP4", "IdentityTypeITP4 should be a proper value!!!"},
        {"txtFolioChrgAD", "FolioChrgAD should not be empty!!!"},
        {"cboConstitutionAI", "Constitution should be a proper value!!!"},
        {"dtdATMToDateAD", "null"},
        {"txtDesignationOTP5", "DesignationOTP5 should not be empty!!!"},
        {"txtPOAAddrArea", "POAAddrArea should not be empty!!!"},
        {"txtGuardianAddrPincode", "GuardianAddrPincode should not be empty!!!"},
        {"txtMinActBalanceAD", "MinActBalanceAD should not be empty!!!"},
        {"txtCustAddrPincode", "CustAddrPincode should not be empty!!!"},
        {"txtACodeOTP5", "ACodeOTP5 should not be empty!!!"},
        {"txtNameITP2", "NameITP2 should not be empty!!!"},
        {"txtReqFlexiPeriodAD", "ReqFlexiPeriodAD should not be empty!!!"},
        {"dtdATMFromDateAD", "null"},
        {"txtGuardianAddrArea", "GuardianAddrArea should not be empty!!!"},
        {"cboNomineeRelationNO", "NomineeRelationNO should be a proper value!!!"},
        {"cboNomineeAddrCity", "NomineeAddrCity should be a proper value!!!"},
        {"txtDocNoITP3", "DocNoITP3 should not be empty!!!"},
        {"chkChequeRetChrgAD", "ChequeRetChrgAD should be selected!!!"},
        {"cboINP5AddrCity", "INP5AddrCity should be a proper value!!!"},
        {"txtGuardianAddrStreet", "GuardianAddrStreet should not be empty!!!"},
        {"cboCategory", "Category should be a proper value!!!"},
        {"cboDocTypeITP3", "DocTypeITP3 should be a proper value!!!"},
        {"txtGuardianACodeNO", "GuardianACodeNO should not be empty!!!"},
        {"txtATMNoAD", "ATMNoAD should not be empty!!!"},
        {"txtPOAACodePA", "POAACodePA should not be empty!!!"},
        {"cboINP5AddrCountry", "INP5AddrCountry should be a proper value!!!"},
        {"dtdExpiryDateITP3", "null"},
        {"chkABBChrgAD", "ABBChrgAD should be selected!!!"},
        {"txtINP5AddrPincode", "INP5AddrPincode should not be empty!!!"},
        {"chkATMAD", "ATMAD should be selected!!!"},
        {"chkNPAChrgAD", "NPAChrgAD should be selected!!!"},
        {"dtdDebitFromDateAD", "null"},
        {"txtNomineePhoneNO", "NomineePhoneNO should not be empty!!!"},
        {"chkFlexiAD", "FlexiAD should be selected!!!"},
        {"txtMinBal1FlexiAD", "MinBal1FlexiAD should not be empty!!!"},
        {"chkStmtChrgAD", "StmtChrgAD should be selected!!!"},
        {"chkPassBook", "PassBook should be selected!!!"},
        {"txtPOAAddrStreet", "POAAddrStreet should not be empty!!!"},
        {"rdoStatus_MinorNO", "Status should be selected!!!"},
        {"cboSettlementModeAI", "SettlementModeAI should be a proper value!!!"},
        {"cboDMYAD", "DMYAD should be a proper value!!!"},
        {"chkCreditAD", "CreditAD should be selected!!!"},
        {"txtCustAddrArea", "CustAddrArea should not be empty!!!"},
        {"cboBaseCurrAI", "BaseCurrAI should be a proper value!!!"},
        {"txtBankITP2", "BankITP2 should not be empty!!!"},
        {"txtRemarksPA", "RemarksPA should not be empty!!!"},
        {"chkChequeBookAD", "ChequeBookAD should be selected!!!"},
        {"txtCustomerIdAI", "Customer ID Should not be empty!!!"},
        {"txtGuardianNameNO", "GuardianNameNO should not be empty!!!"},
        {"txtTotalShareNO", "TotalShareNO should not be empty!!!"},
        {"chkCustGrpLimitValidationAD", "CustGrpLimitValidationAD should be selected!!!"},
        {"txtAccountNoITP1", "AccountNoITP1 should not be empty!!!"},
        {"cboINP5AddrState", "INP5AddrState should be a proper value!!!"},
        {"txtNomineeAddrArea", "NomineeAddrArea should not be empty!!!"},
        {"cboCustAddrState", "CustAddrState should be a proper value!!!"},
        {"txtIdITP4", "IdITP4 should not be empty!!!"},
        {"txtINP5AddrArea", "INP5AddrArea should not be empty!!!"},
        {"dtdDebit", "null"},
        {"chkPayIntOnCrBalIN", "PayIntOnCrBalIN should be selected!!!"},
        {"txtNomineeAddrStreet", "NomineeAddrStreet should not be empty!!!"},
        {"dtdCredit", "null"},
        {"dtdPOAToDatePA", "null"},
        {"txtPhoneOTP5", "PhoneOTP5 should not be empty!!!"},
        {"dtdCreditFromDateAD", "null"},
        {"txtAccCloseChrgAD", "AccCloseChrgAD should not be empty!!!"},
        {"cboNomineeAddrCountry", "NomineeAddrCountry should be a proper value!!!"},
        {"txtNomineeShareNO", "NomineeShareNO should not be empty!!!"},
        {"cboNomineeAddrState", "NomineeAddrState should be a proper value!!!"},
        {"cboCommAddr", "CommunicationAddr should be a proper value!!!"},
        {"txtAmoutTransAI", "AmoutTransAI should not be empty!!!"},
        {"cboOpModeAI", "Mode Of Operation should be a proper value!!!"},
        {"dtdOpeningDateAI", "Opening Date should be a proper value"},
        {"chkNROStatusAD", "NROStatusAD should be selected!!!"},
        {"dtdPOAFromDatePA", "null"},
        {"txtChequeBookChrgAD", "ChequeBookChrgAD should not be empty!!!"},
        {"cboPOAAddrCountry", "POAAddrCountry should be a proper value!!!"},
        {"txtIssuedAuthITP4", "IssuedAuthITP4 should not be empty!!!"},
        {"txtNomineeAddrPincode", "NomineeAddrPincode should not be empty!!!"},
        {"cboPOAAddrCity", "POAAddrCity should be a proper value!!!"},
        {"txtGuardianPhoneNO", "GuardianPhoneNO should not be empty!!!"},
        {"txtPOAPhonePA", "POAPhonePA should not be empty!!!"},
        {"cboRelationNO", "RelationNO should be a proper value!!!"},
        {"txtCreditNoAD", "CreditNoAD should not be empty!!!"},
        {"txtRemarksAI", "RemarksAI should not be empty!!!"},
        {"txtExcessWithChrgAD", "ExcessWithChrgAD should not be empty!!!"},
        {"dtdNPAChrgAD", "null"},
        {"dtdDebitToDateAD", "null"},
        {"chkMobileBankingAD", "MobileBankingAD should be selected!!!"},
        {"txtIssuedByITP3", "IssuedByITP3 should not be empty!!!"},
        {"txtPOAAddrPincode", "POAAddrPincode should not be empty!!!"},
        {"cboGuardianAddrCity", "GuardianAddrCity should be a proper value!!!"},
        {"cboActStatusAI", "ActStatusAI should be a proper value!!!"},
        {"dtdIssuedDateITP3", "null"},
        {"dtdCreditToDateAD", "null"},
        {"chkPayIntOnDrBalIN", "PayIntOnDrBalIN should be selected!!!"},
        {"txtNomineeACodeNO", "NomineeACodeNO should not be empty!!!"},
        {"txtABBChrgAD", "ABBChrgAD should not be empty!!!"},
        {"txtNomineeNameNO", "NomineeNameNO should not be empty!!!"},
        {"cboPreviousActNo", "PreviousActNo should be a proper value!!!"},
        {"chkInopChrgAD", "InopChrgAD should be selected!!!"},
        {"txtBranchCodeAI", "BranchCodeAI should not be empty!!!"},
        {"txtMinNominees", "MinNominees should not be empty!!!"},
        {"cboGroupCodeAI", "Customer Group should be a proper value!!!"},
        {"txtDebitNoAD", "DebitNoAD should not be empty!!!"},
        {"txtPrevActNumAI", "PrevActNumAI should not be empty!!!"},
        {"txtODLimitAI", "ODLimitAI should not be empty!!!"},
        {"txtINP5ddrStreet", "INP5ddrStreet should not be empty!!!"},
        {"txtCustAddrStreet", "CustAddrStreet should not be empty!!!"},
        {"cboStmtFreqAD", "StmtFreqAD should be a proper value!!!"},
        {"txtIntroNameOTP5", "IntroNameOTP5 should not be empty!!!"},
        {"txtPOANamePA", "POANamePA should not be empty!!!"},
        {"cboPOAAddrState", "POAAddrState should be a proper value!!!"},
        {"txtMinBal2FlexiAD", "MinBal2FlexiAD should not be empty!!!"},
        {"chkStopPmtChrgAD", "StopPmtChrgAD should be selected!!!"},
        {"txtAccountNoITP2", "AccountNoITP2 should not be empty!!!"},
        {"txtMisServiceChrgAD", "MisServiceChrgAD should not be empty!!!"},
        {"chkDebitAD", "DebitAD should be selected!!!"},
        {"cboGuardianAddrCountry", "GuardianAddrCountry should be a proper value!!!"},
        {"txtAccOpeningChrgAD", "AccOpeningChrgAD should not be empty!!!"},
        {"cboProductIdAI", "Account Product should be a proper value!!!"},
        {"cboCustAddrCountry", "CustAddrCountry should be a proper value!!!"},
        {"txtActName", "Account Name should not be empty!!!"},
        {"txtRemarks", "Remarks should not be empty!!!"},
        
        {"chkHideBalanceTrans", "HideBalanceTrans should be selected!!!"},
        {"cboRoleHierarchy", "RoleHierarchy should be a proper value!!!"}
   };

}
