/*
 * Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition.  
 * 
 * AccountsRB.java
 */

package com.see.truetransact.ui.operativeaccount;
import java.util.ListResourceBundle;
public class AccountsRB extends ListResourceBundle {
    public AccountsRB(){
    }

    public Object[][] getContents() {
        return contents;
    }

    static final String[][] contents = { 
        {"lblPenalInterestValueIN", ""},
        {"btnClose", ""},
        {"lblState", "State"},
        {"panIdentity", "Identity Info."},
        {"lblCustomerNameValueAI", ""},
        {"lblIntroducerTypeValueIT", ""},
        {"panBank", "Other Bank"},
        {"btnCustDetNew", "New" },
        {"btnCustDetDelete", "Delete" },
        {"btnToMain", "ToMain"},
        {"lblCustomerName", "Customer Name"},
        {"lblCity" , "City"},
        {"lblDOB" , "Date Of Birth" },
        {"lblStreet", "Street" },
        {"lblArea", "Area"},
        {"lblCountry", "Country"},
        {"lblState", "State"},
        {"lblPin" , "Pin" },
        {"chkNonMainMinBalChrgAD", ""},
        {"btnCancel", ""},
        {"lblAgClearingIN", "Ag Clearing"},
        {"lblCrInterestRateIN", "Credit Interest"},
        {"lblFolioChrgAD", "Folio"},
        {"lblDesignationOTP5", "Designation"},
        {"lblMinActBalanceAD", "Minimum Account Balance"},
        {"panDocDetails", "Document Details"},
        {"btnNewNO", "New"},
        {"panLastIntApp", "Last Interest Application Date"},
        {"lblArea", "Area"},
        {"lblPhoneOTP5", "Phone"},
        {"lblBaseCurrAI", "Base Currency"},
        {"lblBankITP2", "Bank Name"},
        {"lblPenalInterestRateIN", "Penal Interest"},
        {"lblNameValueITP1", ""},
        {"lblTBSep3", ""},
        {"lblStatement", "Statement"},
        {"lblPassBook", "PassBook"},
         {"lblStreet", "Street"},
        {"lblNomineeRelationNO", "Relationship"},
        {"lblCommAddr", "Communication Addr Type"},
        {"chkChequeRetChrgAD", ""},
        {"lblCustomerIdAI", "Customer ID"},
        {"lblDebit", "Debit"},
        {"btnException", ""},
        {"lblTotalShareNO", "Total Share (%)"},
        {"lblMinBal2FlexiAD", "Minimum Balance2"},
        {"lblATMToDateAD", "To"},
        {"lblCredit", "Credit"},
        {"lblIntroducerTypeIT", "Type of Introduction:"},
        {"lblNPA", "NPA"},
        {"lblATMNoAD", "No"},
        {"lblRemarksAI", "Remarks"},
        {"lblBranchITP2", "Branch Code"},
        {"lblSpace1", " Status :"},
        {"lblCity", "City"},
        {"lblAccountNumber", "Account No"},
        {"panFlexiOpt", "Flexi Option"},
        {"lblIdentityTypeITP4", "Identity Type"},
        {"chkABBChrgAD", ""},
        {"txtAccountNo", ""},
        {"lblOpeningDateAI", "Opening Date"},
        {"lblBranchCodeValueITP1", ""},
        {"chkATMAD", "ATM"},
        {"chkNPAChrgAD", ""},
        {"lblActStatusAI", "Account Status"},
        {"lblPOAFromDatePA", "PoA From Date"},
        {"panNomineeList", "List of Nominees"},
        {"btnReport", ""},
        {"panNomineeDetails", "Nominee Details"},
        {"lblNameITP1", "Name"},
        {"chkFlexiAD", "Flexi"},
        {"chkStmtChrgAD", ""},
         {"chkPassBook", ""},
        {"btnBranchCode", ""},
        {"rdoStatus_MajorNO", "Major"},
        {"lblABBChrgAD", "ABB"},
        {"btnDelete", ""},
        {"lblNomineeNameNO", "Name"},
        {"rdoStatus_MinorNO", "Minor"},
        {"lblNPAChrgAD", "NPA Date"},
        {"lblBranchValueITP1", ""},
        {"lblAmoutTransAI", "Amount Transfered"},
        {"lblDebitToDateAD", "To"},
        {"chkCreditAD", "Credit"},
        {"panAccountInfo", "Account Info."},
//        {"lblGroupCodeAI", "Group Code"},
        {"lblGroupCodeAI", "Customer Group"},
        {"panPOADetails", "POA Details"},
        {"lblChequeBookChrgAD", "Cheque Book"},
        {"lblIssuedDateITP3", "Issue Date"},
        {"btnReject", ""},
        {"lblCreditToDateAD", "To"},
        {"lblDebitNoAD", "No"},
        {"lblODLimitAI", "Over Draft Limit"},
        {"lblRelationNO", "Relationship"},
        {"lblRateCodeValueIN", ""},
        {"chkChequeBookAD", "Cheque Book"},
        {"lblDebitFromDateAD", "Valid From"},
        {"lblExcessWithChrgAD", "Excess Withdrawal"},
        {"lblBranchNameAI", "Branch Name"},
        {"lblIntroNameOTP5", "Introducer's Name"},
        {"chkCustGrpLimitValidationAD", "Cust. Group Limit Validation"},
        {"lblPOANamePA", "Holder's Name"},
        {"btnEdit", ""},
        {"lblIssuedByITP3", "Issued By"},
        {"lblAgClearingValueIN", ""},
        {"lblAccountNoITP2", "Account No."},
        {"panInterestPayableIN", "Interest"},
        {"lblCollectInoperative", "Collect Inoperative"},
        {"btnCustomerIdAI", ""},
        {"lblProductIdAI", "Account Product"},
        {"btnSave", ""},
        {"chkPayIntOnCrBalIN", "Pay Interest on Credit Balance"},
        {"lblNomineePhoneNO", "Phone No"},
        {"lblMinBal1FlexiAD", "Minimum Balance1"},
        {"panIntroducerDetails", "Introducer Details"},
        {"btnRemovePA", "Delete"},
        {"btnAuthorize", ""},
        {"lblBranchCodeAI", "Branch Code"},
        {"lblPincode", "Pincode"},
        {"lblMsg", ""},
        {"lblSettlementModeAI", "Settlement Mode"},
        {"panCustomerInfo", "Customer Info."},
        {"panIsRequired", "Is Required ?"},
        {"lblPrevActNumAI", "Previous Account No."},
        {"panOthers", "Others"},
        {"lblNonMaintenance", "Non-maintenance of Min Bal."},
        {"lblActOpenDateAI", "Account Opening Date"},
        {"chkNROStatusAD", "NRO Status"},
        {"lblMinorDOBNO", "Date of Birth"},
        {"lblStmtFreqAD", "Statement Frequency"},
        {"btnListAddPA", "Save"},
        {"lblGuardianNameNO", "Gurdian's Name"},
        {"lblDrInterestRateIN", "Debit Interest"},
        {"lblMisServiceChrgAD", "Misc. Service"},
        {"lblBranchCodeITP1", "Branch Code"},
        {"lblDocNoITP3", "Document No."},
        {"lblABB", "ABB"},
        {"lblDocTypeITP3", "Document Type"},
        {"lblCreditFromDateAD", "Valid From"},
        {"lblAccOpeningChrgAD", "Account Opening"},
        {"lblStatus", "                      "},
        {"lblGuardianPhoneNO", "Phone No"},
        {"lblDrInterestRateValueIN", ""},
        {"lblActHeadITP1", "Account Head"},
        {"lblCrInterestRateValueIN", ""},
        {"lblCustomerNameAI", "Name:"},
        {"lblPOAToDatePA", "PoA To Date"},
        {"lblBranchITP1", "Branch Name"},
        {"btnRemoveNO", "Delete"},
        {"panMobileBanking", "Mobile Banking"},
        {"chkMobileBankingAD", "Required"},
        {"lblMobileNo", "Mobile No"},
        {"lblMobileSubscribedFrom", "Subscribed From"},
        {"lblIdITP4", "Document ID"},
        {"lblATMFromDateAD", "Valid From"},
        {"lblActHeadValueAI", ""},
        {"lblCustomerIdITP1", "Customer ID"},
        {"lblConstitutionAI", "Constitution"},
        {"chkPayIntOnDrBalIN", "Receive Interest on Debit Balance"},
        {"panTransferBranchInfo", "Transfering Branch Info."},
        {"lblBranchNameValueAI", ""},
        {"lblNameITP2", "Name"},
        {"lblReqFlexiPeriodAD", "Required Flexi Period"},
        {"lblAccCloseChrgAD", "Account Closing"},
        {"chkInopChrgAD", ""},
        {"lblRateCodeIN", "Code"},
        {"btnAddNO", "Save"},
        {"btnAdd", ""},
        {"lblNomineeShareNO", "Share (%)"},
        {"lblExpiryDateITP3", "Expiry Date"},
        {"lblActHeadAI", "Account Head"},
        {"panPOAList", "List of POAs"},
        {"lblOpModeAI", "Mode of Operation"},
        {"lblActHeadValueITP1", ""},
        {"lblMinNominees", "Min Nominees Reqd."},
        {"btnAccountNoITP1", ""},
        {"panDiffCharges", "Different Charges"},
        {"panRatesIN", "Rate Details"},
        {"panCardInfo", "Card Info."},
        {"lblCategory", "Category"},
        {"btnNewPA", "New"},
        {"panGuardianDetails", "In case of Minor"},
        {"lblPOAPhonePA", "Phone No"},
        {"lblCreditNoAD", "No"},
        {"lblPrevActNoAI", "Previous Account No."},
        {"lblRemarksPA", "Remark"},
        {"lblNomineeStatusNO", "Status"},
        {"lblStopPayment", "Stop Payment"},
        {"lblCustomerIdValueITP1", ""},
        {"chkStopPmtChrgAD", ""},
        {"chkDebitAD", "Debit"},
        {"lblChequeReturn", "Cheque Return"},
        {"panSelfCustomer", "Self or Existing Customer"},
        {"lblIssuedByITP4", "Issuing Authority"},
        {"lblAccountNoITP1", "Account No."},
        {"lblCountry", "Country"}, 
        {"lblCustName", ""},
        {"WARNING_NOMINEE", "No of Nominees are Less than the Specified Number."},
        {"SHARE_NOMINEE", "Total Share must be equal to 100.0 Percent."},
        {"ATMDATEWARNING", "From And To Dates for the ATM Card Should not Be Empty"},
        {"DEBITDATEWARNING", "From And To Dates for the Debit Card Should not Be Empty"},
        {"CREDITDATEWARNING", "From And To Dates for the Credit Card Should not Be Empty"},
        {"JOINTWARNING", "Joint Account needs minimum two customers."},
        {"AUTH_SIGN_WARNING", "Please enter atleast one operational instruction in the Authorized Signatory Tab."},
        {"dialogForJointAccntHolder", "This will reset the Joint Account Holders data. Are you sure to reset it?"},
        {"ROLEWARNING", "Hierarhy Role for Balance selection Should not be null"},
        {"dialogYes", "Yes"},
        {"dialogNo", "No"},
        {"dialogOk", "OK"},
        {"tblJntAccntColumn1", "Name"},
        {"tblJntAccntColumn2", "Cust.Id"},
        {"tblJntAccntColumn3", "Type"},
        {"tblJntAccntColumn4", "Main / Joint"},
        {"tblJntAccntColumn5", "Status"},
        
        {"lblActName", "Account Name"},
        {"lblRemarks", "Remarks"},
        
        {"lblHideBalanceTrans", "Hide Balance in Transaction"},
        {"chkHideBalanceTrans", ""},
        {"lblRoleHierarchy", "Above which Role Hierarchy Balance is to be Shown?"},
        {"selectMainAccntHolder", "Select Main Account Holder before selecting Joint Account Holders"},
        {"LIMITWARNING", "Limit Cannot Be Empty Or Zero In Authorized Signatory Tab"},
        {"REMARK_CASH_TRANS","Cash Transaction Token No"},
        {"REMARK_TRANSFER_TRANS","Transfer Transaction Operative Account No"}
   };

}
