/*
 * Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition. 
 * 
 * PrintUI.java
 *
 * Created on January 13, 2004, 4:28 PM
 */

package com.see.truetransact.ui.forex;

import java.util.HashMap;

import com.see.truetransact.clientutil.ClientUtil;
import com.see.truetransact.uicomponent.CLabel;
import com.see.truetransact.uicomponent.CTextField;
/**
 *
 * @author  bala
 */
public class PrintUI extends com.see.truetransact.uicomponent.CDialog {
    /** Creates new form DenominationUI */
    String _printContent = "";
    
    public PrintUI() {
        initComponents();
        jEditorPane1.setContentType("text/html");
        jEditorPane1.setText(_printContent);
    }
    
    public PrintUI(String content) {
        _printContent = content;
        initComponents();
        jEditorPane1.setContentType("text/html");
        jEditorPane1.setText(_printContent);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        panDenomination = new com.see.truetransact.uicomponent.CPanel();
        cScrollPane1 = new com.see.truetransact.uicomponent.CScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        panBottom = new com.see.truetransact.uicomponent.CPanel();
        btnOk = new com.see.truetransact.uicomponent.CButton();
        btnCancel = new com.see.truetransact.uicomponent.CButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        panDenomination.setLayout(new java.awt.GridBagLayout());

        panDenomination.setMinimumSize(new java.awt.Dimension(700, 300));
        panDenomination.setPreferredSize(new java.awt.Dimension(700, 300));
        jEditorPane1.setFont(new java.awt.Font("Arial", 0, 11));
        cScrollPane1.setViewportView(jEditorPane1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panDenomination.add(cScrollPane1, gridBagConstraints);

        getContentPane().add(panDenomination, java.awt.BorderLayout.CENTER);

        btnOk.setText("Print");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        panBottom.add(btnOk);

        btnCancel.setText("Close");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        panBottom.add(btnCancel);

        getContentPane().add(panBottom, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // Add your handling code here:
        //updateDenominationCount
        this.dispose();
    }//GEN-LAST:event_btnOkActionPerformed
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // Add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        //System.exit(0);
        this.dispose();
    }//GEN-LAST:event_exitForm
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new PrintUI("sdf").show();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.see.truetransact.uicomponent.CButton btnCancel;
    private com.see.truetransact.uicomponent.CButton btnOk;
    private com.see.truetransact.uicomponent.CScrollPane cScrollPane1;
    private javax.swing.JEditorPane jEditorPane1;
    private com.see.truetransact.uicomponent.CPanel panBottom;
    private com.see.truetransact.uicomponent.CPanel panDenomination;
    // End of variables declaration//GEN-END:variables
}