/*
 * Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition. 
 * 
 * SAAJSenderUI.java
 *
 * Created on January 21, 2004, 10:37 AM
 */

package com.see.truetransact.ui.forex;

import java.util.HashMap;
import javax.swing.JFileChooser;
import java.util.ArrayList;
import java.io.File;
import com.see.truetransact.uimandatory.UIMandatoryField;
import com.see.truetransact.uimandatory.MandatoryCheck;
import com.see.truetransact.clientutil.CMandatoryDialog;
import com.see.truetransact.clientutil.ClientUtil;
import com.see.truetransact.commonutil.DateUtil;
import com.see.truetransact.clientutil.ClientConstants;
import com.see.truetransact.commonutil.CommonConstants;

import com.see.truetransact.ui.common.viewall.ViewAll;
import java.util.Observer;
import java.util.Observable;


/**
 *
 * @author  amathan
 */
public class SAAJSenderUI extends com.see.truetransact.uicomponent.CInternalFrame {
    
    /** Creates new form SAAJSenderUI */
    public SAAJSenderUI() {
        initComponents();
        initStartup();
        panFileContent.setVisible(false);
    }    
    
    private void initStartup() {
        disableTextBoxes();           
    }
    
    private void disableTextBoxes() {
        /*txtFile.setEnabled(false);
        txtBranchCode.setEnabled(false);
        txtName.setEnabled(false);
        txtIPAddress.setEnabled(false);*/ 
        
        txtFile.setEditable(false);
        txtBranchCode.setEditable(false);
        txtName.setEditable(false);
        txtIPAddress.setEditable(false);       
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        panSAAJSender = new com.see.truetransact.uicomponent.CPanel();
        panDetails = new com.see.truetransact.uicomponent.CPanel();
        lblFile = new com.see.truetransact.uicomponent.CLabel();
        txtFile = new com.see.truetransact.uicomponent.CTextField();
        btnFile = new com.see.truetransact.uicomponent.CButton();
        txtBranchCode = new com.see.truetransact.uicomponent.CTextField();
        btnBranchCode = new com.see.truetransact.uicomponent.CButton();
        lblBranchCode = new com.see.truetransact.uicomponent.CLabel();
        lblIPAddress = new com.see.truetransact.uicomponent.CLabel();
        txtIPAddress = new com.see.truetransact.uicomponent.CTextField();
        lblName = new com.see.truetransact.uicomponent.CLabel();
        txtName = new com.see.truetransact.uicomponent.CTextField();
        panButtons = new com.see.truetransact.uicomponent.CPanel();
        btnSend = new com.see.truetransact.uicomponent.CButton();
        btnClose = new com.see.truetransact.uicomponent.CButton();
        panFileContent = new com.see.truetransact.uicomponent.CPanel();
        srpFileContent = new com.see.truetransact.uicomponent.CScrollPane();
        txaFileContent = new com.see.truetransact.uicomponent.CTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("SAAJ Sender");
        setPreferredSize(new java.awt.Dimension(400, 210));
        panSAAJSender.setLayout(new java.awt.GridBagLayout());

        panSAAJSender.setBorder(new javax.swing.border.EtchedBorder());
        panDetails.setLayout(new java.awt.GridBagLayout());

        lblFile.setText("File");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        panDetails.add(lblFile, gridBagConstraints);

        txtFile.setPreferredSize(new java.awt.Dimension(200, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 1);
        panDetails.add(txtFile, gridBagConstraints);

        btnFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/see/truetransact/ui/images/TT_SELECT.gif")));
        btnFile.setPreferredSize(new java.awt.Dimension(21, 21));
        btnFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 1, 4, 4);
        panDetails.add(btnFile, gridBagConstraints);

        txtBranchCode.setPreferredSize(new java.awt.Dimension(200, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 1);
        panDetails.add(txtBranchCode, gridBagConstraints);

        btnBranchCode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/see/truetransact/ui/images/TT_SELECT.gif")));
        btnBranchCode.setPreferredSize(new java.awt.Dimension(21, 21));
        btnBranchCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBranchCodeActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 1, 4, 4);
        panDetails.add(btnBranchCode, gridBagConstraints);

        lblBranchCode.setText("Branch Code");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        panDetails.add(lblBranchCode, gridBagConstraints);

        lblIPAddress.setText("IP Address");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        panDetails.add(lblIPAddress, gridBagConstraints);

        txtIPAddress.setPreferredSize(new java.awt.Dimension(200, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 1);
        panDetails.add(txtIPAddress, gridBagConstraints);

        lblName.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        panDetails.add(lblName, gridBagConstraints);

        txtName.setPreferredSize(new java.awt.Dimension(200, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 1);
        panDetails.add(txtName, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        panSAAJSender.add(panDetails, gridBagConstraints);

        panButtons.setLayout(new java.awt.GridBagLayout());

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        panButtons.add(btnSend, gridBagConstraints);

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        panButtons.add(btnClose, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 0);
        panSAAJSender.add(panButtons, gridBagConstraints);

        panFileContent.setLayout(new java.awt.GridBagLayout());

        panFileContent.setBorder(new javax.swing.border.TitledBorder("File Content"));
        srpFileContent.setMinimumSize(new java.awt.Dimension(24, 21));
        srpFileContent.setPreferredSize(new java.awt.Dimension(150, 65));
        srpFileContent.setViewportView(txaFileContent);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        panFileContent.add(srpFileContent, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panSAAJSender.add(panFileContent, gridBagConstraints);

        getContentPane().add(panSAAJSender, java.awt.BorderLayout.NORTH);

        pack();
    }//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // Add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // Add your handling code here:
        File file = new File(txtFile.getText());
        if (file.delete()) {
            com.see.truetransact.uicomponent.COptionPane.showMessageDialog(this, "File has bean sent to " + txtBranchCode.getText() + " Branch.");
        }

        this.dispose();
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnBranchCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBranchCodeActionPerformed
        // Add your handling code here:
        popUp();
    }//GEN-LAST:event_btnBranchCodeActionPerformed
   
    /** To display a popUp window for viewing existing data */    
    private void popUp() {
        final HashMap viewMap = new HashMap();
        viewMap.put(CommonConstants.MAP_NAME, "forex.getBranchDetails");
        new ViewAll(this, viewMap).show();
    }
    
    /** Called by the Popup window created thru popUp method
     * @param param
     */    
    public void fillData(Object param) {
        final HashMap hash = (HashMap) param;
        txtBranchCode.setText((String)hash.get("BRANCH_CODE"));
        txtName.setText((String)hash.get("BRANCH_NAME"));
        txtIPAddress.setText((String)hash.get("IP_ADDR"));
    }
     
    private File getExportFileDirectory() throws Exception{
        //System.out.println("Getting error log file");
        final StringBuffer directory = new StringBuffer().append(System.getProperty("user.home")).append("/tt/export/");
        return new File(directory.toString());
    }
    private void btnFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileActionPerformed
        // Add your handling code here:
        try {
            JFileChooser objJFileChooser = new JFileChooser();
            objJFileChooser.setDialogTitle("Send XML file using SAAJ");
            objJFileChooser.setSelectedFile(getExportFileDirectory());
            objJFileChooser.showOpenDialog(this);
            txtFile.setText(objJFileChooser.getSelectedFile().getAbsolutePath());
        } catch (Exception exc) {
            exc.printStackTrace();
        }
    }//GEN-LAST:event_btnFileActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.see.truetransact.uicomponent.CButton btnBranchCode;
    private com.see.truetransact.uicomponent.CButton btnClose;
    private com.see.truetransact.uicomponent.CButton btnFile;
    private com.see.truetransact.uicomponent.CButton btnSend;
    private com.see.truetransact.uicomponent.CLabel lblBranchCode;
    private com.see.truetransact.uicomponent.CLabel lblFile;
    private com.see.truetransact.uicomponent.CLabel lblIPAddress;
    private com.see.truetransact.uicomponent.CLabel lblName;
    private com.see.truetransact.uicomponent.CPanel panButtons;
    private com.see.truetransact.uicomponent.CPanel panDetails;
    private com.see.truetransact.uicomponent.CPanel panFileContent;
    private com.see.truetransact.uicomponent.CPanel panSAAJSender;
    private com.see.truetransact.uicomponent.CScrollPane srpFileContent;
    private com.see.truetransact.uicomponent.CTextArea txaFileContent;
    private com.see.truetransact.uicomponent.CTextField txtBranchCode;
    private com.see.truetransact.uicomponent.CTextField txtFile;
    private com.see.truetransact.uicomponent.CTextField txtIPAddress;
    private com.see.truetransact.uicomponent.CTextField txtName;
    // End of variables declaration//GEN-END:variables
    
}
