/*Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition.
 * 
 *
 **/
package com.see.truetransact.ui.termloan.agritermloan;
import java.util.ListResourceBundle;
/*
 *@author shanmugavel
 */
public class AgriTermLoanRB extends ListResourceBundle {
    public AgriTermLoanRB(){
    }
    
    public Object[][] getContents() {
        return contents;
    }
    
    static final String[][] contents = {
        {"btnAccNo", ""},
        {"lblRepayScheduleMode", "Repayment Schedule Mode"},
        {"lblAcct_Name", "Account Name"},
        {"rdoYes_Executed_DOC", "Yes"},
        {"rdoNo_Executed_DOC", "No"},
        {"rdoYes_Mandatory_DOC", "Yes"},
        {"rdoNo_Mandatory_DOC", "No"},
        {"lblMandatory_DOC", " Is Mandatory?"},
        {"lblExpiryDate_DOC", "Expiry Date"},
        {"lblExecuteDate_DOC", "Executed Date"},
        {"lblExecuted_DOC", " Is Executed?"},
        {"lblProdID_Disp_ODetails", ""},
        {"lblProdID_ODetails", "Product ID"},
        {"lblAcctHead_Disp_ODetails", ""},
        {"lblAcctHead_ODetails", "Account Head"},
        {"lblAcctNo_Disp_ODetails", ""},
        {"lblAcctNo_ODetails", "Account No."},
        {"lblEligibleLoan", "Eligible Amt"},
        {"panSecutityDetails_Table", "Margin"},
        {"lblPeriodDifference", "Period Difference"},
        {"lblPeriodDifference_Years", "YY"},
        {"lblPeriodDifference_Months", "MM"},
        {"lblPeriodDifference_Days", "DD"},
        {"lblPoANo", "PoA Number"},
        {"lblAddrType_PoA", "Address Type"},
        {"lblIntGetFrom", "Get Interest From"},
        {"lblQIS", "QIS"},
        {"lblFDate", "From Date"},
        {"btnSecurityDelete", "Delete"},
        {"lblAccStatus", "Account Status"},
        {"rdoMultiDisburseAllow_No", "No"},
        {"lblCustName", "Cust Name"},
        {"lblAccLimit", "Account Limit"},
        {"btnDelete_Sec", "Delete"},
        {"chkPrioritySector", ""},
        {"lblPremiumAmt", "Premium Amount"},
        {"lblPhone_BorrowerProfile", "Phone"},
        {"lblArea_GD", "Area"},
        {"chkMoraGiven", ""},
        {"lblScheduleNo", "Schedule No."},
        {"lblRefinancingInsti", "Refinancing Institution"},
        {"lblInterExpLimit", "Interest For Expiry of Limit %"},
        {"lblAccHead_IM", "Account Head"},
        {"lblConstitution_GD", "Constitution"},
        {"lblPoaHolderName", "PoA Holder's Name"},
        {"btnInterestMaintenanceNew", "New"},
        {"lblInsureCompany", "Insurance Company"},
        {"lblForMillIndus", "For Mills / Industrial Users"},
        {"lblCity_BorrowerProfile_2", ""},
        {"chkDocumentcomplete", ""},
        {"btnInterestMaintenanceSave", "Save"},
        {"lblContactPhone", "Contact Phone No."},
        {"lblCategory", "Category"},
        {"lblAccHead_GD", "Account Head"},
        {"lblBusinessPhone_AuthorizedSignatory", "Business Phone"},
        {"lblRiskRating", "Risk Rating"},
        {"rdoPostDatedCheque_No", "No"},
        {"lblAgainstClearingInter", "Against Clearing Interest %"},
        {"lblCountry_GD", "Country"},
        {"lblPhone_BorrowerProfile_2", ""},
        {"lblCustID", "Customer ID"},
        {"lblAccNo_IM", "Account No."},
        {"lblMoraGiven", "Moratorium to be Given"},
        {"btnNew1", "New"},
        {"lblDateEstablishment", "Date of Establishment"},
        {"lblRepayFreq_Repayment", "Repay Frequency"},
        {"lblPenalInter", "Penal Interest %"},
        {"lblState_AuthorizedSignatory", "State"},
        {"lblLastInstall", "Last Installment Date"},
        {"lblTotalBaseAmt", "Total Base Amount"},
        {"lblAddrCommunication_AuthorizedSignatory", "Communication Address"},
        {"lblAccHead_RS_2", ""},
        {"lblLimitAmt", "Limit Amount"},
        {"lblAmtLastInstall", "Amount for Last Installment"},
        {"lblFax_BorrowerProfile", "Fax"},
        {"lblAccHead_2", ""},
        {"btnSave", ""},
        {"chkECGC", ""},
        {"lblDemandPromNoteExpDate", "Expiry Date"},
        {"lblSanctionDate", "Sanction Date"},
        {"lblSecurityType", "Security Type"},
        {"lblPenalStatement", "Statement Penal %"},
        {"btnNew_PoA", "New"},
        {"rdoInterest_Simple", "Simple"},
        {"lblDateInspection", "Date of Inspection"},
        {"btnSave1", "Save"},
        {"lblPolicyNumber", "Policy Number"},
        {"rdoAccLimit_Submit", "Sub-Limit"},
        {"lblDemandPromNoteDate", "Issue Date"},
        {"lblChiefExecutiveName", "Chief Executive's Name"},
        {"rdoSecurityType_Primary", "Primary"},
        {"lblCommodityCode", "Commodity Code"},
        {"lblNatureCharge", "Nature of Charge"},
        {"lblPin_GD", "PIN Code"},
        {"lblPhone_GD", "Phone"},
        {"lblCardType","Card Type"},
        {"btnInterestMaintenanceDelete", "Delete"},
        {"lblArea_AuthorizedSignatory", "Area"},
        {"lblECGC", "ECGC"},
        {"lblHomePhone_AuthorizedSignatory", "Home Phone"},
        {"lblNumberAuthSignatory", "Number of Authorized Signatory"},
        {"lblPin_PowerAttroney", "PIN Code"},
        {"lblToAmt", "To Amount"},
        {"btnNew_Sec", "New"},
        {"lblAccNo_Idetail", "Account No."},
        {"lblExpiryDate", "Expiry Date"},
        {"panCompanyDetailsTrash", "Company Details"},
        {"lblAccNo_Idetail_2", ""},
        {"lblDistrictCode", "District Code"},
        {"lblOpenDate2", ""},
        {"lblRemark_PowerAttroney", "Remarks"},
        {"lblAccType", "Account Type"},
        {"lblRepayFreq", "Repay. Frequency"},
        {"lblRecarable", "Recarable"},
        {"lblFromAmt", "From Amount"},
        {"lblExpiryDate_2", ""},
        {"chkDirectFinance", ""},
        {"lblEmailId_AuthorizedSignatory", "Email ID"},
        {"lblSpace2", "     "},
        {"lblSanctionNo1", "Sanction No."},
        {"lblSanctionSlNo", "Sanction Sl. No."},
        {"lblAccNoSec", "Account No."},
        {"lblSpace3", "     "},
        {"lblHealthCode", "Health Code"},
        {"lblPolicyAmt", "Policy Amount"},
        {"btnAuthorizedNew", "New"},
        {"lblSpace1", " Status :"},
        {"lblCustomerID", "Customer ID"},
        {"lblPostDatedCheque", "Post Dated Cheques Allowed"},
        {"chkGurantor", "Guarantor/Coobligant/surety"},
        {"lblTypeOfFacility", "Type of Facility"},
        {"panSecurityDetails_FD", "Security Details"},
        {"btnsave_Sec", "Save"},
        {"lblMobile_AuthorizedSignatory", "Mobile"},
        {"btnSecurityNew", "New"},
        {"lblOpenDate", "Opening Date"},
        {"lblPin_BorrowerProfile_2", ""},
        {"lblSanctionNo2", ""},
        {"lblPolicyDate", "Policy Date"},
        {"lblTo", "To Date"},
        {"lblState_PowerAttroney", "State"},
        {"lblTotalInstallAmt", "Total Installment Amount"},
        {"lblProdID_RS", "Product ID"},
        {"lblIndusCode", "Industry Code"},
        {"lblGuarantorNetWorth", "Guarantor's Net worth"},
        {"lblAODDate", "AOD Date"},
        {"chkInsurance", "Insurance"},
        {"panBorrowProfile", "Borrower's Profile"},
        {"panSecurityDetails", "Security Details"},
        {"lblCreditFacilityAvailSince", "Cr Facilities Availed Since"},
        {"lblLaonAmt", "Loan Amount"},
        {"lblSectorCode2", "Sector Code"},
        {"panInsuranceDetails", "Insurance Details"},
        {"lblGuaranAccNo", "Guarantor Acct No"},
        {"lblCity_GD", "City"},
        {"lblStatus", "                      "},
        {"lblAccHead_IM_2", ""},
        {"btnGuarantorNew", "New"},
        {"rdoAccType_New", "New"},
        {"btnDelete_PoA", "Delete"},
        {"btnDelete", ""},
        {"lblAssetCode", "Asset Status"},
        {"lblSanctionNo", "Sanction No."},
        {"lblInterest", "Interest"},
        {"btnAuthorizedDelete", "Delete"},
        {"lblSecurityNo", "Security No."},
        {"lblNatureInterest", "Nature of Interest"},
        {"lblState_GD", "State"},
        {"rdoSubsidy_No", "No"},
        {"lblProdId1", "Product ID"},
        {"lblPurposeCode", "Purpose Code"},
        {"lblAccHead_CD_2", ""},
        {"btnDelete1", "Delete"},
        {"lblCountry_CompDetail", "Country"},
        {"lblPeriodFrom_PowerAttroney", "Period From"},
        {"lblStreet_GD", "Street"},
        {"lblProID_CD", "Product ID"},
        {"lblDrawingPower_2", ""},
        {"btnAuthorizedSave", "Save"},
        {"btnCustID", ""},
        {"btnCustID_Security", ""},
        {"btnSecurityNo_Security", ""},
        {"lblCustName_Security_Display", ""},
        {"lblLimits", "Limits"},
        {"lblRiskWeight", "Risk Weight"},
        {"btnClose", ""},
        {"btnDelete", ""},
        {"btnReject", ""},
        {"btnAuthorize", ""},
        {"lblFromDate", "From Date"},
        {"rdoAccType_Transfered", "Transfered"},
        {"lblAddressType", "Address Type"},
        {"lblAccNo_RS_2", ""},
        {"rdoNatureInterest_PLR", "PLR"},
        {"lblMsg", ""},
        {"lblNoMonthsMora", "Moratorium Months"},
        {"lblLimit_SD", "Limit"},
        {"lblSancDate", "Sanction Date"},
        {"lblPin_BorrowerProfile", "PIN Code"},
        {"lblSubsidy", "Subsidy"},
        {"lblCity_PowerAttroney", "City"},
        {"lblBorrowerNo", "Borrower No."},
        {"lblSanctionDate1", "Sanction Date"},
        {"lblModeSanction", "Mode of Communication"},
        {"lblHomeFax_AuthorizedSignatory", "Home Fax"},
        {"lblAmtPenulInstall", "Penultimate Installment Amt"},
        {"rdoSecurityDetails_Unsec", "Unsecured"},
        {"lblPin_AuthorizedSignatory", "PIN Code"},
        {"lblDocumentcomplete", "Document Complete"},
        {"lblAccNo_GD_2", ""},
        {"lblWeakerSectionCode", " Weaker Section Code"},
        {"lblTDate", "To Date"},
        {"lblPLR_Limit", "PLR"},
        {"lblCity_CompDetail", "City"},
        {"lblSecurityValue", "Security Value"},
        {"btnGuarantorSave", "Save"},
        {"lblAccNo_CD_2", ""},
        {"lblDrawingPower", "Drawing Power"},
        {"lblSanctioningAuthority", "Sanctioning Authority"},
        {"lblDateCharge", "Date of Charge"},
        {"panGuarantorDetails", "Guarantor/Coobligant/surety"},
        {"lblName_AuthorizedSignatory", "Name"},
        {"lblFrom", "From Date"},
        {"lblDoAddSIs", "Do You Want to Add SIs?"},
        {"btnCustomerID_GD", ""},
        {"lblAsOn_GD", "As On"},
        {"lblAccNo_IM_2", ""},
        {"lblNetWorth", "Net Worth"},
        {"lblPager_AuthorizedSignatory", "Pager"},
        {"btnPrint", ""},
        {"rdoRecarable_Yes", "Yes"},
        {"lblAccHead", "Account Head"},
        {"lblNoInstallments", "No. of Installments"},
        {"lblNoInstallments_PROD", "Limit Period"},
        {"lblBlank1", ""},
        {"rdoSubsidy_Yes", "Yes"},
        {"lblAccNo_CD", "Account No."},
        {"btnCustomerID", ""},
        {"lblLimitAmt_2", ""},
        {"lblSancDate_2", ""},
        {"lblPrioritySector", "Priority Sector"},
        {"lblInter", "Interest %"},
        {"lblState_CompDetail", "State"},
        {"lblProductId", "Product ID"},
        {"lblProductID_FD", "Product ID"},
        {"lblProductID_FD_Disp", ""},
        {"lblBorrowerNo_2", "3424"},
        {"rdoRiskWeight_No", "No"},
        {"lblFirstInstall", "First Installment Date"},
        {"btnSave_PoA", "Save"},
        {"lblPhone_CompDetail", "Phone"},
        {"lblSanctionDate2", ""},
        {"lblRepayType", "Repayment Type"},
        {"lblArea_PowerAttroney", "Area"},
        {"lblGroupDesc", "Group Description"},
        {"lblSectorCode1", "Sub Sector"},
        {"lblAccHead_CD", "Account Head"},
        {"lblGuaranName", "Name"},
        {"rdoDoAddSIs_No", "No"},
        {"rdoRecarable_No", "No"},
        {"rdoPostDatedCheque_Yes", "Yes"},
        {"lblMargin", "Margin%"},
        {"btnNew", ""},
        {"lblProdId", "Product ID"},
        {"lblProdID_IM", "Product ID"},
        {"lblCustomerID_GD", "Customer ID"},
        {"lblDirectFinance", "Direct Finance"},
        {"lblAccHeadSec", "Account Head"},
        {"lblPeriodTo_PowerAttroney", "Period To"},
        {"lblAccNo_RS", "Account No."},
        {"btnSecuritySave", "Save"},
        {"lblCompanyRegisNo", "Company Registration No."},
        {"lblCustName_Security", "Cust Name"},
        {"lblDealingWithBankSince", "Dealing with the Bank Since"},
        {"chkQIS", ""},
        {"lblTypeFacility", "Type of Facility"},
        {"lblGuarantorNo", "Sl. Number"},
        {"rdoAccLimit_Main", "Main"},
        {"lblInterestType", "Interest Type"},
        {"lblCountry_PowerAttroney", "Country"},
        {"lblConstitution", "Constitution"},
        {"lblRemark_FD", "Remarks"},
        {"lblAccHead_RS", "Account Head"},
        {"lblAccountHead_FD_Disp", ""},
        {"lblAccountHead_FD", "Account Head"},
        {"lblAccHead_Idetail_2", ""},
        {"rdoSecurityDetails_Fully", "Fully Secured"},
        {"rdoSecurityDetails_Partly", "Partly Secured"},
        {"lblArea_CompDetail", "Area"},
        {"btnGuarantorDelete", "Delete"},
        {"lbl20Code", "20 Code"},
        {"lblContactPerson", "Contact Person"},
        {"lblAccHead_Idetail", "Account Head"},
        {"lblState_BorrowerProfile", "State"},
        {"btnEdit", ""},
        {"lblReferences", "References"},
        {"rdoDoAddSIs_Yes", "Yes"},
        {"lblSelCommodityItem", "Selective Commodity Item"},
        {"rdoRiskWeight_Yes", "Yes"},
        {"rdoNatureInterest_NonPLR", "Non-PLR"},
        {"lblAccNoSec_2", ""},
        {"lblCity_BorrowerProfile", "City"},
        {"lblFax_BorrowerProfile_2", ""},
        {"chkStockInspect", "SubSidy/ValuationLand"},//Stock / Inspection
        {"lblGuaranteeCoverCode", "Guarantee Cover Code"},
        {"lblPin_CompDetail", "PIN Code"},
        {"lblNoInstall", "No. of Installments"},
        {"lblMultiDisburseAllow", "Multi Disbursement"},
        {"lblBusinessFax_AuthorizedSignatory", "Business Fax"},
        {"rdoMultiDisburseAllow_Yes", "Yes"},
        {"lblRemarks__CompDetail", "Remarks"},
        {"lblStreet_AuthorizedSignatory", "Street"},
        {"lblNatureBusiness", "Nature of Business"},
        {"lblStreet_CompDetail", "Street"},
        {"lblPhone_PowerAttroney", "Phone"},
        {"lblCountry_AuthorizedSignatory", "Country"},
        {"lblCustName_2", ""},
        {"chkSelCommodityItem", ""},
        {"lblStreet_PowerAttroney", "Street"},
        {"lblStockStateFreq", "Stock Statement Frequency"},
        {"lblProdID_GD", "Product ID"},
        {"lblAccNo_GD", "Account No."},
        {"lblRemarks", "Remarks"},
        {"panDemandPromssoryDate", "Demand Promissory Note"},
        {"lblProdType", "Product Type"},
        {"lblDOB_GD", "Date of Birth"},
        {"lblExpityDate", "Expiry Date"},
        {"lblNPADate", "NPA Date"},
        {"lblState_BorrowerProfile_2", ""},
        {"lblAsOn", "As On"},
        {"lblAccHeadSec_2", ""},
        {"lblPLR_Limit_2", ""},
        {"lblNatureRisk", "Nature of Risk Covered"},
        {"lblDesig_AuthorizedSignatory", "Designation"},
        {"rdoInterest_Compound", "Compound"},
        {"lblCustID_Security", "Customer ID"},
        {"lblAccHead_GD_2", ""},
        {"rdoSecurityType_Collateral", "Collateral"},
        {"lblCity_AuthorizedSignatory", "City"},
        {"lblPurposeDesc", "Purpose Description"},
        {"lblToDate", "To Date"},
        {"lblGovtSchemeCode", "Govt. Scheme Code"},
        {"btnCancel", ""},
        {"lblProdID_IDetail", "Product ID"},
        {"btnSave2_SD", "Save"},
        {"btnNew2_SD", "New"},
        {"btnDelete2_SD", "Delete"},
        {"btnFacilitySave", "Save"},
        {"btnFacilityDelete", "Delete"},
        {"btnNew_Insurance", "New"},
        {"btnSave_Insurance", "Save"},
        {"btnDelete_Insurance", "Delete"},
        {"lblSecurityNo_Insurance", "Security No."},
        {"lblRemark_Insurance", "Remarks"},
        {"btnNew_Borrower", "New"},
        {"btnToMain_Borrower", "To Main"},
        {"btnDelete_Borrower", "Delete"},
        {"lblTotalSecurity_Value", "Total Security Value(%)"},
        {"lblPoACust", "On Behalf of"},
        {"btnRepayment_New", "New"},
        {"btnRepayment_Save", "Save"},
        {"btnRepayment_Delete", "Delete"},
        {"lblAcctNo_Sanction", "Account No."},
        {"lblAcctNo_Sanction_Disp", ""},
        {"lblAcctNo_FD", "Account No."},
        {"lblAcctNo_FD_Disp", ""},
        {"lblFacility_Repay_Date", "Repayment Date"},
        {"lblMoratorium_Given", "Moratorium Given"},
        {"chkMoratorium_Given", ""},
        {"lblFacility_Moratorium_Period", "Moratorium Months"},
        {"btnSave_DocumentDetails", "Save"},
        {"lblAcctHead_DocumentDetails", "Account Head"},
        {"lblAcctHead_Disp_DocumentDetails", ""},
        {"lblAcctNo_DocumentDetails", "Account No."},
        {"lblAcctNo_Disp_DocumentDetails", ""},
        {"lblDocDesc_Disp_DocumentDetails", ""},
        {"lblDocDesc_DocumentDetails", "Description"},
        {"lblDocNo_Disp_DocumentDetails", ""},
        {"lblDocNo_DocumentDetails", "Document No."},
        {"lblDocType_Disp_DocumentDetails", ""},
        {"lblDocType_DocumentDetails", "Document Type"},
        {"lblProdID_Disp_DocumentDetails", ""},
        {"lblProdID_DocumentDetails", "Product ID"},
        {"lblRemarks_DocumentDetails", "Remarks"},
        {"lblSubmitDate_DocumentDetails", "Submitted Date"},
        {"lblSubmitted_DocumentDetails", "Is Submitted?"},
        {"rdoNo_DocumentDetails", "No"},
        {"rdoYes_DocumentDetails", "Yes"},
        {"lblCrInterestRateIN", "Credit Interest"},
        {"lblATMNoAD", "No"},
        {"lblCredit", "Credit"},
        {"lblCreditToDateAD", "To"},
        {"lblPeakSanctionFromDt","PeakSanctionFromDt"},
        {"lblPeakSanctionToDate","PeakSanctionToDate"},
        {"lblPeakSanctionAmt","PeakSanctionAmt"},
        {"btnNew_PSD","New"},
        {"btnSave_PSD","Save"},
        {"panDocumentDetails","Document Details"},
        {"panGuarantorInsuranceDetails","Guarantor Details"},
        {"btnDelete_PSD","Delete"},
        {"chkMobileBankingAD", "Mobile Banking"},
        {"lblAccOpeningChrgAD", "Account Opening"},
        {"panIsRequired", "Is Required ?"},
        {"chkABBChrgAD", ""},
        {"chkPOFAttorney", "POF Attorney"},
        {"chkAuthorizedSignatory", "Auth Signatory"},
        {"chkDocDetails", "Doc Details"},
        {"lblCollectInoperative", "Collect Inoperative"},
        {"panInterestPayableIN", "Interest"},
        {"lblABB", "ABB"},
        {"lblPenalInterestRateIN", "Penal Interest"},
        {"panFlexiOpt", "Mode of Operation"},
        {"lblExcessWithChrgAD", "Excess Withdrawal"},
        {"lblStopPayment", "Stop Payment"},
        {"lblCrInterestRateValueIN", ""},
        {"lblABBChrgAD", "ABB"},
        {"lblSettlementModeAI", "Settlement Mode"},
        {"chkATMAD", "ATM"},
        {"lblCreditFromDateAD", "Valid From"},
        {"panDiffCharges", "Different Charges"},
        {"lblNPA", "NPA"},
        {"lblDebitToDateAD", "To"},
        {"lblFolioChrgAD", "Folio"},
        {"lblMisServiceChrgAD", "Misc. Service"},
        {"lblMinActBalanceAD", "Minimum Account Balance"},
        {"chkNROStatusAD", "NRO Status"},
        {"lblChequeReturn", "Cheque Return"},
        {"lblAgClearingIN", "Ag Clearing"},
        {"lblDebitNoAD", "No"},
        {"chkPayIntOnCrBalIN", "Pay Interest on Credit Balanace"},
        {"lblRateCodeValueIN", ""},
        {"lblDebitFromDateAD", "Valid From"},
        {"lblDrInterestRateValueIN", ""},
        {"chkPayIntOnDrBalIN", "Receive Interest on Debit Balanace"},
        {"lblCreditNoAD", "No"},
        {"lblDrInterestRateIN", "Debit Interest"},
        {"panRatesIN", "Rate Details"},
        {"chkChequeBookAD", "Cheque Book"},
        {"chkInopChrgAD", ""},
        {"lblRateCodeIN", "Code"},
        {"lblAgClearingValueIN", ""},
        {"btnException", ""},
        {"lblNPAChrgAD", "NPA Date"},
        {"lblChequeBookChrgAD", "Cheque Book"},
        {"chkCustGrpLimitValidationAD", "Cust. Group Limit Validation"},
        {"lblNonMaintenance", "Non-maintenance of Min Bal."},
        {"lblATMToDateAD", "To"},
        {"lblStatement", "Statement"},
        {"chkChequeRetChrgAD", ""},
        {"chkStopPmtChrgAD", ""},
        {"chkDebitAD", "Debit"},
        {"lblStmtFreqAD", "Statement Frequency"},
        {"chkNPAChrgAD", ""},
        {"lblOpModeAI", "Mode of Operation"},
        {"chkStmtChrgAD", ""},
        {"chkCreditAD", "Credit"},
        {"lblATMFromDateAD", "Valid From"},
        {"lblDebit", "Debit"},
        {"lblAccCloseChrgAD", "Account Closing"},
        {"panCardInfo", "Card Info."},
        {"chkNonMainMinBalChrgAD", ""},
        {"panLastIntApp", "Last Interest Application Date"},
        {"lblPenalInterestValueIN", ""},
        {"lblDisbursement_Dt", "Disbursement Date"},
        {"lblAccountOpenDate","Account Open Date"},
        {"lblRecommandByType","Recommended By"},
        //insurance Details
        {"lblInsDetails","Insurance Type"},
        {"lblInsUnderScheme","Insurance Under Scheme"},
        {"lblInsComName","Insurance Company Name"},
        {"lblAddress","Address"},
        {"lblPhoneNo","Phone No"},
        {"lblPolicyNo","Policy No"},
        {"lblInsFrom","Insurance From"},
        {"lblInsTo","Insurance To"},
        {"lblInsIssueDt","Insurance Issue Dt"},
        {"lblInsuranceAmt","Insurance Amt"},
        {"lblPremiumAmt","Premium Amt"},
        {"lblNatureOfRiskCoverd","Nature Of Risk Covered"},
        {"lblDebitProdId","Debit prodid"},
        {"lblDebitProdType","Debit prodtype"},
        {"lblFromActNo","Debit Act_no"},
        {"lblFromActHead","Debit acct head"},
        
        {"lblReviewDate","Review Date"},
        {"lblCardType","Card Type"},
        {"lblCardLimit","Card Limit"},
        {"lblCardValidity","Card Validity"},
        
        {"lblFromActNo1","Remarks"},
        //TO ADD MANUALLY...
        {"tblColumnBorrowerName", "Name"},
        {"tblColumnBorrowerCustID", "Customer ID"},
        {"tblColumnBorrowerType", "Type"},
        {"tblColumnBorrowerMain/Joint", "Main/Joint"},
        
        {"tblColumnAuth1", "AS No."},
        {"tblColumnAuth2", "Customer ID"},
        {"tblColumnAuth3", "Name"},
        {"tblColumnAuth4", "Limits"},
        
        {"tblColumnPoA1", "PoA No."},
        {"tblColumnPoA2", "PoA Holder"},
        {"tblColumnPoA3", "Period From"},
        {"tblColumnPoA4", "Period To"},
        
        {"tblColumnSanction_Facility1", "Facility No."},
        {"tblColumnSanction_Facility2", "Type"},
        {"tblColumnSanction_Facility3", "Limit"},
        {"tblColumnSanction_Facility4", "From"},
        {"tblColumnSanction_Facility5", "To"},
        
        
        {"tblColumnSanction_Main1", "Sl No."},
        {"tblColumnSanction_Main2", "Sanction No."},
        {"tblColumnSanction_Main3", "Authority"},
        {"tblColumnSanction_Main4", "Sanction Mode"},
        
        {"tblColumnSecurityNo", "Security No."},
        {"tblColumnSecurityMargin", "Margin"},
        {"tblColumnSecurityValue", "Value"},
        {"tblColumnSecurityEligible", "Eligible"},
        {"tblColumnSecuritySLNO", "SLNO"},
        {"tblColumnSecurityCustID", "Cust ID"},
        
        {"tblColumnDepositNo", "Deposit No."},
        {"tblColumnDepositSubNo", "Sub No."},
        {"tblColumnLienNo", "Lien No."},
        {"tblColumnSecurityValue", "Value"},
        {"tblColumnLienDt", "Lien Dt."},
        
        {"tblColumnInsuranceNo", "Insurance No."},
        {"tblColumnInsuranceSecrityNo", "Security No."},
        {"tblColumnInsuranceCompany", "Company"},
        
        {"tblColumnRepaymentScheduleNo", "Schedule No."},
        {"tblColumnRepaymentLoanAmount", "Loan Amount"},
        {"tblColumnRepaymentSceduleMode", "Schedule Mode"},
        {"tblColumnRepaymentRefScheduleNo", "Reference Schedule No."},
        //for share
        {"tblcolumnShareShareno","Share Acct No"},
        {"tblcolumnShareNoOfShare","No Of Share"},
        {"tblcolumnShareShareAmt","Share Amt"},
        {"tblcolumnShareLoanNo","Loan No"},
        {"tblcolumnShareType","Share Type"},
        {"tblcolumnShareCustId","Cust Id"},
        {"tblcolumnShareCustName","Cust Name"},
        //end
        {"tblColumnGuarantorNo", "G No."},
        {"tblColumnGuarantorCustID", "Cust ID"},
        {"tblColumnGuarantorName", "Name"},
        {"tblColumnGuarantorAcc_No", "A/C No."},
        
        {"tblColumnInterestNo", "IM No."},
        {"tblColumnInterestFromDate", "From Date"},
        {"tblColumnInterestToDate", "To Date"},
        {"tblColumnInterestFromAmt", "From Amount"},
        {"tblColumnInterestToAmt", "To Amount"},
        {"tblColumnInterestInterest", "Interest"},
        {"tblColumnInterestStatus", "ActiveStatus"},
        {"tblColumnAuthorizeStatus", "AuthorizeStatus"},
        {"tblcolumnInsuranceSlno", "InsuranceSlno"},
        {"tblcolumnInsuranceType", "InsuranceType"},
        {"tblcolumnInsuranceScheme", "InsuranceScheme"},
        {"tblcolumnInsuranceCompName", "InsuranceCompName"},
        
        
         {"tblColumnDocumentType", "Document Type"},
        {"tblColumnDocumentNo", "Number"},
        {"tblColumnDocumentDesc", "Description"},
        {"tblColumnDocumentSubmit", "Submitted"},
        
        
        {"tblColumnPeakSanFromDate", "From Date"},
        {"tblColumnPeakToDate", "To Date"},
        {"tblColumnPeakAmt", "Amt"},
        
        
        {"cDialogYes", "Yes"},
        {"cDialogNo", "No"},
        {"cDialogCancel", "Cancel"},
        {"cDialogOk", "Ok"},
        
        {"existanceSanctionDetailsWarning", "Atleast One Facility Details should Exist."},
        {"existanceFacilityWarning", "Facility Details are Available for Selected Row."},
        {"existanceFacilityEditWarning", "Facility Detail is in Edit Mode."},
        {"existanceSanctionNoWarning", "This Sanction Number already exist."},
        {"existenceAuthSignTableWarning", "Enter the Authorized Signatory."},
        {"existenceSancDetailsTableWarning", "Enter the Sanction Details."},
        {"existenceGuarantorDetailsTableWarning", "Enter the Guarantor Details."},
        {"existencePOATableWarning", "Enter the POA Details."},
         {"existenceAurhorizedSignatoryTableWarning", "Enter the Authorized Signatory Details."},
        {"existenceInsuranceTableWarning", "Enter the Insurance Details."},
        {"existenceSecurityWarning", "Enter the Security Details."},
        {"existenceInterestWarning", "Enter the Interst Details Details."},
        {"existenceSubLimitWarning", "Enter the SubLimit Details."},
        {"existenceSubsidyWarning", "Enter the Subsidy Details."},
        {"existanceSecurityNoWarning", "This Security Number has Insurance Details."},
        {"dialogForJointAccntHolder", "This will reset the Joint Account Holders data. Are you sure to reset it?"},
        {"securityValueWarning", "Security value must be greater than or equal to the Limit amount when Fully Secured."},
        {"securityValueMsg", "Security Value is less than the Limit Amount."},
        {"existanceCustomerWarning", "Select Main Account Holder before selecting Joint Account Holders."},
        {"existanceRepayLumpSumWarning", "Lump Sum must have only one schedule."},
        {"loanExceedLimitWarning", "Total loan amount cannot exceed limit amount."},
        {"interestDetailsWarning", "There is in-sufficient Interest Details."},
        {"interestDetailsWarningAmt", "In Interest Details Screen TO_AMOUNT Shoude be 999999999."},
        {"interestDetailsWarningDate", "Interest TO_DATE Not Covering Entire Loan Period."},
        {"interestGetFromValChangeWarning", "Do you want to get the Interest Details from Product?\nAll your data will be deleted."},
        {"repaymentDateExceedLoanLimitDate", "Last Repayment date cannot exceed Loan's To date."},
        {"existanceCustomerWarningPoA", "This Customer has entry in Power of Attorney."},
        {"existanceRepaymentWarning", "Cannot change the Interest from field when Repayment Schedule exists."},
        {"moratorium_Given_Warning", "Enter the No. of Months for Moratorium."},
        {"individualCustWarning", "Corporate Customer is not allowed for Individual"},
        {"corporateCustWarning", "Individual Customer is allowed only for Joint Account and Individual"},
        {"repaymentEditWarning", "Repayment Schedule is in Edit mode"},
        {"authSignatoryEditWarning", "Authorized Signatory is in Edit mode"},
        {"valuationEditWarning", "Valuation/Subsidy  is in Edit mode"},        
        {"authSignatoryInstEditWarning", "Authorized Signatory Instruction is in Edit mode"},
        {"insuranceEditWarning", "Insurance Details is in Edit mode"},
        {"poaEditWarning", "Power of Attorney is in Edit mode"},
        {"securityDetailsEditWarning", "Security Details is in Edit mode"},
        {"documentDetailsEditWarning", "Document Details is in Edit mode"},
        {"interestDetailsEditWarning", "Interest Details is in Edit mode"},
        {"guarantorDetailsEditWarning", "Guarantor Details is in Edit mode"},
        {"isNotADepositAcctHolderWarning", "This Customer is not a Deposit Account Holder"},
        {"jointAcctDontHaveProperCustDetailsWarning", "Atleast 2 Customers should be there for Joint Account"},
        {"isNotAShareHolderWarning", "This Customer is not a Share Holder"},
        {"PENAL_ROI_WARNING", "Interest Rate Should be More than Penal Rate"},
        {"activeScheduleWarning", "Repayment Schedule is already created for Loan Disbursement"},
        {"ROI_Existence_Warn", "The Rate for this Range of Date and Amount already exist. Please Enter the Data Again"},
        {"santionFacilityEditWarning", "Sanction Facility is in Edit mode"},
        {"repayfreqtable","repay table shoude not be empty"}
    };
    
}
