/*
 * Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition.
 * 
 *
 * NewLoanProductMRB.java
 * 
 * Created on Fri Apr 29 16:27:40 IST 2005
 */

package com.see.truetransact.ui.product.loan;

import java.util.ListResourceBundle;

public class NewLoanProductMRB extends ListResourceBundle {
    public NewLoanProductMRB(){
    }

    public Object[][] getContents() {
        return contents;
    }

    static final String[][] contents = {
        {"cboMinPeriod", "MinPeriod should be a proper value!!!"},
        {"rdoProcessCharges_Yes", "ProcessCharges should be selected!!!"},
        {"txtCharge_Limit3", "Charge_Limit3 should not be empty!!!"},
        {"cboPeriodTransLossAssets", "PeriodTransLossAssets should be a proper value!!!"},
        {"txtMiscServCharges", "MiscServCharges should not be empty!!!"},
        {"rdoMobileBanlingClient_Yes", "MobileBanlingClient should be selected!!!"},
        {"txtProvisionLossAssets", "ProvisionLossAssets should not be empty!!!"},
        {"rdoIsDebitInterUnderClearing_Yes", "IsDebitInterUnderClearing should be selected!!!"},
        {"txtPLRRate", "PLRRate should not be empty!!!"},
        {"txtAccHead", "AccHead should not be empty!!!"},
        {"txtLastAccNum", "LastAccNum should not be empty!!!"},
        {"txtMaxAmtLoan", "MaxAmtLoan should not be empty!!!"},
        {"cboLoanPeriodMul", "LoanPeriodMul should be a proper value!!!"},
        {"cboDebitInterComFreq", "DebitInterComFreq should be a proper value!!!"},
        {"txtExposureLimit_Policy2", "ExposureLimit_Policy2 should not be empty!!!"},
        {"cboDebInterCalcFreq", "DebInterCalcFreq should be a proper value!!!"},
        {"tdtNextFolioDDate", "NextFolioDDate should not be empty!!!"},
        {"cboPeriodTransDoubtfulAssets1", "PeriodTransDoubtfulAssets 1 should be a proper value!!!"},
        {"cboPeriodTransDoubtfulAssets2", "PeriodTransDoubtfulAssets 2 should be a proper value!!!"},
        {"cboPeriodTransDoubtfulAssets3", "PeriodTransDoubtfulAssets 3 should be a proper value!!!"},
        {"txtCharge_Limit2", "Charge_Limit2 should not be empty!!!"},
        {"rdoSubsidy_Yes", "Subsidy should be selected!!!"},
        {"rdoPLRRateAppl_Yes", "PLRRateAppl should be selected!!!"},
        {"txtPeriodAfterWhichTransNPerformingAssets", "PeriodAfterWhichTransNPerformingAssets should not be empty!!!"},
        {"cboMinPeriodsArrears", "MinPeriodsArrears should be a proper value!!!"},
        {"rdoIsStaffAccOpened_Yes", "IsStaffAccOpened should be selected!!!"},
        {"rdoStatCharges_Yes", "StatCharges should be selected!!!"},
        {"txtProductDesc", "ProductDesc should not be empty!!!"},
        {"txtMinPeriod", "MinPeriod should not be empty!!!"},
        {"cboIncompleteFolioRoundOffFreq", "IncompleteFolioRoundOffFreq should be a proper value!!!"},
        {"txtNoEntriesPerFolio", "NoEntriesPerFolio should not be empty!!!"},
        {"rdoIsAnyBranBankingAllowed_Yes", "IsAnyBranBankingAllowed should be selected!!!"},
        {"txtStatementCharges", "StatementCharges should not be empty!!!"},
        {"txtMinInterDebited", "MinInterDebited should not be empty!!!"},
        {"tdtPlrApplAccSancForm", "PlrApplAccSancForm should not be empty!!!"},
        {"rdoPLRApplNewAcc_Yes", "PLRApplNewAcc should be selected!!!"},
        {"cboMaxPeriod", "MaxPeriod should be a proper value!!!"},
        {"txtNumPatternFollowed", "NumPatternFollowed should not be empty!!!"},
        {"txtAccCreditInter", "AccCreditInter should not be empty!!!"},
        {"rdoToChargeOn_Man", "ToChargeOn should be selected!!!"},
        {"tdtLastInterAppDate", "LastInterAppDate should not be empty!!!"},
        {"txtStatChargesRate", "StatChargesRate should not be empty!!!"},
        {"cboProductFreq", "ProductFreq should be a proper value!!!"},
        {"txtPeriodTranSStanAssets", "PeriodTranSStanAssets should not be empty!!!"},
        {"txtAccClosingCharges", "AccClosingCharges should not be empty!!!"},
        {"cboDocumentType", "DocumentType should be a proper value!!!"},
        {"rdoFolioChargesAppl_Yes", "FolioChargesAppl should be selected!!!"},
        {"txtDocumentDesc", "DocumentDesc should not be empty!!!"},
        {"txtExposureLimit_Policy", "ExposureLimit_Policy should not be empty!!!"},
        {"tdtLastFolioChargesAppl", "LastFolioChargesAppl should not be empty!!!"},
        {"txtMaxDebitInterAmt", "MaxDebitInterAmt should not be empty!!!"},
        {"txtCheReturnChargest_Out", "CheReturnChargest_Out should not be empty!!!"},
        {"txtPenalInterRate", "PenalInterRate should not be empty!!!"},
        {"cboFolioChargesAppFreq", "FolioChargesAppFreq should be a proper value!!!"},
        {"txtRateAmt", "RateAmt should not be empty!!!"},
        {"rdoATMcardIssued_Yes", "ATMcardIssued should be selected!!!"},
        {"cboToCollectFolioCharges", "ToCollectFolioCharges should be a proper value!!!"},
        {"txtMinDebitInterAmt", "MinDebitInterAmt should not be empty!!!"},
        {"txtDocumentNo", "DocumentNo should not be empty!!!"},
        {"txtAccClosCharges", "AccClosCharges should not be empty!!!"},
        {"txtArcCostAccount", "ArcCostAccount should not be empty!!!"},
        {"txtArcExpenseAccount", "ArcExpenseAccount should not be empty!!!"},
        {"txtEaCostAccount", "EaCostAccount should not be empty!!!"},
        {"txtEaExpenseAccount", "EaExpenseAccount should not be empty!!!"},
        {"txtEpCostAccount", "EpCostAccount should not be empty!!!"},
        {"txtEpExpenseAccount", "EpExpenseAccount should not be empty!!!"},
        {"txtIntPayableAccount","Int Payable Account Head Should Not be empty"},
        {"txtMinAmtLoan", "MinAmtLoan should not be empty!!!"},
        {"cboProdCurrency", "ProdCurrency should be a proper value!!!"},
        {"txtExposureLimit_Prud2", "ExposureLimit_Prud2 should not be empty!!!"},
        {"cboOperatesLike", "OperatesLike should be a proper value!!!"},
        {"cboProdCategory", "Product Category should be a proper value!!!"},
        {"txtMiscSerCharges", "MiscSerCharges should not be empty!!!"},
        {"cboCharge_Limit2", "Charge_Limit2 should be a proper value!!!"},
        {"rdoPenalAppl_Yes", "PenalAppl should be selected!!!"},
        {"cboDebitInterRoundOff", "DebitInterRoundOff should be a proper value!!!"},
        {"cboInterestRepaymentFreq", "Interest Repayment Frequency should be a proper value!!!"},
        
        {"rdoldebitInterCharged_Yes", "ldebitInterCharged should be selected!!!"},
        {"txtAccDebitInter", "AccDebitInter should not be empty!!!"},
        {"txtExposureLimit_Prud", "ExposureLimit_Prud should not be empty!!!"},
        {"cboDebitInterAppFreq", "DebitInterAppFreq should be a proper value!!!"},
        {"txtProductID", "ProductID should not be empty!!!"},
        {"txtProvisionStandardAssetss", "ProvisionStandardAssetss should not be empty!!!"},
        {"rdoPLRApplExistingAcc_Yes", "PLRApplExistingAcc should be selected!!!"},
        {"txtPenalInter", "PenalInter should not be empty!!!"},
        {"tdtPLRAppForm", "PLRAppForm should not be empty!!!"},
        {"rdoCreditCardIssued_Yes", "CreditCardIssued should be selected!!!"},
        {"cboPeriodTranSStanAssets", "PeriodTranSStanAssets should be a proper value!!!"},
        {"txtMaxPeriod", "MaxPeriod should not be empty!!!"},
        {"cboPeriodAfterWhichTransNPerformingAssets", "PeriodAfterWhichTransNPerformingAssets should be a proper value!!!"},
        {"rdoLimitExpiryInter_Yes", "LimitExpiryInter should be selected!!!"},
        {"txtMinDebitInterRate", "MinDebitInterRate should not be empty!!!"},
        {"txtNumPatternFollowedSuffix", "NumPatternFollowedSuffix should not be empty!!!"},
        {"txtCheReturnChargest_In", "CheReturnChargest_In should not be empty!!!"},
        {"txtExpiryInter", "ExpiryInter should not be empty!!!"},
        {"txtProvisionsStanAssets", "ProvisionsStanAssets should not be empty!!!"},
        {"txtRatePerFolio", "RatePerFolio should not be empty!!!"},
        {"tdtLastInterCalcDate", "LastInterCalcDate should not be empty!!!"},
        {"txtProcessingCharges", "ProcessingCharges should not be empty!!!"},
        {"txtCommitCharges", "CommitCharges should not be empty!!!"},
        {"cbocalcType", "calcType should be a proper value!!!"},
        {"cboCharge_Limit3", "Charge_Limit3 should be a proper value!!!"},
        {"txtProvisionDoubtfulAssets1", "ProvisionDoubtfulAssets 1 should not be empty!!!"},
        {"txtProvisionDoubtfulAssets2", "ProvisionDoubtfulAssets 2 should not be empty!!!"},
        {"txtProvisionDoubtfulAssets3", "ProvisionDoubtfulAssets 3 should not be empty!!!"},
        {"txtApplicableInter", "ApplicableInter should not be empty!!!"},
        {"rdoCommitmentCharge_Yes", "CommitmentCharge should be selected!!!"},
        {"txtMaxDebitInterRate", "MaxDebitInterRate should not be empty!!!"},
        {"txtRangeTo", "RangeTo should not be empty!!!"},
        {"txtRangeFrom", "RangeFrom should not be empty!!!"},
        {"cboDebitProdRoundOff", "DebitProdRoundOff should be a proper value!!!"},
        {"txtPeriodTransLossAssets", "PeriodTransLossAssets should not be empty!!!"},
        {"txtPeriodTransDoubtfulAssets1", "PeriodTransDoubtfulAssets 1 should not be empty!!!"},
        {"txtPeriodTransDoubtfulAssets2", "PeriodTransDoubtfulAssets 2 should not be empty!!!"},
        {"txtPeriodTransDoubtfulAssets3", "PeriodTransDoubtfulAssets 3 should not be empty!!!"},
        {"txtMinPeriodsArrears", "MinPeriodsArrears should not be empty!!!"},
        {"txtFolioChargesAcc", "FolioChargesAcc should not be empty!!!"},
        {"rdoIsLimitDefnAllowed_Yes", "IsLimitDefnAllowed should be selected!!!"} ,
        {"txtInterestRebatePercentage","RebatePercentage should not empty"},
        {"cboInterestRebateCalculation","InterestRebateCalculation should Select  proper value!"},
        {"cboRebatePeriod","RebatePeriod should Select  proper value!"},
        {"txtFinYearStartingFromDD","FinYearStartingFromDD should not empty"},
        
        {"cboNoticeType","Notice Type should not empty"},
        {"cboIssueAfter","Issue After should not empty"},
        {"txtNoticeChargeAmt","Notice Charge Amt should not empty"},
        {"txtPostageAmt","Postage Charge Amt should not empty"},
        
        
        {"cboCommodityCode", "CommodityCode should be a proper value!!!"},
        {"cboGuaranteeCoverCode", "GuaranteeCoverCode should be a proper value!!!"},
        {"cboSectorCode", "SectorCode should be a proper value!!!"},
        {"cboHealthCode", "HealthCode should be a proper value!!!"},
        {"cboTypeFacility", "TypeFacility should be a proper value!!!"},
        {"cboPurposeCode", "PurposeCode should be a proper value!!!"},
        {"cboIndusCode", "IndustryCode should be a proper value!!!"},
        {"cbo20Code", "20Code should be a proper value!!!"},
        {"cboRefinancingInsti", "RefinancingInstitution should be a proper value!!!"},
        {"cboGovtSchemeCode", "GovtSchemeCode should be a proper value!!!"},
        {"cboSecurityDeails", "SecurityDeails should be a proper value!!!"},
        {"chkDirectFinance", ""},
        {"chkECGC", ""},
        {"chkQIS", ""}
   };

}
