/*
 * Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition.
 **
 *
 * IndividualCustMRB.java
 *
 * Created on Tue Nov 23 12:37:19 GMT+05:30 2004
 */

package com.see.truetransact.ui.employee;

import java.util.ListResourceBundle;

public class EmployeeMasterMRB extends ListResourceBundle {
    public EmployeeMasterMRB(){
    }
    
    public Object[][] getContents() {
        return contents;
    }
    
    static final String[][] contents = {
        
        {"txtEmployeeId", "Employee Id should not be empty!!!"},
        {"cboTitle", "Title should be a proper value!!!"},
        {"txtFirstName", "FirstName should not be empty!!!"},
        {"txtMiddleName", "MiddleName should not be empty!!!"},
        {"txtLastName", "LastName should not be empty!!!"},
        {"rdoGender_Male", "Gender should be selected!!!"},
        {"rdoGender_Female", "Gender should be selected!!!"},
        {"rdoMaritalStatus_Single", "MaritalStatus should be selected!!!"},
        {"rdoMaritalStatus_Married", "MaritalStatus should be selected!!!"},
        {"rdoFather", "Father or Husband should be selected!!!"},
        {"cboFsatherTitle", "Father Title should not be empty!!!"},
        {"txtFatherFirstName", "Father First Name should be a proper value!!!"},
        {"txtFatherMiddleName", " Father Middle Name should be a proper value!!!"},
        {"txtFatherLastName", " Father Last Name should be a proper value!!!"},
        {"cboMotherTitle", "Mather Title should not be empty!!!"},
        {"txtMotherFirstName", "Mother First Name should be a proper value!!!"},
        {"txtMotherMiddleName", " Mother Middle Name should be a proper value!!!"},
        {"txtMotherLastName", " Mother Last Name should be a proper value!!!"},
        {"tdtDateOfBirth", "Date Of Birth should not be empty!!!"},
        {"txtAge", "Age should not be empty!!!"},
        {"txtPlaceOfBirth", "Birth Place should be a proper value!!!"},
        {"cboReligion", "Religion should not be empty!!!"},
        {"cboCaste", "Caste should be a proper value!!!"},
        {"txtHomeTown", "Home Town should be a proper value!!!"},
        {"txtIDCardNoNo", "ID Card No should be a proper value!!!"},
        {"txtUIDNo", "UID No should be a proper value!!!"},
        {"txtPanNumber", "PanNumber should  be proper value!!!"},
        {"txtPFNumber", "PF Number should be a proper value!!!"},
        {"cboPFAcNominee", "PF A/c Nominee should be a proper value!!!"},
        {"tdtDateOfJoin", "Date of Join should be a proper value!!!"},
        {"tdtDateofRetirement", "Date of Retirement should be a proper value!!!"},
        {"cboAddressType", "AddressType should be a proper value!!!"},
        {"txtStreet", "Street should not be empty!!!"},
        {"txtArea", "Area should not be empty!!!"},
        {"cboCity", "City should be a proper value!!!"},
        {"cboState", "State should be a proper value!!!"},
        {"cboCountry", "Country should be a proper value!!!"},
        {"txtPincode", "Pincode should not be empty!!!"},
        {"txtPhoneNoCountryCode", "Land Line Country Code should not be empty!!!"},
        {"txtPhoneNoCode", "Land Line City Code should not be empty!!!"},
        {"txtPhoneNo", "Phone No should not be empty!!!"},
        {"txtMobileNoCountryCode", "Mobile Country Code should not be empty!!!"},
        {"txtMobileNoCode", "Mobile City Code should not be empty!!!"},
        {"txtMobileNo", "Mobile No should not be empty!!!"},
        {"txtPassportFirstName", "PassPort FirstName should not be empty!!!"},
        {"txtPassportMiddleName", "PassPort Middlename should not be empty!!!"},
        {"tdtPassportIssueDt", "PassPort IssueDate should not be empty!!!"},
        {"tdtPassportValidUpto", "PassPort Valid Upto should not be empty!!!"},
        {"txtPassportLastName", "PassPort LastName should not be empty!!!"},
        {"cboPassportTitle", "PassPort Title should not be empty!!!"},
        {"txtPassportNo", "PassPort Number should not be empty!!!"},
        {"txtPassportIssueAuth", "PassPort Issueing Authority should not be empty!!!"},
        {"cboPassportIssuePlace", "PassPort Issued Place should not be empty!!!"},
        {"cboEmpLevelEducation", "Education Level should be a proper value!!!"},
        {"txtNameOfSchool", "Name Of School/college should not be empty!!!"},
        {"tdtDateOfPassing", "Year of Passing should not be empty!!!"},
        {"cboSpecilization", "Academic Education Specilization should be a proper value!!!"},
        {"txtUniversity", "Academic Education University should not be empty!!!"},
        {"txtMarksScored", "Academic Education MarksScored should be a proper value!!!"},
        {"txtTotMarks", "Academic Education Total Marks should be a proper value!!!"},
        {"txtTotMarksPer", "Academic Education  % should be a proper value!!!"},
        {"cboGrade", "Academic Education Grade should not be empty!!!"},
        {"cboTechnicalQualificationType", "Technical Qualification Type should be a proper value!!!"},
        {"txtNameOfTechInst", "Technical Qualification College/Institution should be a proper value!!!"},
        {"tdtTechnicalQualificationDateOfPassing", "Technical Qualification Date Of Passing should not be empty!!!"},
        {"txtTechnicalQualificationMarksScored", " Technical Qualification Marks Scored should not be empty!!!"},
        {"cboTechnicalQualificationGrade", "Technical Qualification Grade should not be empty!!!"},
        {"cboTechnicalQualificationSpecilization", "Technical Qualification Specilization should not be empty!!!"},
        {"txtTechnicalQualificationUniversity", "Technical Qualification University should be a proper value!!!"},
        {"txtTechnicalQualificationTotMarks", "txt Technical Qualification Total Marks should be a proper value!!!"},
        {"txtTechnicalQualificationTotMarksPer", "Technical Qualification % should not be empty!!!"},
        {"cboLanguageType", "Language Type Password should not be empty!!!"},
        {"rdoLanguageRead", "Language should  be selected!!!"},
        {"rdoLanguageWrite", "Language should  be selected!!!"},
        {"rdoLanguageSpeak", "Language should  be selected!!!"},
        {"cboReletaionShip", "Dependent ReletaionShip should be a proper value!!!"},
        {"cboReleationFHTitle", "Dependent Title should be a proper value!!!"},
        {"txtReleationFHFirstName", "Dependent First Name should not be empty!!!"},
        {"txtReleationFHMiddleName", "Dependent Middle Name should not be empty!!!"},
        {"txtReleationFHLastName", "Dependent Last Name should not be empty!!!"},
        {"tdtRelationShipDateofBirth", "Dependent Date Of Birth should not be empty!!!"},
        {"cboFamilyMemEducation", "Dependent Education should not be empty!!!"},
        {"cboFamilyMemberProf", "Dependent Profession should not be empty!!!"},
        {"rdoDependentYes", "Dependent should not be empty!!!"},
        
        {"txtSsn", "Social Security Number should not be empty!!!"},
        {"cboEducationalLevel", "EducationalLevel should be a proper value!!!"} ,
        {"cboIntroType", "Introducer Type should be a proper value!!!"},
        {"txtAddrRemarks", "Remarks should not be empty!!!"},
        {"chkAddrVerified", "Address Verified should be Selected!!!"},
        {"chkPhVerified", "Phone Number verified should be selected!!!"},
        {"chkFinanceStmtVerified", "Obtain Financial Statement should be selected!!!"},
        {"tdtCrAvldSince", "Credit Availed Since Should not be empty"},
        {"txtRiskRate", "Enter the Risk Rate"},
        {"txtBranchId",  "BranchId should not be empty!!!"},
        {"txtGuardianNameNO","GuardianName should not be empty!!!"},
        {"cboRelationNO","Relationship should not be empty!!!"},
        {"txtGuardianACodeNO","Area Code should not be empty!!!"},
        {"txtGuardianPhoneNO","Phone Number should not be empty!!!"},
        {"txtGStreet","GuardianStreet should not be empty!!!"},
        {"txtGArea","GuardianArea should not be empty!!!"},
        {"cboGCountry","GuardianCountry should be selected!!!"},
        {"cboGCity","GuardianCity  should be selected!!!"},
        {"cboGState","GuardianState be selected!!!"},
        {"txtGPinCode","GuardianPinCode should not be empty!!!"},
        {"chkSentThanksLetter","SentThanksLetter should be selected!!!"},
        {"chkConfirmationfromIntroducer","ConfirmationfromIntroducer should be selected!!!"},
        {"txtStaffId","StaffId should not be empty!!!"},
        {"txtDesignation", "Designation should not be empty!!!"},
        
        
        {"cboAddrProof", "Address Proof should be a proper value!!!"},
        {"cboIdenProof", "Identity Proof should be a proper value!!!"},
        {"cboBloodGroup", "Blood group of the Employee!!! "},
        {"cboFarClass", "Farmer Classification should not be empty!!!"},
        {"txtKartha", "Kartha Name should not be empty!!!"},
        
        {"chkIncParticulars","Income Particulars should be Selected!!!"},
        {"txtIncIncome","Income in Income Particulars  not be empty!!!"},
        {"txtIncName","Name in Income Particulars should not be empty!!!"},
        {"cboIncPack","Package Income Particulars should not be empty!!!"},
        {"cboIncRelation","Relation Income Particulars should not be empty!!!"},
        {"chkLandDetails","Income Particulars should be Selected!!!"},
        {"txtLoc","Land Details Location  should not be empty!!!"},
        {"txtSrNo","Land Details Survey No  should not be empty!!!"},
        {"txtAreaInAcrs","Land Details Area In Acres  should not be empty!!!"},
        {"cboIrrigated","Land Details Irrigated  should not be empty!!!"},
        {"cboSrIrrigation","Land Details Source Of Irrigation should not be empty!!!"},
        {"txtVillage","Land Details Village  should not be empty!!!"},
        {"txtPo","Land Details Post Office  should not be empty!!!"},
        {"txtHobli","Land Details Hobli  should not be empty!!!"},
        {"cboTaluk","Land Details Taluk  should not be empty!!!"},
        {"cboDistrict","Land Details District  should not be empty!!!"},
        {"cboLandDetState","Land Details State  should not be empty!!!"},
        {"txtLandDetPincode","Land Details PinCode  should not be empty!!!"},
        {"txtGuardianAge","Guardian's AGE should Not Be Empty!!!!!"},
        {"txtMajorHealthProbeem","Employee Major Health Problem if any!!"},
        {"txtPhysicalyHandicap","Details If Physically handicapped!!"},
        {"cboDomicileState","Current domicile state of the employee!!"},
        {"txtDrivingLicenceNo","Driving Licence No!!"},
        {"txtEmailId","Enter Valid Email_ID!!"},
        {"txtEmpID","Enter Valid Email_ID!!"},
        {"txtDepIncomePerannum","Enter Valid Annual Income!!"},
        {"txtReleativeStaffId","Enter Valid Annual Income!!"},
        {"txtRelativesWorkingFirstName","Enter Valid First Name!!"},
        {"txtRelativesWorkingMiddleName","Enter Valid Middle Name!!"},
        {"txtWorkingDesignation","Enter Valid Designation!!"},
        {"txtRelativesWorkingBranch","Enter Working Branch!!"},
        {"cboRelativesWorkingReletionShip","Enter RelationShip!!"},
        {"txtDirectorFirstName","Enter Director's First Name!!"},
        {"txtDirectorMiddleName","Enter Director's Middle Name!!"},
        {"txtDirectorLastName","Enter the Last Name!!"},
        {"cboDirectorReleationShip","Enter the Relationship!!"},
        {"txtRelativesWorkingLastName","Enter the last Name!!"},
        {"cboWorkingDesignation","Enter the Designation!!"},
        {"cboRelativesWorkingBranch","Enter the Branch!!"},
        {"cboEmployeedWith","Enter the Employer!!"},
        
        //loans details
        
        {"cboEmployeeLoanType","Enter the Loan type!!"},
        {"cboLoanAvailedBranch","Ener the Availed Branch!!"},
        {"txtLoanSanctionRefNo","Enter the Loan sanction reference no"},
        {"tdtLoanSanctionDate","Enter the Loan sanction date!!"},
        {"txtLoanNo","Enter the loan number!!"},
        {"txtLoanAmount","Enter the loan amount!!"},
        {"txtLoanRateofInterest","enter the ROI!!"},
        {"txtLoanInstallmentAmount","Enter the Installment amount!!"},
        {"txtLoanNoOfInstallments","Enter the No of installments!!"},
        {"tdtLoanRepaymentStartDate","Enter the Loan Repayments start date!!"},
        {"tdtLoanCloserDate","Enter the Closer date!!"},
        {"rdoLoanPreCloserYes","Enter if pre Closer!!"},
        {"tdtLoanRepaymentEndDate","enter the Loan Repayment End date!!"},
        {"txtLoanRemarks","Enter the Remarks!!"},
        {"txtAccountNo","Enter the account no!!"},
        {"cboAccountType","Enter the account type!!"},
        {"cboSalaryCrBranch","Enter the Branch!!!"},
        
        //personal details
        
        {"rdoGradutionIncrementYes","Select if Graduation Increment!!"},
        {"rdoCAIIBPART1IncrementYes","Select if yes!!"},
        {"tdtGradutionIncrementReleasedDate","Enter Valid Date!!"},
        {"tdtCAIIBPART1IncrementReleasedDate","Enter valid date!!"},
        {"rdoCAIIBPART2Increment_Yes","Select If yes!!"},
        {"tdtCAIIBPART2IncrementReleasedDate","Enter Valid date!!"},
        {"rdoAnyOtherIncrement_Yes","Select if any other!!"},
        {"txtAnyOtherIncrementInstitutionName","Select if any other Institution name!!"},
        {"tdtAnyOtherIncrementReleasedDate","Enter Valid date!!"},
        {"tdtLastIncrmentDate","Enter Last Increment date!!"},
        {"txtLossPay_Months","Enter loss of Pay months!!"},
        {"txtLossOfpay_Days","Enter the loss of pay in days!!"},
        {"tdtNextIncrmentDate","Enter the next Increment date!!"},
        {"rdoSignature_Yes","Select if signature!!"},
        {"txtPresentBasic","Enter the present basic!!"},
        {"txtSignatureNo","Enter signature number!!"},
        {"txtSocietyMemberNo","Enter society member number!!"},
        {"cboSocietyMember","Choose which society!!"},
        {"cboUnionMember","choose Which union member!!"},
        {"txtClubName","Enter Club Name!!"},
        {"rdoClubMembership_YES","Select if U have club membership!!"},
        {"cboZonalOffice","Select Zonal Office!!"},
        {"cboPresentBranchId","Select Present Branch ID!!"},        
        {"tdtWorkingSince","Enter Date from which you have been working!"},
        {"cboReginoalOffice","Enter Regional office!!"},
        {"cboPresentGrade","ENter Present Grade!!"},
        {"cboDesignation","Enter designation!!"},
        {"txtProbationPeriod","Enter Probation Period!!"},
        {"cboProbationPeriod","Choose Period!!"},
        {"tdtConfirmationDate","Enter confirmation date!!"},
        {"tdtDateofRetirement","Enter date of retirement!!"},
        {"tdtDateOfJoin","Enter date of joining!!"},
        {"txtPFNumber","Enter PF NUmber!!"},
        {"cboPFAcNominee","Enter PF Account Nominee!!"},
        {"cboPromotedDesignation","Enter the Promoted Designation"},
        {"cboPromotionGradeValue","Enter the Promoted Grade"}
    };
    
}
