/*
 * Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition.
 **
 *
*/
package com.see.truetransact.ui.employee;
import java.util.ListResourceBundle;
public class EmployeeMasterRB extends ListResourceBundle {
    public EmployeeMasterRB(){
    }

    public Object[][] getContents() {
        return contents;
    }

    static final String[][] contents = {
         {"deleteWarningMsg", "Are you sure you want to delete the address selected?"},
        {"cDialogYes", "Yes"},
        {"CDialogNo", "No"},
        {"lblEmpID","Employee ID"},
        {"lblFirstName","First Name"},
        {"lblMiddleName","Middle Name"},
        {"lblLastName","Last Name"},
        {"lblGender","Gender"},
        {"rdoGender_Male","Male"},
        {"rdoGender_Female","FeMale"},
        {"lblMaritalStatus","Marital Status"},
        {"rdoMaritalStatus_Single","Single"},
        {"rdoMaritalStatus_Married","Married"},
        {"rdoFather","Father"},
        {"lblFatherFirstName","Father Name"},
        {"lblFatherMiddleName","Middle Name"},
        {"lblFatherLastName","Last Name"},
        {"lblMotheFirstName","Mother First Name"},
        {"lblMotheMiddleName","Middle Name"},
        {"lblMotherLastName","Last Name"},
        {"lblDateOfBirth","Date Of Birth"},
        {"lblAge","Age"},
        {"lblPlaceOfBirth","Place Of Birth"},
        {"lblReligion","Religion"},
        {"lblCaste","Caste"},
        {"lblHomeTown","Home Town"},
        {"lblIDCardNoNo","ID Card No"},
        {"lblUIDNo","Unique ID No"},
        {"lblPanNumber","Pan Number"},
//        {"lblPFNumber","PF Number"},
//        {"lblPFAcNominee","PF A/c Nominee"},
       // {"lblDateOfJoin","Joining Date"},
        //{"lblDateofRetirement","Retirement Date"},
        {"lblAddressType","Address Type"},
        {"lblStreet","Street"},
        {"lblArea","Area"},
        {"lblCity","City"},
         {"phoneDetailsMsg", " Do you want to enter the Phone Details for this Address?"},
        {"lblState","State"},
        {"lblCountry","Country"},
        {"lblPincode","Pin Code"},
        {"lblPhoneNo","Land Line No"},
        {"lblMobileNo","Mobile No"},
        {"btnContactNew","New"},
        {"btnContactDelete","Delete"},
        {"btnContactAdd","Save"},
        {"btnPhotoLoad","Load"},
        {"btnPhotoRemove","Remove"},
        {"btnSignLoad","Load"},
        {"btnSignRemove","Remove"},
        {"panSign","Remove"},
        {"panSign","Signature"},
        {"panPhoto","Photograph"},
        {"lblPassportFirstName","First Name"},
        {"lblPassportMiddleName","Middle Name"},
        {"lblPassportLastName","Last Name"},
        {"lblPassportIssueAuth","Issue Authority"},
        {"lblPassportIssuePlace","Place Of Issue"},
        {"lblPassportNo","Passport No"},
        {"lblPassportIssueDt","Issued Date"},
        {"lblPassportValidUpto","Valid Upto"},
        {"btnClearPassport","Clear"},
        {"lblSign",""},
        {"btnClose",""},
        {"btnAuthorize",""},
        {"lblMsg",""},
        {"lblSpace4"," "},
        {"lblSpace2"," "},
        {"lblSpace3"," "},
        {"lblEmpLevelEducation", "Level Education"},
        {"lblNameOfSchool", "School/College"},
        {"lblDateOfPassing", "Year Of Passing"},
        {"lblSpecilization", "Specilization"},
        {"lblUniversity", "University"},
        {"lblMarksScored", "Marks Scored"},
        {"lblTotMarks", "Total Marks"},
        {"lblTotMarksPer", "%"},
        {"lblGrade", "Grade"},
        {"btnAcademicEducationDetDel", "Delete"},
        {"btnAcademicEducationDetSave", "Save"},
        {"btnAcademicEducationDetNew", "New"},
        {"lblTechnicalQualificationType", "Qualification Type"},
        {"lblNameOfTechInst", "Institution"},
        {"lblTechnicalQualificationDateOfPassing", "Year of Passing"},
//        {"lblTechnicalQualificationMarksScored", "Marks Scored"},
        {"lblTechnicalQualificationGrade", "Grade"},
        {"lblTechnicalQualificationSpecilization", "Specilization"},
        {"lblTechnicalQualificationUniversity", "University"},
        {"lblTechnicalQualificationTotMarks", "Total Marks"},
        {"lblTechnicalQualificationTotMarksPer", "%"},
        {"btnTechnicalQualificationDetNew", "New"},
        {"btnTechnicalQualificationDetSave", "Save"},
        {"btnTechnicalQualificationDetDel", "Delete"},
        {"lblLanguageType", "Language Type"},
        {"rdoLanguageRead", "Read"},
        {"rdoLanguageWrite", "Write"},
        {"rdoLanguageReadeSpeak", "Speak"},
        {"btnLanguageDetNew", "New"},
        {"btnLanguageDetSave", "Save"},
        {"btnLanguageDetDel", "Delete"},
        {"lblReletaionShip", "RelationShip"},
        {"lblReleationFHFirstName", "Fist Name"},
        {"lblReleationFHMiddleName", "Middle Name"},
        {"lblReleationFHLastName", "Last Name"},
        {"btnLanguageDetNew", "New"},
        {"btnLanguageDetSave", "Save"},
        {"btnLanguageDetDel", "Delete"},
        {"lblRelationShipDateofBirth", "Date of Birth"},
        {"lblFamilyMemEducation", "Education"},
        {"lblReleationFHMiddleName", "Middle Name"},
        {"lblFamilyMemberProf", "Profession"},
        {"rdoDependentYes", "Yes"},
        {"rdoDependentNo", "No"},
        {"btnfamiyDetSave", "Save"},
        {"btnfamiyDetDel", "Delete"},
        {"btnfamiyDetNew", "New"},
          {"btnReject", ""},
        {"btnEdit", ""},
        {"btnPrint", ""},
        {"btnException", ""},
        {"btnSave", ""},
        {"lblPhoto", ""},
        {"btnDelete", ""},
        {"btnNew", ""},
        {"lblBloodGroup", "Blood Group"},
        {"lblMajorHealthProbeem", "If Major Health Problem"},
        {"lblPhysicalHandicap", "If Physically Handicaped"},
        {"lblDrivingLicenceNo", "Driving Licence No"},
        {"lblDLRenewalDate", "DL Renewal Date"},
        {"lblEmailId", "Email Id"},
        {"lblDomicileState", "Domicile State"},
        {"blGradutionIncrementYesNo", "Graduation Increment Released"},
        {"rdoGradutionIncrementYes", "Yes"},
        {"rdoGradutionIncrementNo", "No"},
//        {"lblGradutionIncrementReleasedDate", "Graduation Increment Released Date"},
//        {"lblCAIIBPART1IncrementYesNo", "CAIIB Part1 Increment Released"},
        {"rdoCAIIBPART1IncrementYes", "Yes"},
        {"rdoCAIIBPART1IncrementNo", "No"},
        {"rdoCAIIBPART1IncrementYes", "Yes"},
//        {"lblCAIIBPART1IncrementReleasedDate", "CAIIB Part 1 Increment Released Date"},
//        {"lblCAIIBPART2IncrementYesNo", "CAIIB Part2 Increment Released"},
        {"rdoCAIIBPARTIncrementYes", "Yes"},
        {"rdoCAIIBPARTIncrementNo", "No"},
//        {"lblCAIIBPART2IncrementReleasedDate", "CAIIB Part 2 Increment Released Date"},
//        {"lblAnyOtherIncrementYesNo", "Increment Released Any Other Qualification"},
        {"rdoAnyOtherIncrement_Yes", "Yes"},
        {"rdoAnyOtherIncrement_No", "No"},
//        {"lblAnyOtherIncrementInstitutionName", "Description of Qualification"},
//        {"lblAnyOtherIncrementReleasedDate", "Released Date"},
//        {"lblPresentBasic", "Present Basic Pay"},
//        {"lblLastIncrmentDate", "Last Incement Date"},
//        {"lblAnyLossOfPay", "Loss of Pay"},
//        {"lblLossPay_Months", "Months"},
//        {"lblLossOfpay_Days", "Days"},
//        {"lblNextIncrmentDate", "Next Incement Date"},
//        {"lblSigNoYesNo", "Specimen Signature Lodged"},
        {"rdoSignature_Yes", "Yes"},
        {"rdoSignature_No", "No"},
//        {"lblSignatureNo", "Signing Power No"},
//        {"lblUnionMember", "Union Member If any"},
//        {"lblSocietyMember", "Society Member if Any"},
//        {"lblSocietyMemberNo", "Society MemberShip No"},
//        {"lblClubMembership", "ClubMembership"},
//        {"lblClubName", "Club Name"},
//        {"rdoClubMembership_YES", "Yes"},
//        {"rdoClubMembership_No", "No"},
        {"lblPhoneNumber", "Phone Number"},
        {"lblPhoneType", "Phone Type"},
        {"lblAreaCode", "Area Code"},
        //{"lblDateOfJoin", "Joining Date"},
//        {"lblProbationPeriod", "Probation Period"},
//        {"lblConfirmationDate", "Confirmation Date"},
        //{"lblDateofRetirement", "Date of Retirement"},
        {"lblPFNumber", "PF Number"},
//        {"lblPresentBranchId", "Branch Code"},
//        {"lbReginoalOffice", "DO/RO Code"},
        {"lblZonalOffice", "ZO/CO Code"},
//        {"lblWorkingSince", "Working Since"},
//        {"lblDesignation", "Designation"},
//        {"lblPresentGrade", "Grade"},
//        {"lblAccountType", "Account Type"},
//        {"lblAccountNo", "Account No"},
//        {"lblSalaryCrBranch", "Branch Code"},
        {"lblEmployeedWith", "Employed With"},
        {"lblLiableForTransfer", "Liable For Transfer"},
        {"rdoLiableForTransferYes", "Yes"},
        {"rdoLiableForTransferNo", "No"},
        {"lblDepIncomePerannum", "Income per annum"},
//        {"lblEmployeeLoanType", "Loan Type"},
//        {"lblLoanAvailedBranch", "Loan Availed Branch"},
//        {"lblLoanSanctionRefNo", "Sanction Ref No"},
//        {"lblLoanSanctionDate", "Sanction Date"},
//        {"lblLoanNo", "Loan No"},
//        {"lblLoanAmount", "Loan Amount"},
//        {"lblLoanRateofInterest", "ROI"},
//        {"lblLoanNoOfInstallments", "Repayment Installments"},
//        {"lblLoanInstallmentAmount", "Installment Amount"},
//        {"lblLoanRepaymentStartDate", "Repayment Start Date"},
//        {"lblLoanRepaymentEndDate", "Repayment End  Date"},
//        {"lblLoanPreCloserYesNo", "Loan Pre Close"},
//        {"lblLoanCloserDate", "Loan Closer Date"},
        {"rdoLoanPreCloserYes", "Yes"},
        {"rdoLoanPreCloserNo", "No"},
//        {"lblLoanRemarks", "Remarks"},
//        {"lblGradutionIncrementYesNo", "Graduation Increment Released"},
        {"rdoCAIIBPART2Increment_No", "No"},
        {"lblReleativeStaffId", "Staff ID"},
        {"rdoHusband", "Husband"},
        {"lblRelativesWorkingFirstName", "First Name"},
        {"lblRelativesWorkingMiddleName", "Middle Name"},
        {"lblRelativesWorkingLastName","Last Name"},
        {"lblWorkingDesignation","Designation"},
        {"lblRelativesWorkingBranch","Working Branch"},
        {"lblRelativesWorkingReletionShip","Relationship"},
        {"lblDirectorFirstName","First Name"},
        {"lblDirectorMiddleName","Middle Name"},
        {"lblDirectorLastName","Last Name"},
        {"lblDirectorReleationShip","RelationShip"},
        
        //educational detaisl
        {"btnClose", ""},
        {"lblTechnicalQualificationMarksScored", "Marks Scored"},
        {"btnLanguageDetDel", "Delete"},
        {"rdoLanguageRead", "Read"},
        {"btnAcademicEducationDetSave", "Save"},
        {"btnAuthorize", ""},
        {"lblTechnicalQualificationTotMarks", "Total Marks"},
        {"lblMsg", ""},
        {"lblUniversity", "Name Of the University"},
        {"lblSpace4", "     "},
        {"lblTechnicalQualificationType", "Technical Qualification"},
        {"panAcademicEducation", "Academic Education Details"},
        {"lblSpace2", "     "},
        {"lblSpace3", "     "},
        {"panLanguageDate", ""},
        {"lblSpace1", " Status :"},
        {"btnTechnicalQualificationDetSave", "Save"},
        {"panLanguageTable", ""},
        {"btnReject", ""},
        {"btnEdit", ""},
        {"btnTechnicalQualificationDetDel", "Delete"},
        {"lblTotMarks", "Total Marks"},
        {"btnDeletedDetails", ""},
        {"panAcademicEducation2", "Technical Qualification Details"},
        {"btnPrint", ""},
        {"btnAcademicEducationDetNew", "New"},
        {"lblTechnicalQualificationUniversity", "Name Of the University"},
        {"panCustomer", ""},
        {"lblNameOfSchool", "School /College"},
        {"lblTechnicalQualificationSpecilization", "Specialization"},
        {"btnException", ""},
        {"lblTechnicalQualificationDateOfPassing", "Year Of Passing"},
        {"lblLanguageType", "Language Type"},
        {"btnSave", ""},
        {"lblTotMarksPer", "Marks %"},
        {"lblGrade", "Grade"},
        {"lblEmpLevelEducation", "Level  of Education"},
        {"lblStatus", "                      "},
        {"rdoLanguageReadeSpeak", "Speak"},
        {"btnAcademicEducationDetDel", "Delete"},
        {"btnView", ""},
        {"btnLanguageDetNew", "New"},
        {"lblSpecilization", "Specialization"},
        {"lblSpace5", "     "},
        {"panLanguageStatus", "Language Known Details"},
        {"btnDelete", ""},
        {"lblTechnicalQualificationGrade", "Grade"},
        {"btnNew", ""},
        {"lblMarksScored", "Marks Scored"},
        {"lblDateOfPassing", "Year Of Passing"},
        {"btnCancel", ""},
        {"btnLanguageDetSave", "Save"},
        {"lblTechnicalQualificationTotMarksPer", "Marks %"},
        {"lblNameOfTechInst", "College/Institution"},
        {"btnTechnicalQualificationDetNew", "New"},
        {"rdoLanguageWrite", "Write"}, 
        
        //LOAN DETAILS  
        {"lblLoanRepaymentEndDate", "Repayment End  Date"},
        {"lblAccountType", "Prod Type"},
        {"lblLoanAmount", "Loan Amount"},
        {"btnClose", ""},
        {"lblEmployeeLoanType", "Prod Type"},
        {"btnAuthorize", ""},
        {"btnOprativeDetailsDetSave", "Save"},
        {"lblMsg", ""},
        {"lblLoanRepaymentStartDate", "Repayment Start Date"},
        {"lblSpace4", "     "},
        {"rdoLoanPreCloser_No", "No"},
        {"lblSpace2", "     "},
        {"btnTermLoansDetDel", "Delete"},
        {"lblSpace3", "     "},
        {"lblSpace1", " Status :"},
        {"btnReject", ""},
        {"btnOprativeDetailsDetDel", "Delete"},
        {"btnEdit", ""},
        {"panOprativeDetails", ""},
        {"lblLoanRemarks", "Remarks"},
        {"lblLoanInstallmentAmount", " Installment Amount"},
        {"lblLoanNoOfInstallments", "Repayment Installments"},
        {"btnDeletedDetails", ""},
        {"btnTermLoansDetSave", "Save"},
        {"lblSalaryCrBranch", "Working At"},
        {"rdoLoanPreCloser_Yes", "Yes"},
        {"btnPrint", ""},
        {"panCustomer", ""},
        {"lblLoanNo", "Loan No"},
        {"lblAccountNo", "Account No"},
        {"btnAccountNo", ""},
        {"btnTermLoansDetNew", "New"},
        {"btnException", ""},
        {"lblLoanSanctionRefNo", "Sanction Ref No"},
        {"panLanguageTable1", ""},
        {"btnSave", ""},
        {"lblStatus", "                      "},
        {"lblLoanSanctionDate", "Sanction Date"},
        {"btnView", ""},
        {"btnOprativeDetailsDetNew", "New"},
        {"lblSpace5", "     "},
        {"lblLoanPreCloserYesNo", "Loan Pre Close"},
        {"btnDelete", ""},
        {"lblLoanCloserDate", "Loan Closer Date"},
        {"lblLoanRateofInterest", "Rate of Interest"},
        {"panLanguageStatus1", "Salary Credit Account Details"},
        {"lblLoanAvailedBranch", "Loan Availed Branch"},
        {"btnNew", ""},
        {"btnCancel", ""},
        {"panEmployeeLoan", "Loans/Advance Details"},
       
        
        //personal detais
         {"btnClose", ""},
        {"lblDateofRetirement", "Retirement Date"},
        {"lblGradutionIncrementReleasedDate", "Graduation Increment Released Date"},
        {"lblConfirmationDate", "Confirmation Date"},
        {"lblSignatureNo", "Signing Power No"},
        {"rdoCAIIBPART1Increment_No", "No"},
        {"rdoGradutionIncrement_No", "No"},
        {"btnAuthorize", ""},
        {"lblMsg", ""},
        {"lblSpace4", "     "},
        {"lblCAIIBPART2IncrementReleasedDate", "CO-Op Diploma Increment Released Date"},
        {"lblPFNumber", "PF A/c Number"},
        {"lblSpace2", "     "},
        {"lblZonalOffice", "ZO/CO ID"},
        {"lblSpace3", "     "},
        {"rdoCAIIBPART2Increment_Yes", "Yes"},
        {"rdoSignature_Yes", "Yes"},
        {"lblSocietyMemberNo", "Society MemberShip No"},
        {"lblSpace1", " Status :"},
        {"rdoClubMembership_YES", "Yes"},
        {"rdoCAIIBPART2Increment_No", "No"},
        {"lblPresentBranchId", "Branch Id"},
        {"lblCAIIBPART1IncrementReleasedDate", "CAIIB Increment Date"},
        {"lblPresentGrade", "Grade"},
        {"rdoAnyOtherIncrement_No", "No"},
        {"btnReject", ""},
        {"btnEdit", ""},
        {"lblClubMembership", "ClubMembership"},
        {"lblPresentBasic", "Present Basic Pay"},
        {"lblLossPay_Months", "Months"},
        {"lblNextIncrmentDate", "Next Incement Date"},
        {"lblCAIIBPART2IncrementYesNo", "CO-Operative Diploma Increment Released"},
        {"btnDeletedDetails", ""},
        {"btnPrint", ""},
        {"panCustomer", ""},
        {"panPresentWorkingDetails", "Present Working Details"},
        {"lblSigNoYesNo", "Specimen Signature Lodged"},
        {"lblDateOfJoin", "Joining Date"},
        {"lblPFAcNominee", "PF A/c Nominee"},
        {"lblAnyOtherIncrementYesNo", "Special Increment"},
        {"lbReginoalOffice", "DO/RO ID"},
        {"rdoAnyOtherIncrement_Yes", "Yes"},
        {"lblDesignation", "Designation"},
        {"btnException", ""},
        {"lblProbationPeriod", "Probation Period"},
        {"lblAnyOtherIncrementInstitutionName", "Special Increment Release"},
        {"panOfficeDetails", "Present Details"},
        {"btnSave", ""},
        {"rdoClubMembership_No", "No"},
        {"lblStatus", "                      "},
        {"btnView", ""},
        {"lblLastIncrmentDate", "Last Incement Date"},
        {"lblSpace5", "     "},
        {"btnDelete", ""},
        {"rdoCAIIBPART1IncrementYes", "Yes"},
        {"lblCAIIBPART1IncrementYesNo", "CAIIB Increment"},
        {"lblAnyLossOfPay", "Loss of Pay"},
        {"lblLossOfpay_Days", "Days"},
        {"lblClubName", "Club Name"},
        {"lblSocietyMember", "If Society Member"},
        {"btnNew", ""},
        {"rdoSignature_No", "No"},
        {"btnCancel", ""},
        {"rdoGradutionIncrement_Yes", "Yes"},
        {"lblUnionMember", "If Union Member"},
        {"lblGradutionIncrementYesNo", "Graduation Increment Released"},
        {"lblAnyOtherIncrementReleasedDate", "Released Date"},
        {"lblWorkingSince", "Working Since"},
        {"rdoCAIIBPART2Increment_Yes","Yes"},
        {"lblPromotionDesignation","Present Designation"},
        {"lblPromotedDesignation","Promoted As"}
        
   };

}
