/*
 * Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition. 
 * 
 * frmBorrowings.java
 *
 * Created on September 12, 2011, 10:33 AM
 */

package com.see.truetransact.ui.generalbodydetails;
import com.see.truetransact.clientutil.ClientUtil;
/**
 *
 * @author  user
 */
public class frmBorrowings extends com.see.truetransact.uicomponent.CFrame implements java.util.Observer  {
    
    private GeneralBodyDetailsOB observable;
    /** Creates new form panBorrowings */
    public frmBorrowings() {
        initComponents();
        initIntCompnents();
  //       setMaxLengths();
        observable = new GeneralBodyDetailsOB();
       // observable.addObserver(this);
    }
    private void setMaxLengths() {
       // txtUserID.setAllowAll(true);
       // txtPwd.setAllowAll(true);
        this.setBounds(0,0, 1350, 700);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        cButton1 = new com.see.truetransact.uicomponent.CButton();
        cDesktopPane1 = new com.see.truetransact.uicomponent.CDesktopPane();
        cButton3 = new com.see.truetransact.uicomponent.CButton();
        cButton4 = new com.see.truetransact.uicomponent.CButton();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        cButton1.setText("New Borrwing");
        cButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        getContentPane().add(cButton1);
        cButton1.setBounds(10, 10, 130, 27);

        getContentPane().add(cDesktopPane1);
        cDesktopPane1.setBounds(0, 0, 0, 0);

        cButton3.setText("Borrowing Disbursal");
        cButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        getContentPane().add(cButton3);
        cButton3.setBounds(10, 50, 130, 27);
        cButton3.getAccessibleContext().setAccessibleName("Borrowing Disbursal");

        cButton4.setText("Borrowing funds");
        cButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        getContentPane().add(cButton4);
        cButton4.setBounds(10, 90, 130, 27);

    }//GEN-END:initComponents
    public void initIntCompnents()
    {
      ifrNewBorrowings=new GeneralBodyDetailsUI();
      //ifrNewBorrowings.setVisible(true);
      getContentPane().add(ifrNewBorrowings);
      ifrNewBorrowings.setBounds(160,10,1000,600);
      
    //  ifrBorrowingfunds=new ifrBorrowingfunds();
    //   getContentPane().add(ifrBorrowingfunds);
    //  ifrBorrowingfunds.setBounds(160,10,1150,650);
      
//      ifrDisbursal=new panDisbursal();
//       getContentPane().add(ifrDisbursal);
//      ifrDisbursal.setBounds(160,10,1000,600);
//      
//       ifrRepIntCls=new panRepaymentInt();
//       getContentPane().add(ifrRepIntCls);
//      ifrRepIntCls.setBounds(160,10,1000,600);
    }
    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
         //ClientUtil.displayAlert(evt.);
       // ClientUtil.displayAlert(evt.getActionCommand());
   //  initIntCompnents();
        if(evt.getActionCommand()=="New Borrwing")
        {
          // ifrNewBorrowings=new ifrNewBorrowing();
            ClientUtil.displayAlert("INNN");
            ifrNewBorrowings=new GeneralBodyDetailsUI();
      ifrNewBorrowings.setVisible(true);
      getContentPane().add(ifrNewBorrowings);
      ifrNewBorrowings.setBounds(160,10,1000,600);
      
          ifrNewBorrowings.setVisible(true);
        //   ifrBorrowingfunds.setVisible(false);
     //      ifrRepaymentInterest.setVisible(false);
       //  ifrRepaymentInterest.dispose();
//          ifrRepIntCls.dispose();
//          ifrDisbursal.dispose();
        }
        
//         if(evt.getActionCommand()=="Borrowing Disbursal")
//        {
//           // ifrNewBorrowings=new ifrNewBorrowing();
//          //  ClientUtil.displayAlert("INNN");
////             ifrDisbursal=new panDisbursal();
////       getContentPane().add(ifrDisbursal);
////      ifrDisbursal.setBounds(160,10,1150,650);
////            ifrDisbursal.setVisible(true);
//          ifrNewBorrowings.setVisible(false);
//          ifrNewBorrowings.dispose();
//      //    ifrRepIntCls.setVisible(false);
//         // ifrRepIntCls.dispose();
//       //  ifrBorrowingfunds.setVisible(false);
//        }
//         if(evt.getActionCommand()=="Borrowing funds")
//        {
//            System.out.println("HUIIIOOOOOOOOO");
//           // ifrNewBorrowings=new ifrNewBorrowing();
//          //  ClientUtil.displayAlert("INNN");
////             ifrRepIntCls=new panRepaymentInt();
////       getContentPane().add(ifrRepIntCls);
////      ifrRepIntCls.setBounds(160,10,1150,650);
////            ifrRepIntCls.setVisible(true);
//          ifrNewBorrowings.setVisible(false);
//          ifrNewBorrowings.dispose();
////          ifrDisbursal.setVisible(false);
////          ifrDisbursal.dispose();
//       //  ifrBorrowingfunds.setVisible(false);
//        }
    }//GEN-LAST:event_btnNewActionPerformed
private void exitForm(java.awt.event.WindowEvent evt) {
        System.exit(0);
    }
   public static void main(String args[]) throws Exception {
        new frmBorrowings().show();
    }
    public void update(java.util.Observable observable, Object obj) {
    }    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.see.truetransact.uicomponent.CButton cButton1;
    private com.see.truetransact.uicomponent.CButton cButton3;
    private com.see.truetransact.uicomponent.CButton cButton4;
    private com.see.truetransact.uicomponent.CDesktopPane cDesktopPane1;
    // End of variables declaration//GEN-END:variables
    public GeneralBodyDetailsUI ifrNewBorrowings;
    // public  ifrBorrowingfunds ifrBorrowingfunds;
//     public BorrowingTrans ifrRepaymentInterest;
//     public panDisbursal ifrDisbursal;
//     public panRepaymentInt ifrRepIntCls;
}
