/*
 * Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition. 
 * 
 * TTSplashScreen.java
 *
 * Created on January 16, 2004, 11:33 AM
 */

package com.see.truetransact.ui.login;

import javax.swing.Timer;
import javax.swing.Action;
import javax.swing.AbstractAction;

import java.awt.event.ActionEvent;

import java.awt.Toolkit;
import java.awt.Dimension;
import com.see.truetransact.ui.TrueTransactMain;
/**
 *
 * @author  bala
 */
public class TTSplashScreen extends javax.swing.JWindow {
    
    private Timer timer;
    
    /** Creates new form TTSplashScreen */
    public TTSplashScreen() { 
        initComponents();
//        setPreferredSize(new java.awt.Dimension(650,450));
        initSetup();
    }
    
    private void initSetup() {
        timer = new Timer(20, createLoadAction()); 
        timer.start(); 
    }

    public Action createLoadAction() {
        return new AbstractAction("Load Action") { 
            public void actionPerformed (ActionEvent e) { 
                if(pbrProgress.getValue() < pbrProgress.getMaximum()) { 
                    pbrProgress.setValue(pbrProgress.getValue() + 1); 
                } else { 
                    if(timer != null) { 
                        timer.stop(); 
                        timer = null; 
                    } 
                } 
            }
        };
    } 
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pbrProgress = new com.see.truetransact.uicomponent.CProgressBar();
        lblSplashImg = new com.see.truetransact.uicomponent.CLabel();

        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(570, 240));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(null);

        pbrProgress.setForeground(new java.awt.Color(246, 116, 50));
        pbrProgress.setMaximumSize(new java.awt.Dimension(570, 7));
        pbrProgress.setMinimumSize(new java.awt.Dimension(570, 7));
        pbrProgress.setPreferredSize(new java.awt.Dimension(570, 7));
        getContentPane().add(pbrProgress);
        pbrProgress.setBounds(0, 230, 500, 7);

        lblSplashImg.setBackground(new java.awt.Color(34, 104, 149));
        lblSplashImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/see/truetransact/ui/images/TT_core_banking_splash.jpg"))); // NOI18N
        lblSplashImg.setMaximumSize(new java.awt.Dimension(794, 301));
        lblSplashImg.setMinimumSize(new java.awt.Dimension(794, 301));
        lblSplashImg.setOpaque(true);
        lblSplashImg.setPreferredSize(new java.awt.Dimension(794, 301));
        getContentPane().add(lblSplashImg);
        lblSplashImg.setBounds(0, 0, 630, 301);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        Dimension frameSize;

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        /* Create the splash screen */
        TTSplashScreen objTTSplashScreen = new TTSplashScreen();
        objTTSplashScreen.pack();
        TrueTransactMain.showWindow (objTTSplashScreen);
        try {
                Thread.sleep(3000);
        } catch (InterruptedException ie) {};
        objTTSplashScreen.dispose();        

            LoginUI loginUI = new LoginUI();
         //   loginUI.setVisible(true);
          //  loginUI.show();
            frameSize = loginUI.getSize();
            if (frameSize.height > screenSize.height){
                frameSize.height = screenSize.height;
            }
            if (frameSize.width > screenSize.width){
                frameSize.width = screenSize.width;
            }
            loginUI.setLocation((screenSize.width - frameSize.width) / 2,
            (screenSize.height - frameSize.height) / 2 - 60);
            loginUI.show();

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.see.truetransact.uicomponent.CLabel lblSplashImg;
    private com.see.truetransact.uicomponent.CProgressBar pbrProgress;
    // End of variables declaration//GEN-END:variables
}
