/*
 * Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition.
 **
 *
 * CMandatoryDialog.java
 *
 * Created on September 5, 2003, 11:58 AM
 */

package com.see.truetransact.clientutil;

import com.see.truetransact.commonutil.CommonConstants;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author  karthik, Bala
 */
public class CMandatoryDialog extends com.see.truetransact.uicomponent.CDialog {
    public static final int WARNING = 0;
    public static final int INFO = 1;
    
    /** Creates new form CMandatoryDialog */
    public CMandatoryDialog() {
        initComponents();
        setupInit();
    }
    
    public CMandatoryDialog(int image) {
        initComponents();
        if (image > 0) {
            if (image == 1) {
                lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/see/truetransact/ui/images/TT_INFO.jpg")));
            }
        }
        setupInit();
    }    
    
    private void setupInit() {
        setNames();
        setTitle("Required Fields");
        showInCenter();
    }
    
    private void showInCenter() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        
        Dimension frameSize = getSize();
        if (frameSize.height > screenSize.height){
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width){
            frameSize.width = screenSize.width;
        }
        setLocation((screenSize.width - frameSize.width) / 2,
            (screenSize.height - frameSize.height) / 2 - 60);
        
        setModal(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        panMessage = new com.see.truetransact.uicomponent.CPanel();
        srpMessage = new com.see.truetransact.uicomponent.CScrollPane();
        txaMessage = new com.see.truetransact.uicomponent.CTextArea();
        lblImg = new com.see.truetransact.uicomponent.CLabel();
        btnOK = new com.see.truetransact.uicomponent.CButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        panMessage.setLayout(new java.awt.GridBagLayout());

        panMessage.setMinimumSize(new java.awt.Dimension(400, 200));
        panMessage.setPreferredSize(new java.awt.Dimension(400, 200));
        txaMessage.setEditable(false);
        txaMessage.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 13));
        srpMessage.setViewportView(txaMessage);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panMessage.add(srpMessage, gridBagConstraints);

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/see/truetransact/ui/images/Error.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        panMessage.add(lblImg, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 6, 4);
        getContentPane().add(panMessage, gridBagConstraints);

        btnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/see/truetransact/ui/images/TT_CLOSE.gif")));
        btnOK.setText("Ok");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 6, 4);
        getContentPane().add(btnOK, gridBagConstraints);

        pack();
    }//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // Add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnOKActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        this.dispose();
    }//GEN-LAST:event_exitForm
    
    private void setNames(){
        btnOK.setText(CommonConstants.OK);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new CMandatoryDialog().show();
    }
    
    /** Getter for property message.
     * @return Value of property message.
     *
     */
    public String getMessage() {
        return this.message;
    }    
    
    /** Setter for property message.
     * @param message New value of property message.
     *
     */
    public void setMessage(String message) {
        this.message = message;
        txaMessage.setText(message);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.see.truetransact.uicomponent.CButton btnOK;
    private com.see.truetransact.uicomponent.CLabel lblImg;
    private com.see.truetransact.uicomponent.CPanel panMessage;
    private com.see.truetransact.uicomponent.CScrollPane srpMessage;
    private com.see.truetransact.uicomponent.CTextArea txaMessage;
    // End of variables declaration//GEN-END:variables

    /** Holds value of property message. */
    private String message;    
    
}
