/*
 * Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition.
 * 
 *
 * DepositsProductRB.java
 *
 * Created on Thu Jul 08 12:54:14 IST 2004
 */

package com.see.truetransact.ui.product.deposits;

import java.util.ListResourceBundle;

public class DepositsProductRB extends ListResourceBundle {
    public DepositsProductRB(){
    }
    
    public Object[][] getContents() {
        return contents;
    }
    
    static final String[][] contents = {
        {"rdoSystemCalcValues_No", "Seperate Printing Window"},
        {"btnClose", ""},
        {"lblMaxNoOfPartialWithdrawalAllowed", "Maximum Number of Partial Withdrawal in a Year"},
        {"rdoIntPayableOnExcessInstal_No", "No"},
        {"lblOperatesLike", "Operates Like"},
        {"rdoCanReceiveExcessInstal_yes", "Yes"},
        {"lblMinDepositPeriod", "Minimum Deposit Period"},
        {"lblInterestAfterMaturity", "Interest to be paid after Maturity"},
        {"lblCalcMaturityValue", "Calculate Maturity Value"},
        {"btnTDSGLAcctHd", ""},
        {"lblMaxNopfTimes", "Max No. of Times Auto Renewal Allowed"},
        {"lblProdCurrency", "Product Currency"},
        {"btnAuthorize", ""},
        {"lblMsg", ""},
        {"rdoPartialWithdrawalAllowed_No", "No"},
        {"lblIntDebitPLHead", "Interest Debit P & L Head"},
        {"lblSystemCalcValues", "Certificate Printing Priority"},
        {"rdoInterestAfterMaturity_No", "No"},
        {"rdoRecurringDepositToFixedDeposit_No", "No"},
        {"rdoCalcMaturityValue_No", "No"},
        {"rdoInstallmentInRecurringDepositAcct_Yes", "Fixed"},
        {"rdoCalcTDS_Yes", "Yes"},
        {"rdoRegular", "Normal"},
        {"rdoNRO", "NRO"},
        {"rdoNRE", "NRE"},
        
        {"rdoIntProvisioningApplicable_No", "No"},
        {"lblPenaltyOnLateInstallmentsChargeble", "Penalty on Delayed Installments"},
        {"lblDelayedFromAmt","From Installment Amount"},
        {"lblDelayedToAmt","To Installment Amount"},
        {"lblDelayedChargesAmt","Penalty Charges"},
        {"lblDelayedChargesDet","Per Rs 100 / Per Month Delay"},
        {"tblInterest1","From Amt"},
        {"tblInterest2","To Amt"},
        {"tblInterest3","Delayed Charge Amount"},
        
        {"lblIntCompoundingFreq", "Interest Compounding Frequency"},
        {"lblInterestOnMaturedDepositsDays", "Days"},
        {"lblCalcTDS", "Calculate TDS"},
        {"rdoInterestAfterMaturity_Yes", "Yes"},
        {"lblPrematureWithdrawalDays", "Days"},
        {"lblNextInterestAppliedDate", "Next Interest Applied Date"},
        {"rdoWithdrawalWithInterest_Yes", "Yes"},
        {"lblDepositPerUnit", "Deposit Per Unit"},
        {"lblMinIntToBePaid", "Minimum Interest to be Paid"},
        {"lblTermDeposit", "Term Deposit can be Offered as Security to OD"},
        {"rdoRenewalOfDepositAllowed_Yes", "Yes"},
        {"btnReject", ""},
        {"rdoSystemCalcValues_Yes", "Account Authorizing Time"},
        {"rdoCalcTDS_No", "No"},
        {"rdoDiscounted_No","No"},
        {"rdoDiscounted_Yes","Yes"},
        {"lblFixedDepositAcctHead", "Fixed Deposit A/c Head for Converted Depts"},
        {"lblPenalCharges", "Penal Charges Delayed Installments"},
        {"btnIntDebitPLHead", ""},
        {"lblMaxDepositPeriod", "Maximum Deposit Period"},
        {"rdoTermDeposit_Yes", "Yes"},
        {"rdoProvisionOfInterest_Yes", "Yes"},
        {"lblMinNoOfDays", "Back Dated Deposits are to be"},
        {"lblMinNoOfDays1", "Renewed Within"},
        {"btnIntOnMaturedDepositAcctHead", ""},
        {"panAccountHead", "A/c Head"},
        {"panTax", "Tax"},
        {"rdoAdjustIntOnDeposits_Yes", "Yes"},
        {"lblIntOnMaturedDepositAcctHead", "Interest on Matured Deposit A/c Head"},
        {"lblInstallmentToBeCharged", "Installment to be Changed"},
        
        //added for daily deposits scheme
        {"lblDpeositsFrequency","Deposits Frequency to be Changed"},
        
        {"lblMaturityDepositAcctHead", "Maturity Deposit A/c Head"},
        {"lblNextIntProvisionalDate", "Next Interest Provisional Date"},
        {"btnPrint", ""},
        {"panInCaseOfLien", "In case of Lien"},
        {"lblTDSGLAcctHd", "TDS GL A/c Head"},
        {"rdoTransferToMaturedDeposits_No", "No"},
        {"lblRoundOffCriteria", "Round Off Criteria"},
        {"rdoWithdrawalWithInterest_No", "No"},
        {"lblFlexiFromSBCA", "Flexi (Float) from SB/CA Allowed"},
        {"rdoFlexiFromSBCA_No", "No"},
        {"lblIntCriteria", "Interest Criteria"},
        {"lblTransferToMaturedDeposits", "Transfer to Matured Deposits on Maturity"},
        {"btnException", ""},
        {"lblSchemeIntroDate", "Scheme Introduction Date"},
        {"lblSchemeClosingDate", "Scheme Closing Date"},
        {"lblExtnOfDepositBeforeMaturity", "Extension of Deposit before Maturity Allowed"},
        {"lblAmtInMultiplesOf", "Amount in Multiples of"},
        {"lblIntProvisioningApplicable", "Interest Provisioning Applicable"},
        {"rdoPenaltyOnLateInstallmentsChargeble_No", "No"},
        {"lblIntApplnFreq", "Interest Application Frequency"},
        {"lblAfterHowManyDaysDisplay", "Days"},
        {"btnSave", ""},
        {"lblMinAmtOfPAN", "Minimum Amount for PAN"},
        {"lblMinAmtOfPartialWithdrawalAllowed", "Minimum Amount of Partial Withdrawal Allowed"},
        {"lblInstallmentInRecurringDepositAcct", "Installment in Recurring Deposit Account"},
        {"lblIntProvisioningFreq", "Interest Provisioning Frequency"},
        {"lblMaxAmtOfPartialWithdrawalAllowed", "Maximum Amount of Partial Withdrawal Allowed"},
        {"btnMaturityInterestRate", "After Maturity Interest Rate"},
        {"rdoAutoAdjustment_Yes", "Yes"},
        {"rdoIntProvisioningApplicable_Yes", "Yes"},
        {"panWithdrawal", "Withdrawal"},
        {"lblLastInterestAppliedDate", "Last Interest Applied Date"},
        {"rdoFlexiFromSBCA_Yes", "Yes"},
        {"rdoIntroducerReqd_No", "No"},
        {"lblLastIntProvisionalDate", "Last Interest Provisional Date"},
        {"rdoAmountRounded_Yes", "Yes"},
        {"lblProvisionOfInterest", "Provision of Int. on Matured Deposits"},
        {"btnMaturityInterestType", "After Maturity Interest Type"},
        {"btnNew", ""},
        {"lblAdjustPrincipleToLoan", "Adjust only Priniciple to Loan"},
        {"lblAlphaSuffix", "Alpha Suffix for Printing in TD Receipt"},
        {"rdoInstallmentInRecurringDepositAcct_No", "Variable"},
        {"lblRecalcOfMaturityValue", "Recalculatin of Maturity Value on TDS"},
        {"rdoCalcMaturityValue_Yes", "Yes"},
        {"btnIntPaybleGLHead", ""},
        {"lblMaxAmtPartialWithdrawalPercent", "%"},
        {"rdoTransferToMaturedDeposits_Yes", "Yes"},
        {"lblLimitForBulkDeposit", "Limit for Bulk Deposit"},
        {"lblAfterNoDays", "After No Of Days"},
        {"rdoIntroducerReqd_Yes", "Yes"},
        {"lblWithdrawalsInMultiplesOf", "Further Withdrawals in Multiples of"},
        {"lblIntType", "If Renewed beyond Max Period, Int Type"},
        {"lblPartialWithdrawalAllowed", "Partial Withdrawal Allowed"},
        {"lblIntPeriodForBackDatedRenewal", "Int Period for Back Dated Renewal"},
        {"rdoPayInterestOnHoliday_No", "No"},
        {"lblCutOffDayForPaymentOfInstal", "Cut Off Day for Payment of Installments"},
        {"lblSpace2", "     "},
        {"btnIntProvisioningAcctHd", ""},
        {"lblSpace3", "     "},
        {"lblIntProvisioningAcctHd", "Interest Provisioning A/c Head"},
        {"panRenewalClosure", "Renewal/Closure"},
        {"lblSpace1", " Status :"},
        {"rdoAdjustPrincipleToLoan_No", "No"},
        {"lblIntPaybleGLHead", "Interest Payable GL Head"},
        
        {"lblCommisionPaybleGLHead", "Commision Payable GL Head"},
        {"btnCommisionPaybleGLHead", ""},
        {"lblAcctNumberPattern", "A/c Number Pattern to be Followed"},
        {"lblAcctNumberPattern1", "Next Account Number"},
        {"btnMaturityDepositAcctHead", ""},
        {"btnAcctHeadForFloatAcct", ""},
        {"rdoExtnOfDepositBeforeMaturity_No", "No"},
        {"lblChangeValue", "Change Value"},
        {"rdoProvisionOfInterest_No", "No"},
        {"rdoLastInstallmentAllowed_No", "No"},
        {"btnEdit", ""},
        {"lblDesc", "Product Description"},
        {"lblLastInstallmentAllowed", "Late Installment Allowed"},
        {"lblMaturityDateAfterLastInstalPaid", "Maturity Date after Last Installment Paid"},
        {"lblMaturityDate", "If Renewed beyond Max Period,"},
        {"lblMaturityDate1", "Maturity Date"},
        {"lblProductID", "Product ID"},
        {"rdoAmountRounded_No", "No"},
        {"lblAdjustIntOnDeposits", "Adjust only Interest on Deposits"},
        {"rdoLastInstallmentAllowed_Yes", "Yes"},
        {"rdoCanReceiveExcessInstal_No", "No"},
        {"rdoTermDeposit_No", "No"},
        {"lblRecurringDepositToFixedDeposit", "Convert Recurring Deposit to Fixed Deposit after Maturity Date"},
        {"lblAcctHeadForFloatAcct", "Service Charge A/c Head"},
        {"lblRenewalOfDepositAllowed", "Renewal of Deposit Allowed"},
        {"lblAfterHowManyDays", "After How Many Days"},
        {"lblMinDepositAmt", "Minimum Deposit Amount"},
        {"rdoRecalcOfMaturityValue_No", "No"},
        {"lblIntRoundOff", "Interest Round Off"},
        {"rdoAutoAdjustment_No", "No"},
        {"lblIntPayableOnExcessInstal", "Interest Payable on Excess Installments"},
        {"lblIntCalcMethod", "Interest Calculation Method"},
        {"btnIntProvisionOfMaturedDeposit", ""},
        {"rdoAdjustPrincipleToLoan_Yes", "Yes"},
        {"rdoAdjustIntOnDeposits_No", "No"},
        {"rdoAutoRenewalAllowed_Yes", "Yes"},
        {"lblProvisioningLevel", "Provisioning Level"},
        {"btnAcctHead", ""},
        {"lblAmountRounded", "Should Mat Amt. be Rounded"},
        {"lblAutoAdjustment", "Auto Adjustment of Maturity Proceeds to Loan"},
        {"lblIntMaintainedAsPartOf", "Interest to be Maintained as Part of"},
        {"rdoPartialWithdrawalAllowed_Yes", "Yes"},
        {"lblStatus", "                      "},
        {"lblPayInterestOnHoliday", "Pay Int.on Deposit Maturity on Holiday"},
        {"lblCanReceiveExcessInstal", "Can Receive Excess Installments"},
        {"lblAdvanceMaturityNoticeGenPeriod", "Advance Maturity Notice Generation Period"},
        //{"lblPrematureWithdrawal", "Premature Withdrawal to be Allowed for"},
        {"lblPrematureWithdrawal", "From the Date of Opening, Loan can be granted after"},
        {"lblSpace5", "     "},
        {"btnDelete", ""},
        {"lblNoOfPartialWithdrawalAllowed", "Number of Partial Withdrawal Allowed"},
        {"lblWithdrawalWithInterest", " Withdrawal with Interest"},
        {"lblServiceCharge", "Service Charge Allowed"},
        {"lblInsBeyondMaturityDtYesorNo", "Accept Installments Beyond Maturity Date"},
        {"rdoRenewalOfDepositAllowed_No", "No"},
        {"rdoIntPayableOnExcessInstal_Yes", "Yes"},
        {"lblNoOfDays", "No. of Days in a Year"},
        {"btnFixedDepositAcctHead", ""},
        {"panInterestPayment", "Interest Payment"},
        {"lblMaxDepositAmt", "Maximum Deposit Amount"},
        {"lblMaxAmtOfCashPayment", "Max.Amt.of Cash Payment for Matured Deposits"},
        {"rdoAutoRenewalAllowed_No", "No"},
        {"lblInterestOnMaturedDeposits", "Interest on Maturity Deposits"},
        {"rdoPenaltyOnLateInstallmentsChargeble_Yes", "Yes"},
        {"btnCancel", ""},
        {"lblIntroducerReqd", "Introducer Required"},
        {"rdoExtnOfDepositBeforeMaturity_Yes", "Yes"},
        {"rdoRecurringDepositToFixedDeposit_Yes", "Yes"},
        {"lblPeriodInMultiplesOf", "Period in Multiples of"},
        {"rdoPayInterestOnHoliday_Yes", "Yes"},
        {"rdoRecalcOfMaturityValue_Yes", "Yes"},
        {"lblIntProvisionOfMaturedDeposit", "Int Provision of Matured Deposit A/c Head"},
        {"lblAutoRenewalAllowed", "Auto Renewal Allowed"},
        {"lblAcctHd", "A/c Head"},
        {"lblInterestType", "Interest Type"},
        {"lblDiscounted","Discounted Rate For Monthly IntPay"},
        {"lblDailyDepositCalc","Daily Deposit InterestCalculation basis"},
        {"lblWeekly","Daily Collection credit to be given on"},        
        {"lblStaffAccount","Staff Accounts Allowed"},
        {"lblTypesOfDeposit","Type of Deposit"},
        
        /** UNGENERATED CODE **/
        {"acHdTitle", "List for A/c Head"},
        
        {"lblFromAmount", "From Amount"},
        {"lblToAmount", "To Amount"},
        {"lblFromPeriod", "From Period"},
        {"lblToPeriod", "To Period"},
        {"lblDate", "Date"},
        {"lblToDate", "To Date"},
        {"btnTabNew","New"},
        {"btnTabSave","Save"},
        {"btnTabDelete","Delete"},
        {"lblRateInterest","RateInterest"},
        {"tblInter1", "From Date"},
        {"tblInter2", "To Date"},
        {"tblInter3", "From Amt"},
        {"tblInter4", "To Amt"},
        {"tblInter5", "From Period"},
        {"tblInter6", "To Period"},
        {"tblInter7", "Int Rate"},
        
        {"AMOUNT_WARNING", "To Amount Should Be greater than From Amount"},
        {"RANGE_WARNING", "To Period Should Be greater than From Period"},
        {"RATE_WARNING", "Interest Rate and Penal Rate Should Not be Greater Than or Equal to 100%"},
        {"SYNC_WARNING1", "The Period Range for "},
        {"SYNC_WARNING2", " Combination of Date Range and Amount Range is not Synchronised"},
        {"existanceWarning", "The Rate for this Range of Date and Amount already exist. Please Enter the Data Again"},
        {"NOROWWARNING", "Please Enter the Atleast One Record for Interest Calculation"},
        {"TODATE_WARNING", "Make previous schedule end date with currently selected Date."},
        {"PROD_WARNING", " Please select atleast one Product ID"},
        {"PROD_TYPE_WARNING", " Please select Product Type before Proceding further."},
        {"CATEGORY_WARNING", " Please select atleast one Category for the Selected Product ID"},
        {"DATA_WARNING", "Please Enter the Data for the Selected Combination of Product and Category ID"},
        {"PENAL_WARNING", "Interest Rate Should be More than Penal Rate"},
        
        {"PRODIDWARNING", "This Product Id and/or Description Already Exists."},
        {"PERIODWARNING", "Maximum Deposit Period Should Be greater Than The Minimum Deposit Period."},
        {"AMOUNTWARNING", "Maximum Deposit Amount Should Be greater Than The Minimum Deposit Amount."},
        {"MAXAMOUNTWARNING", "Maximum Withdrawl Amount Cannot Be More Than 100%"},
        {"MAXWITHDRAWLWARNING", "Maximum Number of Withdrawls In A Year Withdrawl Cannot Be More Than The No. Of Withdrawls."},
        {"MINWITHDRAWLWARNING", "Minimum Amount Of Withdrawl Amount Should Be Greater than Minimum Deposit Amount."},
        {"FURTHERWITHDRAWLWARNING", "Further Withdrawl Amount Should Not Be Less Than The Minimum Withdrawl Amount."},
        {"SYNC_WARNING1", "The Period Range for "},
        {"SYNC_WARNING2", " Combination of Date Range and Amount Range is not Synchronised"},
        {"lblMinimumRenewalDeposit","Minimum period of renewal from the date of renewal"},
        {"lblRenewedclosedbefore","Renewed deposit should not be closed before"},
        {"lblclosedwithinperiod","If closed, within above period, whether interest to be paid for the period run"},
        {"lblInterestalreadyPaid","If closed, within above period, whether interest already paid for the overdue period to be recovered"},
        {"lblInterestrateappliedoverdue","Interest rate to be applied for the overdue period is to be based on"},
        {"lblRateAsOnDateOfRenewal","Rate as on the date of renewal"},
        {"lblRateAsOnDateOfMaturity","Rate as on the date of maturity"},
        {"lblBothRateAvail","Either of the above two rates which ever is"},
        {"lblOneRateAvail","If only one of the above two rates is avaialable, then"},
        {"lblBothRateNotAvail","If both the above rates are not available"},
        {"lblAutoRenewalAllowed","Auto Renewal Allowed"},
        {"lblMaxNopfTimes","Max No. of Times Auto Renewal Allowed"},
        {"lblAutoRenewalAllowed1","Same No Allowed"},
        {"lblMaxNopfTimes1","No. of Times Renewal with same number"},
        {"lblIntType","If Renewed beyond Max Period, Interest Type"},
        {"lblMaturityDate","If Renewed beyond Max Period,Maturity Date"},
        {"lblMinNoOfDays","Back Dated Deposits are to be Renewed Within"},
        {"lblIntCriteria","Interest Criteria"},
        {"rdoClosedwithinperiod_Yes","Yes"},
        {"rdoClosedwithinperiod_No","No"},
        {"rdoInterestalreadyPaid_Yes","Yes"},
        {"rdoInterestalreadyPaid_No","No"},
        {"rdoInterestrateappliedoverdue_Yes","SB Rate"},
        {"rdoInterestrateappliedoverdue_No","Deposit Rate"},
        {"rdoSBRateOneRate_Yes","Apply available Rate"},
        {"rdoSBRateOneRate_No","Apply SB Rate"},
        {"rdoBothRateNotAvail_Yes","Apply SB rate"},
        {"rdoBothRateNotAvail_No","Pay no interest"},
        {"rdoAutoRenewalAllowed_Yes","Yes"},
        {"rdoAutoRenewalAllowed_No","No"},
        {"rdoSameNoRenewalAllowed_Yes","Yes"},
        {"rdoSameNoRenewalAllowed_No","No"},
        {"lblRenewalOfDepositAllowed1","If the deposit is renewed after the period mentioned above, then - "},
        {"lblBasedOnDepRate","If based on deposit rate, apply - "},
        {"lblProductType", "Product Type"},
        {"lbInstallmentFrom", "Installment From"},
        {"lblInstallmentTo", "Installment To"},
        {"lblPenal", "Penal"},
        {"lblInstallmentNo", "Installment No."},
        {"lblDueOn", "Due on"},
        {"rdoMonthEnd", "Month End"},
        {"rdoInstallmentDay", "Installment Day"}
    };
    
}
