
/*
 * Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition.
 * 
 *
 * CorporateCustomerRB.java
 *
 * Created on Wed Mar 24 15:39:15 GMT+05:30 2004
 */

package com.see.truetransact.ui.customer;

import java.util.ListResourceBundle;

public class SHGCustomerRB extends ListResourceBundle {
    public SHGCustomerRB(){
    }
    
    public Object[][] getContents() {
        return contents;
    }
    
    static final String[][] contents = {
        {"btnClose", ""},
        {"lblMsg", ""},
        {"panSign", "Signature"},
        {"btnContactNew", "New"},
        {"panCompanyInfo", "Self Help Group Info"},
        {"lblPincode", "Pincode"},
        {"rdoGender_Male", "Male"},
        {"lblSpace2", "     "},
        {"lblSpace3", "     "},
        {"lblSpace1", " Status :"},
        {"lblCustomerID", "SHG ID"},
        {"lblCreatedDt1", "       "},
        {"lblCreatedDt", "Created Date"},
        {"btnPhotoRemove", "Remove"},
        {"lblMiddleName", "Middle Name"},
        {"lblAreaCode", "Area Code"},
        {"btnSignRemove", "Remove"},
        {"lblWebSite", "Web Site"},
        {"lblCountry", "Country"},
        {"lblOtherApplNo", "Other Application No"},
        {"btnEdit", ""},
        {"panContactInfo", "Contact Info"},
        {"btnSignLoad", "Load"},
        {"btnContactDelete", "Delete"},
        {"lblGender", "Gender"},
        {"lblNetWorth", "NetWorth"},
        {"lblRelationManager", "Relation Manager"},
        {"lblLastName", "Last Name"},
        {"btnPrint", ""},
        {"btnPhotoLoad", "Load"},
        {"panTelecomDetails", ""},
        {"btnContactAdd", "Contact"},
        {"lblPhoneNumber", "Number"},
        {"panContacts", "Contacts"},
        {"lblStreet", "Street"},
        {"lblCity", "City"},
        {"lblCustUserid", "User Id"},
        {"lblPrefCommunication", "Pref. Communication"},
        {"rdoGender_Female", "Female"},
        {"lblEmailID", "Email ID"},
        {"lblAuthCustId", "Member Id"},
        {"btnSave", ""},
        {"lblTitle", "Title"},
        {"btnPhoneDelete", ""},
        {"lblStatus", "                      "},
        {"lblCustomerType", "SHG Type"},
        {"lblArea", "Area"},
        {"lblRemarks", "Remarks"},
        {"btnContactNoAdd", ""},
        {"lblPhoneType", "Phone Type"},
        {"lblPhoto", ""},
        {"btnDelete", ""},
        {"lblCompany", "SHG Name"},
        {"btnNew", ""},
        {"btnCancel", ""},
        {"lblCustPwd", "Password"},
        {"btnContactToMain", "To Main"},
        {"lblState", "State"},
        {"btnPhoneNew", ""},
        {"btnAuthCustId", ""},
        {"panPhoto", "Photograph"},
        {"lblFirstName", "First Name"} ,

        {"lblCrAvldSince", "Credit Facilities Availed Since"},
        {"lblRiskRate", "Risk Rate"},
        {"lblBusNature","Nature Of Business"},
        {"lblDtEstablished", "Date Of Establishment"},
        {"lblRegNumber","SHG Reg. No."},
        {"lblCEO","Chief Executive Officer Name"},
        {"lblIntroType","Introducer Type"},
        {"lblNetWorthAsOn","As On"},
         {"lblTinNumber", "TinNumber"},
        {"CheckForMainCust", "Please select one Main Customer for the corporate!!!."},
        {"lblAddrVerified", "Address Verified"},
        {"lblAddrProof", "Address Proof"},
        {"lblIdenProof", "Identity Proof"},
        {"lblFinancialyrEnd","Financial Year End"},
        {"lblTotalIncome","Total Income"},
        {"lblTotalNonTaxExp","Total Non-Tax Expenditure"},
        {"lblProfitBeforeTax","Profit Before Tax"},
        {"lblLiablityTax","Tax Liability"},
        {"lblTransPwd", "Transaction Password"},
        {"lblPanNumber", "PanNumber"},

        {"lblSign", ""},
        {"lblEducationalLevel", "Educational Level"},
        {"lblAddressType", "Address Type"},

        {"lblMaritalStatus", "Marital Status"},
        {"rdoMaritalStatus_Married", "Married"},
        {"lblPrimaryOccupation", "Primary Occupation"},
        {"lblCustomerGroup", "Customer Group"},
        {"panCustomer", ""},
        {"lblDateOfBirth", "Date of Birth"},
        {"lblVehicle", "Vehicle"},
        {"lblLanguage", "Language"},
        {"lblAnnualIncomeLevel", "Annual Income Level"},
        {"lblNationality", "Nationality"},
        {"panPersonalInfo", "Personal Info"},
        {"lblSsn", "Social Security No"},
        {"lblCustomerStatus", ""},
        {"lblProfession", "Profession"},

        {"rdoMaritalStatus_Single", "Single"},
        {"lblResidentialStatus", "Residential Status"},
        {"lblAddrRemarks", "Remarks"},
        {"lblPhVerified", "Phone Verified"},
        {"lblFinanceStmtVerified", "Obtained Finance Statement"},
         {"lblCaste", "Caste"},
         {"lblFirstNamePass","First Name"},
         {"lblMiddleNamePass","Middle Name"},
         {"lblLastNamePass","Last Name"},
         {"lblPassIssueAuth","Issuing Authority"},
         {"lblPassPlaceIssued","Place of Issue"},
         {"lblPassPortNo","PassPort Number"},
         {"lblIssuedDt","Issued Date"},
         {"lblValidUpto","Valid Upto"},
         {"lblKartha","Kartha Name"},
         {"lblFarClass","Classification Of Farmer"},
         {"lblAge","Age"},
         {"lblIncomeParticulars","Income Particulars"},
         {"lblIncName","Name"},
         {"lblIncRelation","Relationship"},
         {"lblIncIncome","Income"},
         {"lblLandDetails","Land Holding Details"},
         {"lblLocation","Location"},
         {"lblSurNo","Survey Number"},
         {"lblAreaInAcrs","Area In Acres"},
         {"lblIrrigated","Irrigated"},
         {"lblSrcIrr","Irrigation Source"},
         {"lblVillage","Village"},
         {"lblPost","Post Office"},
         {"lblHobli","Hobli"},
         {"lblTaluk","Taluk"},
         {"lblDistrict","District"},
         {"lbLandlState","State"},
         {"lblLandPin","PinCode"},
         {"lblGuardianDoB","DOB"},
         {"lblGuardianAge","Age"},
         {"lblSuspendDate","Suspended Date"},
         {"lblSuspendCust","Suspend CustomerID"},
         {"lblRevokeDate","Revoked Date"},
         {"lblSuspendRemarks","Remarks"},
         {"lblRevokeCust","Revoke Suspension"},
         {"lblBankruptsy","Bankruptsy "},
         {"btnClearPassport","Clear Passport Details"},
         {"lblMemNum","MemberShip No"},
         {"pan","P"},
         {"F60","F60"},
         {"F61","F61"},
         {"rdoITDec_Pan","Pan"},
         {"rdoITDec_F60","Form-60"},
         {"rdoITDec_F61","Form-61"},
         {"lblUid","Unique ID"},
         

        /**
         * GENERATED CODE FOR CORPORATE CUSTOMER EXCLUDING ENTRIES FROM CODE GENERATED FOR INDIVIDUAL CUSTOMER
         */
        {"panCorporateCustomer", ""},
       
        
        /**
         * UNGENERATED CODE FOR INDIVIDUAL CUSTOMER
         */
        {"genderMale", "Male"},
        {"genderFeMale", "FeMale"},
        {"maritalStatusSingle", "Single"},
        {"maritalStatusMarried", "Married"},
        {"maritalStatusWidow", "Widow"},
        {"minorYes", "Y"},
        {"minorNo", "N"},
        {"minor", "Minor"},
        {"seniorCitizen", "Senior Citizen"},
        {"minorWards", "Minor court wards"},
        
        {"lblName","Name"},
        {"lblCareOf", "Care Of"},
        {"lblCustStatus", "Customer Status"},
        {"lblMembershipClass", "Membership Class"},
       
        
        
        /**
         * UNGENERATED CODE -- COMMON
         */
        
        {"lblSpace4", "     "},
        {"btnAuthorize", ""},
        {"btnReject", ""},
        {"btnException", ""},
        
        {"tblContactColumn1", "Address Type"},
        {"tblContactColumn2", "Status"},
        {"tblPhoneColumn1", "Sl.No"},
        {"tblPhoneColumn2", "Type"},
        {"tblPhoneColumn3", "Number"},
        
        {"commAddrAlert", "Pls set the main communication address type"},
        {"minAddrType","Atleast one Address Type details should be given"},
        {"mainAddrType","Please make some other Address Type as Main before deleting this entry"},

        {"cDialogYes", "Yes"},
        {"CDialogNo", "No"},
        {"BlockedMsg", "Entered Contact Detail is in Blocked List. Do you want to Continue?"},
        {"tblHistoryTitle1", "Contact Id"},
        {"tblHistoryTitle2", "Relationship"},
        {"tblHistoryTitle3", "Product Id"},
        {"tblHistoryTitle4", "Product Type"},
        {"tblHistoryTitle5", "Account No."},
        {"tblHistoryTitle6", "From"},
        {"tblHistoryTitle7", "To"},
        {"tblHistoryTitle8", "Deposit Amt"},
        {"tblHistoryTitle9", "Maturity Amt"},
        {"tblHistoryTitle10", "Total Balance"},
        {"lblGuardianNameNO",  "Guardian's Name"},
        {"lblRelationNO", "Relationship"},
        {"lblGuardianPhoneNO", "Phone No"},
        {"lblGStreet", "Street"},
        {"lblGArea", "Area"},
        {"lblGCountry", "Country"},
        {"lblGState", "State"},
        {"lblGCity", "City"},
        {"lblGPinCode", "Pincode"},
        {"lblBranchId", "Branch Id"},
        {"lblStaffId", "Staff Id"},
        {"lblConfirmationfromIntroducer", "Confirmation from Introducer"},
        {"lblSentThanksLetter", "Sent Thanks Letter"},
        {"lblDesignation", "Designation"},
        {"btnStaffId", ""},
        {"phoneDetailsMsg", " Do you want to enter the Phone Details for this Address?"},
        {"deleteWarningMsg", "Are you sure you want to delete the address selected?"},
        {"tblIncPar1","No"},
        {"tblIncPar2","Name"},
        {"tblIncPar3","Relation"},
        {"tblIncPar4","Profession"},
        {"tblIncPar5","Institution"},
        {"tblIncPar6","Income"},
        {"tblIncPar7","Yr/Mon"},
        {"btnIncNew", ""},
        {"btnIncDelete", ""},
        {"btnIncSave", ""},
        {"tblLand1","No"},
        {"tblLand2","Location"},
        {"tblLand3","Survey.No"},
        {"tblLand4","Area"},
        {"tblLand5","Irrigated"},
        {"tblLand6","Source"},
        {"tblLand7","Village"},
        {"tblLand8","Post"},
        {"tblLand9","Hobli"},
        {"tblLand10","Taluk"},
        {"tblLand11","District"},
        {"tblLand12","State"},
        {"tblLand13","Pin"},
        {"IncomePar","Income Particulars Details Should Not Be Empty"},
        {"LandPar","Land Details Should Not Be Empty"},
        
        {"panAuthPersonInfo", "Member Info"},
    };
    
}
