/*
 * Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition.
 * 
 *
 * LoanProductRB.java
 * 
 * Created on Tue May 11 16:05:22 IST 2004
 */

package com.see.truetransact.ui.product.loan.agricultureCard;

import java.util.ListResourceBundle;

public class NewLoanAgriProductRB extends ListResourceBundle {
    public NewLoanAgriProductRB(){
    }

    public Object[][] getContents() {
        return contents;
    }

    static final String[][] contents = {
        {"lblPLRApplNewAcc", "PLR Applicable for New Accounts"},
        {"rdoToChargeOn_Both", "Both"},
        {"btnClose", ""},
        {"lblLoanPeriodMul", "Loan Periods in Multiples of"},
        {"lblOperatesLike", "Operates Like"},
        {"rdoProcessCharges_Yes", "Yes"},
        {"lblFolioChargesAppFreq", "Charges Application Frequency"},
        {"rdoMobileBanlingClient_Yes", "Yes"},
        {"btnStatementCharges", ""},
        {"btnMiscServCharges", ""},
        {"btnAccClosCharges", ""},
        {"btnIntPayableAccount",""},
        {"lblLastInterCalcDate", "Last Int Calculated Date - Debit"},
        {"btnAuthorize", ""},
        {"rdoPLRRateAppl_No", "No"},
        {"lblLastInterAppDate", "Last Int Application Date - Debit"},
        {"lblMsg", ""},
        {"lblSubsidy", "Subsidy"},
        {"rdoIsDebitInterUnderClearing_Yes", "Yes"},
        {"lblFolioChargesAcc", "Folio Charges Account - P & L Head"},
        {"lblExposureLimit_Policy_Per", "%"},
        {"panFolio", "Folio"},
        {"lblProvisionsStanAssetsPer", "%"},
        {"lblMaxPeriod", "Maximum Repayment Period"},
        {"rdoStatCharges_No", "No"},
        {"btnCharge_New", "New"},
        {"rdoPenalAppl_No", "No"},
        {"lblPLRRate_Per", "%"},
        {"lblPenalInterRate", "Penal Int Rate For Debit Bal A/c'S"},
        {"lblPenalApplicableAmt","Penal Interest Exception Upto"},
        {"lblProvisionsStanAssets", "Provision for Sub-Standard Assets"},
        {"lblSubsidyAccount","Subsidy Amt Debit Account Head"},
        {"lblMaxAmtCashTrans", "Maximum Amount of Cash Disbursement"},
        {"btnReject", ""},
        {"lblIsStaffAccOpened", "Is Staff Account Opened?"},
        {"btnExpiryInter", ""},
        {"lblSpaces", ""},
        {"lblPLRRateAppl", "PLR Rate Applicable"},
        {"lblProcessCharges", "Processing Charges"},
        {"rdoFolioChargesAppl_No", "No"},
        {"lblNoEntriesPerFolio", "No of Entries per Folio"},
        {"lblMobileBanlingClient", "Mobile Banking Client? "},
        {"btnCheReturnChargest_In", ""},
        {"lblRatePerFolio", "Rate per Folio"},
        {"btnCharge_Delete", "Delete"},
        {"panSpeItems", "Special Items"},
        {"rdoATMcardIssued_No", "No"},
        {"btnAccHead", ""},
        {"lblLimitExpiryInter", "Limit Expiry Interest"},
        {"btnPrint", ""},
        {"lblProductFreq", "Product Accumulation Frequency"},
        {"lblAccHead", "Account Head"},
        {"rdoSubsidy_Yes", "Yes"},
        {"lblRateAmt", "Rate of Amount"},
        {"lblPenalInter", "Penal Interest - P & L Head"},
        {"lblMaxDebitInterAmt", "Maximum Debit Int Amount"},
        {"rdoPLRRateAppl_Yes", "Yes"},
        {"lblDebitProdRoundOff", "Debit Product Round Off"},
        {"lblSunbsidy", "%"},
        {"lblProductDesc", "Product Description"},
        {"lblPLRAppForm", "PLR Applicable From"},
        {"rdoIsStaffAccOpened_Yes", "Yes"},
        {"lblDebitInterAppFreq", "Debit Int Application Frequency"},
        {"rdoStatCharges_Yes", "Yes"},
        {"lblStatus1", "                      "},
        {"btnException", ""},
        {"lblIsAnyBranBankingAllowed", "Is Any Branch Banking Allowed?"},
        {"lblAccDebitInter", "Account for Debit Interest - P & L Head"},
        {"rdoLimitExpiryInter_No", "No"},
        {"lblMiscSerCharges", "Misc Service Charges"},
        {"lblMinDebitInterRate_Per", "%"},
        {"lblNumPatternFollowed", "Numbering Pattern to be Followed"},
        {"btnSave", ""},
        {"lblMinPeriod", "Minimum Repayment Period"},
        {"lblNoticeCharges","Notice Charges - P & L Head"},
        {"lblPostageCharges","Postage Charges"},//- P & L Head
        {"rdoIsAnyBranBankingAllowed_Yes", "Yes"},
        {"lblPLRRate", "PLR Rate"},
        {"lblCreditCardIssued", "Credit Card Issued?"},
        {"rdoPLRApplNewAcc_Yes", "Yes"},
        {"lblPeriodTransLossAssets", "Period to be Transfered to Loss Assets"},
        {"lblMiscServCharges", "Misc Service Charges"},//- P & L Head
        {"lblCharge_1", "Charges"},
        {"btnPenalInter", ""},
        {"lblMaxDebitInterRate_Per", "%"},
        {"lblToCollectFolioCharges", "To Collect Charges"},
        {"lblExposureLimit_Prud_Per", "%"},
        {"rdoToChargeOn_Man", "Manual"},
        {"btnAccCreditInter", ""},
        {"lblPenalInterRate_Per", "%"},
        //insurance Details
        {"lblInsuranceType","Insurance Type"},
        {"lblInsuranceUnderSchume","Insurance Under Schume"},
        {"lblBankSharePremium","Premium Bank Share"},
        {"lblCustomerSharePremium","Premium Customer Share"},
        {"lblInsurancePremiumDebit","Insurance Premium Debit"},
        {"lblInsuranceAmt","Insurance Amt"},
       
        {"btnInsuranceNew","New"}, 
        {"btnInsuranceSave","Save"}, 
        {"btnInsuranceDelete","Delete"},

//        {"lblPenalApplicableAmt","Penal Interest Applicable Amt"},
        {"rdoIsDebitInterUnderClearing_No", "No"},
        {"lblIncompleteFolioRoundOffFreq", "Incomplete Rounding Off freq"},
        {"lblStatCharges", "Statement Charges"},
        {"lblPenalAppl", "Penal Interest Applicable"},
        {"lblIsDebitInterUnderClearing", "Is Debit Interest on Under Clearing Applicable?"},
        {"panChequeReturnCharges", "Cheque Return / Outward Charges"},
        {"btnNew", ""},
        {"rdoFolioChargesAppl_Yes", "Yes"},
        {"lblApplicableInter", "Applicable Interest"},
        {"lblATMcardIssued", "ATM Card Issued?"},
        {"lblExpiryInter", "Expiry Interest - P & L Head"},
        {"rdoPLRApplExistingAcc_No", "No"},
        {"lblAccClosingCharges", "Account Closing Charges"},
        {"lblApplicableInterPer", "%"},
        {"lblPLRApplExistingAcc", "PLR Applicable for Existing Accounts"},
        {"btnCheReturnChargest_Out", ""},
        {"panNonPerAssets", "Non-Performing Assets"},
        {"lblLimit", " Value"},
        {"btnFolioChargesAcc", ""},
        {"lblAccClosCharges", "Account Closing Charges - P & L Head"},
        {"lblIntPayableAccount","Credit Int Recivable Account"},
        {"lblSubsidyAmt","Goverment Sponcered Subsidy Amt"},
        {"lblSubsidyFromDt","Subsidy Applicable FromDt"},
        {"lblSubsidyToDate","Subsidy Applicable ToDt"},
        {"lblMinAmtLoan", "Minimum Amount of Loan"},
        {"lblProvisionDoubtfulAssets1", "Provision for Douibtful Assets 1"},
        {"lblProvisionDoubtfulAssets2", "Provision for Douibtful Assets 2"},
        {"lblProvisionDoubtfulAssets3", "Provision for Douibtful Assets 3"},
        {"rdoATMcardIssued_Yes", "Yes"},
        {"lblCheReturnChargest_In", "Cheque Ret Charges (Inward) - P & L Head"},
        {"lblSpace2", "     "},
        {"lblDebInterCalcFreq", "Debit Int Calculation Frequency"},
        {"rdoldebitInterCharged_No", "No"},
        {"lbldebitInterCharged", "Debit Interest to be Charged"},
        {"rdoCommitmentCharge_No", "No"},
        {"lblExposureLimit_Prud", "Exposure Limit (Prudential Norms)"},
        {"lblSpace3", "     "},
        {"lblSpace1", " Status :"},
        {"lblProcessingCharges", "Processing Charges - P & L Head"},
        {"lblCheReturnChargest_Out", "Cheque Ret Charges (Outward) - P & L Head"},
        {"lblProvisionDoubtfulAssetsPer1", "%"},
        {"lblProvisionDoubtfulAssetsPer2", "%"},
        {"lblProvisionDoubtfulAssetsPer3", "%"},
        {"lblMinDebitInterRate", "Minimum Debit Interest rate"},
        {"lblNextFolioDDate", "Next Due Date"},
        {"lblMinInterDebited", "Minimum Interest to be Debited"},
        {"rdoIsAnyBranBankingAllowed_No", "No"},
        {"rdoPenalAppl_Yes", "Yes"},
        {"lblDebitInterComFreq", "Debit Int Compound Frequency"},
        {"btnEdit", ""},
        {"lblProvisionLossAssetsPer", "%"},
        {"rdoToChargeOn_Sys", "System"},
        {"lblProvisionLossAssets", "Provision for Loss Assets"},
        {"rdoCreditCardIssued_No", "No"},
        {"rdoldebitInterCharged_Yes", "Yes"},
        {"lblProductID", "Product Id"},
        {"btnAccDebitInter", ""},
        {"rdoMobileBanlingClient_No", "No"},
        {"lblDebitInterRoundOff", "Debit Interest Round Off"},
        {"lbStatementCharges", "Statement Charges - P & L Head"},
        {"lblStatChargesRate", "Statement Charges Rate"},
        {"lblPeriodTranSStanAssets", "Period to be Transfered to Sub-Standard Assets"},
        {"lblProvisionStandardAssetss", "Provision for Standard Assets"},
        {"lblLastFolioChargesAppl", "Last Charges Applied On"},
        {"lblCharge_2", "Charges"},
        {"lblDocumentType", "Document Type"},
        {"lblDocumentNo", "Document No"},
        {"lblDocumentDesc", "Document Description"},
        {"lblcalcType", "Calculation Type"},
        {"btnProcessingCharges", ""},
        {"lblFolioChargesAppl", "Charges Applicable"},
        {"lblToChargeOn", "To Charge On"},
        {"lblPlrApplAccSancForm", "PLR Applicable For A'/'cs Sanctioned From"},
        {"rdoPLRApplExistingAcc_Yes", "Yes"},
        {"lblAccCreditInter", "Account for Credit Interest - P & L Head"},
        {"lblMinDebitInterAmt", "Minimum Debit Int Amount"},
        {"lblMinPeriodsArrears", "Minimum Periods of Arrears"},
        {"lblasAndWhenCustomer","As AndWhenCustomerComes"},
        {"lblcalendar","Calendar Frequency"},
        {"lblPenalDue","Penal Applicable On"},
         {"rdoasAndWhenCustomer_No", "No"},
        {"rdoasAndWhenCustomer_Yes", "Yes"},
         {"rdocalendarFrequency_No", "No"},
        {"rdocalendarFrequency_Yes", "Yes"},
        {"lblEligibleDepositAmtForLoan","Eligible Deposit Amt For Loan"},
         {"lblReviewPeriodLoan","Review Period Loan"},
        {"rdoIsLimitDefnAllowed_No", "No"},
        {"rdoCreditCardIssued_Yes", "Yes"},
        {"lblPeriodTransDoubtfulAssets1", "Period to be Transfered to Doubtful Assets 1"},
        {"lblPeriodTransDoubtfulAssets2", "Period to be Transfered to Doubtful Assets 2"},
        {"lblPeriodTransDoubtfulAssets3", "Period to be Transfered to Doubtful Assets 3"},
        {"btnCommitCharges", ""},
        {"lblLastAccNum", "Next Account Number"},
        {"rdoLimitExpiryInter_Yes", "Yes"},
        {"rdoProcessCharges_No", "No"},
        {"lblMaxDebitInterRate", "Maximum Debit Interest Rate"},
        {"lblCommitCharges", "Commitment Charges - P & L Head"},
        {"lblSpace5", "     "},
        {"btnDelete", ""},
        {"rdoPLRApplNewAcc_No", "No"},
        {"lblExposureLimit_Policy", "Exposure Limit (Policy Norms)"},
//        {"lbl_av_Balance","Av_Balance"},
//        {"lblNoOfFreeFolio","NoOFreeFolio"},
        {"rdoIsStaffAccOpened_No", "No"},
        {"lblMaxAmtLoan", "Maximum Amount of Loan"},
        {"lblLegalCharges","Legal Charges"},
        {"lblArbitraryCharges","Arbitrary Charges"},
        {"lblInsuranceCharges","Insurance Charges"},
        {"lblExecutionDecreeCharges","Execution Decree Charges"},
        {"lblPeriodAfterWhichTransNPerformingAssets", "Period After Which to be Transfered to Non-Performing Assets"},
        {"rdoSubsidy_No", "No"},
        {"rdoCommitmentCharge_Yes", "Yes"},
        {"rdoToChargeType_Credit","Credit"},
        {"rdoToChargeType_Debit","Debit"},
        {"rdoToChargeType_Both","Both"},
        {"btnCancel", ""},
        {"lblProvisionStandardAssetssPer", "%"},
        {"btnCharge_Save", "Save"},
        {"btnDocumentNew", "New"},
        {"btnDocumentSave", "Save"},
        {"btnDocumentDelete", "Delete"},
        {"lblCommitmentCharge", "Commitment Charges"},
        {"lblIsLimitDefnAllowed", "Is Limit Definition Allowed?"},
        {"rdoIsLimitDefnAllowed_Yes", "Yes"},
        {"lblLimits", "  Value"},
        {"lblChargeAppliedType","Charge On Tran Type"},
        {"lblProdCurrency", "Product Currency"},
        {"lblRangeFrom", "Range From"},
        {"lblRangeTo", "Range To"},
        
        {"lblCommodityCode", "Commodity Code"},
        {"lblGuaranteeCoverCode", "Guarantee Cover Code"},
        {"lblSectorCode", "Sector Code"},
        {"lblHealthCode", "Health Code"},
        {"lblTypeFacility", "Facility Type"},
        {"lblPurposeCode", "Purpose Code"},
        {"lblIndusCode", "Industry Code"},
        {"lbl20Code", "20 Code"},
        {"lblRefinancingInsti", "Refinancing Institution"},
        {"lblGovtSchemeCode", "Govt. Scheme Code"},
        {"lblSecurityDeails", "Security Details"},
        {"lblDirectFinance", "Direct Finance"},
        {"lblECGC", "ECGC"},
        {"lblQIS", "QIS"},
        
        {"tblColumn1", "Range From"},
        {"tblColumn2", "Range To"},
        {"tblColumn3", "Rate of Amount"},
        {"tblColumn4", "SI No"},
        {"tblColumn5", "Document Type"},
        {"tblColumn6", "Document No"},
        {"tblColumn7",  "Notice_Type"},
        {"tblColumn8",  "Issue_After"},
        {"tblColumn9",   "NoticeChargeAmt"},
        {"tblColumn10", "PostgeAmt"},
        {"tblColumn11", "Insurance Type"},
        {"tblColumn12", "Insurance Scheme"},
        {"tblColumn13", "Bank Share"},
        {"tblColumn14", "Customer Share"},
        {"tblColumn15", "Slno"},
        {"tblColumn16", "Insurnce Amt"},
        {"cDialogYes", "Yes"},
        {"cDialogNo", "No"},
        {"cDialogCancel", "Cancel"},
        {"lblNoticeType","NoticeType"},
        {"lblIssueAfter","Issued After"},
        {"lblNoticeChargeAmt","Notice Charges"},
        {"lblPostageAmt","Postage Charges"},
        {"btnNotice_Charge_New","New"},
        {"btnNotice_Charge_Save","Save"},
        {"btnNotice_Charge_Delete","Delete"},
        {"existanceWarning", "The Rate for this Amount Already exist. Do you want to modify the Rate of Amount?"},
        {"prodIdWarning", "This Product Id Already Exist, please Enter the New one."},
        {"RateWarning", "Minimum Debit Interest Rate Should be Less Tahn The Maximum Debit Interest Rate."},
        {"AmountWarning", "Minimum Debit Interest Amount Should be Less Tahn The Maximum Debit Interest Amount."},
        {"RangeWarning", "Range From Should Be Greater Than To Range."},
        {"PeriodWarning", "Maximum Period Should Be Greater than The Minimum Period."},
        {"MaxLoanWarning", "Maximum Loan Amount Should Be Greater than The Minimum Loan Amount."},
        {"DocTypeDocNoWarning", "Document Type And Document Number Should Not Be Duplicated !!!"},
        {"OD_CCALERT", "Do you want to Configure and/or see the Data for the Selected Product in Advances Product Screen!!!"},
        {"ApplicableLoanWarning", "Applicalble Loan Amount Should Be Between than The Minimum And The Maximum Loan Amounts."},
        {"PREFIXWARNING" ,"Enter the Numbering pattern To Be Followed!! "},
        {"SUFFIXWARNING" ,"Enter the Numbering pattern To Be Followed!! "}

   };

}
