/*
 * Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition.
 * 
 *
 * TermDepositMRB.java
 * 
 * Created on Wed Aug 18 15:24:35 GMT+05:30 2004
 */
package com.see.truetransact.ui.deposit;

import java.util.ListResourceBundle;

public class TermDepositMRB extends ListResourceBundle {

    public TermDepositMRB() {
    }

    public Object[][] getContents() {
        return contents;
    }
    static final String[][] contents = {
        {"txtOtherPhone", "OtherPhone should not be empty!!!"},
        {"txtDepsoitNo", "txtDepsoitNo should not be empty!!!"},
        {"txtNomDetShare", "NomDetShare should not be empty!!!"},
        {"txtNomDetStreet", "NomDetStreet should not be empty!!!"},
        {"txtMaturityAmount", "MaturityAmount should not be empty!!!"},
        {"cboNominatedBy", "NominatedBy should be a proper value!!!"},
        {"tdtPaymentDate", "PaymentDate should not be empty!!!"},
        {"txtInterBranchTransferNo", "InterBranchTransferNo should not be empty!!!"},
        {"tdtExpDt", "ExpDt should not be empty!!!"},
        {"txtAuthSignStreet", "AuthSignStreet should not be empty!!!"},
        {"txtTransferingBranchCode", "TransferingBranchCode should not be empty!!!"},
        {"txtInterestProvidedAmount", "InterestProvidedAmount should not be empty!!!"},
        {"rdoOpeningMode_Normal", "OpeningMode should be selected!!!"},
        {"chk15hDeclarations", "15hDeclarations should be selected!!!"},
        {"cboNomDetRelationship", "NomDetRelationship should be a proper value!!!"},
        {"txtAuthSignName", "AuthSignName should not be empty!!!"},
        {"rdoOpeningMode_Renewal", "OpeningMode should be selected!!!"},
        {"rdoOpeningMode_Extension", "OpeningMode should be selected!!!"},
        {"rdoIntroReqd_Yes", "IntroReqd should be selected!!!"},
        {"txtLastTdsCollected", "LastTdsCollected should not be empty!!!"},
        {"tdtMaturityDate", "MaturityDate should not be empty!!!"},
        {"txtOtherArea", "OtherArea should not be empty!!!"},
        {"cboNomDetMinCountry", "NomDetMinCountry should be a proper value!!!"},
        {"cboNomDetState", "NomDetState should be a proper value!!!"},
        {"cboCredAccDetProductId", "CredAccDetProductId should be a proper value!!!"},
        {"txtDepositAmount", "DepositAmount should not be empty!!!"},
        {"txtPeriodOfDeposit_Years", "PeriodOfDeposit_Years should not be empty!!!"},
        {"txtAccNo", "AccNo should not be empty!!!"},
        {"txtPrintedNoOfTheFdr", "PrintedNoOfTheFdr should not be empty!!!"},
        {"cboPoaCustomerName", "PoaCustomerName should be a proper value!!!"},
        {"txtAuthSignDesignation", "AuthSignDesignation should not be empty!!!"},
        {"chkPowerOfAttorney", "PowerOfAttorney should be selected!!!"},
        {"txtName", "Name should not be empty!!!"},
        {"txtNomDetArea", "NomDetArea should not be empty!!!"},
        {"txtAuthSignPager", "AuthSignPager should not be empty!!!"},
        {"txtAuthSignBusinessPhone", "AuthSignBusinessPhone should not be empty!!!"},
        {"cboNomDetMinAddType", "NomDetMinAddType should be a proper value!!!"},
        {"txtPowOfAttPoASlNo", "PowOfAttPoASlNo should not be empty!!!"},
        {"txtPowOfAttPhone", "PowOfAttPhone should not be empty!!!"},
        {"txtCredAccDetAmt", "CredAccDetAmt should not be empty!!!"},
        {"txtPanNumber", "PanNumber should not be empty!!!"},
        {"cboSettlementMode", "SettlementMode should be a proper value!!!"},
        {"cboNomDetMinGdType", "NomDetMinGdType should be a proper value!!!"},
        {"cboNomDetStatus", "Nominee Status should be a proper value!!!"},
        {"txtCredAccDetParticulars", "CredAccDetParticulars should not be empty!!!"},
        {"cboPowOfAttState", "PowOfAttState should be a proper value!!!"},
        {"txtNomDetNomSlNo", "NomDetNomSlNo should not be empty!!!"},
        {"txtIssBy", "IssBy should not be empty!!!"},
        {"cboPowOfAttCity", "PowOfAttCity should be a proper value!!!"},
        {"txtPoAAreaCode", "PoAAreaCode should not be empty!!!"},
        {"txtIssAuth", "IssAuth should not be empty!!!"},
        {"txtAuthSignMobile", "AuthSignMobile should not be empty!!!"},
        {"cboOnBehalfOf", "OnBehalfOf should be a proper value!!!"},
        {"tdtLastInstallmentReceivedDate", "LastInstallmentReceivedDate should not be empty!!!"},
        {"cboCategory", "Category should be a proper value!!!"},
        {"txtPowOfAttPoAHoldName", "PowOfAttPoAHoldName should not be empty!!!"},
        {"cboNomDetCity", "NomDetCity should be a proper value!!!"},
        {"cboNomDetCountry", "NomDetCountry should be a proper value!!!"},
        {"txtPeriodicInterestAmount", "PeriodicInterestAmount should not be empty!!!"},
        {"cboIdType", "IdType should be a proper value!!!"},
        {"txtNomDetMinGdName", "NomDetMinGdName should not be empty!!!"},
        {"txtPowOfAttArea", "PowOfAttArea should not be empty!!!"},
        {"txtNomDetNomName", "NomDetNomName should not be empty!!!"},
        {"cboCommunicationAddress", "CommunicationAddress should be a proper value!!!"},
        {"cboInterestPaymentFrequency", "InterestPaymentFrequency should be a proper value!!!"},
        {"txtAuthSignHomePhone", "AuthSignHomePhone should not be empty!!!"},
        {"chkNomineeDetails", "NomineeDetails should be selected!!!"},
        {"txtOtherPin", "OtherPin should not be empty!!!"},
        {"txtDocNo", "DocNo should not be empty!!!"},
        {"txtPowOfAttStreet", "PowOfAttStreet should not be empty!!!"},
        {"txtAuthSignNoOfAuthSign", "AuthSignNoOfAuthSign should not be empty!!!"},
        {"txtPowOfAttPincode", "PowOfAttPincode should not be empty!!!"},
        {"txtNomDetMinPhone", "NomDetMinPhone should not be empty!!!"},
        {"cboOtherCity", "OtherCity should be a proper value!!!"},
        {"cboNomDetMinState", "NomDetMinState should be a proper value!!!"},
        {"txtOtherAreaCode", "OtherAreaCode should not be empty!!!"},
        {"txtNomDetPhone", "NomDetPhone should not be empty!!!"},
        {"txtOtherStreet", "OtherStreet should not be empty!!!"},
        {"cboPaymentType", "PaymentType should be a proper value!!!"},
        {"txtPeriodOfDeposit_Months", "PeriodOfDeposit_Months should not be empty!!!"},
        {"txtAuthSignArea", "AuthSignArea should not be empty!!!"},
        {"cboNomDetAddType", "NomDetAddType should be a proper value!!!"},
        {"txtCustomerId", "CustomerId should not be empty!!!"},
        {"chkAuthorizedSignatory", "AuthorizedSignatory should be selected!!!"},
        {"txtTransferingAmount", "TransferingAmount should not be empty!!!"},
        {"cboInterestPaymentMode", "InterestPaymentMode should be a proper value!!!"},
        {"cboProductId", "ProductId should be a proper value!!!"},
        {"cboAuthSignCity", "AuthSignCity should be a proper value!!!"},
        {"txtAuthSignPincode", "AuthSignPincode should not be empty!!!"},
        {"chkTaxDeductions", "TaxDeductions should be selected!!!"},
        {"chkMember", "Member Should be selected!!!"},
        {"cboMemberType", "Member Type should not be empty!!!"},
        {"tdtDateOfDeposit", "DateOfDeposit should not be empty!!!"},
        {"txtInterestPaid", "InterestPaid should not be empty!!!"},
        {"txtAuthSignBusinessFax", "AuthSignBusinessFax should not be empty!!!"},
        {"cboNomDetMinCity", "NomDetMinCity should be a proper value!!!"},
        {"txtIntroName", "IntroName should not be empty!!!"},
        {"cboAuthSignState", "AuthSignState should be a proper value!!!"},
        {"tdtPowOfAttPeriodTo", "PowOfAttPeriodTo should not be empty!!!"},
        {"cboPowOfAttAddType", "PowOfAttAddType should be a proper value!!!"},
        {"txtCredAccDetDepositNo", "CredAccDetDepositNo should not be empty!!!"},
        {"cboAuthSignAddForComm", "AuthSignAddForComm should be a proper value!!!"},
        {"txtNomDetMinAreaCode", "NomDetMinAreaCode should not be empty!!!"},
        {"rdoCustomer_New", "Customer should be selected!!!"},
        {"txtRemarks", "Remarks should not be empty!!!"},
        {"txtNomDetMinStreet", "NomDetMinStreet should not be empty!!!"},
        {"tdtDateOfTransfer", "DateOfTransfer should not be empty!!!"},
        {"tdtLastInterestCalculatedDate", "LastInterestCalculatedDate should not be empty!!!"},
        {"txtPeriodOfDeposit_Days", "PeriodOfDeposit_Days should not be empty!!!"},
        {"txtAuthSignLimits", "AuthSignLimits should not be empty!!!"},
        {"tdtOriginalDateOfDeposit", "OriginalDateOfDeposit should not be empty!!!"},
        {"txtDesig", "Desig should not be empty!!!"},
        {"cboAuthSignCountry", "AuthSignCountry should be a proper value!!!"},
        {"cboInstallmentAmount", "InstallmentAmount should be a proper value!!!"},
        {"cboIntroducerType", "IntroducerType should be a proper value!!!"},
        {"txtTotalNumberOfInstallments", "TotalNumberOfInstallments should not be empty!!!"},
        {"txtBankName", "BankName should not be empty!!!"},
        {"cboOtherCountry", "OtherCountry should be a proper value!!!"},
        {"tdtPowOfAttPeriodFrom", "PowOfAttPeriodFrom should not be empty!!!"},
        {"txtTotalInstallmentReceived", "TotalInstallmentReceived should not be empty!!!"},
        {"cboPowOfAttCountry", "PowOfAttCountry should be a proper value!!!"},
        {"txtNo", "No should not be empty!!!"},
        {"txtNomDetPincode", "NomDetPincode should not be empty!!!"},
        {"cboConstitution", "Constitution should be a proper value!!!"},
        {"cboAddressType", "Communication Address should not be empty!!!"},
        {"txtDebAccDetParticulars", "DebAccDetParticulars should not be empty!!!"},
        {"txtAuthSignHomeAreaCode", "AuthSignHomeAreaCode should not be empty!!!"},
        {"txtIntroducerDetailsAccountNumber", "IntroducerDetailsAccountNumber should not be empty!!!"},
        {"txtTotalInterestAmount", "TotalInterestAmount should not be empty!!!"},
        {"cboDepositNo", "DepositNo should be a proper value!!!"},
        {"cboOtherState", "OtherState should be a proper value!!!"},
        {"txtOriginalAccountNumber", "OriginalAccountNumber should not be empty!!!"},
        {"txtCredAccDetAccNo", "CredAccDetAccNo should not be empty!!!"},
        {"txtNomDetMinPincode", "NomDetMinPincode should not be empty!!!"},
        {"txtAuthSignHomeFax", "AuthSignHomeFax should not be empty!!!"},
        {"txtNomDetMinArea", "NomDetMinArea should not be empty!!!"},
        {"txtNomDetAreaCode", "NomDetAreaCode should not be empty!!!"},
        {"txtRateOfInterest", "RateOfInterest should not be empty!!!"},
        {"txtBranchName", "BranchName should not be empty!!!"},
        {"txtPowOfAttRemarks", "PowOfAttRemarks should not be empty!!!"},
        {"tdtNomDetMinDOB", "NomDetMinDOB should not be empty!!!"},
        {"txtAuthSignEmailId", "AuthSignEmailId should not be empty!!!"},
        {"txtDebAccDetAmt", "DebAccDetAmt should not be empty!!!"},
        {"chkStandingInstructions", "StandingInstructions should be selected!!!"},
        {"cboDocType", "DocType should be a proper value!!!"},
        {"tdtIssDt", "IssDt should not be empty!!!"},
        {"txtAgentId", "Agent Id should not be empty!!!"},
        {"tdtTdsCollectedUpto", "TdsCollectedUpto should not be empty!!!"},
        {"cboProdType", "Product Type should not be empty!!!"},
        {"cboProdId", "Product Id should not be empty!!!"},
        {"tdtCalenderFreqDate", "Calender Frequency Date Should Not be empty!!!"},
        {"cboRenewalDepositProdId", "Product Id Should Not be Empty!!!"},
        {"cboRenewalDepositCategory", "Category Should not be Empty!!!"},
        {"txtRenewalDepTransAmtValue", "Withdrawing Amount Should not be empty!!!"},
        {"cboRenewalDepTransMode", "Withdrawing Mode Should not be empty!!!"},
        {"cboRenewalDepTransProdType", "Product Type should not be empty!!!"},
        {"cboRenewalDepTransProdId", "Product Id should not be empty!!!"},
        {"btnRenewalDepCustomerIdFileOpenCr", "Account number should not be empty!!!"},
        {"txtRenewalDepTransTokenNo", "Token no should not be empty!!!"},
        {"txtRenewalIntAmtValue", "Withdrawing Amount Should not be empty!!!"},
        {"cboRenewalInterestTransMode", "Withdrawing Mode Should not be empty!!!"},
        {"cboRenewalInterestTransProdType", "Product Type should not be empty!!!"},
        {"cboRenewalInterestTransProdId", "Product Id should not be empty!!!"},
        {"btnRenewalIntCustomerIdFileOpenCr", "Account number should not be empty!!!"},
        {"txtRenewalIntTokenNoVal", "Token no should not be empty!!!"},
        {"txtRenewalPeriodOfDeposit_Years", "Period of Year should not be empty!!!"},
        {"txtRenewalPeriodOfDeposit_Days", "Period of Days should not be empty!!!"},
        {"txtRenewalPeriodOfDeposit_Months", "Period of Months should not be empty!!!"},
        {"cboRenewalInterestPaymentFrequency", "Interest Payment Frequency Should not be empty!!!"},
        {"cboRenewalInterestPaymentMode", "Interest Payment Mode should not be empty!!!"},
        {"cboRenewalProdType", "Product Type should not be empty!!!"},
        {"cboRenewalProdId", "Product Id should not be empty!!!"},
        {"btnRenewalCustomerIdFileOpenCr", "Account number should not be empty!!!"},
        {"txtRenewalPrintedOption", "Printing Option should not be empty!!!"},
        {"cboRenewalCalenderFreqDay", "Calender Frequency Should not be empty!!!"},
        {"cboExtensionDepositProdId", "Product Id Should Not be Empty!!!"},
        {"cboExtensionDepositCategory", "Category Should not be Empty!!!"},
        {"txtExtensionDepTransAmtValue", "Withdrawing Amount Should not be empty!!!"},
        {"txtExtensionTransAmtValue", "Withdrawing Amount Should not be empty!!!"},
        {"cboExtensionTransMode", "Withdrawing Mode Should not be empty!!!"},
        {"cboExtensionTransProdType", "Product Type should not be empty!!!"},
        {"cboExtensionTransProdId", "Product Id should not be empty!!!"},
        {"btnExtensionTransCustomerIdFileOpenCr", "Account number should not be empty!!!"},
        {"txtExtensionTransTokenNo", "Token no should not be empty!!!"},
        {"txtExtensionPeriodOfDeposit_Years", "Period of Year should not be empty!!!"},
        {"txtExtensionPeriodOfDeposit_Days", "Period of Days should not be empty!!!"},
        {"txtExtensionPeriodOfDeposit_Months", "Period of Months should not be empty!!!"},
        {"cboExtensionInterestPaymentFrequency", "Interest Payment Frequency Should not be empty!!!"},
        {"cboExtensionInterestPaymentMode", "Interest Payment Mode should not be empty!!!"},
        {"cboExtensionProdType", "Product Type should not be empty!!!"},
        {"cboExtensionProdId", "Product Id should not be empty!!!"},
        {"btnExtensionCustomerIdFileOpenCr", "Account number should not be empty!!!"},
        {"txtExtensionPrintedOption", "Printing Option should not be empty!!!"},
        {"cboExtensionCalenderFreqDay", "Calender Frequency Should not be empty!!!"}
    };
}
