/*
 * Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition.
 * 
 *
 * MDSProductRB.java
 * 
 * Created on Wed Jun 08 13:12:55 IST 2011
 */

package com.see.truetransact.ui.product.mds;

import java.util.ListResourceBundle;

public class MDSProductRB extends ListResourceBundle {
    public MDSProductRB(){
    }

    public Object[][] getContents() {
        return contents;
    }

    static final String[][] contents = {
        {"lblDiscountRateVal", "Value"},
        {"lblBonusGracePeriod", "Bonus grace period"},
        {"panAcceptType", ""},
        {"rdoDiscountPeriodAfter", "On or before"},
        {"lblShortfall", "If there is a shortfall of members in a chit whether"},
        {"btnClose", ""},
        {"lblAcceptableType7", "Class B"},
        {"lblPenalHead", "Penal Interest A/c Head"},
        {"lblPenalPrizedRate", "Penal Prized Interest Rate"},
        {"lblPenalIntRate", "Penal Interest Rate"},
        {"panGeneralDetailsEntry", ""},
        {"lblDiscountPrizedPeriod", "Discount prized grace period"},
        {"btnAuthorize", ""},
        {"lblMsg", ""},
        {"rdoprizedDefaulters_yes", "Yes"},
        {"lblLoanCanbeGranted", "Whether loan can be granted under this scheme ?"},
        {"lblDiscountPeriod", "Discount grace period"},
        {"lblBonusPrizedPreriod", "Bonus prized grace period"},
        {"lblBonusPayableHead", "Bonus Payable A/c Head"},
        {"lblDiscountRate", "Discount Rate"},
        {"lblSuretyRequired", "Surety Required"},
        {"btnSuspenseHead", ""},
        {"btnCaseExpensesHead", ""},
        {"lblOnlyMembers", "Only Members"},
        {"lblAuctionMinAmt", "In case of Auction, minimum bid amount"},
        {"btnReceiptHead", ""},
        {"lblNonPrizedChit1", "installments, whether the Bank will advance the deficit ?"},
        {"rdoBonusAllowed_yes", "Yes"},
        {"btnReject", ""},
        {"chkAcceptableClassAll", ""},
        {"rdoPrizedChitOwner_no", "No"},
        {"chkAcceptableClassB", ""},
        {"lblAcceptableType8", "Class A"},
        {"lblLoanIntRateVal", "Value"},
        {"btnMunnalBonusHead", ""},
        {"rdoShortfall_yes", "Yes"},
        {"lblAcceptableType14", "Class C"},
        {"rdoShortfall_no", "No"},
        {"chkAcceptableClassA", ""},
        {"rdoLoanCanbeGranted_no", "No"},
        {"btnPrint", ""},
        {"lblThalayalBonusHead", "Thalayal VP Suspense A/c Head"},
        {"lblMunnalReceiptsHead", "Munnal Receipts/Payments A/c Head"},
        {"lblProductDesc", "Product Description"},
        {"lblBonusChitOwner", "Bonus allowed for prized defaulters"},
        {"lblCommisionRate", "MDS Commission Rate"},
        {"rdoSuretyRequired_no", "No"},
        {"rdoBonusPrizedAfter", "On or before"},
        {"lblDiscountAllowed", "Discount allowed"},
        {"btnException", ""},
        {"lblChitDefaults1", "the Bank will advance for the balance no.of members ?"},
        {"lblProductId", "Product Id"},
        {"btnCopy", ""},
        {"btnSave", ""},
        {"rdoDiscountPeriodDays", "Days"},
        {"rdoChitDefaults_no", "No"},
        {"lblCaseExpensesHead", "Case Expenses A/c Head"},
        {"btnMunnalReceiptsHead", ""},
        {"lblBonusReceivableHead", "Bonus Receivable A/c Head"},
        {"lblCommisionRateVal", "Value"},
        {"lblPenalPrizedRateVal", "Value"},
        {"rdoDiscountPrizedPeriodAfter", "On or before"},
        {"btnMiscellaneousHead", ""},
        {"lblNonPrizedChit", "Whether a non-prized chit owner can be changed ?"},
        {"rdoBonusPrizedDays", "Days"},
        {"lblAuctionMinAmtVal", "%"},
        {"rdoDiscountPrizedPeriodDays", "Days"},
        {"lblSpace", " Status :"},
        {"chkAcceptableClassC", ""},
        {"lblMargin", "If yes,  the Margin  to be Maintained"},
        {"btnNew", ""},
        {"lblCommisionHead", "Commission A/c Head"},
        {"lblAcceptableType13", "Class A"},
        {"lblLoanIntRate", "Loan Interest Rate"},
        {"panGracePeriodDetails", "Grace Period Details"},
        {"btnThalayalBonusHead", ""},
        {"lblAcceptableType9", "Class C"},
        {"btnNoticeChargesHead", ""},
        {"rdoDiscountPeriodMonth", "Months"},
        {"lblPaymentHead", "Payment A/c Head"},
        {"rdoBonusGraceEnd", "Month end"},
        {"lblMiscellaneousHead", "Miscellaneous A/c Head"},
        {"panMDSLoan", "Loan against MDS"},
        {"rdobonusPayableOwner_yes", "Yes"},
        {"btnCommisionHead", ""},
        {"btnPaymentHead", ""},
        {"chkAcceptClassB", ""},
        {"chkAcceptClassC", ""},
        {"lblAcceptType2", "Acceptable types "},
        {"rdobonusPayableOwner_no", "No"},
        {"btnBonusPayableHead", ""},
        {"lblPenalIntRateVal", "Value"},
        {"lblAcceptableType12", "Class B"},
        {"btnBankingHead", ""},
        {"lblNoticeChargesHead", "Notice Charges A/c Head"},
        {"lblSpace4", "     "},
        {"rdoOnlyMembers_yes", "Yes"},
        {"lblBonusChitOwner2", "After Cash Payment"},
        {"lblMunnalBonusHead", "Munnal MDS A/c Head"},
        {"rdoDiscountPrizedPeriodMonth", "Months"},
        {"lblAcceptableType5", "All"},
        {"rdoLoanCanbeGranted_yes", "Yes"},
        {"panRateDetails", "Rate Details"},
        {"lblSpace3", "     "},
        {"lblAcceptableType10", "All"},
        {"lblHolidayInst", "If installment Date is a holiday, installment to be collected "},
        {"chkAcceptClassAll", ""},
        {"rdoPrizedChitOwner_yes", "Yes"},
        {"lblMaxLoanAmt", "Maximum Loan amount"},
        {"btnEdit", ""},
        {"rdoBonusAllowed_no", "No"},
        {"lblAuctionMaxAmtVal", "%"},
        {"lblAcceptType1", "Acceptable types "},
        {"btnThalayalReceiptsHead", ""},
        {"btnBonusReceivableHead", ""},
        {"lblMarginVal", "%"},
        {"btnPenalHead", ""},
        {"rdoOnlyMembers_no", "No"},
        {"rdoPrizedChitOwnerAfter_no", "No"},
        {"rdoBonusGraceAfter", "On or before"},
        {"chkAcceptClassA", ""},
        {"rdoChitDefaults_yes", "Yes"},
        {"rdoNonPrizedChit_no", "No"},
        {"lblChitDefaults", "If chit owners default in making payment of any"},
        {"rdoPrizedChitOwnerAfter_yes", "Yes"},
        {"rdoprizedDefaulters_no", "No"},
        {"lblBonusChitOwner3", "Prized chit owner is eligible for bonus after cash payment"},
        {"lblSuspenseHead", "Suspense A/c Head"},
        {"rdoDiscountPrizedPeriodEnd", "Month end"},
        {"lblReceiptHead", "Receipt A/c Head"},
        {"rdoNonPrizedChit_yes", "Yes"},
        {"panOnlyMembers", "                             "},
        {"lblStatus", "                      "},
        {"lblPenalPrizedPeriod", "Penal prized grace period"},
        {"lblPenalPeriod", "Penal grace period"},
        {"rdoSuretyRequired_yes", "Yes"},
        {"btnView", ""},
        {"rdoBonusGraceMonth", "Months"},
        {"lblMinLoanAmt", "Minimum Loan amount"},
        {"lblBonusAllowed", "Bonus Allowed"},
        {"lblSpace5", "     "},
        {"btnDelete", ""},
        {"rdoDiscountAllowed_no", "No"},
        {"lblAuctionMaxAmt", "In case of Auction, maximum bid amount"},
        {"rdoBonusGraceDays", "Days"},
        {"panDiscountPeriodDetails", "Discount Period Details"},
        {"rdoDiscountAllowed_yes", "Yes"},
        {"rdoBonusPrizedMonth", "Months"},
        {"lblBonusChitOwner1", "Whether Prized Money Holder Eligible For Bonus"},
        {"btnCancel", ""},
        {"lblPenalCalc", "Penal calculation based on"},
        {"lblThalayalReceiptsHead", "Thalayal MDS A/c Head"},
        {"lblSpace6", "     "},
        {"rdoDiscountPeriodEnd", "Month end"},
        {"lblBankingHead", "Bank Advance A/c Head"},
        {"panAcceptableType", ""},
        {"rdoBonusPrizedEnd", "Month end"} 

   };

}
