/*
 * Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition. 
 * 
 * frmHome.java
 *
 * Created on September 12, 2011, 10:33 AM
 */
package com.see.truetransact.ui.roomrent;

import com.see.truetransact.clientutil.ClientUtil;
/**
 *
 * @author  user
 */
public class frmHome extends com.see.truetransact.uicomponent.CFrame implements java.util.Observer  {
    
    /** Creates new form panBorrowings */
      
 frmRent frmRent;
 frmRentRegister frRentReg;
 frmRentTrans frrentTrans;
// frmStatus frstatus;
    public frmHome() {
        initComponents();
        initIntCompnents();
 
       // observable.addObserver(this);
    }
    private void setMaxLengths() {
       // txtUserID.setAllowAll(true);
       // txtPwd.setAllowAll(true);
        this.setBounds(0,0, 1350, 700);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        cButton1 = new com.see.truetransact.uicomponent.CButton();
        cDesktopPane1 = new com.see.truetransact.uicomponent.CDesktopPane();
        cButton3 = new com.see.truetransact.uicomponent.CButton();
        cButton4 = new com.see.truetransact.uicomponent.CButton();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        cButton1.setText("Rent");
        cButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        getContentPane().add(cButton1);
        cButton1.setBounds(10, 10, 130, 27);

        getContentPane().add(cDesktopPane1);
        cDesktopPane1.setBounds(0, 0, 0, 0);

        cButton3.setText("Rent Register");
        cButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        getContentPane().add(cButton3);
        cButton3.setBounds(10, 50, 130, 27);

        cButton4.setText("Rent Trans");
        cButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        getContentPane().add(cButton4);
        cButton4.setBounds(10, 90, 130, 27);

    }//GEN-END:initComponents
    public void initIntCompnents()
    {
     frmRent=new frmRent();
    
      getContentPane().add(frmRent);
      frmRent.setBounds(160,10,1000,600);
 
    }
    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
         //ClientUtil.displayAlert(evt.);
       // ClientUtil.displayAlert(evt.getActionCommand());
   //  initIntCompnents();
        if(evt.getActionCommand()=="Rent")
        {
            frmRent=new frmRent();
            getContentPane().add(frmRent);
            frmRent.setBounds(160,10,1000,600);
            frmRent.setVisible(true);

        }
        if(evt.getActionCommand()=="Rent Register")
        {
            frRentReg=new frmRentRegister();
            getContentPane().add(frRentReg);
            frRentReg.setBounds(160,10,1000,600);
            frRentReg.setVisible(true);

        }
         if(evt.getActionCommand()=="Rent Trans")
        {
            frrentTrans=new frmRentTrans();
            getContentPane().add(frrentTrans);
            frrentTrans.setBounds(160,10,1000,600);
            frrentTrans.setVisible(true);

        }
       
    }//GEN-LAST:event_btnNewActionPerformed
private void exitForm(java.awt.event.WindowEvent evt) {
        System.exit(0);
    }
   public static void main(String args[]) throws Exception {
        new frmHome().show();
    }
    public void update(java.util.Observable observable, Object obj) {
    }    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.see.truetransact.uicomponent.CButton cButton1;
    private com.see.truetransact.uicomponent.CButton cButton3;
    private com.see.truetransact.uicomponent.CButton cButton4;
    private com.see.truetransact.uicomponent.CDesktopPane cDesktopPane1;
    // End of variables declaration//GEN-END:variables
  
}
