/*
 * Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition.
 * 
 *
 * TermDepositRB.java
 *
 * Created on Wed Aug 18 15:18:50 GMT+05:30 2004
 */
package com.see.truetransact.ui.deposit.multipledeposit;

import java.util.ListResourceBundle;

public class MultipleTermDepositRB extends ListResourceBundle {

    public MultipleTermDepositRB() {
    }

    public Object[][] getContents() {
        return contents;
    }
    static final String[][] contents = {
        {"lblTotalAmount", "0"},
        {"lblTotalAmt", "Total Amount"},
        {"lblOnBehalfOf", "On Behalf of"},
        {"btnPowOfAttDel", "Delete"},
        {"lblValIntroducerDetailsCustomerId", ""},
        {"lblPowOfAttRemarks", "Remarks"},
        {"lblPowOfAttPoAHoldName", "PoA Holder's Name"},
        {"lblNomDetAreaCode", "Area Code"},
        {"lblNomDetPhone", "Phone"},
        {"chk15hDeclarations", ""},
        {"rdoOpeningMode_Multiple", "Multiple"},
        {"rdoIntroReqd_Yes", "Yes"},
        {"lblOtherCountry", "Country"},
        {"lblIssueDt", "Issue Date"},
        {"btnAuthSignSave", "Save"},
        {"lblPowOfAttArea", "Area"},
        {"lblAuthSignMobile", "Mobile"},
        {"lblValCity", ""},
        {"lblTaxDeductions", "Tax Deduction"},
        {"lblPowOfAttPincode", "Pincode"},
        {"lblProductDescription", ""},
        {"lblNomDetCity", "City"},
        {"lblPoaCustomerName", "Customer Name"},
        {"btnReject", ""},
        {"lblCategory", "Category"},
        {"lblDebAccDetDepNo", "Deposit No."},
        //        {"lblInterestPaymentMode", "Interest Payment Mode"},
        {"lblInterestPaymentMode", "Int Payment Mode"},
        {"panDocumentDetails", "Document Introduction"},
        {"btnPowOfAttNew", "New"},
        {"lblValCustomerName", ""},
        {"lblAuthSignPager", "Pager"},
        {"lblTotNomShare", "Total Nominee Share"},
        {"btnNomDetSave", "Save"},
        {"lblValIntroducerDetailsProductId", ""},
        {"lblValArea", ""},
        {"lblNomDetMinAddType", "Address Type"},
        {"lblTransferingBranchName", "Transfering Branch Name"},
        {"btnException", ""},
        {"btnStandInstDel", "Delete"},
        {"lblIdType", "Identity Type"},
        {"lblNominatedBy", "Nominated By"},
        {"btnSave", ""},
        {"lblPowOfAttPeriodTo", "Period To"},
        {"lblMaturityAmount", "Maturity Amt"},
        {"btnCustomerIdFileOpen", ""},
        {"lblArea", "Place"},
        {"btnDepSubNoAccDel", "Delete"},
        {"lblPowOfAttCity", "City"},
        {"lblCustomerName", "Customer Name"},
        {"lblPowerOfAttorney", "Power of Attorney"},
        {"lblPowOfAttPeriodFrom", "Period From"},
        {"lblValTransferingBranchName", ""},
        {"lblOtherState", "State"},
        {"lblNomDetMinPincode", "Pincode"},
        {"lblDebAccDetAccHeadShort", "xx"},
        {"lblAuthSignHomePhone", "Home Phone"},
        {"lblIntroducerDetailsAccountNumber", "Account Number"},
        {"lblDebAccDetAccHeadLong", "XXXX"},
        {"lblCustomerId", "Customer Id"},
        {"btnJointAcctNew", "New"},
        {"lblPeriod_Days", "Days"},
        {"lblInterBranchTransferNo", "Inter Branch Transfer No."},
        {"panStandInstCreditAccDet", "Credit Account Details"},
        {"lblNomDetArea", "Area"},
        {"lblNomDetStatus", "Status"},
        {"btnCredAccDetAccNo", ""},
        {"lblExpDt", "Expiry Date"},
        {"btnStandInstSave", "Save"},
        {"lblModeOfOpening", "Opening Mode"},
        {"panSelfIntroduction", "Self Introduction / Existing Customer"},
        {"rdoOpeningMode_TransferIn", "Transfer In"},
        {"lblNomDetAddType", "Address Type"},
        {"lblDepositAmount", "Deposit Amount"},
        {"lblIssAuth", "Issuing Authority"},
        {"lblSpace2", "     "},
        {"lblPowOfAttPhone", "Phone"},
        {"lblPeriodOfDeposit", "Period of Deposit"},
        {"lblSpace3", "     "},
        {"btnIntroducerDetailsAccountNumber", ""},
        {"lblSpace1", " Status :"},
        {"lblNomDetStreet", "Street"},
        {"btnNomDetNew", "New"},
        {"lblName", "Name"},
        {"lblOtherPin", "Pincode"},
        {"lblNo", "Number"},
        {"lblTotalInterestAmount", "Total Int. Amt"},
        {"lblNomDetMinDOB", "Date of Birth"},
        {"lblTransferingBranchCode", "Transfering Branch Code"},
        {"lblValAccountHead", "Acc Head"},
        {"lblCredAccDetParticulars", "Particulars"},
        {"lblDateOfDeposit", "Date of Deposit"},
        {"lblNomDetMinAreaCode", "Area Code"},
        {"lblDepositSubNo", "Deposit Sub No."},
        {"lblStreet", "House Name"},
        {"lblCity", "City"},
        {"lblAuthSignState", "State"},
        {"lblCredAccDetDepositNo", "Deposit No."},
        {"lblLastInstallmentReceivedDate", "Last Installment Received date"},
        {"lblAuthSignEmailId", "Email Id"},
        {"lblPaymentType", "Payment Type"},
        {"lblPaymentDate", "Payment Date"},
        {"btnAuthSignNew", "New"},
        {"lblAuthSignBusinessFax", "Business Fax"},
        {"lblStatus", "                      "},
        {"lblCredAccDetValAccHeadLong", "XXXX"},
        {"lblValState", ""},
        {"lblBalanceInterestPayable", "Balance Interest Payable"},
        {"lblDocType", "Document Type"},
        {"lblSpace5", "     "},
        {"lblNomDetNomSlNo", "Nominee Sl. No"},
        {"btnDelete", ""},
        {"lblNomDetMinArea", "Area"},
        {"lblDesig", "Designation"},
        {"lblOtherStreet", "Street"},
        //        {"lblInterestPaymentFrequency", "Interest Payment Frequency"},
        {"lblInterestPaymentFrequency", "Int Pay Freq"},
        {"btnStandInstNew", "New"},
        {"lblPoAAreaCode", "Area Code"},
        {"lblInstallmentAmount", "Installment Type"},
        {"lblIntroducerDetailsName", "Name"},
        {"panStandInstDebitAccDet", "Debit Account Details"},
        {"lblBranchName", "Branch Name"},
        {"panNomSlNo", "Nominee Details"},
        {"lblLastTdsCollected", "Last TDS Collected"},
        {"lblCommunicationAddress", "Comm. Address"},
        {"lblNomDetNomName", "Nominee Name"},
        {"lblPrintedNoOfTheFdr", "Printed No. of the FDR"},
        {"panNomMinor", "If Nominee is a Minor"},
        {"lblValCommunicationAddress", ""},
        {"lblBankName", "Bank Name"},
        {"btnClose", ""},
        {"btnNomDetDel", "Delete"},
        {"btnDepSubNoAccNew", "New"},
        {"btnAuthorize", ""},
        {"lblNomDetMinGdName", "Guardian Name"},
        {"lblAuthSignBusinessPhone", "Business Phone"},
        {"lblMsg", ""},
        {"lblNomDetMinCountry", "Country"},
        {"lblPin", "Pin"},
        {"btnDepSubNoAccSave", "Save"},
        {"lblInterestPaid", "Interest Paid"},
        {"lblAuthSignName", "Name"},
        {"lbl15hDeclarations", "15H Declaration"},
        {"lblPeriod_Months", "Months"},
        {"panOthers", "Others"},
        {"lblDebAccDetAccHead", "Account Head"},
        {"lblCredAccDetProductId", "Product Id"},
        {"btnPowOfAttSave", "Save"},
        {"lblAuthSignAddType", "Address Type"},
        {"lblNomDetCountry", "Country"},
        {"lblNomDetMinGnType", "Guardian Type"},
        {"lblNomDetRelationship", "Relationship"},
        {"chkPowerOfAttorney", ""},
        {"lblMember", "Member"},
        {"lblDebAccDetProductId", "Product Id"},
        {"lblAuthSignAreaCode", "Area Code"},
        {"lblOtherCity", "City"},
        {"lblDebAccDetDepSubNo", "Deposit Sub No."},
        {"lblNomDetMinState", "State"},
        {"lblNomDetPincode", "Pincode"},
        {"lblTransferingAmount", "Transferred Amount"},
        {"btnPrint", ""},
        {"lblOtherPhone", "Phone"},
        {"lblPanNumber", "Pan Number"},
        {"lblOriginalDateOfDeposit", "Original Date of Deposit"},
        {"lblAuthSignHomeFax", "Home Fax"},
        {"panDepositDetails", "Deposit Details"},
        {"lblInterestProvidedAmount", "Interest Provided Amount"},
        {"lblTotalInstallmentReceived", "Total Installment Received"},
        {"lblProductId", "Product Id"},
        {"lblValPin", ""},
        {"lblOtherArea", "Area"},
        {"lblDocNo", "Document Number"},
        {"lblNomineeDetails", "Nominee Details"},
        {"lblAuthorizedSignatory", "Authorized Signatory"},
        //        {"lblAuthorizedSignatory1","Signatory"}, 
        {"lblLastInterestCalculatedDate", "Last Interest Calculated Date"},
        {"btnAuthSignDel", "Delete"},
        {"lblAuthSignLimits", "Limits"},
        {"lblOnBehalfOf", "On Behalf of"},
        {"lblDateOfTransfer", "Date of Transfer"},
        {"lblDepositNo", "Deposit No."},
        {"chkNomineeDetails", ""},
        {"lblNomDetShare", "Share%"},
        {"btnNew", ""},
        {"lblAuthSignCountry", "Country"},
        {"lblCredAccDetAmt", "Amount"},
        {"lblPeriod_Years", "Yrs"},
        {"lblPowOfAttAddType", "Address Type"},
        {"lblNomDetMinPhone", "Phone"},
        {"panIdentity", "Identity Information"},
        {"chkAuthorizedSignatory", ""},
        {"btnJointAcctToMain", "To Main"},
        {"lblIntroducerDetailsProductId", "Product Id"},
        {"lblIntroName", "Introducer's Name"},
        {"lblRateOfInterest", "Rate of Int."},
        {"lblOtherAreaCode", "Area Code"},
        {"chkTaxDeductions", ""},
        {"lblValIntroducerDetailsAccountHead", ""},
        {"lblValStreet", ""},
        {"lblValDateOfBirth", ""},
        {"lblOriginalAccountNumber", "Original Account Number"},
        {"lblConstitution", "Constitution"},
        {"lblAddressType", "Comm. Address"},
        {"lblPowOfAttCountry", "Country"},
        {"panCustomerSide", "Customer Details"},
        {"lblCountry", "Country"},
        {"btnEdit", ""},
        {"lblPowOfAttStreet", "Street"},
        {"lblAuthSignStreet", "Street"},
        {"lblTdsCollectedUpto", "TDS Collected Upto"},
        {"lblMaturityDate", "Maturity Date"},
        {"lblValDepositSubNo", ""},
        {"lblValBalanceInterestPayable", ""},
        {"panLastInterestCalculatedDate", "Other Details"},
        {"lblAuthSignCity", "City"},
        {"lblIntroducerType", "Introducer Type"},
        {"lblAccNo", "Account Number"},
        {"lblCredAccDetAccHead", "Account Head"},
        {"lblValTotNomShare", "0"},
        {"lblIntroReqd", "Introduction Required"},
        {"lblAuthSignArea", "Area"},
        {"lblIntroducerDetailsAccountHead", "Account Head"},
        {"panInterBranchFunds", "Inter Branch Funds"},
        {"lblDateOfBirth", "Date of Birth"},
        {"lblAccountHead", "Account Head"},
        {"lblNomDetMinCity", "City"},
        {"lblIssBy", "Issued By"},
        {"lblDebAccDetParticulars", "Particulars"},
        {"btnTransBranchCodeHelp", ""},
        {"btnOriginalAccountNumberHelp", ""},
        {"lblValCountry", ""},
        {"lblAuthSignPincode", "Pincode"},
        {"lblCredAccDetValAccHeadShort", "xx"},
        {"btnJointAcctDel", "Delete"},
        {"lblAuthSignDesignation", "Designation"},
        {"rdoOpeningMode_Renewal", "Renewal"},
        {"lblAuthSignNumberOfAuthorizedSignatory", "No.of Authorized Signatory"},
        //        {"lblSettlementMode", "Repayment Instruction"},
        {"lblSettlementMode", "Repay Instruction"},
        {"lblTotalNumberOfInstallments", "Total Number of Installments"},
        {"lblNomDetState", "State"},
        {"panTransferingBranchCode", "Branch Details"},
        {"lblPeriodicInterestAmount", "Periodic Int. Amt"},
        {"lblRemarks", "Remarks"},
        {"lblPowOfAttState", "State"},
        {"lblProdDesc", "Product Desc"},
        {"lblNomDetMinStreet", "Street"},
        {"lblIntroducerDetailsCustomerId", "Customer Id"},
        {"panOtherBank", "Other Bank / Branch Introduction"},
        {"lblPowOfAttPoASlNo", "PoA Serial Number"},
        {"btnCancel", ""},
        {"lblValIntroducerDetailsName", ""},
        {"rdoIntroReqd_No", "No"},
        {"lblState", "State"},
        {"tblAuthSignColumn1", "Serial No."},
        {"tblAuthSignColumn2", "Name"},
        {"tblAuthSignColumn3", "Designation"},
        {"tblAuthSignColumn4", "Limits"},
        {"tblPoAColumn1", "PoA Serial No"},
        {"tblPoAColumn2", "PoA Holder"},
        {"tblPoAColumn3", "Period From"},
        {"tblPoAColumn4", "Period To"},
        {"tblNomColumn1", "Serial No"},
        {"tblNomColumn2", "Nominee Name"},
        {"tblNomColumn3", "Relationship"},
        {"tblNomColumn4", "Share"},
        {"dialogYes", "Yes"},
        {"dialogNo", "No"},
        {"dialogCancel", "Cancel"},
        {"dialogOk", "OK"},
        {"warningMessage", "This Record Already exist. Do you want to replace it?"},
        {"warningMessageOK", "This Record Already exists"},
        {"dialogForPowOfAtt", "This will reset the Power of Attorney data. Are you sure to reset it?"},
        {"dialogForAuthSign", "This will reset the Authorized Signatory data. Are you sure to reset it?"},
        {"dialogForNomDet", "This will reset the Nominee Details data. Are you sure to reset it?"},
        {"dialogForOpenMode", "This will reset the Transfer In data. Are you sure to reset it?"},
        {"dialogForIntroReq", "This will reset the Introducer details data. Are you sure to reset it?"},
        {"TOCommandError", "Error occured while saving"},
        {"tblDepSubNoColumn1", "Dep Sub No"},
        {"tblDepSubNoColumn2", "Deposit Amt"},
        {"tblDepSubNoColumn3", "Maturity Dt."},
        {"tblDepSubNoColumn4", "Total Int Amt"},
        {"tblDepSubNoRenewColumn1", "Dep Sub No"},
        {"tblDepSubNoRenewColumn2", "Deposit Amt"},
        {"tblDepSubNoRenewColumn3", "Deposit Dt."},
        {"tblDepSubNoRenewColumn4", "Total Int Amt"},
        {"checkDateDialog", "Deposit date should be less than Maturity Date"},
        {"checkInterest", "Rate of Interest should be less than 100"},
        {"dayCheck", "No. of Days should be less than 32"},
        {"monthCheck", "No. of Months should be less than 12"},
        {"shareWarning", "Share has to be between : "},
        {"maxCreditedAmountWarning", "Share has to be between : "},
        {"maturityDateNull", "Maturity Date is null!!"},
        {"selectProdId", "Select the Product Id before entering the Deposit Sub Account details!!"},
        {"selectOpeningMode", "Select the mode of opening before entering the Deposit Sub Account details!!"},
        {"selectCustomer", "Select the customer before entering the Deposit Sub Account details!!"},
        //this details filled with the present Position Details tab.... 
        {"lblAvailableBalance", "Available Balance"},
        {"lblClearBalance", "Clear Balance"},
        {"lblTotalBalance", "Total Balance"},
        {"lblTotalInterest", "Total Interest Amount"},
        {"lblLastInterestPaidDate", "Last Interest Paid Date"},
        {"lblPaidInterestAmount", "Total Interest Paid"},
        {"lblBalanceInterestAmount", "Balance Interest Payable"},
        {"lblAccHead", "GL Head"},
        {"lblDepositLienNo", "Deposit Lien No"},
        {"lblLienAmount", "Lien Amount"},
        {"lblLienDate", "Lien Date"},
        {"lblLoanNo", "Loan No"},
        {"lblLoanBalance", "Loan Balance"},
        {"lblLoanTakenDate", "Loan Taken Date"},
        {"lblTotalInterestPayable", "Total Interest Payable"},
        {"lblProductType", "Product Type"},
        {"lblProdId", "Prod Id"},
        {"lblAccountNo", "Account No"},
        {"lblCustomerNameCr", "Cust Name"},
        {"lblRenewalDate", "Renewed on Date"},
        //Standing instruction time will be adding...
        {"lblSINo", "Standing Instruction No"},
        {"lblSICreatedDate", "Created Date"},
        {"lblSIProductType", "Product Type"},
        {"lblSIProductId", "Product Id"},
        {"lblSIAccountNo", "Account No"},
        {"lblSIAmount", "Amount"},
        {"lblSIParticulars", "Particulars"},
        {"lblSIFrequency", "Frequency"},
        {"lblSIForwardCount", "Forward Count"},
        {"lblSIStartDate", "Start Date"},
        {"lblSIEndDate", "End Date"},
        {"lblAcceptanceCharges", "Acceptance Charges"},
        {"lblSIFailureCharges", "Failure Charges"},
        {"lblSIExecutionCharges", "Execution Charges"},
        {"lblClosedDate", "Closed Date"},
        {"lblClosingType", "Closing Type"},
        {"lblTransferOutBranch", "TransferOut Branch Name"},
        {"lblClosingRateOfInterest", "Closing Rate of Interest"},
        {"lblClosingInterestAmount", "Closing Interest Amount"},
        {"lbldepositPeriodRun", "Deposit Period Run"},
        {"lblDeathClaim", "Death Claim"},
        {"lblRenewalDate", "Date of Renewal"},
        {"lblRenewalDepositAc", "Renewal Deposit No"},
        {"lblSBRateOfInterest", "Period Run for SB Interest"},
        {"lblSBinterestAmount", "SB Interest Amount"},
        {"lblRenewalProdId", "Change the Product Id, If required"},
        {"lblRenewalCategory", "Change the Category, If required"},
        {"lblRenewalWithdrawingDeposit", "Want to withdraw from this deposit ?"},
        {"lblRenewalAddingDepTrans", "Want to add amount to this deposit ?"},
        {"lblRenewalDepTransAmt", "Amount"},
        {"lblRenewalDepositTransMode", "Mode of Withdrawal"},
        {"lblRenewalDepositTransProdType", "Product Type"},
        {"lblRenewalDepositTransProdId", "Product Id"},
        {"lblRenewalDepositTransAccNo", "Account No"},
        {"lblRenewalDepositTransCustName", "Customer Name"},
        {"lblRenewalDepositTransTokenNo", "Token No"},
        {"lblRenewalIntAmount", "Balance Interest Amount"},
        {"lblRenewalOldMaturityDate", "Old Deposit Maturity Date"},
        {"lblRenewalSBPeriod", "Period Run from Date of Maturity"},
        {"lblRenewalSBIntAmt", "SB Interest Amount"},
        {"lblRenewalInterestRepayAmt", "Total Interest to be Repayed"},
        {"lblRenewalWithdrawingIntAmt", "Want to withdraw interest amount ?"},
        {"lblRenewalIntAmt", "Amount"},
        {"lblRenewalInterestTransMode", "Mode of Withdrawal"},
        {"lblRenewalInterestTransProdType", "Product Type"},
        {"lblRenewalInterestTransProdId", "Product Id"},
        {"lblRenewalInterestTransAccNo", "Account No"},
        {"lblRenewalInterestCustName", "Customer Name"},
        {"lblRenewalInterestTokenNo", "Token No"},
        {"lblRenewlaDepositSubNo", "Deposit No"},
        {"lblRenewalDateOfDeposit", "Date of Deposit"},
        {"lblRenewalMaturityDate", "Maturity Date"},
        {"lblRenewalPeriodOfDeposit", "Period of Deposit"},
        {"lblRenewalInterestPaymentFrequency", "Int Pay Freq"},
        {"lblRenewalDepositAmount", "Deposit Amount"},
        {"lblRenewalRateOfInterest", "Rate of Int."},
        {"lblRenewalMaturityAmount", "Maturity Amt"},
        {"lblRenewalTotalInterestAmount", "Total Int. Amt"},
        {"lblRenewalPeriodicInterestAmount", "Periodic Int. Amt"},
        {"lblRenewalInterestPaymentMode", "Int Payment Mode"},
        {"lblRenewalProductType", "Product Type"},
        {"lblRenewalProdId", "Product Id"},
        {"lblRenewalAccountNo", "Account No"},
        {"lblRenewalCustomerNameCr", "Customer Name"},
        {"lblRenewalPrintedOption", "Printing No"},
        {"lblRenewalCalenderFreq", "Calender Frequency"},
        {"lblRenewalCalenderFreqDate", "Calender Frequency Day"},
        {"lblRenewalNoticeNew", "Renewal Notice"},
        {"lblAutoRenewalNew", "Auto Renewal"},
        {"lblRenewalWithIntNew", "Auto Renewal with Int"},
        {"lblExtensionDepositDate", "Old Deposit Date"},
        {"lblExtensionDepositProdId", "Change the Product Id, If required"},
        {"lblExtensionCategory", "Change the Category, If required"},
        {"lblExtensionPaymentFreq", "Interest Payment Frequency"},
        {"lblExtensionPeriodRun", "Actual Period Run"},
        {"lblExtensionRateOfInt", "Rate of Interest"},
        {"lblExtensionWithdrawingDeposit", "Do you want to withdraw deposit Amt ?"},
        {"lblExtensionDepTransAmt", "Amount"},
        {"lblExtensionofPrematureClosure", "Premature Closure for Extension"},
        {"lblExtensionTotalRepayAmt", "Total amount to be Repayed"},
        {"lblExtensionWithdrawingIntAmt", "Do you want to withdraw interest amt?"},
        {"lblExtensionIntAmt", "Amount"},
        {"lblExtensionWithdrawIntAmt", "aaaaaaaaaaaaaaaaa"},
        {"lblExtensionLeftOverIntAmt", "bbbbbbbbbbbbbbbbb"},
        {"lblExtensionTotalIntAmt", "cccccccccccccc"},
        {"lblExtensionBalanceInt", "ddddddddddddd"},
        {"lblExtensionInterestTransMode", "Mode of Transaction"},
        {"lblExtensionInterestTransProdType", "Product Type"},
        {"lblExtensionInterestTransProdId", "Product Id"},
        {"lblExtensionInterestTransAccNo", "Account No"},
        {"lblExtensionInterestCustName", "Customer Name"},
        {"lblExtensionDepositTransTokenNo", "Token No"},
        {"lblExtensionDepositSubNo", "Deposit Sub No"},
        {"lblExtensionDateOfDeposit", "Date of Deposit"},
        {"lblExtensionPeriodOfDeposit", "Period of Deposit"},
        {"lblExtensionMaturityDate", "Maturity Date"},
        {"lblExtensionInterestPaymentFrequency", "Int Pay Freq"},
        {"lblExtensionDepositAmount", "Deposit Amount"},
        {"lblExtensionRateOfInterest", "Rate of Int."},
        {"lblExtensionMaturityAmount", "Maturity Amt"},
        {"lblExtensionTotalInterestAmount", "Total Int. Amt"},
        {"lblExtensionPeriodicInterestAmount", "Periodic Int. Amt"},
        {"lblExtensionInterestPaymentMode", "Int Payment Mode"},
        {"lblExtensionProductType", "Product Type"},
        {"lblExtensionProdId", "Product Id"},
        {"lblExtensionAccountNo", "Account No"},
        {"lblExtensionCustomerNameCr", "Customer Name"},
        {"lblExtensionCalenderFreq", "Calender Frequency"},
        {"lblExtensionCalenderFreqDate", "Calender Frequency Day"},
        {"lblExtensionMatAlertRep", "Renewal Notice"},
        {"lblExtensionAutoRenewal", "Auto Renewal"},
        {"lblExtensionWithIntAutoRenewal", "Auto Renewal with Int"},
        {"lblExtensionPrintedOption", "Printing No"},
        {"REMARK_CASH_TRANS", "Cash Transaction Token No"},
        {"REMARK_TRANSFER_TRANS", "Transfer Transaction Operative Account No"},
        {"lblSalaryRecovery", "Salary Recovery"},
        {"rdoSalaryRecovery_Yes", "Yes"},
        {"rdoSalaryRecovery_No", "No"},
        {"lblLockStatus", "Lock Status"}
    };
}
