/*
 * Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition. 
 * 
 * IndendMaster.java
 *
 * Created on September 12, 2011, 6:27 PM
 */

package com.see.truetransact.ui.indend;

import com.see.truetransact.uicomponent.CInternalFrame;
/**
 *
 * @author  user
 */
public class IndendMaster extends CInternalFrame {
  // private BorrowingTransOB observable; 
    /** Creates new form frmRepaymentInterest */
    public IndendMaster() {
        initComponents();
        initdetails();
        //  observable = new BorrowingTransOB();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        cTabbedPane1 = new com.see.truetransact.uicomponent.CTabbedPane();
        mbrTokenConfig = new com.see.truetransact.uicomponent.CMenuBar();
        mnuProcess = new javax.swing.JMenu();
        mitNew = new javax.swing.JMenuItem();
        mitEdit = new javax.swing.JMenuItem();
        mitDelete = new javax.swing.JMenuItem();
        sptView = new javax.swing.JSeparator();
        mitSave = new javax.swing.JMenuItem();
        mitCancel = new javax.swing.JMenuItem();
        sptCancel = new javax.swing.JSeparator();
        mitClose = new javax.swing.JMenuItem();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(860, 665));
        setPreferredSize(new java.awt.Dimension(860, 665));
        getContentPane().add(cTabbedPane1, java.awt.BorderLayout.CENTER);

        mbrTokenConfig.setInheritsPopupMenu(true);
        mnuProcess.setText("Indend Master");
        mnuProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProcessActionPerformed(evt);
            }
        });

        mitNew.setText("New");
        mnuProcess.add(mitNew);

        mitEdit.setText("Edit");
        mnuProcess.add(mitEdit);

        mitDelete.setText("Delete");
        mnuProcess.add(mitDelete);

        mnuProcess.add(sptView);

        mitSave.setText("Save");
        mnuProcess.add(mitSave);

        mitCancel.setText("Cancel");
        mnuProcess.add(mitCancel);

        mnuProcess.add(sptCancel);

        mitClose.setText("Close");
        mnuProcess.add(mitClose);

        mbrTokenConfig.add(mnuProcess);

        setJMenuBar(mbrTokenConfig);

        pack();
    }//GEN-END:initComponents

    private void mnuProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProcessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuProcessActionPerformed
    public void initdetails()
    {
        cpanel1=new frmSale();
      
        cpanel0=new frmStore();
        cpanel2=new frmDepo();
        cTabbedPane1.addTab( "Sales", cpanel1);
       cTabbedPane1.addTab( "Store", cpanel0);
	cTabbedPane1.addTab( "Depo",cpanel2);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.see.truetransact.uicomponent.CTabbedPane cTabbedPane1;
    private com.see.truetransact.uicomponent.CMenuBar mbrTokenConfig;
    private javax.swing.JMenuItem mitCancel;
    private javax.swing.JMenuItem mitClose;
    private javax.swing.JMenuItem mitDelete;
    private javax.swing.JMenuItem mitEdit;
    private javax.swing.JMenuItem mitNew;
    private javax.swing.JMenuItem mitSave;
    private javax.swing.JMenu mnuProcess;
    private javax.swing.JSeparator sptCancel;
    private javax.swing.JSeparator sptView;
    // End of variables declaration//GEN-END:variables
   private frmSale cpanel1;
   // private Closure cpanel2;
   private frmStore cpanel0;
   private frmDepo cpanel2;
 //  
}
