UPDATE LOOKUP_MASTER SET LOOKUP_ID = 'DATA.CORRECTION_TYPE_VERSION1.0' 
WHERE LOOKUP_ID = 'DATA.CORRECTION_TYPE';

SET DEFINE OFF;
Insert into LOOKUP_MASTER
   (LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC, STATUS, EDITABLE, 
    AUTHORIZED)
 Values
   ('DATA.CORRECTION_TYPE', 'NARRATION_CHANGE', 'Particulars Change', 'CREATED', NULL, 
    'Y');
Insert into LOOKUP_MASTER
   (LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC, STATUS, EDITABLE, 
    AUTHORIZED)
 Values
   ('DATA.CORRECTION_TYPE', 'HEAD_CHANGE', 'Account Head Change', 'CREATED', NULL, 
    'Y');
Insert into LOOKUP_MASTER
   (LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC, STATUS, EDITABLE, 
    AUTHORIZED)
 Values
   ('DATA.CORRECTION_TYPE', 'GOLD_ITEM_CHANGE', 'Gold Item Change', 'CREATED', NULL, 
    'Y');
Insert into LOOKUP_MASTER
   (LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC, STATUS, EDITABLE, 
    AUTHORIZED)
 Values
   ('DATA.CORRECTION_TYPE', 'GOLD_WEIGHT_CHANGE', 'Gold Weight Change', 'CREATED', NULL, 
    'Y');
Insert into LOOKUP_MASTER
   (LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC, STATUS, EDITABLE, 
    AUTHORIZED)
 Values
   ('DATA.CORRECTION_TYPE', 'TRANS_TYPE_INTERCHANGE', 'Transaction Type Inter Change', 'CREATED', NULL, 
    'Y');
Insert into LOOKUP_MASTER
   (LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC, STATUS, EDITABLE, 
    AUTHORIZED)
 Values
   ('DATA.CORRECTION_TYPE', 'AB_TO_ALL_ACTNO_CHANGE', 'Other Bank Account Number Change', 'CREATED', NULL, 
    'Y');
Insert into LOOKUP_MASTER
   (LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC, STATUS, EDITABLE, 
    AUTHORIZED)
 Values
   ('DATA.CORRECTION_TYPE', 'OA_TO_ALL_ACTNO_CHANGE', 'Operative Account Number Change', 'CREATED', NULL, 
    'Y');
Insert into LOOKUP_MASTER
   (LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC, STATUS, EDITABLE, 
    AUTHORIZED)
 Values
   ('DATA.CORRECTION_TYPE', 'SA_TO_ALL_ACTNO_CHANGE', 'Suspense Account Number Change', 'CREATED', NULL, 
    'Y');
Insert into LOOKUP_MASTER
   (LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC, STATUS, EDITABLE, 
    AUTHORIZED)
 Values
   ('DATA.CORRECTION_TYPE', 'TRANS_AMT_CHANGE', 'Transaction Amount Change', 'CREATED', NULL, 
    'Y');
COMMIT;


SET DEFINE OFF;
Insert into LOOKUP_MASTER
   (LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC, STATUS, EDITABLE, 
    AUTHORIZED)
 Values
   ('DATA.CORRECTION_TYPE', 'GL_TO_ACTNO_MAPPING', 'GL To Account Number Change', 'CREATED', NULL, 
    'Y');
COMMIT;
