/*Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition.
 * 
 * 
 **/
package com.see.truetransact.ui.customer.security;
import java.util.ListResourceBundle;
/* 
 *@author shanmugavel
 */
public class SecurityInsuranceRB extends ListResourceBundle {
    public SecurityInsuranceRB(){
    }

    public Object[][] getContents() {
        return contents;
    }

    static final String[][] contents = {
        {"panSecutityDetails_Table", "Margin"},
        {"lblQIS", "QIS"},
        {"lblFDate", "From Date"},
        {"btnSecurityDelete", "Delete"},
        {"rdoMultiDisburseAllow_No", "No"},
        {"lblCustName", "Customer Name"},
        {"lblInsuranceNo_Display", "Insurance No."},
        {"lblAccLimit", "Account Limit"},
        {"btnDelete_Sec", "Delete"},
        {"chkPrioritySector", ""},
        {"lblPremiumAmt", "Premium Amount"},
        {"chkMoraGiven", ""},
        {"lblScheduleNo", "Schedule No."},
        {"lblInsuranceNo_Disp", "Insurance No."},
        {"lblRefinancingInsti", "Refinancing Institution"},
        {"lblInterExpLimit", "Interest For Expiry of Limit"},
        {"lblPoaHolderName", "PoA Holder's Name"},
        {"btnInterestMaintenanceNew", "New"},
        {"lblInsureCompany", "Insurance Company"},
        {"lblForMillIndus", "For Mills / Industrial Users"},
        {"chkDocumentcomplete", ""},
        {"btnInterestMaintenanceSave", "Save"},
        {"lblCategory", "Category"},
        {"lblRiskRating", "Risk Rating"},
        {"rdoPostDatedCheque_No", "No"},
        {"lblAgainstClearingInter", "Against Clearing Interest"},
        {"lblCustID", "Customer ID"},
        {"lblMoraGiven", "Moratorium to be Given"},
        {"btnNew1", "New"},
        {"lblDateEstablishment", "Date of Establishment"},
        {"lblRepayFreq_Repayment", "Repayment Frequency"},
        {"lblPenalInter", "Penal Interest %"},
        {"lblLastInstall", "Last Installment Date"},
        {"lblTotalBaseAmt", "Total Base Amount"},
        {"lblLimitAmt", "Limit Amount"},
        {"lblAmtLastInstall", "Amount for Last Installment"},
        {"btnSave", ""},
        {"chkECGC", ""},
        {"lblDemandPromNoteExpDate", "Expiry Date"},
        {"lblSanctionDate", "Sanction Date"},
        {"lblSecurityType", "Security Type"},
        {"lblLimitAmount", "Limit Amount"},
        {"btnNew_PoA", "New"},
        {"rdoInterest_Simple", "Simple"},
        {"lblDateInspection", "Date of Inspection"},
        {"btnSave1", "Save"},
        {"lblPolicyNumber", "Policy Number"},
        {"rdoAccLimit_Submit", "Sub-Limit"},
        {"lblDemandPromNoteDate", "Issue Date"},
        {"lblChiefExecutiveName", "Chief Executive's Name"},
        {"rdoSecurityType_Primary", "Primary"},
        {"lblCommodityCode", "Commodity Code"},
        {"lblNatureCharge", "Nature of Charge"},
        {"btnInterestMaintenanceDelete", "Delete"},
        {"lblECGC", "ECGC"},
        {"lblToAmt", "To Amount"},
        {"btnNew_Sec", "New"},
        {"lblExpiryDate", "Expiry Date"},
        {"panCompanyDetailsTrash", "Company Details"},
        {"lblDistrictCode", "District Code"},
        {"lblOpenDate2", ""},
        {"lblRepayFreq", "Repay. Frequency"},
        {"lblRecarable", "Recarable"},
        {"lblFromAmt", "From Amount"},
        {"lblExpiryDate_2", ""},
        {"chkDirectFinance", ""},
        {"lblSpace2", "     "},
        {"lblSpace3", "     "},
        {"lblHealthCode", "Health Code"},
        {"lblPolicyAmt", "Policy Amount"},
        {"btnAuthorizedNew", "New"},
        {"lblSpace1", " Status :"},
        {"lblCustomerID", "Customer ID"},
        {"lblPostDatedCheque", "Post Dated Cheques Allowed"},
        {"chkGurantor", "Guarantor"},
        {"lblTypeOfFacility", "Type of Facility"},
        {"panSecurityDetails_FD", "Security Details"},
        {"btnsave_Sec", "Save"},
        {"btnSecurityNew", "New"},
        {"lblOpenDate", "Opening Date"},
        {"lblPolicyDate", "Policy Date"},
        {"lblTo", "To Date"},
        {"lblTotalInstallAmt", "Total Installment Amount"},
        {"lblIndusCode", "Industry Code"},
        {"lblAODDate", "AOD Date"},
        {"chkInsurance", "Insurance"},
        {"panSecurityDetails", "Security Details"},
        {"lblCreditFacilityAvailSince", "Credit Facilities Availed Since"},
        {"lblLaonAmt", "Loan Amount"},
        {"panInsuranceDetails", "Insurance Details"},
        {"lblStatus", "                      "},
        {"btnDelete", ""},
        {"lblInterest", "Interest"},
        {"btnAuthorizedDelete", "Delete"},
        {"lblSecurityNo", "Security No."},
        {"lblNatureInterest", "Nature of Interest"},
        {"rdoSubsidy_No", "No"},
        {"lblPurposeCode", "Purpose Code"},
        {"btnDelete1", "Delete"},
        {"lblDrawingPower_2", ""},
        {"btnAuthorizedSave", "Save"},
        {"btnCustID", ""},
        {"lblLimits", "Limits"},
        {"lblRiskWeight", "Risk Weight"},
        {"btnClose", ""},
        {"lblFromDate", "From Date"},
        {"rdoAccType_Transfered", "Transfered"},
        {"lblAddressType", "Address Type"},
        {"rdoNatureInterest_PLR", "PLR"},
        {"lblMsg", ""},
        {"lblLimit_SD", "Limit"},
        {"lblSancDate", "Sanction Date"},
        {"lblSubsidy", "Subsidy"},
        {"lblModeSanction", "Mode of Communication"},
        {"lblAmtPenulInstall", "Amount for Penultimate Installments"},
        {"rdoSecurityDetails_Unsec", "Unsecured"},
        {"lblDocumentcomplete", "Document Complete"},
        {"lblRepaymentCode", "Repayment Code"},
        {"lblTDate", "To Date"},
        {"lblPLR_Limit", "PLR"},
        {"lblSecurityValue", "Security Value"},
        {"btnGuarantorSave", "Save"},
        {"lblDrawingPower", "Drawing Power"},
        {"lblSanctioningAuthority", "Sanctioning Authority"},
        {"lblDateCharge", "Date of Charge"},
        {"lblFrom", "From Date"},
        {"lblDoAddSIs", "Do You Want to Add SIs?"},
        {"lblNetWorth", "Net Worth"},
        {"btnPrint", ""},
        {"rdoRecarable_Yes", "Yes"},
        {"lblNoInstallments", "No. of Installments"},
        {"btnCustomerID", ""},
        {"lblLimitAmt_2", ""},
        {"lblSancDate_2", ""},
        {"lblPrioritySector", "Priority Sector"},
        {"lblState_CompDetail", "State"},
        {"lblProductId", "Product ID"},
        {"lblProductID_FD", "Product ID"},
        {"lblProductID_FD_Disp", ""},
        {"rdoRiskWeight_No", "No"},
        {"lblFirstInstall", "First Installment Date"},
        {"btnSave_PoA", "Save"},
        {"lblSanctionDate2", ""},
        {"lblRepayType", "Repayment Type"},
        {"lblGroupDesc", "Group Description"},
        {"lblSectorCode1", "Sector Code"},
        {"lblGuaranName", "Name"},
        {"rdoDoAddSIs_No", "No"},
        {"rdoRecarable_No", "No"},
        {"rdoPostDatedCheque_Yes", "Yes"},
        {"lblAvalSecVal", "Available Security Value"},
        {"btnNew", ""},
        {"lblDirectFinance", "Direct Finance"},
        {"btnSecuritySave", "Save"},
        {"lblAson", "As On"},
        {"lblDealingWithBankSince", "Dealing With the Bank Since"},
        {"chkQIS", ""},
        {"lblTypeFacility", "Type of Facility"},
        {"lblGuarantorNo", "Guarantor Number"},
        {"rdoAccLimit_Main", "Main"},
        {"lblInterestType", "Interest Type"},
        {"lblConstitution", "Constitution"},
        {"rdoSecurityDetails_Fully", "Fully Secured"},
        {"rdoSecurityDetails_Partly", "Partly Secured"},
        {"lblArea_CompDetail", "Area"},
        {"btnGuarantorDelete", "Delete"},
        {"lbl20Code", "20 Code"},
        {"lblContactPerson", "Contact Person"},
        {"btnEdit", ""},
        {"lblReferences", "References"},
        {"rdoDoAddSIs_Yes", "Yes"},
        {"lblSelCommodityItem", "Selective Commodity Item"},
        {"rdoRiskWeight_Yes", "Yes"},
        {"rdoNatureInterest_NonPLR", "Non-PLR"},
        {"chkStockInspect", "Stock / Inspection"},
        {"lblGuaranteeCoverCode", "Guarantee Cover Code"},
        {"lblPin_CompDetail", "PIN Code"},
        {"lblNoInstall", "No. of Installments"},
        {"lblMultiDisburseAllow", "Multiple Disbursement Allowed"},
        {"rdoMultiDisburseAllow_Yes", "Yes"},
        {"lblNatureBusiness", "Nature of Business"},
        {"lblCustName_2", ""},
        {"chkSelCommodityItem", ""},
        {"lblStockStateFreq", "Stock Statement Frequency"},
        {"lblRemarks", "Remarks"},
        {"panDemandPromssoryDate", "Demand Promissory Note"},
        {"lblAge", "Age"},
        {"lblExpityDate", "Expiry Date"},
        {"lblNPADate", "NPA Date"},
        {"lblAsOn", "As On"},
        {"lblPLR_Limit_2", ""},
        {"lblNatureRisk", "Nature of Risk Covered"},
        {"lblSecurityCate", "Security Category"},
        {"rdoSecurityType_Collateral", "Collateral"},
        {"lblPurposeDesc", "Purpose Description"},
        {"lblToDate", "To Date"},
        {"lblParticulars", "Particulars"},
        {"lblGovtSchemeCode", "Govt. Scheme Code"},
        {"btnCancel", ""},
        {"lblProdID_IDetail", "Product ID"},
        {"btnSave2_SD", "Save"},
        {"btnNew2_SD", "New"},
        {"btnDelete2_SD", "Delete"},
        {"btnFacilitySave", "Save"},
        {"btnFacilityDelete", "Delete"},
        {"btnNew_Insurance", "New"},
        {"btnSave_Insurance", "Save"},
        {"btnDelete_Insurance", "Delete"},
        {"lblSecurityNo_Insurance", "Security No."},
        {"lblRemark_Insurance", "Remarks"},
        {"lblTotalSecurity_Value", "Total Security Value"},
        {"lblCustID", "Customer ID"},
        {"lblCustID_Disp", ""},
        {"lblCustName", "Name"},
        {"lblCustName_Disp", ""},
        {"lblCustStreet", "Street"},
        {"lblCustStreet_Disp", ""},
        {"lblCustCity", "City"},
        {"lblCustCity_Disp", ""},
        {"lblCustEmail_ID", "Email ID"},
        {"lblCustEmail_ID_Disp", ""},
        {"lblCustPin", "PIN Code"},
        {"lblCustPin_Disp", ""},
        {"lblNetWeight", "NetWeight"},
        {"lblGrossWeight", "GrossWeight"},
        {"panSecurityDetails_Cust", "Customer Details"},
        
        //TO ADD MANUALLY...
        {"tblColumnSecurityNo", "Security No."},
        {"tblColumnSecurityValue", "Value"},
        {"tblColumnSecurityCategory", "Category"},
        {"tblColumnSecurityAson", "As on"},
        
        {"tblColumnLoanBorrowNo", "Borrower No"},
        {"tblColumnLoanAcctNo", "Account No"},
        {"tblColumnLoanFromDt", "From Date"},
        {"tblColumnLoanToDt", "To Date"},
        {"tblColumnLoanMargin", "Margin"},
        {"tblColumnLoanAmt", "Security Amount"},
        
        {"tblColumnInsuranceNo", "I No."},
        {"tblColumnInsuranceSecrityNo", "Security No."},
        {"tblColumnInsuranceCompany", "Company"},
        
        {"cDialogYes", "Yes"},
        {"cDialogNo", "No"},
        {"cDialogCancel", "Cancel"},
        {"cDialogOk", "Ok"},
        
        {"hasInsuranceWarning", " has Insurance Details."},
        {"hasSecurityWarning", " has Security Details."},
        {"securityValueWarning", "Atleast one Security details have to be entered."},
        {"securityNoSelectedWarning", " is already having Insurance."},
        {"insuranceNoSelectedWarning", " is already having Security."},
        {"insuranceDoesntExistWarning", " don't have Security Details."},
        {"insuranceAmtLessThanSecAmtWarning", "Insurance Amount is than the Security Amount for Security No(s) "},
        {"securityTableWarning", "Security Table is in Edit mode."},
        {"insuranceTableWarning", "Insurance Table is in Edit mode."}
        
   };

}
