/*
 * Copyright 2003-2020 FINCuro Solutions Pvt Ltd. All rights reserved.
 *
 * This software and its components are the property of FINCuro Solutions Pvt Limited and its affiliates, through authorship and acquisition.  
 * 
 * TermLoanMRB.java
 */

package com.see.truetransact.ui.termloan;
import java.util.ListResourceBundle;
public class TermLoanMRB extends ListResourceBundle {
    public TermLoanMRB(){
    }

    public Object[][] getContents() {
        return contents;
    }

    static final String[][] contents = {
        {"rdoYes_Executed_DOC", ""},
        {"rdoNo_Executed_DOC", ""},
        {"rdoYes_Mandatory_DOC", ""},
        {"rdoNo_Mandatory_DOC", ""},
        {"txtRepayScheduleMode", "Repayment Schedule Mode."},
        {"txtAcct_Name", "Enter the Account Name."},
        {"tdtExecuteDate_DOC", "Enter the Document Executed Date."},
        {"tdtExpiryDate_DOC", "Enter the Document Expiry Date."},
        {"tdtDisbursement_Dt", "Enter the Loan Disbursement Date."},
        {"txtEligibleLoan", "Enter the Loan Eligible against Security."},
        {"cboIntGetFrom", "Enter the Interest get from field."},
        {"cboAddrType_PoA", "Enter the Address Type of PoA Holder."},
        {"txtPoANo", " "},
        {"cboProdID_IDetail", "Product ID should be a proper value!!!"},
        {"cboGuaranteeCoverCode", "Choose Guarantee Cover Code"},
        {"tdtFrom", "Enter the date on which the interest slab comes into effect"},
        {"txtGuaranAccNo", "Enter the Main Account Number of the Guarantor"},
        {"rdoNatureInterest_PLR", "Nature of Interest should be selected!!!"},
        {"rdoActive_Repayment", "Repayment Schedule is active?"},
        {"rdoInActive_Repayment", "Repayment Schedule is active?"},
        {"tdtCreditFacilityAvailSince", "Credit Facility Available Since should not be empty!!!"},
        {"chkPrioritySector", "Priority Sector should be selected!!!"},
        {"chkMoraGiven", "Moratorium have to give?"},
        {"chkMoratorium_Given", "Moratorium have to give?"},
        {"cboRepayFreq", "Select the Repayment frequency"},
        {"txtPin_GD", "Enter the PIN Code"},
        {"cboCity_CompDetail", "Choose the City"},
        {"txtPremiumAmt", "Enter the Premium Amount"},
        {"txtPolicyNumber", "Enter the Policy Number"},
        {"cbo20Code", "Choose the 20Code"},
        {"txtAgainstClearingInter", "Enter the Against Clearing Interest"},
        {"txtLimits", "Enter the Limit"},
        {"txtChiefExecutiveName", "Enter the Chief Executive Name"},
        {"tdtPeriodTo_PowerAttroney", "Enter the date up to which the PoA is being granted."},
        {"txtArea_CompDetail", "Enter the Area"},
        {"cboCommodityCode", "Choose the Commodity Code"},
        {"txtSecurityNo", "Enter the Security Number"},
        {"rdoSecurityDetails_Unsec", "Select the Security Details"},
        {"txtNoMonthsMora", "Enter the Number of Months for Moratorium"},
        {"tdtFacility_Repay_Date", "Enter the Repayment Date"},
        {"txtFacility_Moratorium_Period", "Enter the Number of Months for Moratorium"},
        {"chkDocumentcomplete", "Check Document complete"},
        {"txtNoInstall", "Enter the Number of Installments"},
        {"txtTotalInstallAmt", "Enter the Total Installment Amount"},
        {"txtPager_AuthorizedSignatory", "Enter the Pager number."},
        {"txtCompanyRegisNo", "Enter the Registration Number."},
        {"tdtLastInstall", "Enter the Last Installment Date"},
        {"txtAmtLastInstall", "Enter the last installment amount"},
        {"tdtToDate", "Enter the To Date"},
        {"txtNoInstallments", "Enter the number of installments"},
        {"txtPin_CompDetail", "Enter the PIN Code"},
        {"rdoSubsidy_Yes", "Subsidy should be selected!!!"},
        {"txtFromAmt", "Enter the initial/starting amount of the slab"},
        {"cboProdID_CD", "Product ID should be a proper value!!!"},
        {"txtPenalStatement", "Enter the Penal Statement %"},
        {"tdtPeriodFrom_PowerAttroney", "Enter the date from which the PoA is being granted."},
        {"cboIndusCode", "Choose the Industry Code"},
        {"tdtPolicyDate", "Enter the Date of Policy"},
        {"txtGuarantorNetWorth", "Enter the Guarantor�s Net worth"},
        {"txtLimit_SD", "Enter the Limit Amount Sanctioned"},
        {"txtLimit_SD2", "Enter the Intial Money Deposit"},
        {"txtNetWorth", "Enter the Net Worth"},
        {"txtContactPerson", "Enter the Contact Person�s Name"},
        {"chkECGC", "ECGC should be selected!!!"},
        {"cboCategory", "Select the Category of the borrower"},
        {"txtCustID_Security", "Select the Customer ID"},
        {"cboSecurityNo_Insurance", "Select the Security Number"},
        {"cboRepayFreq_Repayment", "Select the Repayment Frequency"},
        {"txtPin_PowerAttroney", "Enter the PIN Code."},
        {"cboState_PowerAttroney", "Choose a  State"},
        {"cboForMillIndus", "Select the appropriate value"},
        {"tdtTo", "Enter the To Date"},
        {"rdoInterest_Simple", "Select the Interest type"},
        {"cboStockStateFreq", "Select the Frequency of Stock Statement Submission"},
        {"cboAccStatus", "Select the Account status"},
        {"tdtDateCharge", "Enter the date of creation / registration of charge"},
        {"txtHomeFax_AuthorizedSignatory", "Enter the Home Fax number."},
        {"tdtDateEstablishment", "Enter the date of Establishment of the firm"},
        {"rdoSecurityType_Primary", "Select the security type"},
        {"txtCustomerID_GD", "Enter the Customer ID, if Known else select using the Selection Button"},
        {"cboCity_GD", "Choose the City"},
        {"rdoPostDatedCheque_Yes", "Whether Post dated cheques are allowed for repayment of installments?"},
        {"cboState_AuthorizedSignatory", "Choose a  State"},
        {"txtReferences", "Enter the References"},
        {"txtPhone_GD", "Enter the Phone Number"},
        {"cboInterestType", "Choose the Interest Type"},
        {"txtGuaranName", "Enter the Guarantor Name"},
        {"txtInsureCompany", "Enter the Name of the Insurance Company"},
        {"tdtDateInspection", "Enter the date of last Inspection"},
        {"tdtExpityDate", "Enter the Expiry Date of the Policy"},
        {"tdtAccountOpenDate","Enter the Loan Account Open Date"},
        {"cboRecommendedByType","Choose the Recommended Person"},
        {"cboTypeFacility", "Choose the Type of Facility"},
        {"cboNatureCharge", "Select the Nature of Charge"},
        {"cboDistrictCode", "Choose the District Code"},
        {"cboCity_PowerAttroney", "Choose a  City"},
        {"txtName_AuthorizedSignatory", "Enter the Name of the Authorized Signatory"},
        {"cboTypeOfFacility", "Select the Type of Facility"},
        {"tdtAODDate", "Enter the Date of Acknowledgement of Debt."},
        {"cboConstitution_GD", "Select the constitution"},
        {"txtStreet_PowerAttroney", "Enter the Address type of the PoA Holder."},
        {"txtCustomerID", "Enter the Customer ID"},
        {"txtPhone_CompDetail", "Enter the Phone Number"},
        {"cboWeakerSectionCode", "Choose the Weaker Section Code"},
        {"txtAmtPenulInstall", "Enter the Amount For Penultimate Installment"},
        {"cboProductId", "Select the Product ID under which the loan is sanctioned"},
        {"cboSanctioningAuthority", "Select the Authority who sanctioned the Loan"},
        {"cboprodID_IM", "Product ID should be a proper value!!!"},
        {"txtTotalBaseAmt", "Enter the Total Base Amount"},
        {"txtSanctionRemarks", ""},
        {"cboHealthCode", "Choose the Health Code"},
        {"tdtFDate", "Enter the From Date"},
        {"txtPurposeDesc", "Enter the Purpose for which the Loan is sanctioned"},
        {"chkQIS", "QIS should be selected!!!"},
        {"cboAddrCommunication_AuthorizedSignatory", "Enter the Address type of the Authorized Signatory"},
        {"cboAddressType", "Choose the Address Type"},
        {"chkDirectFinance", "Direct Finance should be selected!!!"},
        {"cboCountry_PowerAttroney", "Choose a  Country"},
        {"txtContactPhone", "Enter the Contact Phone Number"},
        {"txtStreet_CompDetail", "Enter the Street"},
        {"txtSanctionNo", "Enter the Sanction Number."},
        {"rdoAccLimit_Main", "Account Limit should be selected!!!"},
        {"txtRiskRating", "Enter the Risk Rate"},
        {"txtPoaHolderName", "Enter the Name of the Power of Attorney Holder"},
        {"tdtDemandPromNoteDate", "Enter the Date of Demand Promissory Note"},
        {"chkGurantor", "Guarantor should be selected!!!"},
        {"txtArea_AuthorizedSignatory", "Enter the Address type of the Authorized Signatory"},
        {"txtLaonAmt", "Enter the Limit Amount Sanctioned"},
        {"txtArea_GD", "Enter the Area"},
        {"cboProdID_GD", "Product ID should be a proper value!!!"},
        {"txtRemarks", ""},
        {"cboSectorCode2", "Choose the Sector Code2"},
        {"txtMobile_AuthorizedSignatory", "Enter the Mobile number."},
        {"cboAssetCode", "Choose the Asset Code"},
        {"txtRemark_PowerAttroney", ""},
        {"tdtAsOn", "Enter the Date"},
        {"rdoDoAddSIs_Yes", "Do you want to add Standing Instructions for repayment of installments?"},
        {"cboNatureBusiness", "Select the Nature of Business of  the borrower"},
        {"tdtSanctionDate", "Enter the Sanction Date."},
        {"cboModeSanction", "Select the mode by which the Sanction was communicated"},
        {"txtPin_AuthorizedSignatory", "Enter the PIN Code"},
        {"cboSectorCode1", "Choose the Sector Code"},
        {"txtArea_PowerAttroney", "Enter the Address type of the PoA Holder."},
        {"tdtDemandPromNoteExpDate", "Enter the Expiry Date of Demand Promissory Note"},
        {"txtScheduleNo", "Enter the Schedule Number"},
        {"txtBusinessFax_AuthorizedSignatory", "Enter the Business  Fax."},
        {"txtBusinessPhone_AuthorizedSignatory", "Enter the Business  Phone."},
        {"rdoRiskWeight_Yes", "Risk Weight should be selected!!!"},
        {"cboCountry_GD", "Choose the Country"},
        {"tdtDealingWithBankSince", "Dealing with Bank Since should not be empty!!!"},
        {"txtDesig_AuthorizedSignatory", "Enter the Designation of the Authorized Signatory"},
        {"txtStreet_GD", "Enter the Street"},
        {"cboCity_AuthorizedSignatory", "Choose a  City"},
        {"cboState_GD", "Choose the State"},
        {"txtRemark_Insurance", ""},
        {"cboNatureRisk", "Select the appropriate value"},
        {"txtToAmt", "Enter the ending amount of the slab"},
        {"tdtFirstInstall", "Enter the First Installment Date"},
        {"chkStockInspect", "Stock Inspect should be selected!!!"},
        {"txtStreet_AuthorizedSignatory", "Enter the Address type of the Authorized Signatory"},
        {"txtCustID", "Enter the Customer ID, if Known else select using the Selection Button"},
        {"txtSecurityValue", "Enter the value of the Security"},
        {"cboConstitution", "Select the constitution of the borrower"},
        {"cboCountry_AuthorizedSignatory", "Choose a  Country"},
        {"chkInsurance", "Insurance should be selected!!!"},
        {"txtPolicyAmt", "Enter the Amount Insured"},
        {"txtInterExpLimit", "Enter the Interest Expiry Limit"},
        {"txtEmailId_AuthorizedSignatory", "Enter the Email ID."},
        {"cboState_CompDetail", "Choose the State"},
        {"txtGroupDesc", "Enter the Group Name to which the Borrower belongs"},
        {"txtPenalInter", "Enter the Penal Interest"},
        {"cboProdID_RS", "Product ID should be a proper value!!!"},
        {"rdoMultiDisburseAllow_Yes", "Multiple Disbursement allowed?"},
        {"cboCountry_CompDetail", "Choose the Country"},
        {"txtInter", "Enter the applicable Rate of Interest"},
        {"txtMargin", "Enter the Percentage of margin stipulated on the security"},
        {"cboPoACust", "Select the account holder whose �Power of Attorney� is being Registered"},
        {"txtNumberAuthSignatory", "Enter the number of authorized signatories for this account"},
        {"txtParticulars", "Enter the Particulars of the security"},
        {"tdtAson", "Enter the Date"},
        {"chkSelCommodityItem", "Check the Box if the security comes under the selective sensitive commodity"},
        {"rdoAccType_New", "Select the Account Type"},
        {"cboInstallType", "Select the Installment Type"},
        {"txtHomePhone_AuthorizedSignatory", "Enter the Home Phone."},
        {"cboRepayType", "Select the type of Repayment"},
        {"cboRefinancingInsti", "Choose the Refinancing Institution"},
        {"tdtAsOn_GD", "Enter the net worth date as on "},
        {"cboGovtSchemeCode", "Choose the Government Scheme Code"},
        {"txtRemarks__CompDetail", ""},
        {"cboPurposeCode", "Choose the Purpose Code"},
        {"tdtDOB_GD", "Enter the Date of Birth of the Guarantor"},
        {"cboProdId", "Enter the Product ID"},
        {"cboProdType", "Enter the Product Type"},
        {"txtPhone_PowerAttroney", "Entere the Phone Number."},
        {"tdtTDate", "Enter the To Date"},
        {"tdtNPADate", "Enter the NPADate"},
        {"tdtFromDate", "Enter the From Date"},
        {"cboSanctionSlNo", "Choose the Sanction Serial Number"},
        {"rdoNo_DocumentDetails", ""},
        {"rdoYes_DocumentDetails", ""},
        {"tdtSubmitDate_DocumentDetails", "Enter the Submitted Date."},
        {"txtRemarks_DocumentDetails", "Enter the Remarks."},
        {"chkChequeBookAD", "ChequeBookAD should be selected!!!"},
        {"txtCustomerIdAI", "CustomerIdAI should not be empty!!!"},
        {"txtGuardianNameNO", "GuardianNameNO should not be empty!!!"},
        {"txtTotalShareNO", "TotalShareNO should not be empty!!!"},
        {"chkCustGrpLimitValidationAD", "CustGrpLimitValidationAD should be selected!!!"},
        {"txtAccountNoITP1", "AccountNoITP1 should not be empty!!!"},
        {"cboINP5AddrState", "INP5AddrState should be a proper value!!!"},
        {"txtNomineeAddrArea", "NomineeAddrArea should not be empty!!!"},
        {"cboCustAddrState", "CustAddrState should be a proper value!!!"},
        {"txtIdITP4", "IdITP4 should not be empty!!!"},
        {"txtINP5AddrArea", "INP5AddrArea should not be empty!!!"},
        {"tdtDebit", "Enter the Debit Date"},
        {"chkPayIntOnCrBalIN", "PayIntOnCrBalIN should be selected!!!"},
        {"txtNomineeAddrStreet", "NomineeAddrStreet should not be empty!!!"},
        {"tdtCredit", "Enter the Credit Date"},
        {"tdtPOAToDatePA", "Enter the PoA To Date"},
        {"txtPhoneOTP5", "PhoneOTP5 should not be empty!!!"},
        {"tdtCreditFromDateAD", "Enter the Credit Card From Date."},
        {"txtAccCloseChrgAD", "AccCloseChrgAD should not be empty!!!"},
        {"cboNomineeAddrCountry", "NomineeAddrCountry should be a proper value!!!"},
        {"txtNomineeShareNO", "NomineeShareNO should not be empty!!!"},
        {"cboNomineeAddrState", "NomineeAddrState should be a proper value!!!"},
        {"cboCommAddr", "CommunicationAddr should be a proper value!!!"},
        {"txtAmoutTransAI", "AmoutTransAI should not be empty!!!"},
        {"cboOpModeAI", "Select the Mode of Operation. From Other Details "},
        {"tdtOpeningDateAI", "Opening Date should be a proper value"},
        {"chkNROStatusAD", "NROStatusAD should be selected!!!"},
        {"tdtPOAFromDatePA", "Enter the PoA From Date"},
        {"txtChequeBookChrgAD", "ChequeBookChrgAD should not be empty!!!"},
        {"cboPOAAddrCountry", "POAAddrCountry should be a proper value!!!"},
        {"txtIssuedAuthITP4", "IssuedAuthITP4 should not be empty!!!"},
        {"txtNomineeAddrPincode", "NomineeAddrPincode should not be empty!!!"},
        {"cboPOAAddrCity", "POAAddrCity should be a proper value!!!"},
        {"txtGuardianPhoneNO", "GuardianPhoneNO should not be empty!!!"},
        {"txtPOAPhonePA", "POAPhonePA should not be empty!!!"},
        {"cboRelationNO", "RelationNO should be a proper value!!!"},
        {"txtCreditNoAD", "Enter the Credit Card No."},
        {"txtRemarksAI", "RemarksAI should not be empty!!!"},
        {"txtExcessWithChrgAD", "ExcessWithChrgAD should not be empty!!!"},
        {"tdtNPAChrgAD", "Enter the NPA Charge Date"},
        {"tdtDebitToDateAD", "Enter the Debit Card To Date."},
        {"chkMobileBankingAD", "MobileBankingAD should be selected!!!"},
        {"txtIssuedByITP3", "IssuedByITP3 should not be empty!!!"},
        {"txtPOAAddrPincode", "POAAddrPincode should not be empty!!!"},
        {"cboGuardianAddrCity", "GuardianAddrCity should be a proper value!!!"},
        {"cboActStatusAI", "ActStatusAI should be a proper value!!!"},
        {"tdtIssuedDateITP3", "Enter the Issued Date"},
        {"tdtCreditToDateAD", "Enter the Credit Card To Date."},
        {"chkPayIntOnDrBalIN", "PayIntOnDrBalIN should be selected!!!"},
        {"txtNomineeACodeNO", "NomineeACodeNO should not be empty!!!"},
        {"txtABBChrgAD", "Enter the ABB Charge."},
        {"txtNomineeNameNO", "NomineeNameNO should not be empty!!!"},
        {"cboPreviousActNo", "PreviousActNo should be a proper value!!!"},
        {"chkInopChrgAD", "InopChrgAD should be selected!!!"},
        {"txtBranchCodeAI", "BranchCodeAI should not be empty!!!"},
        {"txtMinNominees", "MinNominees should not be empty!!!"},
        {"cboGroupCodeAI", "GroupCodeAI should be a proper value!!!"},
        {"txtDebitNoAD", "Enter the Debit Card No."},
        {"txtPrevActNumAI", "PrevActNumAI should not be empty!!!"},
        {"txtODLimitAI", "ODLimitAI should not be empty!!!"},
        {"txtINP5ddrStreet", "INP5ddrStreet should not be empty!!!"},
        {"txtCustAddrStreet", "CustAddrStreet should not be empty!!!"},
        {"cboStmtFreqAD", "StmtFreqAD should be a proper value!!!"},
        {"txtIntroNameOTP5", "IntroNameOTP5 should not be empty!!!"},
        {"txtPOANamePA", "POANamePA should not be empty!!!"},
        {"cboPOAAddrState", "POAAddrState should be a proper value!!!"},
        {"txtMinBal2FlexiAD", "MinBal2FlexiAD should not be empty!!!"},
        {"chkStopPmtChrgAD", "StopPmtChrgAD should be selected!!!"},
        {"txtAccountNoITP2", "AccountNoITP2 should not be empty!!!"},
        {"txtMisServiceChrgAD", "MisServiceChrgAD should not be empty!!!"},
        {"chkDebitAD", "DebitAD should be selected!!!"},
        {"cboGuardianAddrCountry", "GuardianAddrCountry should be a proper value!!!"},
        {"txtAccOpeningChrgAD", "AccOpeningChrgAD should not be empty!!!"},
        {"cboProductIdAI", "ProductIdAI should be a proper value!!!"},
        {"cboCustAddrCountry", "CustAddrCountry should be a proper value!!!"},
        {"tdtATMFromDateAD", "Enter the ATM Card From Date"},
        {"tdtATMToDateAD", "Enter the ATM Card To Date"},
        {"txtATMNoAD", "Enter the ATM Card No."},
        {"tdtExpiryDateITP3", "Enter the Expiry Date"},
        {"tdtDebitFromDateAD", "Enter the Debit Card From Date."},
        {"chkNPAChrgAD", "NPAChrgAD should be selected!!!"},
        {"txtMinActBalanceAD", "Enter the Minimum Account Balance."},
        {"chkABBChrgAD", "ABBChrgAD should be selected!!!"},
        {"chkCreditAD", "CreditAD should be selected!!!"},
        {"chkNonMainMinBalChrgAD", "NonMainMinBalChrgAD should be selected!!!"},
        {"cboSettlementModeAI", "SettlementModeAI should be a proper value!!!"},
        {"tdtDebit", "Enter the Debit Date"},
        {"tdtCredit", "Enter the Credit Date"},
        {"chkStmtChrgAD", "StmtChrgAD should be selected!!!"},
        {"chkChequeRetChrgAD", "ChequeRetChrgAD should be selected!!!"},
        {"txtFolioChrgAD", "FolioChrgAD should not be empty!!!"},
        {"tdtPOAToDatePA", "Enter the To Date"},
        {"tdtOpeningDateAI", "Opening Date should be a proper value"},
        {"tdtPOAFromDatePA", "null"},
        {"tdtNPAChrgAD", "null"},
        {"tdtIssuedDateITP3", "null"},
        {"chkATMAD", ""},
        
        {"cboCaseStatus", "CaseStatus should be a proper value!!!"},
        {"txtCaseNumber", "CaseNumber should not be empty!!!"},
        {"tdtlFillingDt", "Enter the Filling Date"},
        {"txtFillingFees", "FillingFees should not be empty!!!"},
        {"txtMiscCharges", "MiscCharges should not be empty!!!"},
        
        {"txtCourtOrderNo", "CourtOrderNo should not be empty!!!"},
        {"tdtCourtOrderDate", "CourtOrderDate should not be empty!!!"},
        {"tdtOTSDate", "OTSDate should not be empty!!!"},
        {"txtOTSRate", "OTSRate should not be empty!!!"},
        {"txtTotAmountDue", "TotAmountDue should not be empty!!!"},
        {"txtSettlementAmt", "SettlementAmt should not be empty!!!"},
        
        
        {"txtNoInstallment", "NoInstallment should not be empty!!!"},
        {"cboFreq", "Freq should not be empty!!!"},
        {"txtInstallmentAmt", "InstallmentAmt should not be empty!!!"},
        {"tdtFirstInstallDt", "FirstInstallDt should not be empty!!!"},
        {"txtPenal", "Penal should not be empty!!!"},
        {"cboSanRepaymentType", "Enter Repayment Type"}
        
   };

}
