INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.RESIDENTIALSTATUS', 'Lease', 'Lease'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.RESIDENTIALSTATUS', 'Own House', 'Own House'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.RESIDENTIALSTATUS', 'Rental', 'Rental'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.CUSTOMERTYPE', 'Employee', 'Employee'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.CUSTOMERTYPE', 'Individual', 'Individual'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.CUSTOMERTYPE', 'Student', 'Student'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.CUSTOMERTYPE', 'NRI', 'NRI'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.CUSTOMERTYPE', 'Professional', 'Professional'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.CUSTOMERTYPE', 'Self Employeed', 'Self Employeed'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.CUSTOMERGROUP', 'Management', 'Management'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.CUSTOMERGROUP', 'Technical', 'Technical'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.RELATIONMANAGER', 'Manager1', 'Manager1'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.RELATIONMANAGER', 'Manager2', 'Manager2'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.VEHICLE', 'Two Wheeler', 'Two Wheeler'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.VEHICLE', 'Four Wheeler', 'Four Wheeler'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.PROFESSION', 'Engineer', 'Engineer'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.PROFESSION', 'Doctor', 'Doctor'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.PRIMARYOCCUPATION', 'business', 'business'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.ANNINCOME', '1', 'Upto Rs 50,000'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.ANNINCOME', '2', 'Rs 50,001 to 1,00,000'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.ANNINCOME', '3', 'Rs 1,00,001 to 5,00,000'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.ANNINCOME', '4', 'Rs 5,00,001 to 10,00,000'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.ANNINCOME', '5', 'Above Rs 10,00,000'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.EDUCATION', '1', 'Post Graduate'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.EDUCATION', '2', 'Graduate'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.EDUCATION', '3', 'Diploma'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.EDUCATION', '4', 'HSC'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.EDUCATION', '5', 'SSC'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.PREFCOMM', 'Post', 'Post'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.PREFCOMM', 'Phone', 'Phone'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.PREFCOMM', 'Email', 'Email'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.ADDRTYPE', 'Business', 'Business'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.ADDRTYPE', 'Home', 'Home'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.CITY', 'Ahemadabad', 'Ahemadabad'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.CITY', 'Amristar', 'Amristar'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.CITY', 'Bangalore', 'Bangalore'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.CITY', 'Chennai', 'Chennai'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.CITY', 'Delhi', 'Delhi'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.CITY', 'Hyderabad', 'Hyderabad'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.CITY', 'Kolkatta', 'Kolkatta'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.CITY', 'Mumbai', 'Mumbai'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.STATE', 'AndhraPradesh', 'AndhraPradesh'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.STATE', 'Delhi', 'Delhi'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.STATE', 'TamilNadu', 'TamilNadu'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.STATE', 'Punjab', 'Punjab'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.STATE', 'Karnataka', 'Karnataka'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.STATE', 'Maharastra', 'Maharastra'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.STATE', 'West Bengal', 'West Bengal'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.COUNTRY', 'AU', 'Australia'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.COUNTRY', 'IN', 'India'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.COUNTRY', 'US', 'US'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.PHONETYPE', 'Land Line', 'Land Line'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.PHONETYPE', 'Mobile', 'Mobile'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.PHONETYPE', 'Fax', 'Fax'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.PHONETYPE', 'Pager', 'Pager'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CURRENCYTYPE', 'INR', 'INR'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACCOUNTTYPE', 'Assets', 'Assets'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CURRENCYTYPE', 'USD', 'USD'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CURRENCYTYPE', 'CAD', 'CAD'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CURRENCYTYPE', 'SGD', 'SGD'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CURRENCYTYPE', 'EUR', 'EUR'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CURRENCYTYPE', 'YEN', 'YEN'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACCOUNTTYPE', 'Liability', 'Liability'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACCOUNTTYPE', 'ContraAssets', 'Contra Assets'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACCOUNTTYPE', 'ContraLiability', 'Contra Liability'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACCOUNTTYPE', 'Income', 'Income'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACCOUNTTYPE', 'Expenditure', 'Expenditure'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.TITLE', 'Mr', 'Mr'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.TITLE', 'Ms', 'Ms'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.TITLE', 'Mrs', 'Mrs'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CUSTOMER.TITLE', 'Dr', 'Dr'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'INSTRUMENTTYPE', 'DD', 'Demand Draft'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'INSTRUMENTTYPE', 'CHEQUE', 'Cheque'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CHANNELTYPE', 'ATM', 'ATM Machine'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CHANNELTYPE', 'NET', 'Internet'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'OPERATIVEACCTPRODUCT.BEHAVES', 'SB', 'SB'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'OPERATIVEACCTPRODUCT.BEHAVES', 'CA', 'CA'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'PERIOD', 'Days', 'Days'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'PERIOD', 'Months', 'Months'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'PERIOD', 'Years', 'Years'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'FREQUENCY', '1', 'Daily'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'FREQUENCY', '7', 'Weekly'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'FREQUENCY', '30', 'Monthly'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'FREQUENCY', '90', 'Quaterly'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'FREQUENCY', '180', 'Half Yearly'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'FREQUENCY', '365', 'Yearly'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'OPERATIVEACCTPRODUCT.CALCCRITERIA', 'Minimum', 'Minimum'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'OPERATIVEACCTPRODUCT.CALCCRITERIA', 'Average', 'Average'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'OPERATIVEACCTPRODUCT.CALCCRITERIA', 'Maximum', 'Maximum'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'OPERATIVEACCTPRODUCT.FOLIOCHRG', 'Upto Balance', 'Upto Balance'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'OPERATIVEACCTPRODUCT.FOLIOCHRG', 'Upto Over Drawing Balance', 'Upto Over Drawing Balance'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'OPERATIVEACCTPRODUCT.FOLIOCHRG', 'Not to collect if the balance In-sufficient', 'Not to collect if the balance In-sufficient'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'OPERATIVEACCTPRODUCT.INTROUNDOFF', 'No Round Off', 'No Round Off'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'OPERATIVEACCTPRODUCT.INTROUNDOFF', 'Nearest Rupee', 'Nearest Rupee'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'OPERATIVEACCTPRODUCT.INTROUNDOFF', 'Lower Value', 'Lower Value'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'OPERATIVEACCTPRODUCT.INTROUNDOFF', 'Higher Value', 'Higher Value'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'OPERATIVEACCTPRODUCT.NONMINBAL', 'Per Transaction', 'Per Transaction'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'OPERATIVEACCTPRODUCT.NONMINBAL', 'Per Day', 'Per Day'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'OPERATIVEACCTPRODUCT.NONMINBAL', 'Per Month', 'Per Month'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'OPERATIVEACCTPRODUCT.ROUNDOFF', 'No Round Off', 'No Round Off'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'OPERATIVEACCTPRODUCT.ROUNDOFF', 'Nearest Rupee', 'Nearest Rupee'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'OPERATIVEACCTPRODUCT.ROUNDOFF', 'Nearest Tens', 'Nearest Tens'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'OPERATIVEACCTPRODUCT.ROUNDOFF', 'Nearest Hundreds', 'Nearest Hundreds'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'OPERATIVEACCTPRODUCT.STATCHRG', 'Per Statement', 'Per Statement'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'OPERATIVEACCTPRODUCT.STATCHRG', 'Per Month', 'Per Month'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'OPERATIVEACCTPRODUCT.STATCHRG', 'Per Quarter', 'Per Quarter'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'MONTH', 'January', 'January'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'MONTH', 'February', 'February'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'MONTH', 'March', 'March'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'MONTH', 'April', 'April'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'MONTH', 'May', 'May'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'MONTH', 'June', 'June'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'MONTH', 'July', 'July'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'MONTH', 'August', 'August'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'MONTH', 'September', 'September'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'MONTH', 'October', 'October'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'MONTH', 'November', 'November'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'MONTH', 'December', 'December'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'TRANSFER.INST_TYPE', 'DD', 'DD'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'TRANSFER.INST_TYPE', 'CHEQUE', 'CHEQUE'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CASHTRANOPEN', 'AccHdId', 'Acct Head Id'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CASHTRANOPEN', 'ActNum', 'Account No'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CASHTRANOPEN', 'INP_AMOUNT', 'Input Amount'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CASHTRANOPEN', 'AMOUNT', 'Amount'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CASHTRANOPEN', 'TRANS_DT', 'Transaction Date'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CASHTRANOPEN', 'TRANS_TYPE', 'Transaction Type'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CASHTRANOPEN', 'INST_TYPE', 'Instrument Type'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CASHTRANOPEN', 'INST_NO', 'Instrument No'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CASHTRANOPEN', 'INST_DT', 'Instrument Date'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CASHTRANOPEN', 'TOKEN_NO', 'Token No'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CASHTRANOPEN', 'INIT_TRANS_ID', 'Initiator Trans Id'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CASHTRANOPEN', 'INIT_CHANN_TYPE', 'Initiator Channel Type'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CASHTRANOPEN', 'PARTICULARS', 'Particulars'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACCOUNTSTATUS', 'NEW', 'New'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'CASHTRANOPEN', 'TransId', 'Transaction Id'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACCOUNTSTATUS', 'OPERATIONAL', 'Operational'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACCOUNTSTATUS', 'COMP_FREEZE', 'Complete Freeze'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACCOUNTSTATUS', 'PART_FREEZE', 'Partial Freeze'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACCOUNTSTATUS', 'DORMANT', 'Dormant'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACCOUNTSTATUS', 'CLOSED', 'Closed'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACCOUNTSTATUS', 'TRANSFER_IN', 'Transfer In'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACCOUNTSTATUS', 'IN_OPERATIVE', 'Inoperative'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_CONSTITUTION', 'INDIVIDUAL', 'Individual'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_CONSTITUTION', 'JOINT', 'Joint'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'ALL_JOINTLY', 'All Jointly'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'ANY_THREE_JOINTLY', 'Any Three Jointly'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'ANY_TWO_THREE_TRUSTEES_JOINTLY', 'Any Two/Three Trustees Jointly'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'ANY_TWO_JOINTLY', 'Any Two Jointly'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'SINGLE_SURVIVOR', 'Anyone Single or Survivor (S)'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'AUTH_SIGNATORY_CONST_ATTORNEY', 'Authorized Signatory and Const. Attorney'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'CHAIRMAN_TREASURER', 'Chairman and Treasurer'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'CHAIRMAN_OR_VICE_AND_SECRETORY', 'Chairman/ Vice Chairman and Secretar'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'EXECUTIVE_FAN_OR_FAC_MANAGER', 'Executive Finance or Factory Manager'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'EXECUTOR_ADMIN', 'Executor or Administrator'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'FORMER_SURVIVOR', 'Former or Servivor'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'JOINT', 'Joint'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'JOINT_SURVIVOR', 'Jointly or Survivor'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'KARTHA_HUF', 'Kartha of H.U.F.'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'LH_THUMB_IMP_BLIND', 'Left Hand Thumb Impression - Blind'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'LH_THUMB_IMP_ILLITERATE', 'Left Hand Thumb Impression - Illiterate'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'LH_THUMB_IMP_PHY_HANDCAP', 'Left Hand Thumb Impression - Phy. Handicapped'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'LEGAL_TEST_GUARDIAN', 'Legal or Testamentory Guardian'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'MD_DIR', 'Managing Director or Director'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'MNG_PARTNER', 'Managing Partner'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'MEMBER_SECRETARY', 'Member and Secretary'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'MINOR_ABOVE_12', 'Minor Above 12 Years'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'NO_ONE', 'No. 1'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'LIQUIDATOR_OR_COURT', 'Official Liquidator or Court Receiver'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'ONLY_FIRST', 'Only First'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'PARDANASHIN_WOMAN', 'Pardanashin Woman'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'POWER_OF_ATTORNEY', 'Power of Attorney'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'PRESIDENT', 'President'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'SECRETARY', 'Secretary'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'SECRETARY_PRESIDENT', 'Secretary and President'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'SECRETARY_TREASURER', 'Secretary and Treasurer'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'SEE_OP_MODE_REMARKS', 'See Mode of Operation Remarks'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'SELF', 'Self'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'TREASURER', 'Treasurer'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'POWER_ATTORNEY_OR_MANDATE', 'Under Power of Attorney or Mandate'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACT_OP_MODE', 'VICE_PRESIDENT', 'Vice President'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'INTRODUCTION', 'OTHER_BANK', 'Other Bank'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'INT_CAT_ID', 'MINOR NO GUARDIAN', 'Minor Jointly with No Guardian Depositor'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'INTRODUCTION', 'SELF_CUSTOMER', 'Self or Existing Customer'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'INTRODUCTION', 'DOC_DETAILS', 'Document Details'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'INTRODUCTION', 'IDENTITY', 'Identity'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'INTRODUCTION', 'OTHERS', 'Others'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'SETTLEMENT_MODE', 'ANYONE_OR_SURVIVOR', 'Anyone or Survivor'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'SETTLEMENT_MODE', 'EITHER_OR_SURVIVOR', 'Either or Survivor'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'SETTLEMENT_MODE', 'FORMER_OR_SURVIVOR', 'Former or Survivor'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'SETTLEMENT_MODE', 'JOINTLY', 'Jointly'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'SETTLEMENT_MODE', 'LATER_OR_SURVIVOR', 'Latter or Survivor'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'SETTLEMENT_MODE', 'LEGAL_HEIR', 'Legal Heir'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'SETTLEMENT_MODE', 'NATURAL_GUARDIAN', 'Natural Guardian'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'SETTLEMENT_MODE', 'NOMINEE', 'Nominee'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'SETTLEMENT_MODE', 'NA', 'Not Applicable'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'SETTLEMENT_MODE', 'OTHERS', 'Others'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'SETTLEMENT_MODE', 'SEVERALLY', 'Severally'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'SETTLEMENT_MODE', 'SERVIVOR', 'Servivor'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'INT_CAT_ID', 'MINOR GUARDIAN', 'Minor with Guardian (Guardian Operated)'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'INT_CAT_ID', 'MINOR GUARDIAN OPT BOTH', 'Minor with Guardian (Operated by Both);'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'INT_CAT_ID', 'MINOR ABOVE 12', 'Minor Above 12 Yrs'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'INT_CAT_ID', 'MINOR ABOVE 18', 'Minor Above 18 Yrs but Less than 21 Yrs'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'INT_CAT_ID', 'HANDICAPPED', 'Handicapped'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'INT_CAT_ID', 'UNSOUND MIND', 'Persons of Unsound Mind'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'INT_CAT_ID', 'NRF', 'N R F'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'INTRO_DOCUMENT', 'HOUSE', 'House'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'INTRO_DOCUMENT', 'LEASE', 'Lease'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'INTRO_DOCUMENT', 'RENTAL', 'Rental'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'INDENTITY_TYPE', 'CREDIT_CARD', 'Credit Card'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'INDENTITY_TYPE', 'PAN', 'PAN'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'INDENTITY_TYPE', 'PASSPORT', 'Passport'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'INDENTITY_TYPE', 'RATION_CARD', 'Ration Card'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'INDENTITY_TYPE', 'SSN', 'SSN'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACCTHEADMAIN.TRANSPOST', 'Manual', 'Manual'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACCTHEADMAIN.TRANSPOST', 'Integrated', 'Integrated'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACCTHEADMAIN.TRANSPOST', 'Both', 'Both'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACCTHEADMAIN.POSTMODE', 'Individual', 'Individual'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACCTHEADMAIN.POSTMODE', 'Consolidated', 'Consolidated'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACCTHEADMAIN.BALTYPE', 'Debit', 'Debit'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACCTHEADMAIN.BALTYPE', 'Credit', 'Credit'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'RELATIONSHIP', 'FATHER', 'Father'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'RELATIONSHIP', 'MOTHER', 'Mother'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'RELATIONSHIP', 'BROTHER', 'Brother'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'RELATIONSHIP', 'SISTER', 'Sister'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'RELATIONSHIP', 'SPOUSE', 'Spouse'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'RELATIONSHIP', 'SON', 'Son'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'RELATIONSHIP', 'DAUGHTER', 'Daughter'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACTIVITY_CODE', 'CONSULTANT', 'Consultant'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ACCOUNTSTATUS', 'CLOSEPENDING', 'Sent to Closing'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'FREEZE.FREEZETYPE', 'Partial', 'Partial'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'FREEZE.FREEZETYPE', 'Complete', 'Complete'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'LOANPRODUCT.AMOUNT', 'UPTO_RS_100000', 'Upto Rs. 1,00,000'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'LOANPRODUCT.AMOUNT', 'RS_100001_TO_RS_1000000', 'Rs. 1,00,001-Rs. 10,00,000'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'LOANPRODUCT.AMOUNT', 'RS_1000001_TO_RS_10000000', 'Rs. 10,00,001-Rs. 1,00,00,000'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'LOANPRODUCT.CALCTYPE', 'DAILY_PRODUCT', 'Daily Product'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'LOANPRODUCT.CALCTYPE', 'MONTHLY_PRODUCT', 'Monthly Product'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'OPERATIVEACCTPRODUCT.PRODFREQ', '1', 'Daily'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'OPERATIVEACCTPRODUCT.PRODFREQ', '7', 'Weekly'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'OPERATIVEACCTPRODUCT.PRODFREQ', '30', 'Monthly'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'LOANPRODUCT.CALCTYPE', 'NO_PRODUCT', 'No Product'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'LOANPRODUCT.CALCTYPE', 'MONTHLY_MINIMUM_BALANCE', 'Monthly Minimum Balance'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'LIENMARKING.LIENTYPE', 'Own Branch', 'Own Branch'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'LIENMARKING.LIENTYPE', 'Other Branch', 'Other Branch'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'LIENMARKING.LIENTYPE', 'Other Bank', 'Other Bank'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'LOANPRODUCT.OPERATESLIKE', 'FIR', 'FIR'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'LOANPRODUCT.OPERATESLIKE', 'ARIL', 'ARIL'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'LOANPRODUCT.OPERATESLIKE', 'TERM_LOAN_CUMMILATIVE_DEPOSITS', 'Term Loan Cummilative Deposits'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'LOANPRODUCT.OPERATESLIKE', 'NO_INTEREST', 'No Interest'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'LOANPRODUCT.OPERATESLIKE', 'MONTHLY_MAXIMUM', 'Monthly Maximum'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'LOANPRODUCT.OPERATESLIKE', 'MONTHLY_MINIMUM', 'Monthly Minimum'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ADVANCESPRODUCT.OPERATESLIKE', 'OD', 'OD'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
' LOANPRODUCT.LOANPERIODS', 'HALF_YEARLY', 'Half Yearly
_DESC'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'LOANPRODUCT.LOANPERIOD', 'MONTHLY', 'Monthly'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'LOANPRODUCT.LOANPERIOD', 'QUATERLY', 'Quaterly'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'LOANPRODUCT.LOANPERIOD', 'HALF_YEARLY', 'Half Yearly'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'LOANPRODUCT.LOANPERIOD', 'YEARLY', 'Yearly'); 
INSERT INTO LOOKUP_MASTER ( LOOKUP_ID, LOOKUP_REF_ID, LOOKUP_DESC ) VALUES ( 
'ADVANCESPRODUCT.OPERATESLIKE', 'CC', 'CC'); 
commit;
 
