
CREATE TABLE ACCESS_LVL_MASTER ( 
  ACCESS_LVL_ID    VARCHAR2 (8)  NOT NULL, 
  ACCESS_LVL_DESC  VARCHAR2 (128), 
  MENU_ID          VARCHAR2 (8), 
  SCREEN_ID        VARCHAR2 (8), 
  FUNC_ID          VARCHAR2 (8), 
  CONSTRAINT ACCESS_LVL_MASTER_PK
  PRIMARY KEY ( ACCESS_LVL_ID ) ) ; 

CREATE TABLE ACT_ACTION_HISTORY ( 
  ACT_NUM      VARCHAR2 (10), 
  ACTION_BY    VARCHAR2 (64), 
  ACTION_TYPE  VARCHAR2 (32), 
  ACTION_DT    DATE, 
  REMARKS      VARCHAR2 (256) ) ; 

CREATE TABLE ACT_CLOSING ( 
  ACT_NUM           VARCHAR2 (10), 
  UNUSED_CHK        NUMBER (4), 
  ACT_CLOSING_CHRG  NUMBER (16,2), 
  INT_PAYABLE       NUMBER (16,2), 
  CHRG_DETAILS      NUMBER (16,2), 
  PAYABLE_BAL       NUMBER (16,2) ) ; 

CREATE TABLE ACT_FREEZE ( 
  ACT_NUM           VARCHAR2 (10), 
  FREEZE_ID         VARCHAR2 (8), 
  FREEZE_AMT        NUMBER (16,2), 
  FREEZE_DT         DATE, 
  FREEZE_TYPE       VARCHAR2 (64), 
  FREEZE_DR_CR      VARCHAR2 (32), 
  FREEZE_STATUS     VARCHAR2 (64), 
  UNFREEZE_DT       DATE, 
  REMARKS           VARCHAR2 (256), 
  UNFREEZE_REMARKS  VARCHAR2 (256) ) ; 

CREATE TABLE ACT_INTRO_DOC ( 
  ACT_NUM    VARCHAR2 (10), 
  DOC_TYPE   VARCHAR2 (64), 
  ISSUE_DT   DATE, 
  EXPIRY_DT  DATE, 
  ISSUED_BY  VARCHAR2 (64), 
  DOC_NO     VARCHAR2 (32) ) ; 

CREATE TABLE ACT_INTRO_OTHERBANK ( 
  ACT_NUM         VARCHAR2 (10), 
  BANK_NAME       VARCHAR2 (64), 
  BRANCH_NAME     VARCHAR2 (64), 
  OTHER_ACT_NUM   VARCHAR2 (32), 
  OTHER_ACT_NAME  VARCHAR2 (64) ) ; 

CREATE TABLE ACT_INTRO_OTHERS ( 
  ACT_NUM       VARCHAR2 (10), 
  INTRO_NAME    VARCHAR2 (64), 
  INTRO_DESIG   VARCHAR2 (64), 
  STREET        VARCHAR2 (256), 
  AREA          VARCHAR2 (128), 
  CITY          VARCHAR2 (128), 
  STATE         VARCHAR2 (128), 
  PIN_CODE      VARCHAR2 (16), 
  AREA_CODE     VARCHAR2 (8), 
  PH_NO         VARCHAR2 (16), 
  COUNTRY_CODE  VARCHAR2 (32) ) ; 

CREATE TABLE ACT_INTRO_PROOF ( 
  ACT_NUM         VARCHAR2 (10), 
  PROOF_TYPE_ID   VARCHAR2 (32), 
  PROOF_NUM       VARCHAR2 (32), 
  ISSUE_AUTH      VARCHAR2 (128), 
  ACT_INTRO_FLAG  VARCHAR2 (16) ) ; 

CREATE TABLE ACT_INTRO_SELF ( 
  ACT_NUM        VARCHAR2 (10), 
  ACT_NUM_INTRO  VARCHAR2 (10) ) ; 

CREATE TABLE ACT_LIEN ( 
  ACT_NUM         VARCHAR2 (10), 
  LIEN_ID         VARCHAR2 (8), 
  LIEN_AMT        NUMBER (16,2), 
  LIEN_DT         DATE, 
  LIEN_ACT_NUM    VARCHAR2 (10), 
  LIEN_STATUS     VARCHAR2 (32), 
  UNLIEN_DT       DATE, 
  REMARKS         VARCHAR2 (256), 
  LIEN_AC_HD      VARCHAR2 (16), 
  LIEN_TYPE       VARCHAR2 (32), 
  BRANCH_ID       VARCHAR2 (16), 
  BANK_ID         VARCHAR2 (16), 
  UNLIEN_REMARKS  VARCHAR2 (256) ) ; 

CREATE TABLE ACT_MASTER ( 
  ACT_NUM               VARCHAR2 (10), 
  PROD_ID               VARCHAR2 (16), 
  CUST_ID               VARCHAR2 (8), 
  BRANCH_CODE           VARCHAR2 (8), 
  CREATE_DT             DATE, 
  ACT_STATUS_ID         VARCHAR2 (32), 
  ACT_CAT_ID            VARCHAR2 (32), 
  OPT_MODE_ID           VARCHAR2 (32), 
  INTRO_TYPE_ID         VARCHAR2 (32), 
  TOD_LIMIT             NUMBER (16,2), 
  GROUP_CODE_ID         VARCHAR2 (32), 
  SETTMT_MODE_ID        VARCHAR2 (32), 
  ACT_CODE_ID           VARCHAR2 (32), 
  PREV_ACT_NUM          VARCHAR2 (10), 
  CLEAR_BALANCE         NUMBER (16,2), 
  UNCLEAR_BALANCE       NUMBER (16,2), 
  FLOAT_BALANCE         NUMBER (16,2), 
  EFFECTIVE_BALANCE     NUMBER (16,2), 
  AVAILABLE_BALANCE     NUMBER (16,2), 
  CREATED_BY            VARCHAR2 (64), 
  AUTHORIZED_BY         VARCHAR2 (64), 
  AUTHORIZATION_STATUS  VARCHAR2 (32), 
  CLOSED_BY             VARCHAR2 (64), 
  CLOSED_DT             DATE, 
  BASE_CURR             VARCHAR2 (32), 
  LAST_TRANS_DT         DATE ) ; 

CREATE TABLE ACT_NOMINEE_DETAIL ( 
  ACT_NUM         VARCHAR2 (10), 
  NOMINEE_ID      VARCHAR2 (8), 
  NOMINEE_NAME    VARCHAR2 (64), 
  RELATIONSHIP    VARCHAR2 (32), 
  STREET          VARCHAR2 (256), 
  AREA            VARCHAR2 (128), 
  CITY            VARCHAR2 (128), 
  STATE           VARCHAR2 (128), 
  PIN_CODE        VARCHAR2 (16), 
  AREA_CODE       VARCHAR2 (8), 
  PH_NO           VARCHAR2 (64), 
  SHARE_PER       NUMBER (10), 
  NOMINEE_STATUS  VARCHAR2 (32), 
  NOMINEE_DOB     DATE, 
  GUARDIAN_NAME   VARCHAR2 (64), 
  G_STREET        VARCHAR2 (256), 
  G_AREA          VARCHAR2 (128), 
  G_CITY          VARCHAR2 (128), 
  G_STATE         VARCHAR2 (128), 
  G_PIN_CODE      VARCHAR2 (16), 
  G_AREA_CODE     VARCHAR2 (8), 
  G_PH_NO         VARCHAR2 (64), 
  G_RELATIONSHIP  VARCHAR2 (32), 
  COUNTRY_CODE    VARCHAR2 (4), 
  G_COUNTRY_CODE  VARCHAR2 (4) ) ; 

CREATE TABLE ACT_PARAM_DETAIL ( 
  ACT_NUM                   VARCHAR2 (10), 
  INT_CR_BAL                CHAR (1), 
  INT_DR_BAL                CHAR (1), 
  CHK_BOOK                  CHAR (1), 
  NRO_STATUS                CHAR (1), 
  MOBILE_BANKING            CHAR (1), 
  ATM_CARD                  CHAR (1), 
  ATM_CARD_NO               VARCHAR2 (16), 
  ATM_CARD_EXPRDT           DATE, 
  CR_CARD                   CHAR (1), 
  CR_CARD_NO                VARCHAR2 (16), 
  CR_CARD_EXPRDT            DATE, 
  DR_CARD                   CHAR (1), 
  DR_CARD_NO                VARCHAR2 (16), 
  DR_CARD_EXPRDT            DATE, 
  ABB                       CHAR (1), 
  ABB_CHRG                  NUMBER (16,2), 
  NPA                       CHAR (1), 
  NPA_DT                    DATE, 
  STOP_PAY_CHRG             CHAR (1), 
  FLEXI                     CHAR (1), 
  MIN_BAL1_FLEXI            NUMBER (16,2), 
  MIN_BAL2_FLEXI            NUMBER (16,2), 
  ACT_OPEN_CHRG             NUMBER (16,2), 
  CHK_RETURN                CHAR (1), 
  INOP_CHRG                 CHAR (1), 
  STAT_CHRG                 CHAR (1), 
  NONMAIN_CHRG              CHAR (1), 
  LAST_DR_INT_APPLDT        DATE, 
  CUSTGRP_LIMIT_VALIDATION  CHAR (1), 
  MIN_ACT_BAL               NUMBER (16,2), 
  CHK_BOOK_CHRG             NUMBER (16,2), 
  REQ_FLEXI_PD              NUMBER (10), 
  MISC_SERV_CHRG            NUMBER (16,2), 
  FOLIO_CHRG                NUMBER (16,2), 
  ACT_CLOSING_CHRG          NUMBER (16,2), 
  STAT_FREQ                 NUMBER (10), 
  EXCESS_WITHD_CHRG         NUMBER (16,2), 
  LAST_CR_INT_APPLDT        DATE ) ; 

CREATE TABLE ACT_POA ( 
  ACT_NUM       VARCHAR2 (10), 
  POA_ID        VARCHAR2 (8), 
  POA_NAME      VARCHAR2 (64), 
  STREET        VARCHAR2 (256), 
  AREA          VARCHAR2 (128), 
  CITY          VARCHAR2 (128), 
  STATE         VARCHAR2 (128), 
  PIN_CODE      VARCHAR2 (16), 
  AREA_CODE     VARCHAR2 (8), 
  PH_NO         VARCHAR2 (64), 
  PERIOD_FROM   DATE, 
  PERIOD_TO     DATE, 
  REMARKS       VARCHAR2 (256), 
  COUNTRY_CODE  VARCHAR2 (4) ) ; 

CREATE TABLE AC_HD ( 
  MJR_AC_HD_ID  VARCHAR2 (4), 
  SUB_AC_HD_ID  VARCHAR2 (4), 
  AC_HD_CODE    VARCHAR2 (16)  NOT NULL, 
  AC_HD_ID      VARCHAR2 (16), 
  AC_HD_DESC    VARCHAR2 (128), 
  STATUS        VARCHAR2 (32), 
  CREATED_DT    DATE, 
  DELETED_DT    DATE, 
  CONSTRAINT AC_HD_PK
  PRIMARY KEY ( AC_HD_ID ) ) ; 

ALTER TABLE AC_HD ADD  CONSTRAINT AC_HD_CALLING_UNIQUE
 UNIQUE (AC_HD_ID) ;



CREATE TABLE AC_HD_PARAM ( 
  AC_HD_ID         VARCHAR2 (16)  NOT NULL, 
  AC_HD_STATUS_ID  VARCHAR2 (16), 
  FLOAT_ACT        CHAR (1), 
  CONTRA_ACT       VARCHAR2 (16), 
  CR_CLR           CHAR (1), 
  CR_TRANS         CHAR (1), 
  CR_CASH          CHAR (1), 
  DR_CLR           CHAR (1), 
  DR_TRANS         CHAR (1), 
  DR_CASH          CHAR (1), 
  RECONS           CHAR (1), 
  F_TRANS_DT       DATE, 
  L_TRANS_DT       DATE, 
  TRANSPOST        VARCHAR2 (32), 
  POSTMODE         VARCHAR2 (32), 
  BALANCETYPE      VARCHAR2 (32), 
  GLBALANCE        NUMBER (16,2), 
  AC_OPEN_DT       DATE, 
  AC_CLOSE_DT      DATE, 
  STATUS           VARCHAR2 (16), 
  CONSTRAINT AC_HD_PARAM_PK
  PRIMARY KEY ( AC_HD_ID ) ) ; 

CREATE TABLE ADVANCES_PRODUCT ( 
  PROD_ID       VARCHAR2 (8), 
  PROD_DESC     VARCHAR2 (128), 
  ACCT_HEAD     VARCHAR2 (16), 
  BEHAVES_LIKE  VARCHAR2 (32), 
  STATUS        VARCHAR2 (16) ) ; 

CREATE TABLE ADVANCES_PROD_ACHD ( 
  PROD_ID               VARCHAR2 (8), 
  AC_CLOSING_CHRG       VARCHAR2 (16), 
  MISC_SERV_CHRG        VARCHAR2 (16), 
  STAT_CHRG             VARCHAR2 (16), 
  AC_DEBIT_INT          VARCHAR2 (16), 
  PENAL_INT             VARCHAR2 (16), 
  AC_CREDIT_INT         VARCHAR2 (16), 
  CLEARING_INT          VARCHAR2 (16), 
  EXPIRY_INT            VARCHAR2 (16), 
  EXCESS_LIMIT          VARCHAR2 (16), 
  CHQBK_ISSUE_CHRG      VARCHAR2 (16), 
  STOP_PAY_CHRG         VARCHAR2 (16), 
  CHQ_RET_CHRG_OUTWARD  VARCHAR2 (16), 
  CHQ_RET_CHRG_INWARD   VARCHAR2 (16), 
  FOLIO_CHRG_AC         VARCHAR2 (16) ) ; 

CREATE TABLE ADVANCES_PROD_ACPARAM ( 
  PROD_ID              VARCHAR2 (8), 
  CHK_ALLOWED          VARCHAR2 (1), 
  DISC_EOL_PERC        NUMBER (3), 
  NUMBER_PATTERN       VARCHAR2 (16), 
  LAST_AC_NO           VARCHAR2 (16), 
  STAT_FREQ            NUMBER (3), 
  NO_FREE_CHQ_LEAVES   NUMBER (3), 
  FREE_CHQ_PERIOD      NUMBER (4), 
  FREE_CHQ_START       DATE, 
  LIMIT_DEF_ALLOWED    VARCHAR2 (1), 
  TEMP_OD_ALLOWED      VARCHAR2 (1), 
  STAFF_AC_OPENED      VARCHAR2 (1), 
  DEBIT_UNCLEAR_APPL   VARCHAR2 (1), 
  CREDIT_UNCLEAR_APPL  VARCHAR2 (1), 
  ISSUE_TOKEN          VARCHAR2 (1), 
  ALLOW_WD_SLIP        VARCHAR2 (1), 
  MAX_AMT_ALLOWED      NUMBER (16,2) ) ; 

CREATE TABLE ADVANCES_PROD_CHARGES ( 
  PROD_ID                VARCHAR2 (8), 
  AC_CLOSING_CHRG        NUMBER (16,2), 
  MISC_SERV_CHRG         NUMBER (16,2), 
  STAT_CHRG              VARCHAR2 (1), 
  STAT_CHRG_RATE         NUMBER (16,2), 
  CHQBK_ISSUED_CHRG      VARCHAR2 (1), 
  CHQBK_ISSUED_CHRG_PER  NUMBER (16,2), 
  STOP_PAY_CHRG          VARCHAR2 (1), 
  STOP_PAY_CHRG_RATE     NUMBER (16,2), 
  FOLIO_CHRG_APPL        VARCHAR2 (1), 
  LAST_FOLIO_CHRGON      DATE, 
  NO_ENTRIES_PER_FOLIO   NUMBER (5), 
  NEXT_FOLIO_DUEDATE     DATE, 
  RATE_PER_FOLIO         NUMBER (16,2), 
  TO_CHRG_ON             VARCHAR2 (16), 
  FOLIO_CHRG_APPLFREQ    NUMBER (3), 
  TO_COLLECT_FOLIOCHRG   VARCHAR2 (64), 
  TO_COLLECT_CHRG_ON     VARCHAR2 (32), 
  INCOMP_FOLIO_ROUNDOFF  NUMBER (3), 
  PROC_CHRG              VARCHAR2 (1), 
  PROC_CHRG_PER          NUMBER (3), 
  PROC_CHRG_AMT          NUMBER (16,2), 
  COMMIT_CHRG            VARCHAR2 (1), 
  COMMIT_CHRG_PER        NUMBER (3), 
  COMMIT_CHRG_AMT        NUMBER (16,2) ) ; 

CREATE TABLE ADVANCES_PROD_CHQCHRG ( 
  PROD_ID           VARCHAR2 (8), 
  CHQ_RET_CHRGTYPE  VARCHAR2 (16), 
  CHQ_RET_CHRGAMT   VARCHAR2 (32), 
  CHQ_RET_CHRGRATE  NUMBER (16,2) ) ; 

CREATE TABLE ADVANCES_PROD_INTPAY ( 
  PROD_ID             VARCHAR2 (8), 
  CR_INT_PAID         VARCHAR2 (1), 
  APPL_CRINT_RATE     NUMBER (3), 
  CR_INT_CALCFREQ     NUMBER (3), 
  CR_INT_APPLFREQ     NUMBER (3), 
  LAST_INTCALC_DTCR   DATE, 
  LAST_INTAPPL_DTCR   DATE, 
  CR_COMP             VARCHAR2 (1), 
  CR_INT_COMPFREQ     NUMBER (3), 
  CR_PROD_ROUNDOFF    VARCHAR2 (16), 
  CR_INT_ROUNDOFF     VARCHAR2 (16), 
  CALC_CRITERIA       VARCHAR2 (16), 
  PROD_FREQ           NUMBER (3), 
  ADDI_INT_STAFF      VARCHAR2 (1), 
  ADDI_INT_STAFF_PER  NUMBER (3) ) ; 

CREATE TABLE ADVANCES_PROD_INTREC ( 
  PROD_ID               VARCHAR2 (8), 
  DEBIT_INT_CHARGED     VARCHAR2 (1), 
  MIN_DEBITINT_RATE     NUMBER (3), 
  MAX_DEBITINT_RATE     NUMBER (3), 
  MIN_DEBITINT_AMT      NUMBER (16,2), 
  MAX_DEBITINT_AMT      NUMBER (16,2), 
  DEBITINT_CALC_FREQ    NUMBER (3), 
  DEBITINT_APPL_FREQ    NUMBER (3), 
  DEBIT_COMP_REQ        VARCHAR2 (1), 
  DEBITINT_COMP_FREQ    NUMBER (3), 
  DEBIT_PROD_ROUNDOFF   VARCHAR2 (16), 
  DEBIT_INT_ROUNDOFF    VARCHAR2 (16), 
  LAST_INTCALC_DTDEBIT  DATE, 
  LAST_INTAPPL_DTDEBIT  DATE, 
  PROD_FREQ             NUMBER (3), 
  UNCLEAR_ADV_INTCHARG  VARCHAR2 (1), 
  PLR_RATE_APPL         VARCHAR2 (1), 
  PLR_RATE              NUMBER (3), 
  PLR_APPL_FROM         DATE, 
  PLR_APPL_NEWAC        VARCHAR2 (1), 
  PLR_APPL_EXISTAC      VARCHAR2 (1), 
  PLR_APPL_SANCFROM     DATE, 
  EOL_APPL              VARCHAR2 (1), 
  PENAL_APPL            VARCHAR2 (1), 
  LIMIT_EXPIRY_INT      VARCHAR2 (1), 
  PENAL_INT_RATE        NUMBER (3) ) ; 

CREATE TABLE ADVANCES_PROD_SPECIALITEM ( 
  PROD_ID                 VARCHAR2 (8), 
  ATM_CARD_ISSUED         VARCHAR2 (1), 
  CR_CARD_ISSUED          VARCHAR2 (1), 
  DEBIT_CARD_ISSUED       VARCHAR2 (1), 
  MOBILE_BANK_CLIENT      VARCHAR2 (1), 
  BRANCH_BANKING_ALLOWED  VARCHAR2 (1) ) ; 

CREATE TABLE ADVANCES_PROD_SPLASSET ( 
  PROD_ID                 VARCHAR2 (8), 
  ASSET_CATEGORY          VARCHAR2 (32), 
  ASSET_CATEGORY_RATEPER  NUMBER (3) ) ; 

CREATE TABLE ADV_BORROWER ( 
  BORROW_NO          VARCHAR2 (16), 
  BORROW_STATUS      VARCHAR2 (16), 
  CUST_ID            VARCHAR2 (16), 
  ACCT_STATUS        VARCHAR2 (16), 
  CONSTITUTION       VARCHAR2 (32), 
  CATEGORY           VARCHAR2 (32), 
  REFERENCES         VARCHAR2 (128), 
  AUTHORIZE_REMARKS  VARCHAR2 (128), 
  AUTHORIZE_STATUS   VARCHAR2 (16) ) ; 

CREATE TABLE ADV_CLASSIFY_DETAILS ( 
  BORROW_NO                VARCHAR2 (16), 
  PROD_ID                  VARCHAR2 (16), 
  COMMODITY_CODE           VARCHAR2 (32), 
  BUSINESS_SECTOR_CODE     VARCHAR2 (32), 
  FACILITY_TYPE            VARCHAR2 (32), 
  PURPOSE_CODE             VARCHAR2 (32), 
  INDUSTRY_CODE            VARCHAR2 (32), 
  TWENTY_CODE              VARCHAR2 (32), 
  GOVT_SCHEME_CODE         VARCHAR2 (32), 
  NPA_DT                   DATE, 
  ECGC                     VARCHAR2 (1), 
  DOCUMENT_COMPLETE        VARCHAR2 (1), 
  GUARANTEE_COVER_CODE     VARCHAR2 (32), 
  HEALTH_CODE              VARCHAR2 (32), 
  DISTRICT_CODE            VARCHAR2 (32), 
  SECTOR_CODE              VARCHAR2 (32), 
  PAYMENT_CODE             VARCHAR2 (32), 
  REFINANCING_INSTITUTION  VARCHAR2 (32), 
  ASSET_STATUS             VARCHAR2 (32), 
  DIRECT_FINANCE           VARCHAR2 (1), 
  PRIORITY_SECTOR          VARCHAR2 (1), 
  QIS                      VARCHAR2 (1), 
  AUTHORIZE_REMARKS        VARCHAR2 (128), 
  AUTHORIZE_STATUS         VARCHAR2 (16) ) ; 

CREATE TABLE ADV_CLOSING ( 
  PROD_ID        VARCHAR2 (16), 
  BORROW_NO      VARCHAR2 (16), 
  REMARKS        VARCHAR2 (128), 
  OTHER_CHARGES  NUMBER (16,2) ) ; 

CREATE TABLE ADV_COMPANY ( 
  BORROW_NO            VARCHAR2 (16), 
  CO_REG_NO            VARCHAR2 (32), 
  ESTABLISH_DT         DATE, 
  DEAL_BANK_SINCE      DATE, 
  NET_WORTH            NUMBER (16,2), 
  NET_WORTH_ON         DATE, 
  CHIEF_EXEC_NAME      VARCHAR2 (32), 
  ADDR_TYPE            VARCHAR2 (16), 
  STREET               VARCHAR2 (256), 
  AREA                 VARCHAR2 (128), 
  CITY                 VARCHAR2 (128), 
  STATE                VARCHAR2 (128), 
  COUNTRY_CODE         VARCHAR2 (4), 
  PINCODE              VARCHAR2 (16), 
  PHONE                VARCHAR2 (64), 
  RISK_RATE            NUMBER (3), 
  BUSINESS_NATURE      VARCHAR2 (64), 
  REMARKS              VARCHAR2 (128), 
  CR_FACILITIES_SINCE  DATE, 
  AUTHORIZE_REMARKS    VARCHAR2 (128), 
  AUTHORIZE_STATUS     VARCHAR2 (16) ) ; 

CREATE TABLE ADV_DRAWING_POWER ( 
  BORROW_NO               VARCHAR2 (16), 
  PROD_ID                 VARCHAR2 (16), 
  ACCT_NO                 VARCHAR2 (16), 
  STOCK_STAT_FREQ         NUMBER (3), 
  PREV_DPVALUE_CALCDT     DATE, 
  PREV_DP_MONTH           VARCHAR2 (16), 
  PREV_DP_VALUE           NUMBER (16,2), 
  CURR_DP_MONTH           VARCHAR2 (16), 
  DUE_DT                  DATE, 
  STOCK_SUBMIT_DT         DATE, 
  GOODS_PARTICULARS       VARCHAR2 (128), 
  INSPECTION_DT           DATE, 
  OPENING_STOCK_VALUE     NUMBER (16,2), 
  PURCHASE                NUMBER (16,2), 
  CLOSING_STOCK_VALUE     NUMBER (16,2), 
  SALES                   NUMBER (16,2), 
  SECURITY_NO             VARCHAR2 (16), 
  PRESENT_STOCK_VALUE     NUMBER (16,2), 
  MARGIN                  NUMBER (16,2), 
  LAST_STOCK_VALUE        NUMBER (16,2), 
  CALC_DRAWING_POWER      NUMBER (16,2), 
  TOTAL_DRAWING_POWER     NUMBER (16,2), 
  DRAWING_POWER_SANCTION  NUMBER (16,2), 
  AUTHORIZE_REMARKS       VARCHAR2 (128), 
  AUTHORIZE_STATUS        VARCHAR2 (16) ) ; 

CREATE TABLE ADV_ENHANCEMENT ( 
  BORROW_NO          VARCHAR2 (16), 
  ACCT_NO            VARCHAR2 (16), 
  PROD_ID            VARCHAR2 (16), 
  ENHANCE_NO         VARCHAR2 (16), 
  ENHANCE_AMT        NUMBER (16,2), 
  ENHANCE_DT         DATE, 
  ENHANCE_PD_FROM    DATE, 
  ENHANCE_PD_TO      DATE, 
  AUTHORIZE_REMARKS  VARCHAR2 (128), 
  AUTHORIZE_STATUS   VARCHAR2 (16) ) ; 

CREATE TABLE ADV_FACILITY_DETAILS ( 
  BORROW_NO           VARCHAR2 (16), 
  SANCTION_NO         VARCHAR2 (16), 
  SL_NO               VARCHAR2 (8), 
  PROD_ID             VARCHAR2 (16), 
  SECURITY_TYPE       VARCHAR2 (16), 
  SECURITY_DETAILS    VARCHAR2 (64), 
  ACCOUNT_TYPE        VARCHAR2 (16), 
  INTEREST_NATURE     VARCHAR2 (16), 
  ACCOUNT_LIMIT       VARCHAR2 (16), 
  RISK_WEIGHT         VARCHAR2 (16), 
  DEMAND_PROM_DT      DATE, 
  DEMAND_PROM_EXPDT   DATE, 
  FROM_DT             DATE, 
  TO_DT               DATE, 
  MARGIN              NUMBER (16,2), 
  DRAWING_POWER       NUMBER (16,2), 
  DRAWING_POWER_APPL  VARCHAR2 (1), 
  PURPOSE_DESC        VARCHAR2 (128), 
  CONTACT_PERSON      VARCHAR2 (64), 
  REMARKS             VARCHAR2 (128), 
  OPERATION_MODE      VARCHAR2 (32), 
  GROUP_DESC          VARCHAR2 (128), 
  CONTACT_PHONE       VARCHAR2 (32), 
  AUTHORIZE_STATUS    VARCHAR2 (16), 
  AUTHORIZE_REMARKS   VARCHAR2 (128) ) ; 

CREATE TABLE ADV_GUARANTOR_DETAILS ( 
  BORROW_NO              VARCHAR2 (16), 
  PROD_ID                VARCHAR2 (16), 
  CUST_ID                VARCHAR2 (16), 
  GUARANTOR_AC_HD        VARCHAR2 (16), 
  GUARANTOR_AC_NO        VARCHAR2 (16), 
  NAME                   VARCHAR2 (64), 
  AGE                    NUMBER (3), 
  STREET                 VARCHAR2 (256), 
  AREA                   VARCHAR2 (128), 
  CITY                   VARCHAR2 (128), 
  STATE                  VARCHAR2 (128), 
  COUNTRY_CODE           VARCHAR2 (4), 
  PINCODE                VARCHAR2 (16), 
  PHONE                  VARCHAR2 (32), 
  CONSTITUTION           VARCHAR2 (64), 
  GUARANTOR_NET_WORTH    NUMBER (16,2), 
  GUARANTOR_NETWORTH_ON  DATE, 
  AUTHORIZE_REMARKS      VARCHAR2 (128), 
  AUTHORIZE_STATUS       VARCHAR2 (16) ) ; 

CREATE TABLE ADV_INSURANCE_DETAILS ( 
  BORROW_NO          VARCHAR2 (16), 
  PROD_ID            VARCHAR2 (16), 
  INSURANCE_COMPANY  VARCHAR2 (32), 
  POLICY_NO          VARCHAR2 (16), 
  POLICY_AMT         NUMBER (16,2), 
  POLICY_DT          DATE, 
  PREMIUM_AMT        NUMBER (16,2), 
  EXPIRY_DT          DATE, 
  RISK_NATURE        VARCHAR2 (32), 
  AUTHORIZE_REMARKS  VARCHAR2 (128), 
  AUTHORIZE_STATUS   VARCHAR2 (16) ) ; 

CREATE TABLE ADV_INT_MAINTENANCE ( 
  BORROW_NO              VARCHAR2 (16), 
  PROD_ID                VARCHAR2 (16), 
  FROM_DT                DATE, 
  TO_DT                  DATE, 
  FROM_AMT               NUMBER (16,2), 
  TO_AMT                 NUMBER (16,2), 
  INTEREST               NUMBER (16,2), 
  PENAL_INTEREST         NUMBER (16,2), 
  AGAINST_CLEARING_INT   NUMBER (16,2), 
  LIMIT_AMT              NUMBER (16,2), 
  INTEREST_EXPIRY_LIMIT  NUMBER (16,2), 
  AUTHORIZE_REMARKS      VARCHAR2 (128), 
  AUTHORIZE_STATUS       VARCHAR2 (16) ) ; 

CREATE TABLE ADV_POA ( 
  BORROW_NO          VARCHAR2 (16), 
  POA_NO             VARCHAR2 (16), 
  POA_HOLDER_NAME    VARCHAR2 (64), 
  STREET             VARCHAR2 (256), 
  AREA               VARCHAR2 (128), 
  CITY               VARCHAR2 (128), 
  STATE              VARCHAR2 (128), 
  COUNTRY_CODE       VARCHAR2 (4), 
  PINCODE            VARCHAR2 (16), 
  PHONE              VARCHAR2 (32), 
  PERIOD_FROM        DATE, 
  PERIOD_TO          DATE, 
  REMARKS            VARCHAR2 (128), 
  AUTHORIZE_REMARKS  VARCHAR2 (128), 
  AUTHORIZE_STATUS   VARCHAR2 (16) ) ; 

CREATE TABLE ADV_SANCTION ( 
  BORROW_NO           VARCHAR2 (16), 
  SANCTION_NO         VARCHAR2 (16), 
  SANCTION_AUTHORITY  VARCHAR2 (32), 
  SANCTION_DT         DATE, 
  SANCTION_MODE       VARCHAR2 (32), 
  REMARKS             VARCHAR2 (128), 
  AUTHORIZE_REMARKS   VARCHAR2 (128), 
  AUTHORIZE_STATUS    VARCHAR2 (32) ) ; 

CREATE TABLE ADV_SANCTION_DETAILS ( 
  BORROW_NO      VARCHAR2 (16), 
  SANCTION_NO    VARCHAR2 (16), 
  SL_NO          VARCHAR2 (8), 
  FACILITY_TYPE  VARCHAR2 (16), 
  LIMIT          VARCHAR2 (32), 
  FROM_DT        DATE, 
  TO_DT          DATE ) ; 

CREATE TABLE BANK ( 
  BANK_CODE      VARCHAR2 (8)  NOT NULL, 
  BANK_NAME      VARCHAR2 (128), 
  WEB_SITE_ADDR  VARCHAR2 (64), 
  WEB_SITE_IP    VARCHAR2 (32), 
  SUPPORT_EMAIL  VARCHAR2 (64), 
  CONSTRAINT BANK_PK
  PRIMARY KEY ( BANK_CODE ) ) ; 

CREATE TABLE BANK_ADDRESS ( 
  BANK_CODE     VARCHAR2 (8), 
  STREET        VARCHAR2 (256), 
  AREA          VARCHAR2 (128), 
  CITY          VARCHAR2 (128), 
  STATE         VARCHAR2 (128), 
  PIN_CODE      VARCHAR2 (16), 
  COUNTRY_CODE  VARCHAR2 (4), 
  AREA_CODE     VARCHAR2 (8) ) ; 

CREATE TABLE BANK_EMPLOYEE ( 
  BRANCH_CODE     VARCHAR2 (8), 
  EMPLOYEE_CODE   VARCHAR2 (8)  NOT NULL, 
  TITLE           VARCHAR2 (8), 
  LNAME           VARCHAR2 (64), 
  FNAME           VARCHAR2 (64), 
  MNAME           VARCHAR2 (64), 
  DESIG_ID        VARCHAR2 (8), 
  DOB             DATE, 
  MARITAL_STATUS  VARCHAR2 (16), 
  GENDER          VARCHAR2 (8), 
  EDUCATION       VARCHAR2 (32), 
  DOJ             DATE, 
  DOL             DATE, 
  DOW             DATE, 
  NO_OF_CHILD     NUMBER (2), 
  FATHER          VARCHAR2 (128), 
  HUSBAND         VARCHAR2 (128), 
  WIFE            VARCHAR2 (128), 
  DEPTT_ID        VARCHAR2 (8), 
  CONSTRAINT BANK_EMP_PK
  PRIMARY KEY ( EMPLOYEE_CODE ) ) ; 

CREATE TABLE BANK_PHONE ( 
  BANK_CODE     VARCHAR2 (8), 
  CONTACT_NO    VARCHAR2 (16), 
  CONTACT_TYPE  CHAR (1) ) ; 

CREATE TABLE BILLS_PRODUCT ( 
  PROD_ID             VARCHAR2 (8), 
  GL_ACHD             VARCHAR2 (16), 
  MANAGING_ACHD       VARCHAR2 (16), 
  INTEREST_ACHD       VARCHAR2 (16), 
  CHRG_ACHD           VARCHAR2 (16), 
  CONTRA_ACHD_YESNO   VARCHAR2 (1), 
  DD_ACHD             VARCHAR2 (16), 
  TRANSIT_PERIOD      NUMBER (4), 
  POST_DTCHQ_ALLOWED  VARCHAR2 (1), 
  COMM_ACHD           VARCHAR2 (16), 
  POSTAGE_ACHD        VARCHAR2 (16), 
  CONTRA_ACHD         VARCHAR2 (16), 
  IBR_ACHD            VARCHAR2 (16), 
  AT_PAR_LIMIT        VARCHAR2 (16) ) ; 

CREATE TABLE BRANCH_MASTER ( 
  BRANCH_CODE   VARCHAR2 (8)  NOT NULL, 
  BRANCH_NAME   VARCHAR2 (128), 
  STREET        VARCHAR2 (256), 
  AREA          VARCHAR2 (128), 
  CITY          VARCHAR2 (128), 
  STATE         VARCHAR2 (128), 
  PIN_CODE      VARCHAR2 (16), 
  COUNTRY_CODE  VARCHAR2 (4), 
  AREA_CODE     VARCHAR2 (8), 
  IP_ADDR       VARCHAR2 (32), 
  PORT          NUMBER (6), 
  CREATED_DT    DATE, 
  DELETED_DT    DATE, 
  STATUS        VARCHAR2 (16), 
  CONSTRAINT BRANCH_MASTER_BRANCHCODE_PK
  PRIMARY KEY ( BRANCH_CODE ) ) ; 

CREATE TABLE BRANCH_PHONE ( 
  BRANCH_CODE   VARCHAR2 (8), 
  CONTACT_NO    VARCHAR2 (16), 
  CONTACT_TYPE  VARCHAR2 (64) ) ; 

CREATE TABLE CASH_TRANS ( 
  TRANS_ID         VARCHAR2 (16), 
  AC_HD_ID         VARCHAR2 (8), 
  ACT_NUM          VARCHAR2 (10), 
  INP_AMOUNT       NUMBER (16,2), 
  INP_CURR         VARCHAR2 (32), 
  AMOUNT           NUMBER (16,2), 
  TRANS_DT         DATE, 
  TRANS_TYPE       VARCHAR2 (32), 
  INST_TYPE        VARCHAR2 (32), 
  INST_NO          VARCHAR2 (32), 
  INST_DT          DATE, 
  TOKEN_NO         NUMBER (32), 
  INIT_TRANS_ID    VARCHAR2 (32), 
  INIT_CHANN_TYPE  VARCHAR2 (32), 
  PARTICULARS      VARCHAR2 (128), 
  STATUS           VARCHAR2 (16) ) ; 

CREATE TABLE CUSTOMER ( 
  CUST_ID             VARCHAR2 (8)  NOT NULL, 
  BRANCH_CODE         VARCHAR2 (8), 
  LNAME               VARCHAR2 (128), 
  FNAME               VARCHAR2 (128), 
  MNAME               VARCHAR2 (128), 
  DOB                 DATE, 
  NETWORTH            NUMBER (16,2), 
  CREATEDDT           DATE, 
  DELETEDDT           DATE, 
  GENDER              VARCHAR2 (16), 
  PROFESSION          VARCHAR2 (64), 
  MINOR               CHAR (1), 
  ANNINCOME           VARCHAR2 (32), 
  EDUCATION           VARCHAR2 (128), 
  VEHICLE             VARCHAR2 (128), 
  REMARKS             VARCHAR2 (256), 
  COMP_NAME           VARCHAR2 (128), 
  COMM_ADDR_TYPE      VARCHAR2 (32), 
  EMAIL_ID            VARCHAR2 (64), 
  TITLE               VARCHAR2 (16), 
  RESIDENTIALSTATUS   VARCHAR2 (32), 
  NATIONALITY         VARCHAR2 (48), 
  LANGUAGE            VARCHAR2 (48), 
  CUSTOMERGROUP       VARCHAR2 (64), 
  RELATIONMANAGER     VARCHAR2 (64), 
  PRIMARY_OCCUPATION  VARCHAR2 (64), 
  PREFERRED_COMM      VARCHAR2 (64), 
  STATUS              VARCHAR2 (32), 
  MARITALSTATUS       VARCHAR2 (32), 
  CUST_TYPE_ID        VARCHAR2 (32), 
  CONSTRAINT CUSTOMER_PK
  PRIMARY KEY ( CUST_ID ) ) ; 

CREATE TABLE CUST_ADDR ( 
  BRANCH_CODE   VARCHAR2 (8), 
  CUST_ID       VARCHAR2 (8), 
  STREET        VARCHAR2 (256), 
  AREA          VARCHAR2 (128), 
  CITY          VARCHAR2 (128), 
  STATE         VARCHAR2 (128), 
  PIN_CODE      VARCHAR2 (16), 
  COUNTRY_CODE  VARCHAR2 (4), 
  ADDR_TYPE     VARCHAR2 (32) ) ; 

CREATE TABLE CUST_PHONE ( 
  CUST_ID        VARCHAR2 (8), 
  PHONE_TYPE_ID  VARCHAR2 (64), 
  AREA_CODE      VARCHAR2 (16), 
  PHONE_NUMBER   VARCHAR2 (16), 
  ADDR_TYPE      VARCHAR2 (32), 
  PHONE_ID       NUMBER (2) ) ; 

CREATE TABLE CUST_TYPE ( 
  CUST_TYPE_ID    VARCHAR2 (8)  NOT NULL, 
  CUST_TYPE_DESC  VARCHAR2 (128), 
  CONSTRAINT CUST_TYPE_PK
  PRIMARY KEY ( CUST_TYPE_ID ) ) ; 

CREATE TABLE DENOMIN_DETAILS ( 
  TRANS_ID      VARCHAR2 (16), 
  DENOM_AMOUNT  VARCHAR2 (16), 
  NO_OF_NOTES   VARCHAR2 (8) ) ; 

CREATE TABLE DEPOSITS_PRODUCT ( 
  PROD_ID       VARCHAR2 (8), 
  PROD_DESC     VARCHAR2 (128), 
  ACCT_HEAD     VARCHAR2 (16), 
  BEHAVES_LIKE  VARCHAR2 (32), 
  REMARKS       VARCHAR2 (128), 
  STATUS        VARCHAR2 (16) ) ; 

CREATE TABLE DEPOSITS_PROD_ACHD ( 
  PROD_ID              VARCHAR2 (8), 
  INT_PROV_ACHD        VARCHAR2 (16), 
  INT_PAY              VARCHAR2 (16), 
  INT_DEBIT            VARCHAR2 (16), 
  MATURITY_DEPOSIT     VARCHAR2 (16), 
  INT_MATURED_DEPOSIT  VARCHAR2 (16), 
  INT_PROV_MATURED     VARCHAR2 (16), 
  ACHD_FLOAT_AC        VARCHAR2 (16), 
  FIXED_DEPOSIT_ACHD   VARCHAR2 (16) ) ; 

CREATE TABLE DEPOSITS_PROD_INTPAY ( 
  PROD_ID             VARCHAR2 (8), 
  INT_MAINTAIN_PART   VARCHAR2 (32), 
  INT_CALC_METHOD     NUMBER (3), 
  INT_PROV_APPL       VARCHAR2 (1), 
  INT_PROV_FREQ       NUMBER (3), 
  PROV_LEVEL          VARCHAR2 (16), 
  NO_DAYS_YEAR        NUMBER (3), 
  INT_COMP_FREQ       NUMBER (3), 
  INT_APPL_FREQ       NUMBER (3), 
  LAST_INT_PROVDT     DATE, 
  NEXT_INT_PROVDT     DATE, 
  LAST_INT_APPLDT     DATE, 
  NEXT_INT_APPLDT     DATE, 
  INT_ROUNDOFF_TERMS  NUMBER (16,2), 
  MIN_INT_PAID        NUMBER (16,2) ) ; 

CREATE TABLE DEPOSITS_PROD_RD ( 
  PROD_ID                  VARCHAR2 (8), 
  LATE_INSTALL_ALLOWED     VARCHAR2 (1), 
  PENALTY_LATE_INSTALL     VARCHAR2 (1), 
  MATURITY_DT_LASTINSTALL  NUMBER (3), 
  CONVERT_RD_TO_FIXED      VARCHAR2 (1), 
  INSTALL_RECURRING_DEPAC  VARCHAR2 (16), 
  INSTALL_CHARGED          NUMBER (3), 
  CHANGE_VALUE             VARCHAR2 (16), 
  RECEIVE_EXCESS_INSTALL   VARCHAR2 (1), 
  INTPAY_EXCESS_INSTALL    VARCHAR2 (1), 
  CUTOFF_PAY_INSTALL       DATE, 
  FROM_DEPOSIT_DT          DATE, 
  LAST_DAY_MONTH           DATE, 
  CHOSEN_DT                DATE ) ; 

CREATE TABLE DEPOSITS_PROD_RENEWAL ( 
  PROD_ID                  VARCHAR2 (8), 
  MAX_PDBKDT_RENEWAL       NUMBER (3), 
  MAX_PD_INTTYPE           VARCHAR2 (16), 
  MAX_PD_MATURITYDT        DATE, 
  MAX_PD_PRESENTDT         DATE, 
  INT_CRITERIA             VARCHAR2 (16), 
  RENEWAL_DEPOSIT_ALLOWED  VARCHAR2 (1), 
  MIN_DAYS_BKDT_DEPOSITS   NUMBER (3), 
  AUTO_RENEWAL_ALLOWED     VARCHAR2 (1), 
  MAX_NO_AUTO_RENEWAL      NUMBER (3) ) ; 

CREATE TABLE DEPOSITS_PROD_SCHEME ( 
  PROD_ID                VARCHAR2 (8), 
  CALCULATE_TDS          VARCHAR2 (1), 
  PAYINT_DEP_MATURITY    VARCHAR2 (1), 
  MATURITY_AMT_ROUND     VARCHAR2 (1), 
  ROUNDOFF_CRITERIA      VARCHAR2 (32), 
  INTPAID_AFTERMATURITY  VARCHAR2 (1), 
  AFTERMATURITY_INTTYPE  VARCHAR2 (16), 
  AFTERMATURITY_INTRATE  VARCHAR2 (16), 
  INTEREST_CRITERIA      VARCHAR2 (16), 
  DEPOSIT_PER_UNIT       NUMBER (3), 
  MIN_DEPOSIT_PERIOD     NUMBER (3), 
  MAX_DEPOSIT_PERIOD     NUMBER (3), 
  PERIOD_MULTIPLES       NUMBER (3), 
  MIN_DEPOSIT_AMT        NUMBER (16,2), 
  MAX_DEPOSIT_AMT        NUMBER (16,2), 
  AMT_MULTIPLES          NUMBER (16,2), 
  CALC_MATURITY_VALUE    VARCHAR2 (1), 
  TRANS_MATURED_DEP      VARCHAR2 (1), 
  AFTER_DAYS             NUMBER (3), 
  ADV_MATURITY_GENPD     NUMBER (3), 
  PROV_INTMATURED_DEP    VARCHAR2 (1), 
  INT_MATURED_DEP        NUMBER (6,2), 
  PARTIAL_WITHDRAWAL     VARCHAR2 (1), 
  NO_PARTIAL_WITHDRAWAL  NUMBER (3), 
  MAX_AMT_WITHDRAWAL     NUMBER (16,2), 
  MAX_NO_WITHDRAWAL_YR   NUMBER (3), 
  MIN_AMT_WITHDRAWAL     NUMBER (16,2), 
  WITHDRAWAL_MULTI       NUMBER (3), 
  WITHDRAWAL_INTEREST    VARCHAR2 (1), 
  EXT_DEP_MATURITY       VARCHAR2 (1), 
  ADJ_MATURITY_LOAN      VARCHAR2 (1), 
  ADJ_INT_LIEN           VARCHAR2 (1), 
  ADJ_PRIN_LOAN_LIEN     VARCHAR2 (1), 
  PREMATURE_WITHDRAWAL   NUMBER (3), 
  FLEXI_SB_CA            VARCHAR2 (1), 
  TD_SECURITY_OD         VARCHAR2 (1), 
  ACNUM_PATTERN          VARCHAR2 (32), 
  ALPHA_SUFFIX_TDREC     VARCHAR2 (16), 
  MAX_AMT_CASH           NUMBER (16,2), 
  MIN_AMT_PAN            NUMBER (16,2), 
  INTRO_REQUIRED         VARCHAR2 (1), 
  SCHEME_INTRO_DT        DATE, 
  SCHEME                 VARCHAR2 (32), 
  SYS_CALC_CHG           VARCHAR2 (1), 
  LIMIT_BULK_DEPOSIT     NUMBER (16,2) ) ; 

CREATE TABLE DEPOSITS_PROD_TAX ( 
  PROD_ID                 VARCHAR2 (8), 
  TDS_GL_ACHD             VARCHAR2 (1), 
  RECALC_MATURITY_VALTDS  VARCHAR2 (1) ) ; 

CREATE TABLE DEPOSIT_ACINFO ( 
  OPENING_MODE          VARCHAR2 (16), 
  PROD_ID               VARCHAR2 (16), 
  CUST_TYPE             VARCHAR2 (16), 
  INTRO_REQUIRED        VARCHAR2 (1), 
  CUST_ID               VARCHAR2 (16), 
  DEPOSIT_NO            VARCHAR2 (16), 
  DEPOSIT_SUB_NO        VARCHAR2 (16), 
  DEPOSIT_DT            DATE, 
  DEPOSIT_PERIOD_YY     VARCHAR2 (2), 
  DEPOSIT_PERIOD_MM     VARCHAR2 (2), 
  DEPOSIT_PERIOD_DD     VARCHAR2 (2), 
  INTPAY_FREQ           NUMBER (3), 
  SETTLEMENT_MODE       VARCHAR2 (16), 
  POA                   VARCHAR2 (1), 
  STANDING_INSTRUCT     VARCHAR2 (1), 
  FIFTEENH_DECLARE      VARCHAR2 (1), 
  REMARKS               VARCHAR2 (128), 
  DEPOSIT_AMT           NUMBER (16,2), 
  PAN_NUMBER            VARCHAR2 (16), 
  INTPAY_MODE           VARCHAR2 (16), 
  COMM_ADDRESS          VARCHAR2 (16), 
  AUTHORIZED_SIGNATORY  VARCHAR2 (1), 
  TAX_DEDUCTIONS        VARCHAR2 (1), 
  NOMINEE_DETAILS       VARCHAR2 (1), 
  MATURITY_DT           DATE, 
  RATE_OF_INT           NUMBER (3), 
  MATURITY_AMT          NUMBER (16,2), 
  TOT_INT_AMT           NUMBER (16,2), 
  PERIODIC_INT_AMT      NUMBER (16,2) ) ; 

CREATE TABLE DEPOSIT_AUTHORIZED ( 
  DEPOSIT_NO      VARCHAR2 (16), 
  AUTHORIZED_NO   VARCHAR2 (16), 
  NAME            VARCHAR2 (64), 
  COMM_ADDR       VARCHAR2 (32), 
  DESIGNATION     VARCHAR2 (64), 
  STREET          VARCHAR2 (256), 
  AREA            VARCHAR2 (128), 
  CITY            VARCHAR2 (128), 
  STATE           VARCHAR2 (128), 
  PIN_CODE        VARCHAR2 (16), 
  COUNTRY_CODE    VARCHAR2 (32), 
  AREA_CODE       VARCHAR2 (8), 
  HOME_PHONE      VARCHAR2 (32), 
  HOME_FAX        VARCHAR2 (32), 
  PAGER           VARCHAR2 (32), 
  EMAILID         VARCHAR2 (32), 
  BUSINESS_PHONE  VARCHAR2 (32), 
  BUSINESS_FAX    VARCHAR2 (32), 
  MOBILE          VARCHAR2 (32), 
  LIMITS          NUMBER (16,2) ) ; 

CREATE TABLE DEPOSIT_DEATH_MARKING ( 
  DEPOSIT_NO    VARCHAR2 (16), 
  PROD_ID       VARCHAR2 (16), 
  DEATH_DT      DATE, 
  REPORTED_ON   DATE, 
  REPORTED_BY   VARCHAR2 (64), 
  RELATIONSHIP  VARCHAR2 (64), 
  REFERENCE_NO  VARCHAR2 (32), 
  DM_DT         DATE, 
  REMARKS       VARCHAR2 (128) ) ; 

CREATE TABLE DEPOSIT_FREEZE ( 
  DEPOSIT_NO      VARCHAR2 (16), 
  DEPOSIT_SUB_NO  VARCHAR2 (16), 
  PROD_ID         VARCHAR2 (16), 
  FSL_NO          VARCHAR2 (16), 
  AMOUNT          NUMBER (16,2), 
  FREEZE_DT       DATE, 
  TYPE            VARCHAR2 (32), 
  BALANCE         NUMBER (16,2), 
  REMARKS         VARCHAR2 (128), 
  UNFREEZE_DT     DATE ) ; 

CREATE TABLE DEPOSIT_INTRO_OTHERS ( 
  DEPOSIT_NO    VARCHAR2 (16), 
  INTRO_NAME    VARCHAR2 (64), 
  INTRO_DESIG   VARCHAR2 (64), 
  STREET        VARCHAR2 (256), 
  AREA          VARCHAR2 (128), 
  CITY          VARCHAR2 (128), 
  STATE         VARCHAR2 (128), 
  PIN_CODE      VARCHAR2 (16), 
  COUNTRY_CODE  VARCHAR2 (32), 
  AREA_CODE     VARCHAR2 (8), 
  PH_NO         VARCHAR2 (16) ) ; 

CREATE TABLE DEPOSIT_INTRO_PROOF ( 
  DEPOSIT_NO     VARCHAR2 (16), 
  PROOF_TYPE_ID  VARCHAR2 (32), 
  PROOF_NUM      VARCHAR2 (32), 
  ISSUE_AUTH     VARCHAR2 (128) ) ; 

CREATE TABLE DEPOSIT_INTRO_SELF ( 
  DEPOSIT_NO     VARCHAR2 (16), 
  INTRO_CUST_ID  VARCHAR2 (16) ) ; 

CREATE TABLE DEPOSIT_LIEN ( 
  DEPOSIT_NO          VARCHAR2 (16), 
  DEPOSIT_SUB_NO      VARCHAR2 (16), 
  CUSTOMER_SERIAL_NO  VARCHAR2 (16), 
  LIEN_NO             VARCHAR2 (16), 
  LIEN_AMOUT          NUMBER (16,2), 
  LIEN_DT             DATE, 
  LIEN_AC_HD          VARCHAR2 (16), 
  LIEN_AC_NO          VARCHAR2 (16), 
  REMARKS             VARCHAR2 (128), 
  CREDIT_LIEN_ACCT    VARCHAR2 (16), 
  UNFREEZE_DT         DATE ) ; 

CREATE TABLE DEPOSIT_NOMINEE ( 
  DEPOSIT_NO      VARCHAR2 (16), 
  NOMINEE_ID      VARCHAR2 (16), 
  NOMINEE_NAME    VARCHAR2 (64), 
  RELATIONSHIP    VARCHAR2 (64), 
  STREET          VARCHAR2 (256), 
  AREA            VARCHAR2 (128), 
  CITY            VARCHAR2 (128), 
  STATE           VARCHAR2 (128), 
  PIN_CODE        VARCHAR2 (16), 
  COUNTRY_CODE    VARCHAR2 (32), 
  AREA_CODE       VARCHAR2 (8), 
  PH_NO           VARCHAR2 (32), 
  SHARE_PER       NUMBER (3), 
  NOMINEE_STATUS  VARCHAR2 (16), 
  NOMINEE_DOB     DATE, 
  GUARDIAN_NAME   VARCHAR2 (64), 
  G_STREET        VARCHAR2 (256), 
  G_AREA          VARCHAR2 (128), 
  G_CITY          VARCHAR2 (128), 
  G_STATE         VARCHAR2 (128), 
  G_PIN_CODE      VARCHAR2 (16), 
  G_COUNTRY_CODE  VARCHAR2 (32), 
  G_AREA_CODE     VARCHAR2 (8), 
  G_PH_NO         VARCHAR2 (32) ) ; 

CREATE TABLE DEPOSIT_POA ( 
  DEPOSIT_NO       VARCHAR2 (16), 
  POA_NO           VARCHAR2 (16), 
  POA_HOLDER_NAME  VARCHAR2 (64), 
  STREET           VARCHAR2 (256), 
  AREA             VARCHAR2 (128), 
  CITY             VARCHAR2 (128), 
  STATE            VARCHAR2 (128), 
  PIN_CODE         VARCHAR2 (16), 
  COUNTRY_CODE     VARCHAR2 (32), 
  AREA_CODE        VARCHAR2 (8), 
  PH_NO            VARCHAR2 (32), 
  PERIOD_FROM      DATE, 
  PERIOD_TO        DATE, 
  REMARKS          VARCHAR2 (128) ) ; 

CREATE TABLE DEPOSIT_RDINSTALL ( 
  PROD_ID         VARCHAR2 (16), 
  DEPOSIT_NO      VARCHAR2 (16), 
  DEPOSIT_SUB_NO  VARCHAR2 (16), 
  TRANS_DT        DATE, 
  TRANS_AMT       NUMBER (16,2) ) ; 

CREATE TABLE DEPOSIT_STANDING_INSTRU ( 
  DEPOSIT_NO      VARCHAR2 (16), 
  DEBIT_PROD_ID   VARCHAR2 (16), 
  DEBIT_ACHD      VARCHAR2 (16), 
  DEPOSIT_SUB_NO  VARCHAR2 (16), 
  AMOUNT          NUMBER (16,2), 
  PARTICULARS     VARCHAR2 (128), 
  CR_PROD_ID      VARCHAR2 (16), 
  CR_ACHD         VARCHAR2 (16), 
  CR_AC_NO        VARCHAR2 (16), 
  CR_DEPOSIT_NO   VARCHAR2 (16), 
  CR_AMOUNT       NUMBER (16,2), 
  CR_PARTICULARS  VARCHAR2 (128) ) ; 

CREATE TABLE DEPOSIT_TRANSIN ( 
  DEPOSIT_NO            VARCHAR2 (16), 
  TRANS_BRANCH_CODE     VARCHAR2 (16), 
  ORIGINAL_AC_NUMBER    VARCHAR2 (16), 
  ORIGINAL_DEPOSIT_DT   DATE, 
  PRINTED_FDR           NUMBER (4), 
  INTERBRANCH_TRANS_NO  VARCHAR2 (16), 
  TRANS_DT              DATE, 
  TRANS_AMT             NUMBER (16,2), 
  LAST_INTCALC_DT       DATE, 
  TDS_COLLECTED_UPTO    DATE, 
  INT_PROV_AMT          NUMBER (16,2), 
  LAST_TDS_COLLECTED    NUMBER (16,2), 
  INT_PAID              NUMBER (16,2), 
  TOT_NO_INSTALL        NUMBER (4), 
  TOT_INSTALL_RECEIVED  NUMBER (16,2), 
  LAST_INSTALL_RECDT    DATE, 
  BALANCE_INT_PAYABLE   NUMBER (16,2) ) ; 

CREATE TABLE DEPTT_MASTER ( 
  DEPTT_ID    VARCHAR2 (8)  NOT NULL, 
  DEPTT_NAME  VARCHAR2 (64), 
  CONSTRAINT DEPTT_PK
  PRIMARY KEY ( DEPTT_ID ) ) ; 

CREATE TABLE DESIG_MASTER ( 
  DESIG_ID      VARCHAR2 (8)  NOT NULL, 
  DESIG_DESCIP  VARCHAR2 (128), 
  CONSTRAINT DESIG_PK
  PRIMARY KEY ( DESIG_ID ) ) ; 

CREATE TABLE EMPLOYEE_ADDR ( 
  EMPLOYEE_ID   VARCHAR2 (8), 
  STREET        VARCHAR2 (256), 
  AREA          VARCHAR2 (128), 
  CITY          VARCHAR2 (128), 
  STATE         VARCHAR2 (128), 
  PIN_CODE      VARCHAR2 (16), 
  COUNTRY_CODE  VARCHAR2 (4), 
  AREA_CODE     VARCHAR2 (8) ) ; 

CREATE TABLE FUNC_ID_MASTER ( 
  MENU_ID    VARCHAR2 (8), 
  SCREEN_ID  VARCHAR2 (8), 
  FUNC_ID    VARCHAR2 (8)  NOT NULL, 
  FUNC_DESC  VARCHAR2 (128), 
  CONSTRAINT FUNCID_MASTER_PK
  PRIMARY KEY ( FUNC_ID ) ) ; 

CREATE TABLE GL ( 
  AC_HD_ID     VARCHAR2 (16), 
  OPN_BAL      NUMBER (16,2), 
  CUR_BAL      NUMBER (16,2), 
  BRANCH_CODE  VARCHAR2 (8), 
  USER_ID      VARCHAR2 (8) ) ; 

CREATE TABLE GL_ABSTRACT ( 
  AC_HD_ID     VARCHAR2 (16), 
  OPN_BAL      NUMBER (16,2), 
  CLOSE_BAL    NUMBER (16,2), 
  BRANCH_CODE  VARCHAR2 (8), 
  USER_ID      VARCHAR2 (8), 
  DT           DATE ) ; 

CREATE TABLE ID_GENERATION ( 
  ID_KEY        VARCHAR2 (32), 
  CURR_VALUE    NUMBER (16), 
  PREFIX        VARCHAR2 (8), 
  LAST_UPDATED  DATE, 
  ID_LENGTH     NUMBER (2) ) ; 

CREATE TABLE LOANS_AUTHORIZE ( 
  BORROW_NO          VARCHAR2 (16), 
  AUTHRIZE_NO        VARCHAR2 (16), 
  CUST_ID            VARCHAR2 (16), 
  CUST_NAME          VARCHAR2 (64), 
  COMM_ADDR          VARCHAR2 (32), 
  STREET             VARCHAR2 (256), 
  AREA               VARCHAR2 (128), 
  CITY               VARCHAR2 (128), 
  STATE              VARCHAR2 (128), 
  COUNTRY_CODE       VARCHAR2 (4), 
  PINCODE            VARCHAR2 (16), 
  LIMITS             NUMBER (16,2), 
  DESIGNATION        VARCHAR2 (32), 
  HOME_PHONE         VARCHAR2 (32), 
  HOME_FAX           VARCHAR2 (32), 
  PAGER              VARCHAR2 (32), 
  EMAIL_ID           VARCHAR2 (32), 
  BUSINESS_PHONE     VARCHAR2 (32), 
  BUSINESS_FAX       VARCHAR2 (32), 
  MOBILE             VARCHAR2 (32), 
  AUTHORIZE_REMARKS  VARCHAR2 (128), 
  AUTHORIZE_STATUS   VARCHAR2 (16) ) ; 

CREATE TABLE LOANS_BORROWER ( 
  BORROW_NO          VARCHAR2 (16), 
  BORROW_STATUS      VARCHAR2 (16), 
  CUST_ID            VARCHAR2 (16), 
  ACCT_STATUS        VARCHAR2 (16), 
  CONSTITUTION       VARCHAR2 (64), 
  CATEGORY           VARCHAR2 (32), 
  REFERENCES         VARCHAR2 (128), 
  AUTHORIZE_REMARKS  VARCHAR2 (128), 
  AUTHORIZE_STATUS   VARCHAR2 (16) ) ; 

CREATE TABLE LOANS_CLASSIFY_DETAILS ( 
  BORROW_NO                VARCHAR2 (16), 
  PROD_ID                  VARCHAR2 (16), 
  COMMODITY_CODE           VARCHAR2 (32), 
  BUSINESS_SECTOR_CODE     VARCHAR2 (32), 
  FACILITY_TYPE            VARCHAR2 (32), 
  PURPOSE_CODE             VARCHAR2 (32), 
  INDUSTRY_CODE            VARCHAR2 (32), 
  TWENTY_CODE              VARCHAR2 (32), 
  GOVT_SCHEME_CODE         VARCHAR2 (32), 
  NPA_DT                   DATE, 
  ECGC                     VARCHAR2 (1), 
  DOCUMENT_COMPLETE        VARCHAR2 (1), 
  GUARANTEE_COVER_CODE     VARCHAR2 (16), 
  HEALTH_CODE              VARCHAR2 (16), 
  DISTRICT_CODE            VARCHAR2 (16), 
  SECTOR_CODE              VARCHAR2 (16), 
  PAYMENT_CODE             VARCHAR2 (16), 
  REFINANCING_INSTITUTION  VARCHAR2 (16), 
  ASSET_STATUS             VARCHAR2 (32), 
  DIRECT_FINANCE           VARCHAR2 (1), 
  PRIORITY_SECTOR          VARCHAR2 (1), 
  QIS                      VARCHAR2 (1), 
  AUTHORIZE_REMARKS        VARCHAR2 (128), 
  AUTHORIZE_STATUS         VARCHAR2 (16) ) ; 

CREATE TABLE LOANS_COMPANY ( 
  BORROW_NO            VARCHAR2 (16), 
  CO_REG_NO            VARCHAR2 (16), 
  ESTABLISH_DT         DATE, 
  DEAL_BANK_SINCE      DATE, 
  NET_WORTH            NUMBER (16,2), 
  NET_WORTH_ON         DATE, 
  CHIEF_EXEC_NAME      VARCHAR2 (32), 
  ADDR_TYPE            VARCHAR2 (32), 
  STREET               VARCHAR2 (256), 
  AREA                 VARCHAR2 (128), 
  CITY                 VARCHAR2 (128), 
  STATE                VARCHAR2 (128), 
  COUNTRY_CODE         VARCHAR2 (4), 
  PINCODE              VARCHAR2 (16), 
  PHONE                VARCHAR2 (32), 
  RISK_RATE            NUMBER (3), 
  BUSINESS_NATURE      VARCHAR2 (64), 
  REMARKS              VARCHAR2 (128), 
  CR_FACILITIES_SINCE  DATE, 
  AUTHORIZE_REMARKS    VARCHAR2 (128), 
  AUTHORIZE_STATUS     VARCHAR2 (16) ) ; 

CREATE TABLE LOANS_DRAWING_POWER ( 
  BORROW_NO               VARCHAR2 (16), 
  PROD_ID                 VARCHAR2 (16), 
  ACCT_NO                 VARCHAR2 (16), 
  STOCK_STAT_FREQ         NUMBER (3), 
  PREV_DPVALUE_CALCDT     DATE, 
  PREV_DP_MONTH           VARCHAR2 (16), 
  PREV_DP_VALUE           NUMBER (16,2), 
  CURR_DP_MONTH           VARCHAR2 (16), 
  DUE_DT                  DATE, 
  STOCK_SUBMIT_DT         DATE, 
  GOODS_PARTICULARS       VARCHAR2 (128), 
  INSPECTION_DT           DATE, 
  OPENING_STOCK_VALUE     NUMBER (16,2), 
  PURCHASE                NUMBER (16,2), 
  CLOSING_STOCK_VALUE     NUMBER (16,2), 
  SALES                   NUMBER (16,2), 
  SECURITY_NO             VARCHAR2 (16), 
  PRESENT_STOCK_VALUE     NUMBER (16,2), 
  MARGIN                  NUMBER (16,2), 
  LAST_STOCK_VALUE        NUMBER (16,2), 
  CALC_DRAWING_POWER      NUMBER (16,2), 
  TOTAL_DRAWING_POWER     NUMBER (16,2), 
  DRAWING_POWER_SANCTION  NUMBER (16,2), 
  AUTHORIZE_REMARKS       VARCHAR2 (128), 
  AUTHORIZE_STATUS        VARCHAR2 (16) ) ; 

CREATE TABLE LOANS_FACILITY_DETAILS ( 
  BORROW_NO          VARCHAR2 (16), 
  SANCTION_NO        VARCHAR2 (16), 
  SL_NO              VARCHAR2 (16), 
  PROD_ID            VARCHAR2 (16), 
  SECURITY_TYPE      VARCHAR2 (32), 
  SECURITY_DETAILS   VARCHAR2 (64), 
  ACCOUNT_TYPE       VARCHAR2 (16), 
  INTEREST_NATURE    VARCHAR2 (16), 
  INTEREST_TYPE      VARCHAR2 (16), 
  ACCOUNT_LIMIT      VARCHAR2 (16), 
  RISK_WEIGHT        VARCHAR2 (1), 
  DEMAND_PROM_DT     DATE, 
  DEMAND_PROM_EXPDT  DATE, 
  MULTI_DISBURSE     VARCHAR2 (1), 
  SUBSIDY            VARCHAR2 (1), 
  AOD_DT             DATE, 
  PURPOSE_DESC       VARCHAR2 (128), 
  GROUP_DESC         VARCHAR2 (128), 
  INTEREST           VARCHAR2 (16), 
  RECARABLE          VARCHAR2 (1), 
  CONTACT_PERSON     VARCHAR2 (32), 
  CONTACT_PHONE      VARCHAR2 (32), 
  REMARKS            VARCHAR2 (128), 
  AUTHORIZE_STATUS   VARCHAR2 (16), 
  AUTHORIZE_REMARKS  VARCHAR2 (128) ) ; 

CREATE TABLE LOANS_GUARANTOR_DETAILS ( 
  BORROW_NO              VARCHAR2 (16), 
  PROD_ID                VARCHAR2 (16), 
  CUST_ID                VARCHAR2 (16), 
  GUARANTOR_AC_HD        VARCHAR2 (16), 
  GUARANTOR_AC_NO        VARCHAR2 (16), 
  NAME                   VARCHAR2 (32), 
  AGE                    NUMBER (3), 
  STREET                 VARCHAR2 (256), 
  AREA                   VARCHAR2 (128), 
  CITY                   VARCHAR2 (128), 
  STATE                  VARCHAR2 (128), 
  COUNTRY_CODE           VARCHAR2 (4), 
  PINCODE                VARCHAR2 (16), 
  PHONE                  VARCHAR2 (32), 
  CONSTITUTION           VARCHAR2 (64), 
  GUARANTOR_NET_WORTH    NUMBER (16,2), 
  GUARANTOR_NETWORTH_ON  DATE, 
  AUTHORIZE_REMARKS      VARCHAR2 (128), 
  AUTHORIZE_STATUS       VARCHAR2 (16) ) ; 

CREATE TABLE LOANS_INSURANCE_DETAILS ( 
  BORROW_NO          VARCHAR2 (16), 
  PROD_ID            VARCHAR2 (16), 
  INSURANCE_COMPANY  VARCHAR2 (64), 
  POLICY_NO          VARCHAR2 (32), 
  POLICY_AMT         NUMBER (16,2), 
  POLICY_DT          DATE, 
  PREMIUM_AMT        NUMBER (16,2), 
  EXPIRY_DT          DATE, 
  RISK_NATURE        VARCHAR2 (32), 
  AUTHORIZE_REMARKS  VARCHAR2 (128), 
  AUTHORIZE_STATUS   VARCHAR2 (16) ) ; 

CREATE TABLE LOANS_INT_MAINTENANCE ( 
  BORROW_NO              VARCHAR2 (16), 
  PROD_ID                VARCHAR2 (16), 
  FROM_DT                DATE, 
  TO_DT                  DATE, 
  FROM_AMT               NUMBER (16,2), 
  TO_AMT                 NUMBER (16,2), 
  INTEREST               NUMBER (3), 
  PENAL_INTEREST         NUMBER (3), 
  AGAINST_CLEARING_INT   NUMBER (3), 
  LIMIT_AMT              NUMBER (16,2), 
  INTEREST_EXPIRY_LIMIT  NUMBER (3), 
  AUTHORIZE_REMARKS      VARCHAR2 (128), 
  AUTHORIZE_STATUS       VARCHAR2 (16) ) ; 

CREATE TABLE LOANS_POA ( 
  BORROW_NO          VARCHAR2 (16), 
  POA_NO             VARCHAR2 (16), 
  POA_HOLDER_NAME    VARCHAR2 (32), 
  STREET             VARCHAR2 (256), 
  AREA               VARCHAR2 (128), 
  CITY               VARCHAR2 (128), 
  STATE              VARCHAR2 (128), 
  COUNTRY_CODE       VARCHAR2 (4), 
  PINCODE            VARCHAR2 (16), 
  PHONE              VARCHAR2 (32), 
  PERIOD_FROM        DATE, 
  PERIOD_TO          DATE, 
  REMARKS            VARCHAR2 (128), 
  AUTHORIZE_REMARKS  VARCHAR2 (128), 
  AUTHORIZE_STATUS   VARCHAR2 (16) ) ; 

CREATE TABLE LOANS_PRODUCT ( 
  PROD_ID       VARCHAR2 (8), 
  PROD_DESC     VARCHAR2 (128), 
  ACCT_HEAD     VARCHAR2 (16), 
  BEHAVES_LIKE  VARCHAR2 (32), 
  REMARKS       VARCHAR2 (128), 
  STATUS        VARCHAR2 (16) ) ; 

CREATE TABLE LOANS_PROD_ACHD ( 
  PROD_ID               VARCHAR2 (8), 
  AC_CLOSING_CHRG       VARCHAR2 (16), 
  MISC_SERV_CHRG        VARCHAR2 (16), 
  STAT_CHRG             VARCHAR2 (16), 
  AC_DEBIT_INT          VARCHAR2 (16), 
  PENAL_INT             VARCHAR2 (16), 
  AC_CREDIT_INT         VARCHAR2 (16), 
  EXPIRY_INT            VARCHAR2 (16), 
  CHQ_RET_CHRG_OUTWARD  VARCHAR2 (16), 
  CHQ_RET_CHRG_INWARD   VARCHAR2 (16), 
  FOLIO_CHRG_AC         VARCHAR2 (16), 
  COMMITMENT_CHRG       VARCHAR2 (16), 
  PROC_CHRG             VARCHAR2 (16), 
  INT_REC_GL            VARCHAR2 (16) ) ; 

CREATE TABLE LOANS_PROD_ACPARAM ( 
  PROD_ID                 VARCHAR2 (8), 
  NUMBER_PATTERN          VARCHAR2 (16), 
  LAST_AC_NO              VARCHAR2 (16), 
  LIMIT_DEF_ALLOWED       VARCHAR2 (1), 
  STAFF_AC_OPENED         VARCHAR2 (1), 
  DEBIT_INT_CLEARINGAPPL  VARCHAR2 (1) ) ; 

CREATE TABLE LOANS_PROD_CHARGES ( 
  PROD_ID                VARCHAR2 (8), 
  AC_CLOSING_CHRG        NUMBER (16,2), 
  MISC_SERV_CHRG         NUMBER (16,2), 
  STAT_CHRG              VARCHAR2 (1), 
  STAT_CHRG_RATE         NUMBER (16,2), 
  FOLIO_CHRG_APPL        VARCHAR2 (1), 
  LAST_FOLIO_CHRGON      DATE, 
  NO_ENTRIES_PER_FOLIO   NUMBER (5), 
  NEXT_FOLIO_DUEDATE     DATE, 
  RATE_PER_FOLIO         NUMBER (16,2), 
  FOLIO_CHRG_APPLFREQ    NUMBER (3), 
  TO_COLLECT_FOLIOCHRG   VARCHAR2 (64), 
  TO_COLLECT_CHRG_ON     VARCHAR2 (32), 
  INCOMP_FOLIO_ROUNDOFF  NUMBER (3), 
  PROC_CHRG              VARCHAR2 (1), 
  PROC_CHRG_PER          NUMBER (3), 
  PROC_CHRG_AMT          NUMBER (16,2), 
  COMMIT_CHRG            VARCHAR2 (1), 
  COMMIT_CHRG_PER        NUMBER (3), 
  COMMIT_CHRG_AMT        NUMBER (16,2) ) ; 

CREATE TABLE LOANS_PROD_CHQCHRG ( 
  PROD_ID               VARCHAR2 (8), 
  CHQ_RETURN_CHRG       VARCHAR2 (64), 
  CHQ_RETURN_CHRG_RATE  NUMBER (16,2) ) ; 

CREATE TABLE LOANS_PROD_INTCALC ( 
  PROD_ID                 VARCHAR2 (8), 
  CALC_TYPE               VARCHAR2 (32), 
  MIN_PERIOD              NUMBER (4), 
  MAX_PERIOD              NUMBER (4), 
  MIN_AMT_LOAN            NUMBER (16,2), 
  MAX_AMT_LOAN            NUMBER (16,2), 
  MIN_INTEREST            NUMBER (3), 
  MAX_INTEREST            NUMBER (3), 
  MIN_INT_DEBIT           NUMBER (3), 
  SUBSIDY                 VARCHAR2 (1), 
  LOAN_PERIODS_MULTIPLES  NUMBER (3) ) ; 

CREATE TABLE LOANS_PROD_INTREC ( 
  PROD_ID                 VARCHAR2 (8), 
  DEBIT_INT_CHARGED       VARCHAR2 (1), 
  MIN_DEBITINT_RATE       NUMBER (3), 
  MAX_DEBITINT_RATE       NUMBER (3), 
  MIN_DEBITINT_AMT        NUMBER (16,2), 
  MAX_DEBITINT_AMT        NUMBER (16,2), 
  DEBITINT_CALC_FREQ      NUMBER (3), 
  DEBITINT_APPL_FREQ      NUMBER (3), 
  DEBITINT_COMP_FREQ      NUMBER (3), 
  DEBIT_PROD_ROUNDOFF     VARCHAR2 (16), 
  DEBIT_INT_ROUNDOFF      VARCHAR2 (16), 
  LAST_INTCALC_DTDEBIT    DATE, 
  LAST_INTAPPL_DTDEBIT    DATE, 
  PROD_FREQ               NUMBER (3), 
  PLR_RATE_APPL           VARCHAR2 (1), 
  PLR_RATE                NUMBER (3), 
  PLR_APPL_FROM           DATE, 
  PLR_APPL_NEWAC          VARCHAR2 (1), 
  PLR_APPL_EXISTAC        VARCHAR2 (1), 
  PLR_APPL_SANCFROM       DATE, 
  PENAL_APPL              VARCHAR2 (1), 
  LIMIT_EXPIRY_INT        VARCHAR2 (1), 
  PENAL_INT_RATE          NUMBER (3), 
  EXPO_LMT_PRUDENTIALAMT  NUMBER (16,2), 
  EXPO_LMT_POLICYAMT      NUMBER (16,2), 
  EXPO_LMT_PRUDENTIALPER  NUMBER (3), 
  EXPO_LMT_POLICYPER      NUMBER (3) ) ; 

CREATE TABLE LOANS_PROD_NONPERASSET ( 
  PROD_ID                    VARCHAR2 (8), 
  MIN_PERIOD_ARREARS         NUMBER (4), 
  PERIOD_TRANS_SUBSTANDARD   NUMBER (4), 
  PROVISION_SUBSTANDARD      VARCHAR2 (1), 
  PERIOD_TRANS_DOUBTFUL      NUMBER (4), 
  PROVISION_DOUBTFUL         VARCHAR2 (1), 
  LAST_INT_APPLDT_CR         DATE, 
  PERIOD_TRANS_LOSS          NUMBER (4), 
  PERIOD_TRANS_NOPERFORMING  NUMBER (4) ) ; 

CREATE TABLE LOANS_PROD_SPECIALITEM ( 
  PROD_ID                 VARCHAR2 (8), 
  ATM_CARD_ISSUED         VARCHAR2 (1), 
  CR_CARD_ISSUED          VARCHAR2 (1), 
  MOBILE_BANK_CLIENT      VARCHAR2 (1), 
  BRANCH_BANKING_ALLOWED  VARCHAR2 (1) ) ; 

CREATE TABLE LOANS_REPAY_SCHEDULE ( 
  BORROW_NO                VARCHAR2 (16), 
  PROD_ID                  VARCHAR2 (16), 
  SCHEDULE_NO              VARCHAR2 (16), 
  LOAN_AMOUNT              NUMBER (16,2), 
  INT_TYPE                 VARCHAR2 (32), 
  INSTALL_TYPE             VARCHAR2 (32), 
  REPAYMENT_TYPE           NUMBER (3), 
  NO_INSTALLMENTS          NUMBER (3), 
  MORATORIUM_GIVEN         VARCHAR2 (1), 
  NO_MORATORIUM            NUMBER (3), 
  FIRST_INSTALL_DT         DATE, 
  LAST_INSTALL_DT          DATE, 
  TOTAL_BASE_AMT           NUMBER (16,2), 
  BALANCE_LOAN_AMT         NUMBER (16,2), 
  AMT_PENULTIMATE_INSTALL  NUMBER (16,2), 
  EMI                      NUMBER (16,2), 
  AMT_LAST_INSTALL         NUMBER (16,2), 
  REPAYMENT_PR             NUMBER (16,2), 
  TOTAL_INSTALL_AMT        NUMBER (16,2), 
  REPAY_INTEREST           NUMBER (3), 
  ADD_SI                   VARCHAR2 (1), 
  POST_DATE_CHQALLOWED     VARCHAR2 (1), 
  AUTHORIZE_REMARKS        VARCHAR2 (128), 
  AUTHORIZE_STATUS         VARCHAR2 (16) ) ; 

CREATE TABLE LOANS_SANCTION ( 
  BORROW_NO           VARCHAR2 (16), 
  SANCTION_NO         VARCHAR2 (16), 
  SANCTION_AUTHORITY  VARCHAR2 (32), 
  SANCTION_DT         DATE, 
  SANCTION_MODE       VARCHAR2 (32), 
  NO_INSTALLMENT      NUMBER (3), 
  REPAYMENT_FREQ      NUMBER (3), 
  REMARKS             VARCHAR2 (128), 
  AUTHORIZE_REMARKS   VARCHAR2 (128), 
  AUTHORIZE_STATUS    VARCHAR2 (16) ) ; 

CREATE TABLE LOANS_SANCTION_DETAILS ( 
  BORROW_NO      VARCHAR2 (16), 
  SANCTION_NO    VARCHAR2 (16), 
  SL_NO          VARCHAR2 (16), 
  FACILITY_TYPE  VARCHAR2 (32), 
  LIMIT          NUMBER (16,2), 
  FROM_DT        DATE, 
  TO_DT          DATE ) ; 

CREATE TABLE LOANS_SECURITY_DETAILS ( 
  BORROW_NO            VARCHAR2 (16), 
  PROD_ID              VARCHAR2 (16), 
  SECURITY_NO          VARCHAR2 (16), 
  SECURITY_CATEGORY    VARCHAR2 (32), 
  SECURITY_VALUE       NUMBER (16,2), 
  SECURITY_VALUE_ON    DATE, 
  PARTICULARS          VARCHAR2 (128), 
  SECURITY_TYPE        VARCHAR2 (32), 
  FROM_DT              DATE, 
  TO_DT                DATE, 
  MARGIN               NUMBER (16,2), 
  CHARGE_NATURE        VARCHAR2 (32), 
  CHARGE_DT            DATE, 
  SELECTIVE_COMMODITY  VARCHAR2 (1), 
  INDUSTRIAL_USERS     VARCHAR2 (32), 
  INSPECTION_DT        DATE, 
  STOCK_STAT_FREQ      NUMBER (3), 
  AUTHORIZE_REMARKS    VARCHAR2 (128), 
  AUTHORIZE_STATUS     VARCHAR2 (16) ) ; 

CREATE TABLE LOOKUP_MASTER ( 
  LOOKUP_ID      VARCHAR2 (64), 
  LOOKUP_REF_ID  VARCHAR2 (64), 
  LOOKUP_DESC    VARCHAR2 (128) ) ; 

CREATE TABLE MENU_MASTER ( 
  MENU_ID     VARCHAR2 (8)  NOT NULL, 
  MENU_NAME   VARCHAR2 (32), 
  MENU_DESC   VARCHAR2 (64), 
  PR_MENU_ID  VARCHAR2 (8), 
  CONSTRAINT MENU_MASTER_PK
  PRIMARY KEY ( MENU_ID ) ) ; 

CREATE TABLE MJR_AC_HD ( 
  MJR_AC_HD_ID    VARCHAR2 (4)  NOT NULL, 
  MJR_AC_HD_DESC  VARCHAR2 (128), 
  MJR_AC_HD_TYPE  VARCHAR2 (32), 
  STATUS          VARCHAR2 (8), 
  CONSTRAINT MJR_AC_HD_PK
  PRIMARY KEY ( MJR_AC_HD_ID ) ) ; 

CREATE TABLE OP_AC_ACCOUNT_PARAM ( 
  PROD_ID                 VARCHAR2 (16), 
  CHK_ALLOWED             CHAR (1), 
  MIN_BAL_W_CHK           NUMBER (16,2), 
  MIN_BAL_WT_CHK          NUMBER (16,2), 
  INT_REQ                 CHAR (1), 
  NOMINEE_REQ             CHAR (1), 
  NO_OF_NOMINEE           NUMBER (10), 
  AC_OP_REQ               CHAR (1), 
  MIN_PD_NEW              NUMBER (10), 
  MIN_PD_DORMANT          NUMBER (10), 
  MIN_PD_INOP             NUMBER (10), 
  MIN_PD_CLS              NUMBER (10), 
  STAT_FREQUENCY          NUMBER (10), 
  FREE_WITHDRAWALS        NUMBER (10), 
  FREE_WITHDRAWALS_PD     NUMBER (10), 
  FREE_WITHDRAWAL_FROM    DATE, 
  NO_FREE_CHK_LEAVES      NUMBER (10), 
  FREE_CHK_LEAVES_PD      NUMBER (10), 
  FREE_CHK_LEAVES_FROM    DATE, 
  TAX_INT_APPLICABLE      CHAR (1), 
  RATE_OF_INT             NUMBER (6,2), 
  LMT_DEFINITION_ALLOWED  CHAR (1), 
  TEMP_OD_ALLOWED         CHAR (1), 
  STAFF_ACCT_OPENED       CHAR (1), 
  EXTRA_INT_APPLICABLE    CHAR (1), 
  COLLECT_INT_CREDIT      CHAR (1), 
  DEBIT_INT_CLEARING      CHAR (1), 
  CREDIT_INT_UNCLEAR      CHAR (1), 
  ISSUE_TOKEN             CHAR (1), 
  ALLOW_WITHDRAWAL_SLIP   CHAR (1), 
  MAX_ALLOWED_WD_SLIP     NUMBER (16,2) ) ; 

CREATE TABLE OP_AC_ACHEAD_PARAM ( 
  PROD_ID            VARCHAR2 (16), 
  INOP_AC_CHRG       VARCHAR2 (16), 
  PREMATCLOSE_CHRG   VARCHAR2 (16), 
  ACCLOSE_CHRG       VARCHAR2 (16), 
  MISSER_CHRG        VARCHAR2 (16), 
  STAT_CHRG          VARCHAR2 (16), 
  FREEWITHD_CHRG     VARCHAR2 (16), 
  DEBIT_INT          VARCHAR2 (16), 
  CREDIT_INT         VARCHAR2 (16), 
  CLR_INT            VARCHAR2 (16), 
  CHQ_ISSUE_CHRG     VARCHAR2 (16), 
  STOP_PMT_CHRG      VARCHAR2 (16), 
  CHQ_RET_OUT        VARCHAR2 (16), 
  CHQ_RET_IN         VARCHAR2 (16), 
  ACT_OP_CHRG        VARCHAR2 (16), 
  EXCESS_FREE_WITHD  VARCHAR2 (16), 
  TAX                VARCHAR2 (16), 
  NONMNT_MIN_CHRG    VARCHAR2 (16), 
  INOPT              VARCHAR2 (16), 
  FOLIO_CHRG         VARCHAR2 (16) ) ; 

CREATE TABLE OP_AC_CHARGES_PARAM ( 
  PROD_ID                      VARCHAR2 (16), 
  INOPERATIVE_AC_CHARGES       NUMBER (16,2), 
  INOPERATIVE_AC_CHARGE_PD     NUMBER (10), 
  CHG_PREMATURE_CLOSURE        NUMBER (16,2), 
  ACCT_CLOSING_CHG             NUMBER (16,2), 
  MISC_SERVICE_CHG             NUMBER (16,2), 
  NONMAIN_MIN_BAL_CHG          CHAR (1), 
  AMT_NONMAIN_MINBAL           NUMBER (16,2), 
  AMT_NONMAIN_MINBAL_PD        VARCHAR2 (32), 
  STAT_CHARGE                  VARCHAR2 (32), 
  AMT_CHARGE_STAT              NUMBER (16,2), 
  AMT_CHARGE_STAT_TYPE         VARCHAR2 (32), 
  CHK_ISSUE_CHG                CHAR (1), 
  CHK_ISSUE_CHGPERLEAF         NUMBER (16,2), 
  STOP_PAYMENT_CHG             CHAR (1), 
  STOP_PAYMENT_AMTCHG          NUMBER (16,2), 
  CHK_RETURN_CHG_OUTWARD       NUMBER (16,2), 
  CHK_RETURN_CHG_INWARD        NUMBER (16,2), 
  ACCT_OPENING_CHG             NUMBER (16,2), 
  FOLIO_CHG_APPLICABLE         CHAR (1), 
  NO_ENTRIESPER_FOLIO          NUMBER (10), 
  RATE_PER_FOLIO               NUMBER (16,2), 
  TO_CHARGE_ON                 VARCHAR2 (32), 
  FOLIO_CHG_APPL_FREQ          NUMBER (10), 
  TO_COLLECT_FOLIO_CHG         VARCHAR2 (32), 
  TO_CHARGE_ON_TYPE            VARCHAR2 (32), 
  INCOMPLETE_FOLIO_ROUND_FREQ  VARCHAR2 (32), 
  CHG_EXCESSFREEWD_PERTRANS    NUMBER (16,2), 
  OUTST_CHK_CHARGES            CHAR (1) ) ; 

CREATE TABLE OP_AC_INTPAY_PARAM ( 
  PROD_ID                VARCHAR2 (16), 
  MIN_CR_INT_RATE        NUMBER (16,2), 
  MAX_CR_INT_RATE        NUMBER (16,2), 
  APPL_CR_INT_RATE       NUMBER (16,2), 
  MIN_CR_INT_AMT         NUMBER (16,2), 
  MAX_CR_INT_AMT         NUMBER (16,2), 
  CR_INT_CALC_FREQ       NUMBER (10), 
  CR_INT_APPL_FREQ       NUMBER (10), 
  STARTMON_INT_CALC      VARCHAR2 (32), 
  ENDMON_INT_CALC        VARCHAR2 (32), 
  LAST_INT_CALCDT_CR     DATE, 
  LAST_INT_APPLDT_CR     DATE, 
  CR_COMPOUND            CHAR (1), 
  CR_COMPOUND_CALC_FREQ  NUMBER (10), 
  CR_PRODUCT_ROUNDOFF    VARCHAR2 (32), 
  CR_INT_ROUNDOFF        VARCHAR2 (32), 
  STARTDAY_PROD_CALC     NUMBER (16,2), 
  ENDDAY_PROD_CALC       NUMBER (16,2), 
  CALC_CRITERIA          VARCHAR2 (64), 
  PRODUCT_FREQ_INT_PAY   VARCHAR2 (32), 
  CREDIT_INT_GIVEN       CHAR (1), 
  ADDITIONAL_INT_STAFF   NUMBER (16,2) ) ; 

CREATE TABLE OP_AC_INTRATEMAINT_PARAM ( 
  PROD_ID     VARCHAR2 (16), 
  INT_CAT_ID  VARCHAR2 (16), 
  INT_DATE    DATE, 
  INT_RATE    NUMBER (6,2), 
  AC_HD_ID    VARCHAR2 (16) ) ; 

CREATE TABLE OP_AC_INTRECV_PARAM ( 
  PROD_ID                  VARCHAR2 (16), 
  DEBIT_INT_CHARGED        CHAR (1), 
  MIN_DEBIT_INT_RATE       NUMBER (16,2), 
  MAX_DEBIT_INT_RATE       NUMBER (16,2), 
  APPL_DEBIT_INT_RATE      NUMBER (16,2), 
  MIN_DEBIT_INT_AMT        NUMBER (16,2), 
  MAX_DEBIT_INT_AMT        NUMBER (16,2), 
  DEBIT_INT_CALC_FREQ      NUMBER (10), 
  DEBIT_INT_APPL_FREQ      NUMBER (10), 
  DEBIT_COMPOUND           CHAR (1), 
  DEBIT_COMPINT_CALC_FREQ  NUMBER (10), 
  DEBIT_PRODUCT_ROUNDOFF   VARCHAR2 (32), 
  DEBIT_INT_ROUNDOFF       VARCHAR2 (32), 
  LAST_INT_CALCDT_DEBIT    DATE, 
  LAST_INT_APPLDT_DEBIT    DATE, 
  PRODUCT_FREQ             NUMBER (10), 
  PENAL_INT_DEBIT_BALACCT  NUMBER (16,2), 
  PENAL_INT_CHARGE_STDAY   NUMBER (10) ) ; 

CREATE TABLE OP_AC_INT_CAT_MASTER ( 
  INT_CAT_ID    VARCHAR2 (16), 
  INT_CAT_DESC  VARCHAR2 (128) ) ; 

CREATE TABLE OP_AC_PRODUCT ( 
  AC_HD_ID   VARCHAR2 (16), 
  PROD_ID    VARCHAR2 (8), 
  PROD_DESC  VARCHAR2 (128), 
  BEHAVIOR   VARCHAR2 (128), 
  STATUS     VARCHAR2 (32) ) ; 

CREATE TABLE OP_AC_SPCLITEM_PARAM ( 
  PROD_ID                VARCHAR2 (16), 
  LINKED_FLEXI_ACCT      CHAR (1), 
  MIN_BAL1_FLEXIDEPOSIT  NUMBER (16,2), 
  MIN_BAL2_FLEXIDEPOSIT  NUMBER (16,2), 
  FLEXI_HAPPEN           VARCHAR2 (32), 
  ATM_CARD_ISSUED        CHAR (1), 
  MIN_BAL_ATM            NUMBER (16,2), 
  CR_CARD_ISSUED         CHAR (1), 
  MIN_BAL_CR_CARD        NUMBER (16,2), 
  DR_CARD_ISSUED         CHAR (1), 
  MIN_BAL_DR_CARD        NUMBER (16,2), 
  IVRS_PROVIDED          CHAR (1), 
  MIN_BAL_IVRS           NUMBER (16,2), 
  MOBILE_BANKING         CHAR (1), 
  MIN_BAL_MOBILE         NUMBER (16,2), 
  ANY_BRANCH_BANKING     CHAR (1), 
  MIN_BAL_ABB            NUMBER (16,2), 
  FLEXI_PROD_ID          VARCHAR2 (16) ) ; 

CREATE TABLE PRIVI_MASTER ( 
  PRIVI_ID       VARCHAR2 (8)  NOT NULL, 
  PRIVI_DESC     VARCHAR2 (128), 
  ACCESS_LVL_ID  VARCHAR2 (8), 
  FIN_LIMIT      NUMBER (16,2), 
  CONSTRAINT PRIVI_MASTER_PK
  PRIMARY KEY ( PRIVI_ID ) ) ; 

CREATE TABLE PWD_MASTER ( 
  USER_ID         VARCHAR2 (16)  NOT NULL, 
  PWD_ID          VARCHAR2 (16)  NOT NULL, 
  PWD             VARCHAR2 (32), 
  LPWDCHANGEDT    DATE, 
  LLOGINCHANGEDT  DATE, 
  STATUS          VARCHAR2 (32), 
  PRIVI_ID        VARCHAR2 (8), 
  PWD_USAGE       VARCHAR2 (128), 
  CONSTRAINT PWD_MASTER_PK
  PRIMARY KEY ( USER_ID, PWD_ID ) ) ; 

CREATE TABLE REMITTANCE_PRODUCT ( 
  PROD_ID            VARCHAR2 (8), 
  PROD_DESC          VARCHAR2 (128), 
  ISSUE_HD           VARCHAR2 (16), 
  EXCHANGE_HD        VARCHAR2 (16), 
  TELEGRAM_CHRG_HD   VARCHAR2 (16), 
  REVAL_CHRG_HD      VARCHAR2 (16), 
  OTHER_CHRG_HD      VARCHAR2 (16), 
  LAPSED_HD          VARCHAR2 (16), 
  EFT_PRODUCT        VARCHAR2 (1), 
  CASH_LIMIT         NUMBER (16,2), 
  PRINT_SERVICES     VARCHAR2 (1), 
  PAY_HD             VARCHAR2 (16), 
  POSTAGE_HD         VARCHAR2 (16), 
  DUPL_CHRG_HD       VARCHAR2 (16), 
  CANCELL_CHRG_HD    VARCHAR2 (16), 
  LAPSE_APPL         VARCHAR2 (1), 
  LAPSE_PERIOD       NUMBER (3), 
  PAY_ISSUE_BRANCH   VARCHAR2 (1), 
  NUMBER_PATTERN     VARCHAR2 (16), 
  SERIES_MAINTAINED  VARCHAR2 (1), 
  REMARKS            VARCHAR2 (128), 
  STATUS             VARCHAR2 (16) ) ; 

CREATE TABLE REMITTANCE_PROD_BRANCH ( 
  PROD_ID           VARCHAR2 (8), 
  BRANCH_CODE       VARCHAR2 (16), 
  BRANCH_NAME       VARCHAR2 (64), 
  REMITTANCE_TYPE   VARCHAR2 (32), 
  APPLICABILITY     VARCHAR2 (32), 
  REMITTANCE_LIMIT  NUMBER (16,2) ) ; 

CREATE TABLE REMITTANCE_PROD_NUMBER ( 
  PROD_ID              VARCHAR2 (8), 
  INWARD_VARIABLE_NO   VARCHAR2 (16), 
  OUTWARD_VARIABLE_NO  VARCHAR2 (16), 
  MIN_AMT              NUMBER (16,2), 
  MAX_AMT              NUMBER (16,2) ) ; 

CREATE TABLE SCREEN_MASTER ( 
  SCREEN_ID    VARCHAR2 (8)  NOT NULL, 
  MENU_ID      VARCHAR2 (8), 
  SCREEN_NAME  VARCHAR2 (64), 
  CONSTRAINT SCREEN_MASTER_PK
  PRIMARY KEY ( SCREEN_ID ) ) ; 

CREATE TABLE SUB_AC_HD ( 
  MJR_AC_HD_ID    VARCHAR2 (4), 
  SUB_AC_HD_ID    VARCHAR2 (4)  NOT NULL, 
  SUB_AC_HD_DESC  VARCHAR2 (128), 
  STATUS          VARCHAR2 (8), 
  CONSTRAINT SUB_AC_HD_PK
  PRIMARY KEY ( SUB_AC_HD_ID ) ) ; 

CREATE TABLE TRANSFER_TRANS ( 
  TRANS_ID         VARCHAR2 (16), 
  BATCH_ID         VARCHAR2 (8), 
  AC_HD_ID         VARCHAR2 (8), 
  ACT_NUM          VARCHAR2 (10), 
  INP_AMOUNT       NUMBER (16,2), 
  INP_CURR         VARCHAR2 (32), 
  AMOUNT           NUMBER (16,2), 
  TRANS_DT         DATE, 
  TRANS_TYPE       VARCHAR2 (32), 
  INST_TYPE        VARCHAR2 (32), 
  INST_NO          VARCHAR2 (32), 
  INST_DT          DATE, 
  TOKEN_NO         VARCHAR2 (16), 
  INIT_TRANS_ID    VARCHAR2 (32), 
  INIT_CHANN_TYPE  VARCHAR2 (32), 
  PARTICULARS      VARCHAR2 (128), 
  STATUS           VARCHAR2 (16) ) ; 

CREATE TABLE USER_MASTER ( 
  USER_ID          VARCHAR2 (8)  NOT NULL, 
  PWD              VARCHAR2 (32), 
  STATUS           VARCHAR2 (32), 
  EMPLOYEE_ID      VARCHAR2 (8), 
  EMAIL_ID         VARCHAR2 (64), 
  EXPIRY_DATE      DATE, 
  REMARKS          VARCHAR2 (256), 
  PIN_LOGIN        CHAR (1), 
  SUSPEND_BY_USER  CHAR (1), 
  SUSPEND_USER     CHAR (1), 
  ACTIVATION_DATE  DATE, 
  CONSTRAINT USER_MASTER_PK
  PRIMARY KEY ( USER_ID ) ) ; 

ALTER TABLE ACCESS_LVL_MASTER ADD  CONSTRAINT ACCESS_LVL_MASTER_FUNCID_FK
 FOREIGN KEY (FUNC_ID) 
  REFERENCES TTUSER.FUNC_ID_MASTER (FUNC_ID) ;

ALTER TABLE ACCESS_LVL_MASTER ADD  CONSTRAINT ACCESS_LVL_MASTER_MENUID_FK
 FOREIGN KEY (MENU_ID) 
  REFERENCES TTUSER.MENU_MASTER (MENU_ID) ;

ALTER TABLE ACCESS_LVL_MASTER ADD  CONSTRAINT ACCESS_LVL_MASTER_SCREENID_FK
 FOREIGN KEY (SCREEN_ID) 
  REFERENCES TTUSER.SCREEN_MASTER (SCREEN_ID) ;

ALTER TABLE AC_HD ADD  CONSTRAINT AC_HD_MJRID_FK
 FOREIGN KEY (MJR_AC_HD_ID) 
  REFERENCES TTUSER.MJR_AC_HD (MJR_AC_HD_ID) ;

ALTER TABLE AC_HD ADD  CONSTRAINT AC_HD_SUBID_FK
 FOREIGN KEY (SUB_AC_HD_ID) 
  REFERENCES TTUSER.SUB_AC_HD (SUB_AC_HD_ID) ;

ALTER TABLE BANK_ADDRESS ADD  CONSTRAINT BANK_ADDR_BANKCODE_FK
 FOREIGN KEY (BANK_CODE) 
  REFERENCES TTUSER.BANK (BANK_CODE) ;

ALTER TABLE BANK_EMPLOYEE ADD  CONSTRAINT BANK_EMP_DEPTTID_FK
 FOREIGN KEY (DEPTT_ID) 
  REFERENCES TTUSER.DEPTT_MASTER (DEPTT_ID) ;

ALTER TABLE BANK_EMPLOYEE ADD  CONSTRAINT BANK_EMP_DESIGID
 FOREIGN KEY (DESIG_ID) 
  REFERENCES TTUSER.DESIG_MASTER (DESIG_ID) ;

ALTER TABLE BANK_PHONE ADD  CONSTRAINT BANK_PHONE_BANKCODE_FK
 FOREIGN KEY (BANK_CODE) 
  REFERENCES TTUSER.BANK (BANK_CODE) ;

ALTER TABLE BRANCH_PHONE ADD  CONSTRAINT BRANCH_PHONE_BRANCHCODE_FK
 FOREIGN KEY (BRANCH_CODE) 
  REFERENCES TTUSER.BRANCH_MASTER (BRANCH_CODE) ;

ALTER TABLE CUST_ADDR ADD  CONSTRAINT CUST_ADDR_CUSTID_FK
 FOREIGN KEY (CUST_ID) 
  REFERENCES TTUSER.CUSTOMER (CUST_ID) ;

ALTER TABLE CUST_PHONE ADD  CONSTRAINT CUST_PHONE_CUSTID_FK
 FOREIGN KEY (CUST_ID) 
  REFERENCES TTUSER.CUSTOMER (CUST_ID) ;

ALTER TABLE EMPLOYEE_ADDR ADD  CONSTRAINT EMPLOYEE_ADDR_EMPYID_FK
 FOREIGN KEY (EMPLOYEE_ID) 
  REFERENCES TTUSER.BANK_EMPLOYEE (EMPLOYEE_CODE) ;

ALTER TABLE FUNC_ID_MASTER ADD  CONSTRAINT FUNCID_MASTER_MENUID_FK
 FOREIGN KEY (MENU_ID) 
  REFERENCES TTUSER.MENU_MASTER (MENU_ID) ;

ALTER TABLE FUNC_ID_MASTER ADD  CONSTRAINT FUNCID_MASTER_SCREENID_FK
 FOREIGN KEY (SCREEN_ID) 
  REFERENCES TTUSER.SCREEN_MASTER (SCREEN_ID) ;

ALTER TABLE PRIVI_MASTER ADD  CONSTRAINT PRIVI_MASTER_ACCESSLVLID_FK
 FOREIGN KEY (ACCESS_LVL_ID) 
  REFERENCES TTUSER.ACCESS_LVL_MASTER (ACCESS_LVL_ID) ;

ALTER TABLE SCREEN_MASTER ADD  CONSTRAINT SCREEN_MASTER_MENUID_FK
 FOREIGN KEY (MENU_ID) 
  REFERENCES TTUSER.MENU_MASTER (MENU_ID) ;

ALTER TABLE SUB_AC_HD ADD  CONSTRAINT SUB_AC_HD_MJRID_FK
 FOREIGN KEY (MJR_AC_HD_ID) 
  REFERENCES TTUSER.MJR_AC_HD (MJR_AC_HD_ID) ;

ALTER TABLE USER_MASTER ADD  CONSTRAINT USER_MASTER_EMP_ID_FK
 FOREIGN KEY (EMPLOYEE_ID) 
  REFERENCES TTUSER.BANK_EMPLOYEE (EMPLOYEE_CODE) ;

