DROP TABLE ID_GENERATION CASCADE CONSTRAINTS ; 

CREATE TABLE ID_GENERATION (
   ID_KEY         VARCHAR2(32),
   CURR_VALUE     NUMBER (16),
   PREFIX         VARCHAR2(8),
   ID_LENGTH      NUMBER (2),
   LAST_UPDATED   DATE);

DROP TABLE ACCESS_LVL_MASTER CASCADE CONSTRAINTS ; 

CREATE TABLE ACCESS_LVL_MASTER ( 
  ACCESS_LVL_ID    VARCHAR2 (8)  NOT NULL, 
  ACCESS_LVL_DESC  VARCHAR2 (128), 
  MENU_ID          VARCHAR2 (8), 
  SCREEN_ID        VARCHAR2 (8), 
  FUNC_ID          VARCHAR2 (8), 
  CONSTRAINT ACCESS_LVL_MASTER_PK
  PRIMARY KEY ( ACCESS_LVL_ID ) ) ; 


DROP TABLE ACT_ACTION_HISTORY CASCADE CONSTRAINTS ; 

CREATE TABLE ACT_ACTION_HISTORY ( 
  ACT_NUM      VARCHAR2 (10), 
  ACTION_BY    VARCHAR2 (64), 
  ACTION_TYPE  VARCHAR2 (32), 
  ACTION_DT    DATE, 
  REMARKS      VARCHAR2 (256) ) ; 

DROP TABLE ACT_CLOSING CASCADE CONSTRAINTS ; 

CREATE TABLE ACT_CLOSING ( 
  ACT_NUM           VARCHAR2 (10), 
  UNUSED_CHK        NUMBER (4), 
  ACT_CLOSING_CHRG  NUMBER (16,2), 
  INT_PAYABLE       NUMBER (16,2), 
  CHRG_DETAILS      NUMBER (16,2), 
  PAYABLE_BAL       NUMBER (16,2)) ; 

DROP TABLE ACT_FREEZE CASCADE CONSTRAINTS ; 

CREATE TABLE ACT_FREEZE ( 
  ACT_NUM        VARCHAR2 (10), 
  FREEZE_ID      VARCHAR2 (8), 
  FREEZE_AMT     NUMBER (16,2), 
  FREEZE_DT      DATE, 
  FREEZE_TYPE    VARCHAR2 (64), 
  FREEZE_DR_CR   VARCHAR2 (32), 
  FREEZE_STATUS  VARCHAR2 (64), 
  UNFREEZE_DT    DATE, 
  REMARKS        VARCHAR2 (256) ) ; 

DROP TABLE ACT_INTRO_OTHERS CASCADE CONSTRAINTS ; 

CREATE TABLE ACT_INTRO_OTHERS ( 
  ACT_NUM       VARCHAR2 (10), 
  INTRO_NAME    VARCHAR2 (64), 
  INTRO_DESIG   VARCHAR2 (64), 
  STREET        VARCHAR2 (256), 
  AREA          VARCHAR2 (128), 
  CITY          VARCHAR2 (128), 
  STATE         VARCHAR2 (128), 
  PIN_CODE      VARCHAR2 (16), 
  COUNTRY_CODE  VARCHAR2 (32), 
  AREA_CODE     VARCHAR2 (8), 
  PH_NO         VARCHAR2 (16) ) ; 

DROP TABLE ACT_INTRO_DOC CASCADE CONSTRAINTS ; 

CREATE TABLE ACT_INTRO_DOC ( 
  ACT_NUM       VARCHAR2 (10), 
  DOC_TYPE      VARCHAR2 (64), 
  ISSUE_DT      DATE, 
  EXPIRY_DT     DATE, 
  ISSUED_BY     VARCHAR2 (64), 
  DOC_NO        VARCHAR2 (32)); 


DROP TABLE ACT_INTRO_OTHERBANK CASCADE CONSTRAINTS ; 

CREATE TABLE ACT_INTRO_OTHERBANK ( 
  ACT_NUM        VARCHAR2 (10), 
  BANK_NAME      VARCHAR2 (64), 
  BRANCH_NAME    VARCHAR2 (64), 
  OTHER_ACT_NUM  VARCHAR2 (32), 
  OTHER_ACT_NAME VARCHAR2 (64)); 

DROP TABLE ACT_INTRO_PROOF CASCADE CONSTRAINTS ; 

CREATE TABLE ACT_INTRO_PROOF ( 
  ACT_NUM         VARCHAR2 (10), 
  PROOF_TYPE_ID   VARCHAR2 (32), 
  PROOF_NUM       VARCHAR2 (32), 
  ISSUE_AUTH      VARCHAR2 (128), 
  ACT_INTRO_FLAG  VARCHAR2 (16) ) ; 

DROP TABLE ACT_INTRO_SELF CASCADE CONSTRAINTS ; 

CREATE TABLE ACT_INTRO_SELF ( 
  ACT_NUM        VARCHAR2 (10), 
  ACT_NUM_INTRO  VARCHAR2 (10) ) ; 

DROP TABLE ACT_LIEN CASCADE CONSTRAINTS ; 

CREATE TABLE ACT_LIEN ( 
  ACT_NUM       VARCHAR2 (10), 
  LIEN_ID       VARCHAR2 (8), 
  LIEN_AMT      NUMBER (16,2), 
  LIEN_DT       DATE, 
  LIEN_AC_HD    VARCHAR2 (16), 
  LIEN_ACT_NUM  VARCHAR2 (10), 
  LIEN_STATUS   VARCHAR2 (32), 
  UNLIEN_DT     DATE, 
  REMARKS       VARCHAR2 (256) ) ; 

DROP TABLE ACT_MASTER CASCADE CONSTRAINTS ; 

CREATE TABLE ACT_MASTER ( 
  ACT_NUM               VARCHAR2 (10), 
  PROD_ID               VARCHAR2 (16), 
  CUST_ID               VARCHAR2 (8), 
  BRANCH_CODE           VARCHAR2 (8), 
  CREATE_DT             DATE, 
  ACT_STATUS_ID         VARCHAR2 (32), 
  ACT_CAT_ID            VARCHAR2 (32), 
  OPT_MODE_ID           VARCHAR2 (32), 
  INTRO_TYPE_ID         VARCHAR2 (32), 
  TOD_LIMIT             NUMBER (16,2), 
  GROUP_CODE_ID         VARCHAR2 (32), 
  SETTMT_MODE_ID        VARCHAR2 (32), 
  ACT_CODE_ID           VARCHAR2 (32), 
  PREV_ACT_NUM          VARCHAR2 (10), 
  CLEAR_BALANCE         NUMBER (16,2), 
  UNCLEAR_BALANCE       NUMBER (16,2), 
  FLOAT_BALANCE         NUMBER (16,2), 
  EFFECTIVE_BALANCE     NUMBER (16,2), 
  AVAILABLE_BALANCE     NUMBER (16,2), 
  CREATED_BY            VARCHAR2 (64), 
  AUTHORIZED_BY         VARCHAR2 (64), 
  AUTHORIZATION_STATUS  VARCHAR2 (32), 
  LAST_TRANS_DT         DATE, 
  CLOSED_BY             VARCHAR2 (64), 
  CLOSED_DT             DATE, 
  BASE_CURR             VARCHAR2 (32) ) ; 

DROP TABLE ACT_NOMINEE_DETAIL CASCADE CONSTRAINTS ; 

CREATE TABLE ACT_NOMINEE_DETAIL ( 
  ACT_NUM         VARCHAR2 (10), 
  NOMINEE_ID      VARCHAR2 (8), 
  NOMINEE_NAME    VARCHAR2 (64), 
  RELATIONSHIP    VARCHAR2 (32), 
  STREET          VARCHAR2 (256), 
  AREA            VARCHAR2 (128), 
  CITY            VARCHAR2 (128), 
  STATE           VARCHAR2 (128), 
  PIN_CODE        VARCHAR2 (16), 
  COUNTRY         VARCHAR2 (32), 
  AREA_CODE       VARCHAR2 (8), 
  PH_NO           VARCHAR2 (64), 
  SHARE_PER       NUMBER (10), 
  NOMINEE_STATUS  VARCHAR2 (32), 
  NOMINEE_DOB     DATE, 
  GUARDIAN_NAME   VARCHAR2 (64), 
  G_RELATIONSHIP  VARCHAR2 (32), 
  G_STREET        VARCHAR2 (256), 
  G_AREA          VARCHAR2 (128), 
  G_CITY          VARCHAR2 (128), 
  G_STATE         VARCHAR2 (128), 
  G_PIN_CODE      VARCHAR2 (16), 
  G_COUNTRY_CODE  VARCHAR2 (4), 
  G_AREA_CODE     VARCHAR2 (8), 
  G_PH_NO         VARCHAR2 (64) ); 

DROP TABLE ACT_PARAM_DETAIL CASCADE CONSTRAINTS ; 

CREATE TABLE ACT_PARAM_DETAIL ( 
 ACT_NUM                       VARCHAR2(10),
 INT_CR_BAL                    CHAR(1),
 INT_DR_BAL                    CHAR(1),
 CHK_BOOK                      CHAR(1),
 NRO_STATUS                    CHAR(1),
 MOBILE_BANKING                CHAR(1),
 ATM_CARD                      CHAR(1),
 ATM_CARD_NO                   VARCHAR2(16),
 ATM_CARD_EXPRDT               DATE,
 CR_CARD                       CHAR(1),
 CR_CARD_NO                    VARCHAR2(16),
 CR_CARD_EXPRDT                DATE,
 DR_CARD                       CHAR(1),
 DR_CARD_NO                    VARCHAR2(16),
 DR_CARD_EXPRDT                DATE,
 ABB                           CHAR(1),
 ABB_CHRG                      NUMBER(16,2),
 NPA                           CHAR(1),
 NPA_DT                        DATE,
 STOP_PAY_CHRG                 CHAR(1),
 FLEXI                         CHAR(1),
 MIN_BAL1_FLEXI                NUMBER(16,2),
 MIN_BAL2_FLEXI                NUMBER(16,2),
 ACT_OPEN_CHRG                 NUMBER(16,2),
 CHK_RETURN                    CHAR(1),
 INOP_CHRG                     CHAR(1),
 STAT_CHRG                     CHAR(1),
 NONMAIN_CHRG                  CHAR(1),
 LAST_DR_INT_APPLDT            DATE,
 CUSTGRP_LIMIT_VALIDATION      CHAR(1),
 MIN_ACT_BAL                   NUMBER(16,2),
 CHK_BOOK_CHRG                 NUMBER(16,2),
 REQ_FLEXI_PD                  NUMBER(10),
 MISC_SERV_CHRG                NUMBER(16,2),
 FOLIO_CHRG                    NUMBER(16,2),
 ACT_CLOSING_CHRG              NUMBER(16,2),
 STAT_FREQ                     NUMBER(10),
 EXCESS_WITHD_CHRG             NUMBER(16,2),
 LAST_CR_INT_APPLDT            DATE
) ; 

DROP TABLE ACT_POA CASCADE CONSTRAINTS ; 

CREATE TABLE ACT_POA ( 
  ACT_NUM       VARCHAR2 (10), 
  POA_ID        VARCHAR2 (8), 
  POA_NAME      VARCHAR2 (64), 
  STREET        VARCHAR2 (256), 
  AREA          VARCHAR2 (128), 
  CITY          VARCHAR2 (128), 
  STATE         VARCHAR2 (128), 
  PIN_CODE      VARCHAR2 (16), 
  COUNTRY       VARCHAR2 (32), 
  AREA_CODE     VARCHAR2 (8), 
  PH_NO         VARCHAR2 (64), 
  PERIOD_FROM   DATE, 
  PERIOD_TO     DATE, 
  REMARKS       VARCHAR2 (256) ) ; 

DROP TABLE AC_HD CASCADE CONSTRAINTS ; 

CREATE TABLE AC_HD ( 
  MJR_AC_HD_ID  VARCHAR2 (4), 
  SUB_AC_HD_ID  VARCHAR2 (4), 
  AC_HD_ID      VARCHAR2 (16)  NOT NULL, 
  CALLING_CODE  VARCHAR2 (16), 
  AC_HD_DESC    VARCHAR2 (128), 
  STATUS        VARCHAR2 (32), 
  CREATED_DT    DATE, 
  DELETED_DT    DATE, 
  CONSTRAINT AC_HD_CALLING_UNIQUE
    UNIQUE (CALLING_CODE), 
  CONSTRAINT AC_HD_PK
  PRIMARY KEY ( AC_HD_ID ) ) ; 


DROP TABLE AC_HD_PARAM CASCADE CONSTRAINTS ; 

CREATE TABLE AC_HD_PARAM ( 
  AC_HD_ID         VARCHAR2 (16), 
  AC_HD_STATUS_ID  VARCHAR2 (16), 
  FLOAT_ACT        CHAR (1), 
  CONTRA_ACT       VARCHAR2 (16), 
  CR_CLR           CHAR (1), 
  CR_TRANS         CHAR (1), 
  CR_CASH          CHAR (1), 
  DR_CLR           CHAR (1), 
  DR_TRANS         CHAR (1), 
  DR_CASH          CHAR (1), 
  RECONS           CHAR (1), 
  F_TRANS_DT       DATE, 
  L_TRANS_DT       DATE,
  AC_OPEN_DT       DATE, 
  AC_CLOSE_DT      DATE,
  TRANSPOST        VARCHAR2 (32),
  POSTMODE         VARCHAR2 (32),
  BALANCETYPE      VARCHAR2 (32),
  GLBALANCE        NUMBER(16,2)),
  STATUS           VARCHAR2 (16); 

/*
Table Dropped
--------------
DROP TABLE AC_HD_STATUS CASCADE CONSTRAINTS ; 

CREATE TABLE AC_HD_STATUS ( 
  AC_HD_STATUS_ID  VARCHAR2 (16)  NOT NULL, 
  TYPE             VARCHAR2 (32), 
  REMARKS          VARCHAR2 (128), 
  CONSTRAINT AC_HD_STATUS_PK
  PRIMARY KEY ( AC_HD_STATUS_ID ) ) ; 
*/

DROP TABLE BANK CASCADE CONSTRAINTS ; 

CREATE TABLE BANK ( 
  BANK_CODE      VARCHAR2 (8)  NOT NULL, 
  BANK_NAME      VARCHAR2 (128), 
  WEB_SITE_ADDR  VARCHAR2 (64), 
  WEB_SITE_IP    VARCHAR2 (32), 
  SUPPORT_EMAIL  VARCHAR2 (64), 
  CONSTRAINT BANK_PK
  PRIMARY KEY ( BANK_CODE ) ) ; 

DROP TABLE BANK_ADDRESS CASCADE CONSTRAINTS ; 

CREATE TABLE BANK_ADDRESS ( 
  BANK_CODE     VARCHAR2 (8), 
  STREET        VARCHAR2 (256), 
  AREA          VARCHAR2 (128), 
  CITY          VARCHAR2 (128), 
  STATE         VARCHAR2 (128), 
  PIN_CODE      VARCHAR2 (16), 
  COUNTRY_CODE  VARCHAR2 (4), 
  AREA_CODE     VARCHAR2 (8) ) ; 


DROP TABLE BANK_EMPLOYEE CASCADE CONSTRAINTS ; 

CREATE TABLE BANK_EMPLOYEE ( 
  BRANCH_CODE     VARCHAR2 (8), 
  EMPLOYEE_CODE   VARCHAR2 (8)  NOT NULL, 
  TITLE           VARCHAR2 (8), 
  LNAME           VARCHAR2 (64), 
  FNAME           VARCHAR2 (64), 
  MNAME           VARCHAR2 (64), 
  DESIG_ID        VARCHAR2 (8), 
  DOB             DATE, 
  MARITAL_STATUS  VARCHAR2 (16), 
  GENDER          VARCHAR2 (8), 
  EDUCATION       VARCHAR2 (32), 
  DOJ             DATE, 
  DOL             DATE, 
  DOW             DATE, 
  NO_OF_CHILD     NUMBER (2), 
  FATHER          VARCHAR2 (128), 
  HUSBAND         VARCHAR2 (128), 
  WIFE            VARCHAR2 (128), 
  DEPTT_ID        VARCHAR2 (8), 
  CONSTRAINT BANK_EMP_PK
  PRIMARY KEY ( EMPLOYEE_CODE ) ) ; 


DROP TABLE BANK_PHONE CASCADE CONSTRAINTS ; 

CREATE TABLE BANK_PHONE ( 
  BANK_CODE     VARCHAR2 (8), 
  CONTACT_NO    VARCHAR2 (16), 
  CONTACT_TYPE  CHAR (1) ) ; 


/*DROP TABLE BRANCH_ADDRESS CASCADE CONSTRAINTS ; 

CREATE TABLE BRANCH_ADDRESS ( 
  BRANCH_CODE   VARCHAR2 (8), 
  STREET        VARCHAR2 (256), 
  AREA          VARCHAR2 (128), 
  CITY          VARCHAR2 (128), 
  STATE         VARCHAR2 (128), 
  PIN_CODE      VARCHAR2 (16), 
  COUNTRY_CODE  VARCHAR2 (4), 
  AREA_CODE     VARCHAR2 (8) ) ; */


DROP TABLE BRANCH_MASTER CASCADE CONSTRAINTS ; 

CREATE TABLE BRANCH_MASTER ( 
  BRANCH_CODE  VARCHAR2 (8)  NOT NULL, 
  BRANCH_NAME  VARCHAR2 (128), 
  STREET        VARCHAR2 (256), 
  AREA          VARCHAR2 (128), 
  CITY          VARCHAR2 (128), 
  STATE         VARCHAR2 (128), 
  PIN_CODE      VARCHAR2 (16), 
  COUNTRY_CODE  VARCHAR2 (4), 
  AREA_CODE     VARCHAR2 (8), 
  CREATED_DT    DATE, 
  DELETED_DT    DATE,
  STATUS        VARCHAR2 (16), 
  CONSTRAINT BRANCH_MASTER_BRANCHCODE_PK
  PRIMARY KEY ( BRANCH_CODE ) ) ; 

DROP TABLE BRANCH_PHONE CASCADE CONSTRAINTS ; 

CREATE TABLE BRANCH_PHONE ( 
  BRANCH_CODE   VARCHAR2 (8), 
  CONTACT_NO    VARCHAR2 (16), 
  CONTACT_TYPE  VARCHAR2 (64) ) ; 


DROP TABLE CASH_TRANS CASCADE CONSTRAINTS ; 

CREATE TABLE CASH_TRANS ( 
  TRANS_ID         VARCHAR2 (16), 
  AC_HD_ID         VARCHAR2 (8), 
  ACT_NUM          VARCHAR2 (10), 
  INP_AMOUNT       NUMBER (16,2), 
  INP_CURR         VARCHAR2 (32), 
  AMOUNT           NUMBER (16,2), 
  TRANS_DT         DATE, 
  TRANS_TYPE       VARCHAR2 (32), 
  INST_TYPE        VARCHAR2 (32), 
  INST_NO          VARCHAR2 (32), 
  INST_DT          DATE, 
  TOKEN_NO         NUMBER (32), 
  INIT_TRANS_ID    VARCHAR2 (32), 
  INIT_CHANN_TYPE  VARCHAR2 (32), 
  PARTICULARS      VARCHAR2 (128),
  STATUS           VARCHAR2 (16)) ; 

DROP TABLE CUSTOMER CASCADE CONSTRAINTS ; 

CREATE TABLE CUSTOMER ( 
  CUST_ID            VARCHAR2 (8)  NOT NULL, 
  BRANCH_CODE        VARCHAR2 (8), 
  LNAME              VARCHAR2 (128), 
  FNAME              VARCHAR2 (128), 
  MNAME              VARCHAR2 (128), 
  DOB                DATE, 
  CUST_TYPE_ID       VARCHAR2 (32), 
  NETWORTH           NUMBER (16,2), 
  CREATEDDT          DATE, 
  DELETEDDT          DATE, 
  GENDER             VARCHAR2 (16), 
  MARITALSTATUS      VARCHAR2 (32), 
  PROFESSION         VARCHAR2 (64), 
  MINOR              CHAR (1), 
  ANNINCOME          VARCHAR2 (32), 
  EDUCATION          VARCHAR2 (128), 
  VEHICLE            VARCHAR2 (128), 
  REMARKS            VARCHAR2 (256), 
  COMP_NAME          VARCHAR2 (128), 
  COMM_ADDR_TYPE     VARCHAR2 (32), 
  EMAIL_ID           VARCHAR2 (64), 
  TITLE              VARCHAR2 (16), 
  RESIDENTIALSTATUS  VARCHAR2 (32), 
  NATIONALITY        VARCHAR2 (48), 
  LANGUAGE           VARCHAR2 (48), 
  CUSTOMERGROUP      VARCHAR2 (64), 
  RELATIONMANAGER    VARCHAR2 (64),
  PRIMARY_OCCUPATION VARCHAR2 (64),
  PREFERRED_COMM     VARCHAR2 (64),
  STATUS	     VARCHAR2 (32),
  CONSTRAINT CUSTOMER_PK
  PRIMARY KEY ( CUST_ID ) ) ; 


DROP TABLE CUST_ADDR CASCADE CONSTRAINTS ; 

CREATE TABLE CUST_ADDR ( 
  BRANCH_CODE   VARCHAR2 (8), 
  CUST_ID       VARCHAR2 (8), 
  STREET        VARCHAR2 (256), 
  AREA          VARCHAR2 (128), 
  CITY          VARCHAR2 (128), 
  STATE         VARCHAR2 (128), 
  PIN_CODE      VARCHAR2 (16), 
  COUNTRY_CODE  VARCHAR2 (4), 
  ADDR_TYPE     VARCHAR2 (32) ) ; 

DROP TABLE CUST_PHONE CASCADE CONSTRAINTS ; 

CREATE TABLE CUST_PHONE ( 
  CUST_ID        VARCHAR2 (8), 
  PHONE_ID       NUMBER(2),
  PHONE_TYPE_ID  VARCHAR2 (64), 
  AREA_CODE      VARCHAR2 (16), 
  ADDR_TYPE      VARCHAR2 (32),
  PHONE_NUMBER   VARCHAR2 (16) ) ; 

DROP TABLE CUST_TYPE CASCADE CONSTRAINTS ; 

CREATE TABLE CUST_TYPE ( 
  CUST_TYPE_ID    VARCHAR2 (8)  NOT NULL, 
  CUST_TYPE_DESC  VARCHAR2 (128), 
  CONSTRAINT CUST_TYPE_PK
  PRIMARY KEY ( CUST_TYPE_ID ) ) ; 

DROP TABLE DENOMIN_DETAILS CASCADE CONSTRAINTS ; 

CREATE TABLE DENOMIN_DETAILS ( 
  TRANS_ID      VARCHAR2 (16), 
  DENOM_AMOUNT  VARCHAR2 (16), 
  NO_OF_NOTES   VARCHAR2 (8) ) ; 

DROP TABLE DEPTT_MASTER CASCADE CONSTRAINTS ; 

CREATE TABLE DEPTT_MASTER ( 
  DEPTT_ID    VARCHAR2 (8)  NOT NULL, 
  DEPTT_NAME  VARCHAR2 (64), 
  CONSTRAINT DEPTT_PK
  PRIMARY KEY ( DEPTT_ID ) ) ; 

DROP TABLE DESIG_MASTER CASCADE CONSTRAINTS ; 

CREATE TABLE DESIG_MASTER ( 
  DESIG_ID      VARCHAR2 (8)  NOT NULL, 
  DESIG_DESCIP  VARCHAR2 (128), 
  CONSTRAINT DESIG_PK
  PRIMARY KEY ( DESIG_ID ) ) ; 

DROP TABLE EMPLOYEE_ADDR CASCADE CONSTRAINTS ; 

CREATE TABLE EMPLOYEE_ADDR ( 
  EMPLOYEE_ID   VARCHAR2 (8), 
  STREET        VARCHAR2 (256), 
  AREA          VARCHAR2 (128), 
  CITY          VARCHAR2 (128), 
  STATE         VARCHAR2 (128), 
  PIN_CODE      VARCHAR2 (16), 
  COUNTRY_CODE  VARCHAR2 (4), 
  AREA_CODE     VARCHAR2 (8) ) ; 


DROP TABLE FUNC_ID_MASTER CASCADE CONSTRAINTS ; 

CREATE TABLE FUNC_ID_MASTER ( 
  MENU_ID    VARCHAR2 (8), 
  SCREEN_ID  VARCHAR2 (8), 
  FUNC_ID    VARCHAR2 (8)  NOT NULL, 
  FUNC_DESC  VARCHAR2 (128), 
  CONSTRAINT FUNCID_MASTER_PK
  PRIMARY KEY ( FUNC_ID ) ) ; 


DROP TABLE GL CASCADE CONSTRAINTS ; 

CREATE TABLE GL ( 
  AC_HD_ID     VARCHAR2 (16), 
  OPN_BAL      NUMBER (16,2), 
  CUR_BAL      NUMBER (16,2), 
  BRANCH_CODE  VARCHAR2 (8), 
  USER_ID      VARCHAR2 (8) ) ; 

DROP TABLE GL_ABSTRACT CASCADE CONSTRAINTS ; 

CREATE TABLE GL_ABSTRACT ( 
  AC_HD_ID     VARCHAR2 (16), 
  OPN_BAL      NUMBER (16,2), 
  CLOSE_BAL    NUMBER (16,2), 
  BRANCH_CODE  VARCHAR2 (8), 
  USER_ID      VARCHAR2 (8), 
  DT           DATE ) ; 

DROP TABLE LOOKUP_MASTER CASCADE CONSTRAINTS ; 

CREATE TABLE LOOKUP_MASTER ( 
  LOOKUP_ID      VARCHAR2 (64), 
  LOOKUP_REF_ID  VARCHAR2 (64), 
  LOOKUP_DESC    VARCHAR2 (128) ) ; 

DROP TABLE MENU_MASTER CASCADE CONSTRAINTS ; 

CREATE TABLE MENU_MASTER ( 
  MENU_ID     VARCHAR2 (8)  NOT NULL, 
  MENU_NAME   VARCHAR2 (32), 
  MENU_DESC   VARCHAR2 (64), 
  PR_MENU_ID  VARCHAR2 (8), 
  CONSTRAINT MENU_MASTER_PK
  PRIMARY KEY ( MENU_ID ) ) ; 

DROP TABLE MJR_AC_HD CASCADE CONSTRAINTS ; 

CREATE TABLE MJR_AC_HD ( 
  MJR_AC_HD_ID    VARCHAR2 (4)  NOT NULL, 
  MJR_AC_HD_DESC  VARCHAR2 (128), 
  MJR_AC_HD_TYPE  VARCHAR2 (32),
  STATUS          VARCHAR2 (8), 
  CONSTRAINT MJR_AC_HD_PK
  PRIMARY KEY ( MJR_AC_HD_ID ) ) ; 

DROP TABLE OP_AC_ACCOUNT_PARAM CASCADE CONSTRAINTS ; 

CREATE TABLE OP_AC_ACCOUNT_PARAM ( 
  PROD_ID                 VARCHAR2 (16), 
  CHK_ALLOWED             CHAR (1), 
  MIN_BAL_W_CHK           NUMBER (16,2), 
  MIN_BAL_WT_CHK          NUMBER (16,2), 
  INT_REQ                 CHAR (1), 
  NOMINEE_REQ             CHAR (1), 
  NO_OF_NOMINEE           NUMBER (10), 
  AC_OP_REQ               CHAR (1), 
  MIN_PD_NEW              NUMBER (10), 
  MIN_PD_DORMANT          NUMBER (10), 
  MIN_PD_INOP             NUMBER (10), 
  MIN_PD_CLS              NUMBER (10), 
  STAT_FREQUENCY          NUMBER (10), 
  FREE_WITHDRAWALS        NUMBER (10), 
  FREE_WITHDRAWALS_PD     NUMBER (10), 
  FREE_WITHDRAWAL_FROM    DATE, 
  NO_FREE_CHK_LEAVES      NUMBER (10), 
  FREE_CHK_LEAVES_PD      NUMBER (10), 
  FREE_CHK_LEAVES_FROM    DATE, 
  TAX_INT_APPLICABLE      CHAR (1), 
  RATE_OF_INT             NUMBER (6,2), 
  LMT_DEFINITION_ALLOWED  CHAR (1), 
  TEMP_OD_ALLOWED         CHAR (1), 
  STAFF_ACCT_OPENED       CHAR (1), 
  EXTRA_INT_APPLICABLE    CHAR (1), 
  COLLECT_INT_CREDIT      CHAR (1), 
  DEBIT_INT_CLEARING      CHAR (1), 
  CREDIT_INT_UNCLEAR      CHAR (1), 
  ISSUE_TOKEN             CHAR (1), 
  ALLOW_WITHDRAWAL_SLIP   CHAR (1), 
  MAX_ALLOWED_WD_SLIP     NUMBER (16,2) ) ; 

DROP TABLE OP_AC_ACHEAD_PARAM CASCADE CONSTRAINTS ; 

CREATE TABLE OP_AC_ACHEAD_PARAM ( 
  PROD_ID            VARCHAR2 (16), 
  INOP_AC_CHRG       VARCHAR2 (16), 
  PREMATCLOSE_CHRG   VARCHAR2 (16), 
  ACCLOSE_CHRG       VARCHAR2 (16), 
  MISSER_CHRG        VARCHAR2 (16), 
  STAT_CHRG          VARCHAR2 (16), 
  FREEWITHD_CHRG     VARCHAR2 (16), 
  DEBIT_INT          VARCHAR2 (16), 
  CREDIT_INT         VARCHAR2 (16), 
  CLR_INT            VARCHAR2 (16), 
  CHQ_ISSUE_CHRG     VARCHAR2 (16), 
  STOP_PMT_CHRG      VARCHAR2 (16), 
  CHQ_RET_OUT        VARCHAR2 (16), 
  CHQ_RET_IN         VARCHAR2 (16), 
  ACT_OP_CHRG        VARCHAR2 (16), 
  EXCESS_FREE_WITHD  VARCHAR2 (16), 
  TAX                VARCHAR2 (16), 
  NONMNT_MIN_CHRG    VARCHAR2 (16), 
  INOPT              VARCHAR2 (16), 
  FOLIO_CHRG         VARCHAR2 (16) ) ; 

DROP TABLE OP_AC_CHARGES_PARAM CASCADE CONSTRAINTS ; 

CREATE TABLE OP_AC_CHARGES_PARAM ( 
  PROD_ID                      VARCHAR2 (16), 
  INOPERATIVE_AC_CHARGES       NUMBER (16,2), 
  INOPERATIVE_AC_CHARGE_PD     NUMBER (10), 
  CHG_PREMATURE_CLOSURE        NUMBER (16,2), 
  ACCT_CLOSING_CHG             NUMBER (16,2), 
  MISC_SERVICE_CHG             NUMBER (16,2), 
  NONMAIN_MIN_BAL_CHG          CHAR (1), 
  AMT_NONMAIN_MINBAL           NUMBER (16,2), 
  AMT_NONMAIN_MINBAL_PD        VARCHAR2 (32), 
  STAT_CHARGE                  VARCHAR2 (32), 
  AMT_CHARGE_STAT              NUMBER (16,2), 
  AMT_CHARGE_STAT_TYPE         VARCHAR2 (32), 
  CHK_ISSUE_CHG                CHAR (1), 
  CHK_ISSUE_CHGPERLEAF         NUMBER (16,2), 
  STOP_PAYMENT_CHG             CHAR (1), 
  STOP_PAYMENT_AMTCHG          NUMBER (16,2), 
  CHK_RETURN_CHG_OUTWARD       NUMBER (16,2), 
  CHK_RETURN_CHG_INWARD        NUMBER (16,2), 
  ACCT_OPENING_CHG             NUMBER (16,2), 
  FOLIO_CHG_APPLICABLE         CHAR (1), 
  NO_ENTRIESPER_FOLIO          NUMBER (10), 
  RATE_PER_FOLIO               NUMBER (16,2), 
  TO_CHARGE_ON                 VARCHAR2 (32), 
  FOLIO_CHG_APPL_FREQ          NUMBER (10), 
  TO_COLLECT_FOLIO_CHG         VARCHAR2 (32), 
  TO_CHARGE_ON_TYPE            VARCHAR2 (32), 
  INCOMPLETE_FOLIO_ROUND_FREQ  VARCHAR2 (32), 
  CHG_EXCESSFREEWD_PERTRANS    NUMBER (16,2), 
  OUTST_CHK_CHARGES            CHAR (1) ) ; 

DROP TABLE OP_AC_INTPAY_PARAM CASCADE CONSTRAINTS ; 

CREATE TABLE OP_AC_INTPAY_PARAM ( 
  PROD_ID                VARCHAR2 (16), 
  MIN_CR_INT_RATE        NUMBER (16,2), 
  MAX_CR_INT_RATE        NUMBER (16,2), 
  APPL_CR_INT_RATE       NUMBER (16,2), 
  MIN_CR_INT_AMT         NUMBER (16,2), 
  MAX_CR_INT_AMT         NUMBER (16,2), 
  CR_INT_CALC_FREQ       NUMBER (10), 
  CR_INT_APPL_FREQ       NUMBER (10), 
  STARTMON_INT_CALC      VARCHAR2 (32), 
  ENDMON_INT_CALC        VARCHAR2 (32), 
  LAST_INT_CALCDT_CR     DATE, 
  LAST_INT_APPLDT_CR     DATE, 
  CR_COMPOUND            CHAR (1), 
  CR_COMPOUND_CALC_FREQ  NUMBER (10), 
  CR_PRODUCT_ROUNDOFF    VARCHAR2 (32), 
  CR_INT_ROUNDOFF        VARCAHR2 (32), 
  STARTDAY_PROD_CALC     NUMBER (16,2), 
  ENDDAY_PROD_CALC       NUMBER (16,2), 
  CALC_CRITERIA          VARCHAR2 (64), 
  PRODUCT_FREQ_INT_PAY   VARCHAR2 (32), 
  CREDIT_INT_GIVEN       CHAR (1), 
  ADDITIONAL_INT_STAFF   NUMBER (16,2) ) ; 

DROP TABLE OP_AC_INTRATEMAINT_PARAM CASCADE CONSTRAINTS ; 

CREATE TABLE OP_AC_INTRATEMAINT_PARAM ( 
  PROD_ID     VARCHAR2 (16), 
  INT_CAT_ID  VARCHAR2 (16), 
  INT_DATE    DATE, 
  INT_RATE    VARCHAR2 (16),
  AC_HD_ID    VARCHAR2 (16)); 

DROP TABLE OP_AC_INTRECV_PARAM CASCADE CONSTRAINTS ; 

CREATE TABLE OP_AC_INTRECV_PARAM ( 
  PROD_ID                  VARCHAR2 (16), 
  DEBIT_INT_CHARGED        CHAR (1), 
  MIN_DEBIT_INT_RATE       NUMBER (16,2), 
  MAX_DEBIT_INT_RATE       NUMBER (16,2), 
  APPL_DEBIT_INT_RATE      NUMBER (16,2), 
  MIN_DEBIT_INT_AMT        NUMBER (16,2), 
  MAX_DEBIT_INT_AMT        NUMBER (16,2), 
  DEBIT_INT_CALC_FREQ      NUMBER (10), 
  DEBIT_INT_APPL_FREQ      NUMBER (10), 
  DEBIT_COMPOUND           CHAR (1), 
  DEBIT_COMPINT_CALC_FREQ  NUMBER (10), 
  DEBIT_PRODUCT_ROUNDOFF   VARCHAR2 (32), 
  DEBIT_INT_ROUNDOFF       VARCHAR2 (32), 
  LAST_INT_CALCDT_DEBIT    DATE, 
  LAST_INT_APPLDT_DEBIT    DATE, 
  PRODUCT_FREQ             NUMBER (10), 
  PENAL_INT_DEBIT_BALACCT  NUMBER (16,2), 
  PENAL_INT_CHARGE_STDAY   NUMBER (10) ) ; 

DROP TABLE OP_AC_INT_CAT_MASTER CASCADE CONSTRAINTS ; 

CREATE TABLE OP_AC_INT_CAT_MASTER ( 
  INT_CAT_ID    VARCHAR2 (16), 
  INT_CAT_DESC  VARCHAR2 (128) ) ; 

DROP TABLE OP_AC_PRODUCT CASCADE CONSTRAINTS ; 

CREATE TABLE OP_AC_PRODUCT ( 
  AC_HD_ID   VARCHAR2 (16), 
  PROD_ID    VARCHAR2 (8), 
  PROD_DESC  VARCHAR2 (128), 
  BEHAVIOR   VARCHAR2 (128),
  STATUS     VARCHAR2 (32)
) ; 

DROP TABLE OP_AC_SPCLITEM_PARAM CASCADE CONSTRAINTS ; 

CREATE TABLE OP_AC_SPCLITEM_PARAM ( 
  PROD_ID                VARCHAR2 (16), 
  LINKED_FLEXI_ACCT      CHAR (1), 
  MIN_BAL1_FLEXIDEPOSIT  NUMBER (16,2), 
  MIN_BAL2_FLEXIDEPOSIT  NUMBER (16,2), 
  FLEXI_HAPPEN           VARCHAR2 (32), 
  FLEXI_PROD_ID          VARCHAR2 (16), 
  ATM_CARD_ISSUED        CHAR (1), 
  MIN_BAL_ATM            NUMBER (16,2), 
  CR_CARD_ISSUED         CHAR (1), 
  MIN_BAL_CR_CARD        NUMBER (16,2), 
  DR_CARD_ISSUED         CHAR (1), 
  MIN_BAL_DR_CARD        NUMBER (16,2), 
  IVRS_PROVIDED          CHAR (1), 
  MIN_BAL_IVRS           NUMBER (16,2), 
  MOBILE_BANKING         CHAR (1), 
  MIN_BAL_MOBILE         NUMBER (16,2), 
  ANY_BRANCH_BANKING     CHAR (1), 
  MIN_BAL_ABB            NUMBER (16,2) ) ; 

DROP TABLE PRIVI_MASTER CASCADE CONSTRAINTS ; 

CREATE TABLE PRIVI_MASTER ( 
  PRIVI_ID       VARCHAR2 (8)  NOT NULL, 
  PRIVI_DESC     VARCHAR2 (128), 
  ACCESS_LVL_ID  VARCHAR2 (8), 
  FIN_LIMIT      NUMBER (16,2), 
  CONSTRAINT PRIVI_MASTER_PK
  PRIMARY KEY ( PRIVI_ID ) ) ; 

/*
DROP TABLE PWD_MASTER CASCADE CONSTRAINTS ; 

CREATE TABLE PWD_MASTER ( 
  USER_ID         VARCHAR2 (16)  NOT NULL, 
  PWD_ID          VARCHAR2 (16)  NOT NULL, 
  PWD             VARCHAR2 (32), 
  LPWDCHANGEDT    DATE, 
  LLOGINCHANGEDT  DATE, 
  STATUS          VARCHAR2 (32), 
  PRIVI_ID        VARCHAR2 (8), 
  PWD_USAGE       VARCHAR2 (128), 
  CONSTRAINT PWD_MASTER_PK
  PRIMARY KEY ( USER_ID, PWD_ID ) ) ; */



DROP TABLE SCREEN_MASTER CASCADE CONSTRAINTS ; 

CREATE TABLE SCREEN_MASTER ( 
  SCREEN_ID    VARCHAR2 (8)  NOT NULL, 
  MENU_ID      VARCHAR2 (8), 
  SCREEN_NAME  VARCHAR2 (64), 
  CONSTRAINT SCREEN_MASTER_PK
  PRIMARY KEY ( SCREEN_ID ) ) ; 



DROP TABLE SUB_AC_HD CASCADE CONSTRAINTS ; 

CREATE TABLE SUB_AC_HD ( 
  MJR_AC_HD_ID    VARCHAR2 (4), 
  SUB_AC_HD_ID    VARCHAR2 (4)  NOT NULL, 
  SUB_AC_HD_DESC  VARCHAR2 (128),
  STATUS          VARCHAR2 (8), 
  CONSTRAINT SUB_AC_HD_PK
  PRIMARY KEY ( SUB_AC_HD_ID ) ) ; 



DROP TABLE TRANSFER_TRANS CASCADE CONSTRAINTS ; 

CREATE TABLE TRANSFER_TRANS ( 
  TRANS_ID         VARCHAR2 (16), 
  BATCH_ID         VARCHAR2 (8), 
  AC_HD_ID         VARCHAR2 (8), 
  ACT_NUM          VARCHAR2 (10), 
  INP_AMOUNT       NUMBER (16,2), 
  INP_CURR         VARCHAR2 (32), 
  AMOUNT           NUMBER (16,2), 
  TRANS_DT         DATE, 
  TRANS_TYPE       VARCHAR2 (32), 
  INST_TYPE        VARCHAR2 (32), 
  INST_NO          VARCHAR2 (32), 
  INST_DT          DATE, 
  TOKEN_NO         VARCHAR2 (16), 
  INIT_TRANS_ID    VARCHAR2 (32), 
  INIT_CHANN_TYPE  VARCHAR2 (32), 
  PARTICULARS      VARCHAR2 (128),
  STATUS           VARCHAR2 (16)) ; 

DROP TABLE USER_MASTER CASCADE CONSTRAINTS ; 

/*CREATE TABLE USER_MASTER ( 
  USER_ID      VARCHAR2 (8)  NOT NULL, 
  STATUS       VARCHAR2 (32), 
  EMPLOYEE_ID  VARCHAR2 (8), 
  EMAIL_ID     VARCHAR2 (64), 
  CONSTRAINT USER_MASTER_PK
  PRIMARY KEY ( USER_ID ) ) ; */

CREATE TABLE USER_MASTER ( 
  USER_ID           VARCHAR2 (8)  NOT NULL, 
  PWD               VARCHAR2 (32),
  STATUS            VARCHAR2 (32), 
  EMPLOYEE_ID       VARCHAR2 (8), 
  EMAIL_ID          VARCHAR2 (64),
  EXPIRY_DATE       DATE,
  REMARKS           VARCHAR2 (256),
  PIN_LOGIN         CHAR (1),
  SUSPEND_BY_USER   CHAR (1),
  SUSPEND_USER      CHAR(1),
  ACTIVATION_DATE   DATE, 
  CONSTRAINT USER_MASTER_PK
  PRIMARY KEY ( USER_ID ) ) ; 


ALTER TABLE USER_MASTER ADD  CONSTRAINT USER_MASTER_EMP_ID_FK
 FOREIGN KEY (EMPLOYEE_ID) 
  REFERENCES BANK_EMPLOYEE (EMPLOYEE_CODE) ;


ALTER TABLE ACCESS_LVL_MASTER ADD  CONSTRAINT ACCESS_LVL_MASTER_FUNCID_FK
 FOREIGN KEY (FUNC_ID) 
  REFERENCES FUNC_ID_MASTER (FUNC_ID) ;

ALTER TABLE ACCESS_LVL_MASTER ADD  CONSTRAINT ACCESS_LVL_MASTER_MENUID_FK
 FOREIGN KEY (MENU_ID) 
  REFERENCES MENU_MASTER (MENU_ID) ;

ALTER TABLE ACCESS_LVL_MASTER ADD  CONSTRAINT ACCESS_LVL_MASTER_SCREENID_FK
 FOREIGN KEY (SCREEN_ID) 
  REFERENCES SCREEN_MASTER (SCREEN_ID) ;

ALTER TABLE AC_HD ADD  CONSTRAINT AC_HD_MJRID_FK
 FOREIGN KEY (MJR_AC_HD_ID) 
  REFERENCES MJR_AC_HD (MJR_AC_HD_ID) ;

ALTER TABLE AC_HD ADD  CONSTRAINT AC_HD_SUBID_FK
 FOREIGN KEY (SUB_AC_HD_ID) 
  REFERENCES SUB_AC_HD (SUB_AC_HD_ID) ;


ALTER TABLE AC_HD_PARAM ADD  CONSTRAINT AC_HD_PARAM_ACHDSTATUSID_FK
 FOREIGN KEY (AC_HD_STATUS_ID) 
  REFERENCES AC_HD_STATUS (AC_HD_STATUS_ID) ;

ALTER TABLE AC_HD_PARAM ADD  CONSTRAINT AC_HD_PARAM_ACHD_FK
 FOREIGN KEY (AC_HD_ID) 
  REFERENCES AC_HD (AC_HD_ID) ;


ALTER TABLE BANK_ADDRESS ADD  CONSTRAINT BANK_ADDR_BANKCODE_FK
 FOREIGN KEY (BANK_CODE) 
  REFERENCES BANK (BANK_CODE) ;

ALTER TABLE BANK_EMPLOYEE ADD  CONSTRAINT BANK_EMP_BRANCHCODE_FK
 FOREIGN KEY (BRANCH_CODE) 
  REFERENCES BRANCH_MASTER (BRANCH_CODE) ;

ALTER TABLE BANK_EMPLOYEE ADD  CONSTRAINT BANK_EMP_DEPTTID_FK
 FOREIGN KEY (DEPTT_ID) 
  REFERENCES DEPTT_MASTER (DEPTT_ID) ;

ALTER TABLE BANK_EMPLOYEE ADD  CONSTRAINT BANK_EMP_DESIGID
 FOREIGN KEY (DESIG_ID) 
  REFERENCES DESIG_MASTER (DESIG_ID) ;

ALTER TABLE BANK_PHONE ADD  CONSTRAINT BANK_PHONE_BANKCODE_FK
 FOREIGN KEY (BANK_CODE) 
  REFERENCES BANK (BANK_CODE) ;

/*ALTER TABLE BRANCH_ADDRESS ADD  CONSTRAINT BRANCH_ADDR_BRANCHCODE_FK
 FOREIGN KEY (BRANCH_CODE) 
  REFERENCES BRANCH_MASTER (BRANCH_CODE) ;*/

ALTER TABLE BRANCH_PHONE ADD  CONSTRAINT BRANCH_PHONE_BRANCHCODE_FK
 FOREIGN KEY (BRANCH_CODE) 
  REFERENCES BRANCH_MASTER (BRANCH_CODE) ;

ALTER TABLE CUSTOMER ADD  CONSTRAINT CUSTOMER_BRANCHCODE_FK
 FOREIGN KEY (BRANCH_CODE) 
  REFERENCES BRANCH_MASTER (BRANCH_CODE) ;

ALTER TABLE CUST_ADDR ADD  CONSTRAINT CUST_ADDR_BRANCHCODE_FK
 FOREIGN KEY (BRANCH_CODE) 
  REFERENCES BRANCH_MASTER (BRANCH_CODE) ;

ALTER TABLE CUST_ADDR ADD  CONSTRAINT CUST_ADDR_CUSTID_FK
 FOREIGN KEY (CUST_ID) 
  REFERENCES CUSTOMER (CUST_ID) ;

ALTER TABLE CUST_PHONE ADD  CONSTRAINT CUST_PHONE_CUSTID_FK
 FOREIGN KEY (CUST_ID) 
  REFERENCES CUSTOMER (CUST_ID) ;

ALTER TABLE EMPLOYEE_ADDR ADD  CONSTRAINT EMPLOYEE_ADDR_EMPYID_FK
 FOREIGN KEY (EMPLOYEE_ID) 
  REFERENCES BANK_EMPLOYEE (EMPLOYEE_CODE) ;

ALTER TABLE FUNC_ID_MASTER ADD  CONSTRAINT FUNCID_MASTER_MENUID_FK
 FOREIGN KEY (MENU_ID) 
  REFERENCES MENU_MASTER (MENU_ID) ;

ALTER TABLE FUNC_ID_MASTER ADD  CONSTRAINT FUNCID_MASTER_SCREENID_FK
 FOREIGN KEY (SCREEN_ID) 
  REFERENCES SCREEN_MASTER (SCREEN_ID) ;

ALTER TABLE PRIVI_MASTER ADD  CONSTRAINT PRIVI_MASTER_ACCESSLVLID_FK
 FOREIGN KEY (ACCESS_LVL_ID) 
  REFERENCES ACCESS_LVL_MASTER (ACCESS_LVL_ID) ;

/*ALTER TABLE PWD_MASTER ADD  CONSTRAINT PWD_MASTER_USERID_FK
 FOREIGN KEY (USER_ID) 
  REFERENCES USER_MASTER (USER_ID) ;*/

ALTER TABLE SCREEN_MASTER ADD  CONSTRAINT SCREEN_MASTER_MENUID_FK
 FOREIGN KEY (MENU_ID) 
  REFERENCES MENU_MASTER (MENU_ID) ;

ALTER TABLE SUB_AC_HD ADD  CONSTRAINT SUB_AC_HD_MJRID_FK
 FOREIGN KEY (MJR_AC_HD_ID) 
  REFERENCES MJR_AC_HD (MJR_AC_HD_ID) ;


ALTER TABLE AC_HD_PARAM DROP CONSTRAINT "AC_HD_PARAM_ACHD_FK";

ALTER TABLE AC_HD_PARAM
ADD CONSTRAINT AC_HD_PARAM_PK PRIMARY KEY (AC_HD_ID)

------- Note :
------- ACT_FREEZE table, compound primary constraint needed


